### ISSUE TITLE
FIRApp.m line 515 + [FIRApp firebaseUserAgent]

### ISSUE THREAD

**Issue by uboncukcu** [firebase/quickstart-unity#338] opened 2019-03-29 21:46 UTC
## Please fill in the following fields:
Unity editor version: 2018.3.8f1
Firebase Unity SDK version: 5.5.0
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, admob, gameanalytics, unityads, mopub, adcolony, vungle, Safedk
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): IOS

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
<img width="1257" alt="Ekran Resmi 2019-03-30 00 30 34" src="https://user-images.githubusercontent.com/2920249/55264358-181a1000-5285-11e9-85ed-1b23195e7a8a.png">

FIRApp.m line 515
+[FIRApp firebaseUserAgent]
We get this crash message 32000 times in the last 24 hours on Crashlytics. I am very concerned about this situation because the game has reached a large number of users. And, we do not know the result of this crash. Actually, we do not get this crash on our test devices therefore we have to. send new update to store in order to see if the error has been resolved. 
Need urgent solution.
Thank you for any help.

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
No applicable, because we get this error only from live app .

**Comment by a-maurice** [comment] 2019-03-29 22:24
Marking this as a duplicate of https://github.com/firebase/quickstart-unity/issues/337

We are looking into finding a fix or workaround as soon as possible.

**Closed by a-maurice** 2019-03-29 22:24 UTC
Labels: duplicate
