### ISSUE TITLE
Firebase Realtime Database slow build performance

### ISSUE THREAD

**Issue by danwillm** [firebase/quickstart-unity#735] opened 2020-07-20 19:22 UTC
### Please fill in the following fields:
Unity editor version: 2019.4.4f1
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Auth, Database (Realtime Database)
Additional SDKs you are using (Facebook, AdMob, etc.): -
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android, Desktop
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:

I'm currently experiencing slow build performance when trying to run my unity project inside the editor. When going back to the unity editor after changing part of my code, it takes around 15 seconds for it to recompile and when I go to press run it takes another 10-20 seconds for it to enter play mode.

I've seen other threads on the unity forums of other people experiencing the same issue that I [have,](https://forum.unity.com/threads/unity-is-slow-entering-play-mode-with-firebase-database.886519/) and other issues on this repo seem to mention it, but for different packages. The fixes they mentioned don't seem to work for me.

Any suggestions on how to speed up the build time?

Thanks in advance.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by giorgiocav1** [comment] 2020-07-20 19:26
Have been experiencing this too, very long load times every time I click the play button. A fix would be much appreciated.

**Comment by chkuang-g** [comment] 2020-07-24 23:01
Duplicate of #639

**Closed by chkuang-g** 2020-07-24 23:01 UTC
Labels: new
