### ISSUE TITLE
Unable to find FirebaseCppApp-6.1.1

### ISSUE THREAD

**Issue by babak-ss** [firebase/quickstart-unity#398] opened 2019-06-26 09:33 UTC
## Please fill in the following fields:
Unity editor version: 2019.1.2f1
Firebase Unity SDK version: 6.1.1
Firebase plugins in use (Auth, Database, etc.): Analytics, Remote Config
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Appodeal
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:

- Delete all the Firebase files in the /Assets includeing:
    /Assets/Editor Default Resources/Firebase
    /Assets/Firebase
    /Assets/Parse
    /Assets/Plugins/Android/Firebase
    /Assets/Plugins/iOS/Firebase
    /Assets/Plugins/x86_64/Firebase
- First imported Remote Config then imported Analytics
- Target Architecture: Armv7, Arm64, x86
- Android Build

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? No

When I look inside the .apk file there is no \lib\armeabi-v7a\FirebaseCppApp-6.1.1.so but there is \lib\armeabi-v7a\libFirebaseCppApp-5.5.0.so(my older version)

![Image of Editor](https://imgur.com/ydsiwPG) https://imgur.com/ydsiwPG
I tried turning Android on, the error occurred again but this time in the .apk there was FirebaseCppApp-6.1.1.so and also libFirebaseCppApp-5.5.0.so

I tried building with Mono & IL2CPP build but none worked. I also tried Force Resolving seveal times with Armv7, Arm64, x86 on but that did not work either. 

Here's the error:

> 06-26 12:41:08.821 30826 30934 I Unity   : Using Facebook Unity SDK v7.14.0 with FBAndroidSDK/4.38.1
> 06-26 12:41:08.821 30826 30934 I Unity   : Facebook.Unity.CompiledFacebookLoader:Start()
> 06-26 12:41:08.821 30826 30934 I Unity   :  
> 06-26 12:41:08.821 30826 30934 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
> 06-26 12:41:08.821 30826 30934 I Unity   : 
> 06-26 12:41:08.826 30826 30934 E Unity   : Unable to find FirebaseCppApp-6.1.106-26 12:41:14.246 30826 30970 E Unity   : DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6.1.1': The specified module could not be found.
> 06-26 12:41:14.246 30826 30970 E Unity   :   at Firebase.AppUtilPINVOKE.SetLogFunction (Firebase.LogUtil+LogMessageDelegate jarg1) [0x00000] in <00000000000000000000000000000000>:0 
> 06-26 12:41:14.246 30826 30970 E Unity   :   at Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) [0x00000] in <00000000000000000000000000000000>:0 
> 06-26 12:41:14.246 30826 30970 E Unity   :   at Firebase.LogUtil.Finalize () [0x00000] in <00000000000000000000000000000000>:0

The Remote config works just fine in the Editor and the Firebase Initializes successfully but not on Android.

I updated Google Play Service Resolver to 1.2.120 from [here](https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.120.0.unitypackage ) but that did not solve the issue

**Comment by stewartmiles** [comment] 2019-06-26 17:01
@babak-ss is it possible resolution is failing given that you're including other libraries in your application, what do the console logs in Unity say when you force resolve for Android?

If you're seeing `libFirebaseCppApp-5.5.0.so` in your APK it sounds like resolution isn't working.  Have you tried reproducing this with our remote config sample application?

**Comment by babak-ss** [comment] 2019-06-27 18:07
sorry for the delay. I checked the logs:

> No .*\*\*DEPS\*\*.* token found in gradle template Assets/Plugins/Android\mainTemplate.gradle, Android Resolver libraries will not be added to the file.

So I've Add the *\*\*DEPS\*\*.* to dependencies and then I force resolved
Some .aar files added  to /Assets/Firebase
But when I try to build I get this error message:

> Execution failed for task ':transformClassesWithJarMergingForRelease'.> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/auto/value/extension/memoized/Memoized.class

I'll try to see if I can reproduce this error with the sample project tomorrow.

**Comment by babak-ss** [comment] 2019-06-30 07:35
I noticed smth.
Making a new build changes the `mainTemplate.gradle` file 
I attached my `mainTemplate.gradle` file in 3 stages: 0) before adding **DEPS** 1) after removing all the implementations and adding DEPS 3) after I build (which failed with the above error)

[(0)mainTemplate.txt](https://github.com/firebase/quickstart-unity/files/3342636/0.mainTemplate.txt)
[(1)mainTemplate.txt](https://github.com/firebase/quickstart-unity/files/3342637/1.mainTemplate.txt)
[(2)mainTemplate.txt](https://github.com/firebase/quickstart-unity/files/3342638/2.mainTemplate.txt)

**Comment by stewartmiles** [comment] 2019-07-01 17:13
@babak-ss I recommend starting with Unity's default `mainTemplate.txt`, the Android Resolver plugin patches it in a few different places, if you change the format it's not going to patch it.

The code that injects the dependencies is here if you're interested.
https://github.com/googlesamples/unity-jar-resolver/blob/7f438bac0f1ffed421788c6e84ef679d573adba1/source/PlayServicesResolver/src/GradleTemplateResolver.cs#L305

**Comment by babak-ss** [comment] 2019-07-02 16:03
I did as you said but only I also added multidex to my dependencies:
`implementation 'com.android.support:multidex:1.0.3'`
But then I get a new error:

> Execution failed for task ':transformClassesWithDexBuilderForRelease'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: 
com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\BSS\.gradle\caches\transforms-1\files-1.1\com.google.android.gms.play-services-measurement-16.4.0.aar\473fb8d4f5684d8ede14abc39ef91325\jars\classes.jar

**Comment by stewartmiles** [comment] 2019-07-02 16:22
@babak-ss I recommend starting with our sample project(s) - this repo - verifying you can build for Android at all then looking at the delta between your game project and the sample to narrow down the difference.

The log you shared appears to be a partial log.

**Comment by Vah94** [comment] 2019-07-10 08:29
Unable to load DLL 'FirebaseCppApp-6.2.0'
After Firebase init crashed if build "Scripting Backend" is "IL2CPP" and "ARM64" checkmark is active.
[logs.txt](https://github.com/firebase/quickstart-unity/files/3376500/logs.txt)

**Comment by chkuang-g** [comment] 2019-07-27 04:56
Hi @babak-ss  and @Vah94 

Could you try to reproduce the issue with our sample project and the logs??
https://github.com/firebase/quickstart-unity

Otherwise,there are a couple things you can try:

1.  If you upgraded to the latest Play Service Resolver, try to downgrade to that provided in Firebase SDK.
2.  Try to use Assets > Play Services Resolver > Android Resolver > Force Resolve
3.  Try to remove all Firebase plugin and reimport again.

Please let us know.

**Comment by ravitalsaniya** [comment] 2019-07-27 12:26
Unable to load DLL 'FirebaseCppApp-6.2.0'
Same Problem here 
we try it this, but this is problem is only "IL2CPP" 64 bit, not with "IL2CPP" 32,
in 32 bit build every thinks works perfect 
If Any new update Available then please, let me know.

**Comment by ryanmeier** [comment] 2019-07-30 18:04
@babak-ss @Vah94 @ravitalsaniya We fixed several 'Unable to find/load DLL' errors in the latest version of the Firebase Unity SDK (6.2.2) released last week.  Could you try installing the new SDK and see if you're still encountering these issues?

**Comment by patm1987** [comment] 2019-08-19 19:31
Just checking in to see if y'all are still experiencing the problem to see if we should keep investigating or if I can close this bug.

Thanks,
--Patrick

**Comment by babak-ss** [comment] 2019-08-26 10:16
Hi @patm1987 sorry for the late reply
I'll try the new version (6.2.2) and will let you know.

**Comment by stewartmiles** [comment] 2019-09-06 21:47
@babak-ss since we haven't heard from you we're closing this issue.

**Closed by stewartmiles** 2019-09-06 21:47 UTC
Labels: help wanted

**Comment by tonyjoseph456** [comment] 2019-09-11 06:40
@stewartmiles Im also getting similar issue in my Unity project with firebase. Here is the error log:

`E Unity   : Unable to find FirebaseCppApp-6_4_0
 E Unity   : DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6_4_0': The specified module could not be found.
 E Unity   :   at Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil (Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate applicationDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate arithmeticDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate divideByZeroDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate indexOutOfRangeDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate invalidCastDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate invalidOperationDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate ioDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate nullReferenceDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate outOfMemoryDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate overflowDelegate,`
