### ISSUE TITLE
FCM IllegalStateException crash in onTokenRefresh

### ISSUE THREAD

**Issue by khambadkone** [firebase/quickstart-unity#330] opened 2019-03-11 03:57 UTC
## Please fill in the following fields:
Unity editor version: Various 2018.2.x
Firebase Unity SDK version: 5.4.3, 5.1.1
Additional SDKs you are using (Facebook, AdMob, etc.): MoPub with Facebook, IronSource. 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
Many of our games that we have migrated from GCM (via Prime31's plugin) to Firebase report crashes.  All throw the following logs 👍 java.lang.IllegalStateException: 
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1666)
  at android.app.ContextImpl.startService (ContextImpl.java:1611)
  at android.content.ContextWrapper.startService (ContextWrapper.java:677)
  at com.google.firebase.messaging.cpp.FcmInstanceIDListenerService.onTokenRefresh (FcmInstanceIDListenerService.java:24)
  at com.google.firebase.iid.FirebaseInstanceIdService.zza (Unknown Source:71)
  at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent (Unknown Source:158)
  at com.google.firebase.iid.zzg.run (Unknown Source:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

## Please answer the following, if applicable:
No.  However, our implementation in each of our games follows this same approach.

## Additional question
Why isn't FirebaseMessagingService's onNewToken triggered, instead of the deprecated FcmInstanceIDListenerService.onTokenRefresh ?

**Comment by stewartmiles** [comment] 2019-03-11 17:16
@khambadkone I think the exception you're seeing is due to the use of the Android component from the a release of the Firebase Unity SDK before 5.1.1 (see https://github.com/firebase/quickstart-unity/issues/165 for more information).  The token listener service is redistributed in `Assets/Firebase/Editor/m2repository/com/google/firebase/firebase-messaging-unity/VERSION` which will end up being resolved into `Assets/Plugins/Android/com.google.firebase.firebase-messaging-unity-VERSION.aar`.  If you're running an old version of this component new tokens cause the background service to attempt to launch another service will doesn't work on Android 8 and beyond.  So I recommend making sure that you're running the latest revision of the Android component.  If you are doing so already, it would probably be useful to share a project based upon our messaging sample that reproduces this.

Why we're using `FirebaseInstanceIdService. onTokenRefresh` vs. `FirebaseMessagingService.onNewToken`, it's primarily a syntactic change that we decided to not apply to the C++ SDK yet.  `FirebaseInstanceIdService` isn't deprecated as it is still used if you just want to use FirebaseInstanceId without messaging.

**Comment by chkuang-g** [comment] 2019-04-02 02:28
Hi @khambadkone 
Is the issue resolved on your end?

**Comment by stewartmiles** [comment] 2019-04-17 22:00
@khambadkone since we haven't heard from you we'll assume that your issue is resolved with the latest SDK.

**Closed by stewartmiles** 2019-04-17 22:00 UTC
Labels: help wanted
