### ISSUE TITLE
iOS notifications after second app run

### ISSUE THREAD

**Issue by bakalarczuk** [firebase/quickstart-unity#822] opened 2020-10-14 15:30 UTC
Hi,
I'm using unity SDK. When I first run iOS app and give permission for pushes and then I'm sending a message,
there is no action. But when I close an app, and open it second time, pushes working 

What can be an issue?

EDIT: I've figured, that this is conflict in our app. Is there a list of known conflicts?

**Comment by chkuang-g** [comment] 2020-10-16 01:28
Duplicate of #820

Could you detail the conflict you found in #820?  I'm going to close this thread so that it is easier to keep track of the same issue.

Shawn

**Closed by chkuang-g** 2020-10-16 01:28 UTC
Labels: needs-triage
