### ISSUE TITLE
Processing AARs Error. Stuck.

### ISSUE THREAD

**Issue by ThePumpel** [firebase/quickstart-unity#295] opened 2019-01-22 09:57 UTC
I am getting an error after importing Firebase to my unity proyect. I uninstalled all plugins just in case and it still happens. This happens when the PlayServicesResolver is processing AARs.

`Stopped polling job due to exception: System.UnauthorizedAccessException: Access to the path is denied.
  at System.IO.Directory.Move (System.String sourceDirName, System.String destDirName) [0x000dd] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at GooglePlayServices.DefaultResolver.ProcessAar (System.String dir, System.String aarFile, System.Boolean antProject, GooglePlayServices.AndroidAbis& abis) [0x002bf] in Z:\tmp\tmp.mz1RZCSjez\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\DefaultResolver.cs:395 
  at GooglePlayServices.ResolverVer1_1+<ProcessAars>c__AnonStorey8.<>m__0 () [0x000c7] in Z:\tmp\tmp.mz1RZCSjez\third_party\unity\unity_jar_resolver\source\PlayServicesResolver\src\ResolverVer1_1.cs:1374 
  at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in Z:\tmp\tmp.x6o0WrFOpy\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:286 
UnityEngine.Debug:LogError(Object)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.x6o0WrFOpy/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:289)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.x6o0WrFOpy/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:400)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.x6o0WrFOpy/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.x6o0WrFOpy/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()`

I have been trying to fix this issue rolling back for hours not sure what to do.

I am using:
Unity 3D 2018.3.2f1
Latest Firebase.Analytics 5.4.4 plugin using .NET 4.X (tried .NET 3 but it also happens)

**Comment by stewartmiles** [comment] 2019-01-23 18:11
It sounds like the Android Resolver is blowing up here
https://github.com/googlesamples/unity-jar-resolver/blob/12b868f1932f438c93ae86adbdba8a029125f5e7/source/PlayServicesResolver/src/DefaultResolver.cs#L395

Are you sure your project directory is writable?

**Comment by ThePumpel** [comment] 2019-01-23 23:22
Hi! Yes it's writable.

**Comment by ThePumpel** [comment] 2019-01-23 23:34
So I finally managed to not get the issue.

I marked the use Gradle system. I was switching back and forth from internal build system to gradle to test some things exporting the project for Android Studio. So yeah when I set it to Internal it "breaks".

**Comment by stewartmiles** [comment] 2019-01-25 18:54
@ThePumpel I've been playing around with this on Windows and Mac boxes and still can't reproduce this issue.  I did find that File.Move() and Directory.Move() have an _interesting_ behavior with permissions on Windows though, so I'm patching the Android Resolver plugin to copy file permissions when moving files / directories around to see whether that makes a difference.  I'll post when I have the patch published on https://github.com/googlesamples/unity-jar-resolver

**Comment by stewartmiles** [comment] 2019-01-25 23:48
@ThePumpel could you give https://github.com/googlesamples/unity-jar-resolver/raw/master/play-services-resolver-1.2.100.0.unitypackage a try?  You'll need to import it over your current Firebase packages.

**Comment by rishitbhatia** [comment] 2019-02-06 22:28
Exact same issue Unity 2017.2.0p2. Trying to Import Firebase messaging 5.4.4 for 3.x. I used the resolution suggested by @ThePumpel and it works after that.

@stewartmiles The Package import never goes through with this issue, it gets stuck, so Unity has to be killed. So with that resolver package you shared, it might have to be imported beforehand and excluded when importing the main public Firebase package

**Comment by stewartmiles** [comment] 2019-02-27 00:40
We released a fix for this in Play Services Resolver 1.2.100 which was included in the Firebase Unity SDK 5.5.0 release.

**Closed by stewartmiles** 2019-02-27 00:40 UTC
Labels: bug
