### ISSUE TITLE
Firebase iOS Initialization Crash, mostly on ios 12.1

### ISSUE THREAD

**Issue by ozbra** [firebase/quickstart-unity#275] opened 2018-12-18 18:55 UTC
Hi,

I am not sure why this problem occurs but there is a wierd crash on ios side. I am saying wierd because I haven't been able to reproduce myself. It doesn't crash on Editor, and most of the devices. I am getting crash reports from iTunes and that shows around 10% of the devices are crashes. Most of the IOS 12.1 devices are effected by this. I have even tried to update my test devices to get this crash but I couldn't. I even tried to putting try-catch the all firebase Initialization, not to make app to crash, but it seems it is still happening. 

Is there any other one who have this problem? 

He is how it looks like in Xcode Crashes side
![ios crash](https://user-images.githubusercontent.com/3050280/50175987-7aff2100-02fe-11e9-8ca5-6e84a74b5618.png)

Here is the Crash Stack info below. This log looks similar App Initialization on editor but I am not 100% sure is this really happening because of this.

```
InterfaceFuncInvoker0<int>::Invoke(unsigned int, Il2CppClass*, Il2CppObject*) + 76
FirebaseLogger_LogMessage_m2677119794
ReversePInvokeWrapper_FirebaseApp_LogMessage_m43..
firebase::ApplogCallback(firebase:LogLevel, char const..
firebase::LogMessaageWithCallbackV(firebase::LogLevel,
firebase::LogWarning(char const*,
firebase::CppInstanceManager<firebase::App>:::~CppIns...
```

Firebase SKD: 5.4.3
Bitcode enabled : false;
Used Firebase Components, 
Auth
Database,
Cloud Messaging,
Remote Config,
Functions
InstanceID
Analytics

**Comment by stewartmiles** [comment] 2018-12-18 19:04
@ozbra this is a dupe of #271 we're working on it.

**Closed by stewartmiles** 2018-12-18 19:04 UTC
