### ISSUE TITLE
SDK Installation causing lots of fatal issues.

### ISSUE THREAD

**Issue by cryptogrounds** [firebase/quickstart-unity#658] opened 2020-04-27 20:45 UTC
### Please fill in the following fields:
Unity editor version: **2019.3.11f1** and **2019.3.0f6** maybe it occurs in more?
Firebase Unity SDK version: **6.14.0**
Source you installed the SDK (.unitypackage or Unity Package Manager): **FirebaseAnalytics.unitypackage** (Dotnet4)
Firebase plugins in use (Auth, Database, etc.): **Analytics**
Additional SDKs you are using (Facebook, AdMob, etc.):  **Admob**
Platform you are using the Unity editor on (Mac, Windows, or Linux):  **Windows 10**
Platform you are targeting (iOS, Android, and/or desktop): **All three**
Scripting Runtime (Mono, and/or IL2CPP): **IL2CPP for iOS/Android, Mono for PC/Mac Standalone**

### Please describe the issue here:
So I have three issues: 
First one is a bunch of errors just whenever I load into the project, or import, etc. The errors are: https://hatebin.com/yfsujgvldd

Second is not having the ability to go to Window>Firebase>Documentation, I get an error for that: https://hatebin.com/dsrtwcoqfj

Lastly, whenever I try to build for Android, unity's process just starts to not respond when the build phase it at **"Building Scene 0: <Scene Name>"**

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? **Yes and an empty project**

Extra Questions:
Have I tried importing the package again? **Yes**
Have I tried building without the SDK? **Yes and it works perfectly fine**
Have I tried reimport all? **Yes**
Have I tried relaunching Unity? **Yes**
Do I have both iOS and Android modules installed? **Yes*

What's the issue repro rate? **100%**

**Comment by NightStormYT** [comment] 2020-05-04 18:05
Bump, really want to be able to use firebase.

**Comment by chkuang-g** [comment] 2020-05-21 23:42
I was not able to reproduce on Mac so it could be a Windows specific issue.

According to your log, there seems to have two issues:
- **Could not resolve field token** - This looks like EDM4U libraries are not enabled properly. A quick workaround with this:
  1. Find all libraries (`.dll`) under `Assets/ExternalDependencyManager/Editor/`
  2. In Inspector window, check "Editor" platform and click "Apply"
- **jar not found, C:/Program Files/Unity/Hub/Editor/2020.1.0a7/Editor/Data/PlaybackEngines/AndroidPlayer\OpenJDK** - This looks like a path issue.
   https://github.com/googlesamples/unity-jar-resolver/blob/6cef4b5f4a12dc7545626676206e52f502c8289b/source/AndroidResolver/src/JavaUtilities.cs#L55
  https://github.com/googlesamples/unity-jar-resolver/blob/6cef4b5f4a12dc7545626676206e52f502c8289b/source/AndroidResolver/src/PlayServicesResolver.cs#L858
  Judge by the code here, there might be some issue with Unity SDK here
  https://docs.unity3d.com/ScriptReference/BuildPipeline.GetPlaybackEngineDirectory.html
  Need a bit more dig for this.

Thanks for reporting this.

**Comment by NightStormYT** [comment] 2020-05-21 23:58
Ok, I will give that a try for the .dll files right now.

**Comment by NightStormYT** [comment] 2020-05-22 00:25
![image](https://user-images.githubusercontent.com/22107195/82618285-e8684e80-9b8f-11ea-890e-0203bf735f1c.png)
![image](https://user-images.githubusercontent.com/22107195/82618305-f4541080-9b8f-11ea-8555-05ea88e7996e.png)
![image](https://user-images.githubusercontent.com/22107195/82618314-f918c480-9b8f-11ea-9167-e9c5aa41db68.png)
![image](https://user-images.githubusercontent.com/22107195/82618321-fe760f00-9b8f-11ea-9975-331729b1457f.png)
![image](https://user-images.githubusercontent.com/22107195/82618328-02099600-9b90-11ea-9ac6-f2c50f9bb30d.png)

here is all the spam i get after i check editor in all the .dll files in the folder 

![image](https://user-images.githubusercontent.com/22107195/82618443-53198a00-9b90-11ea-870c-81ad7590ab6c.png)
 and yeah unity still freezes on build, thought i might as well add that again since this is my third time trying to import it :(

**Comment by patm1987** [comment] 2020-06-19 17:07
Hi @NightStormYT ,

Sorry that it took so long to get to your question!

My first request would be that you try the new 6.15 SDK - but I don't want to make you wait longer before giving you some more things to look at.

Looking through your logs, I'm noticing lines like:
```
Failed with exception GooglePlayServices.JavaUtilities+ToolNotFoundException: jar not found,
```

So a few things. First, I'd suggest trying to reinstall Java/Android SDK via Unity Hub:
![image](https://user-images.githubusercontent.com/1111611/85159131-513bf880-b21a-11ea-9dc4-9ce6c210c472.png)

(I see in your error log that you do have it setup)

And I'd make sure that you are using the built in Java SDK:
![image](https://user-images.githubusercontent.com/1111611/85159238-77fa2f00-b21a-11ea-9e68-6c4278d21bf3.png)

There have been reports about needing to toggle this checkbox in newer versions of Unity.

If you have a system wide Java installed - you may try using that (or temporarily clearing the $JAVA_HOME variable). There are some other suggestions [in this forum post](https://forum.unity.com/threads/toolnotfoundexception-jar-not-found.638689/) regarding this option in Unity.

Another thing I might suggest trying is clearing out your `Temp/` and `Library/` folders with Unity closed (`Temp/` should actually go away when you close Unity). If you're using `.meta` files (default), it will just regenerate itself automatically and sometimes clears up funky project-level issues.

Let me know if any of those work - or if you resolved it on your own since posting this issue!

--Patrick

**Comment by chkuang-g** [comment] 2021-02-11 05:35
@cryptogrounds

It's been awhile and we change quite a lot for unity-jar-resolver (currently named External Dependency Manager for Unity).

Are you still experiencing the same issue with later version of Firebase?

**Comment by cryptogrounds** [comment] 2021-02-11 05:41
Nope, all good now.

**Comment by chkuang-g** [comment] 2021-02-11 18:47
I'll close the issue for now.

**Closed by chkuang-g** 2021-02-11 18:47 UTC
Labels: edm4u, needs-attention
