### ISSUE TITLE
Fail to build with version after 6.1.1 with Facebook SDK

### ISSUE THREAD

**Issue by walaoRIKI** [firebase/quickstart-unity#452] opened 2019-08-21 01:55 UTC
## Please fill in the following fields:
Unity editor version: 2019.2.1f1
Firebase Unity SDK version: 6.3.0
Firebase plugins in use (Auth, Database, etc.): Auth and Storage
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook Unity SDK
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Import the 6.3.0 and dotnet 4 version of Firebase auth and storage, then import Facebook Unity SDK 7.17.2, then Import google play services. Switch the Unity target platform to Android and setup all the required file like google play services, firebase and facebook. Switch scripting backend to IL2CPP, API Compatibility Level to .Net 4.x and minimum API level to Android 5.0. Drag all the example scene from Facebook to build settings and build the project. Then error occur

Error Log:
CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Unity/Hub/Editor/2019.2.1f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2019.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-5.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class android.support.v4.app.INotificationSideChannel found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:com.android.support.support-compat-27.0.2:)
  Duplicate class android.support.v4.app.INotificationSideChannel$Stub found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:com.android.support.support-compat-27.0.2:)
  Duplicate class android.support.v4.app.INotificationSideChannel$Stub$Proxy found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:com.android.support.support-compat-27.0.2:)
  Duplicate class android.support.v4.os.IResultReceiver found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:com.android.support.support-compat-27.0.2:)
  Duplicate class android.support.v4.os.IResultReceiver$Stub found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:com.android.support.support-compat-27.0.2:)
  Duplicate class android.support.v4.os.IResultReceiver$Stub$Proxy found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:com.android.support.support-compat-27.0.2:)
  Duplicate class android.support.v4.os.ResultReceiver found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:com.android.support.support-compat-27.0.2:)
  Duplicate class android.support.v4.os.ResultReceiver$1 found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:com.android.support.support-compat-27.0.2:)
  Duplicate class android.support.v4.os.ResultReceiver$MyResultReceiver found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:com.android.support.support-compat-27.0.2:)
  Duplicate class android.support.v4.os.ResultReceiver$MyRunnable found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (:com.android.support.support-compat-27.0.2:)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
]
stdout[

> Configure project :
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\28.0.3\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-28\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\28.0.3\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-28\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only

> Task :preBuild UP-TO-DATE
> Task :Firebase:preBuild UP-TO-DATE
> Task :Firebase:preReleaseBuild UP-TO-DATE
> Task :Firebase:checkReleaseManifest
> Task :Firebase:processReleaseManifest
> Task :GooglePlayGamesManifest.plugin:preBuild UP-TO-DATE
> Task :GooglePlayGamesManifest.plugin:preReleaseBuild UP-TO-DATE
> Task :GooglePlayGamesManifest.plugin:checkReleaseManifest
> Task :GooglePlayGamesManifest.plugin:processReleaseManifest
> Task :preReleaseBuild
> Task :Firebase:compileReleaseAidl NO-SOURCE
> Task :GooglePlayGamesManifest.plugin:compileReleaseAidl NO-SOURCE
> Task :compileReleaseAidl NO-SOURCE
> Task :Firebase:packageReleaseRenderscript NO-SOURCE
> Task :GooglePlayGamesManifest.plugin:packageReleaseRenderscript NO-SOURCE
> Task :compileReleaseRenderscript NO-SOURCE
> Task :checkReleaseManifest
> Task :generateReleaseBuildConfig
> Task :prepareLintJar
> Task :generateReleaseSources
> Task :Firebase:compileReleaseRenderscript NO-SOURCE
> Task :Firebase:generateReleaseBuildConfig
> Task :Firebase:generateReleaseResValues
> Task :Firebase:generateReleaseResources
> Task :Firebase:packageReleaseResources
> Task :Firebase:generateReleaseRFile
> Task :Firebase:prepareLintJar
> Task :Firebase:generateReleaseSources
> Task :Firebase:javaPreCompileRelease
> Task :Firebase:compileReleaseJavaWithJavac
> Task :Firebase:bundleLibCompileRelease
> Task :GooglePlayGamesManifest.plugin:compileReleaseRenderscript NO-SOURCE
> Task :GooglePlayGamesManifest.plugin:generateReleaseBuildConfig
> Task :GooglePlayGamesManifest.plugin:generateReleaseResValues
> Task :GooglePlayGamesManifest.plugin:generateReleaseResources
> Task :GooglePlayGamesManifest.plugin:packageReleaseResources
> Task :GooglePlayGamesManifest.plugin:generateReleaseRFile
> Task :GooglePlayGamesManifest.plugin:prepareLintJar
> Task :GooglePlayGamesManifest.plugin:generateReleaseSources
> Task :GooglePlayGamesManifest.plugin:javaPreCompileRelease
> Task :GooglePlayGamesManifest.plugin:compileReleaseJavaWithJavac
> Task :GooglePlayGamesManifest.plugin:bundleLibCompileRelease
> Task :javaPreCompileRelease
> Task :mainApkListPersistenceRelease
> Task :generateReleaseResValues
> Task :generateReleaseResources
> Task :mergeReleaseResources
> Task :createReleaseCompatibleScreenManifests

> Task :processReleaseManifest
C:\Users\Spacepup\Documents\GitHub\AndroidPluginTest\Temp\gradleOut\src\main\AndroidManifest.xml:24:9-31:50 Warning:
	activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present

> Task :processReleaseResources
> Task :compileReleaseJavaWithJavac
> Task :compileReleaseSources
> Task :Firebase:prepareLintJarForPublish
> Task :GooglePlayGamesManifest.plugin:prepareLintJarForPublish
> Task :lintVitalRelease
> Task :mergeReleaseShaders
> Task :compileReleaseShaders
> Task :generateReleaseAssets
> Task :Firebase:mergeReleaseShaders
> Task :Firebase:compileReleaseShaders
> Task :Firebase:generateReleaseAssets
> Task :Firebase:packageReleaseAssets
> Task :GooglePlayGamesManifest.plugin:mergeReleaseShaders
> Task :GooglePlayGamesManifest.plugin:compileReleaseShaders
> Task :GooglePlayGamesManifest.plugin:generateReleaseAssets
> Task :GooglePlayGamesManifest.plugin:packageReleaseAssets
> Task :mergeReleaseAssets
> Task :validateSigningRelease
> Task :signingConfigWriterRelease
> Task :checkReleaseDuplicateClasses FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
47 actionable tasks: 47 executed
]
exit code: 1
  at UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) [0x00031] in <7ac42593e2164800905edc596770b55e>:0 
  at UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) [0x00015] in <7ac42593e2164800905edc596770b55e>:0 
  at UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) [0x0000a] in <7ac42593e2164800905edc596770b55e>:0 
  at UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) [0x0001f] in <7ac42593e2164800905edc596770b55e>:0 
  at UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) [0x00029] in <7ac42593e2164800905edc596770b55e>:0 
Rethrow as GradleInvokationException: Gradle build failed
  at UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) [0x0004d] in <7ac42593e2164800905edc596770b55e>:0 
  at UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) [0x000a8] in <7ac42593e2164800905edc596770b55e>:0 
  at UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) [0x00074] in <7ac42593e2164800905edc596770b55e>:0 
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
  at UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) [0x0001e] in <7ac42593e2164800905edc596770b55e>:0 
  at UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) [0x00110] in <7ac42593e2164800905edc596770b55e>:0 
  at UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) [0x002c8] in <7ac42593e2164800905edc596770b55e>:0 
  at UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) [0x00001] in <7ac42593e2164800905edc596770b55e>:0 
  at UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) [0x000da] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\PostprocessBuildPlayer.cs:281 
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions, Boolean)
UnityEditor.DefaultBuildMethods:BuildPlayer(BuildPlayerOptions) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:169)
UnityEditor.BuildPlayerWindow:CallBuildMethods(Boolean, BuildOptions) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:95)
UnityEditor.BuildPlayerWindow:GUIBuildButtons(IBuildWindowExtension, Boolean, Boolean, Boolean, BuildPlatform) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:896)
UnityEditor.BuildPlayerWindow:ShowBuildTargetSettings() (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:786)
UnityEditor.BuildPlayerWindow:OnGUI() (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:358)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
UnityEditor.HostView:Invoke(String, Object) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:359)
UnityEditor.HostView:Invoke(String) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:353)
UnityEditor.HostView:OldOnGUI() (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:138)
UnityEngine.UIElements.IMGUIContainer:DoOnGUI(Event, Matrix4x4, Rect, Boolean, Rect) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:281)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event, Matrix4x4, Rect) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:483)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:466)
UnityEngine.UIElements.IMGUIContainer:HandleEvent(EventBase) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:447)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent(EventBase, IPanel) (at C:\buildslave\unity\build\Modules\UIElements\Events\MouseCaptureDispatchingStrategy.cs:93)
UnityEngine.UIElements.EventDispatcher:ProcessEvent(EventBase, IPanel) (at C:\buildslave\unity\build\Modules\UIElements\EventDispatcher.cs:280)
UnityEngine.UIElements.EventDispatcher:Dispatch(EventBase, IPanel, DispatchMode) (at C:\buildslave\unity\build\Modules\UIElements\EventDispatcher.cs:156)
UnityEngine.UIElements.BaseVisualElementPanel:SendEvent(EventBase, DispatchMode) (at C:\buildslave\unity\build\Modules\UIElements\Panel.cs:190)
UnityEngine.UIElements.UIElementsUtility:DoDispatch(BaseVisualElementPanel) (at C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:255)
UnityEngine.UIElements.UIElementsUtility:ProcessEvent(Int32, IntPtr) (at C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:78)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:\buildslave\unity\build\Modules\IMGUI\GUIUtility.cs:179)
 
(Filename: <7ac42593e2164800905edc596770b55e> Line: 0)

Unloading 136 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 80.6 MB.
System memory in use after: 80.4 MB.

Unloading 147 unused Assets to reduce memory usage. Loaded Objects now: 1954.
Total: 374.061200 ms (FindLiveObjects: 0.409100 ms CreateObjectMapping: 0.057100 ms MarkObjects: 373.155900 ms  DeleteObjects: 0.437800 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Loaded scene 'Temp/__Backupscenes/0.backup'
	Deserialize:            0.679 ms
	Integration:            104.598 ms
	Integration of assets:  0.005 ms
	Thread Wait Time:       18.640 ms
	Total Operation Time:   123.922 ms
System memory in use before: 76.2 MB.
System memory in use after: 76.3 MB.

Unloading 3 unused Assets to reduce memory usage. Loaded Objects now: 1939.
Total: 346.743500 ms (FindLiveObjects: 0.346300 ms CreateObjectMapping: 0.044800 ms MarkObjects: 346.297100 ms  DeleteObjects: 0.054200 ms)

[ScriptCompilation] Recompiling all scripts because: Recompiling scripts for editor after player build.
- Starting compile Library/ScriptAssemblies/UnityEngine.TestRunner.dll
- Starting compile Library/ScriptAssemblies/UnityEngine.UI.dll
- Finished compile Library/ScriptAssemblies/UnityEngine.TestRunner.dll
- Starting compile Library/ScriptAssemblies/UnityEditor.TestRunner.dll
- Finished compile Library/ScriptAssemblies/UnityEngine.UI.dll
- Finished compile Library/ScriptAssemblies/UnityEditor.TestRunner.dll
- Starting compile Library/ScriptAssemblies/UnityEditor.UI.dll
- Finished compile Library/ScriptAssemblies/UnityEditor.UI.dll
- Starting compile Library/ScriptAssemblies/Unity.TextMeshPro.dll
- Starting compile Library/ScriptAssemblies/Unity.Timeline.dll
- Starting compile Library/ScriptAssemblies/Unity.CollabProxy.Editor.dll
- Starting compile Library/ScriptAssemblies/Unity.VSCode.Editor.dll
- Finished compile Library/ScriptAssemblies/Unity.CollabProxy.Editor.dll
- Starting compile Library/ScriptAssemblies/Unity.Rider.Editor.dll
- Finished compile Library/ScriptAssemblies/Unity.VSCode.Editor.dll
- Finished compile Library/ScriptAssemblies/Unity.Timeline.dll
- Starting compile Library/ScriptAssemblies/Unity.Timeline.Editor.dll
- Finished compile Library/ScriptAssemblies/Unity.TextMeshPro.dll
- Starting compile Library/ScriptAssemblies/Unity.TextMeshPro.Editor.dll
- Finished compile Library/ScriptAssemblies/Unity.Rider.Editor.dll
- Finished compile Library/ScriptAssemblies/Unity.TextMeshPro.Editor.dll
- Finished compile Library/ScriptAssemblies/Unity.Timeline.Editor.dll
- Starting compile Library/ScriptAssemblies/Assembly-CSharp.dll
- Finished compile Library/ScriptAssemblies/Assembly-CSharp.dll
- Starting compile Library/ScriptAssemblies/Assembly-CSharp-Editor.dll
- Finished compile Library/ScriptAssemblies/Assembly-CSharp-Editor.dll
Assets\GooglePlayGames\Platforms\Android\Developers\JavaObjWrapper.cs(352,39): warning CS0618: 'AndroidJNI.CallByteMethod(IntPtr, IntPtr, jvalue[])' is obsolete: 'AndroidJNI.CallByteMethod is obsolete. Use AndroidJNI.CallSByteMethod method instead'
Assets\GooglePlayGames\Platforms\Android\Developers\JavaObjWrapper.cs(417,39): warning CS0618: 'AndroidJNI.CallStaticByteMethod(IntPtr, IntPtr, jvalue[])' is obsolete: 'AndroidJNI.CallStaticByteMethod is obsolete. Use AndroidJNI.CallStaticSByteMethod method instead'
Build completed with a result of 'Failed'
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEditor.DefaultBuildMethods:BuildPlayer(BuildPlayerOptions) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:189)
UnityEditor.BuildPlayerWindow:CallBuildMethods(Boolean, BuildOptions) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:95)
UnityEditor.BuildPlayerWindow:GUIBuildButtons(IBuildWindowExtension, Boolean, Boolean, Boolean, BuildPlatform) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:896)
UnityEditor.BuildPlayerWindow:ShowBuildTargetSettings() (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:786)
UnityEditor.BuildPlayerWindow:OnGUI() (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:358)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
UnityEditor.HostView:Invoke(String, Object) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:359)
UnityEditor.HostView:Invoke(String) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:353)
UnityEditor.HostView:OldOnGUI() (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:138)
UnityEngine.UIElements.IMGUIContainer:DoOnGUI(Event, Matrix4x4, Rect, Boolean, Rect) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:281)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event, Matrix4x4, Rect) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:483)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:466)
UnityEngine.UIElements.IMGUIContainer:HandleEvent(EventBase) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:447)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent(EventBase, IPanel) (at C:\buildslave\unity\build\Modules\UIElements\Events\MouseCaptureDispatchingStrategy.cs:93)
UnityEngine.UIElements.EventDispatcher:ProcessEvent(EventBase, IPanel) (at C:\buildslave\unity\build\Modules\UIElements\EventDispatcher.cs:280)
UnityEngine.UIElements.EventDispatcher:Dispatch(EventBase, IPanel, DispatchMode) (at C:\buildslave\unity\build\Modules\UIElements\EventDispatcher.cs:156)
UnityEngine.UIElements.BaseVisualElementPanel:SendEvent(EventBase, DispatchMode) (at C:\buildslave\unity\build\Modules\UIElements\Panel.cs:190)
UnityEngine.UIElements.UIElementsUtility:DoDispatch(BaseVisualElementPanel) (at C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:255)
UnityEngine.UIElements.UIElementsUtility:ProcessEvent(Int32, IntPtr) (at C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:78)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:\buildslave\unity\build\Modules\IMGUI\GUIUtility.cs:179)
 
(Filename: C:/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs Line: 189)

UnityEditor.BuildPlayerWindow+BuildMethodException: 118 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x00242] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:190 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x0007f] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:95 
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEditor.BuildPlayerWindow:CallBuildMethods(Boolean, BuildOptions) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:100)
UnityEditor.BuildPlayerWindow:GUIBuildButtons(IBuildWindowExtension, Boolean, Boolean, Boolean, BuildPlatform) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:896)
UnityEditor.BuildPlayerWindow:ShowBuildTargetSettings() (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:786)
UnityEditor.BuildPlayerWindow:OnGUI() (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:358)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
UnityEditor.HostView:Invoke(String, Object) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:359)
UnityEditor.HostView:Invoke(String) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:353)
UnityEditor.HostView:OldOnGUI() (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:138)
UnityEngine.UIElements.IMGUIContainer:DoOnGUI(Event, Matrix4x4, Rect, Boolean, Rect) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:281)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event, Matrix4x4, Rect) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:483)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:466)
UnityEngine.UIElements.IMGUIContainer:HandleEvent(EventBase) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:447)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent(EventBase, IPanel) (at C:\buildslave\unity\build\Modules\UIElements\Events\MouseCaptureDispatchingStrategy.cs:93)
UnityEngine.UIElements.EventDispatcher:ProcessEvent(EventBase, IPanel) (at C:\buildslave\unity\build\Modules\UIElements\EventDispatcher.cs:280)
UnityEngine.UIElements.EventDispatcher:Dispatch(EventBase, IPanel, DispatchMode) (at C:\buildslave\unity\build\Modules\UIElements\EventDispatcher.cs:156)
UnityEngine.UIElements.BaseVisualElementPanel:SendEvent(EventBase, DispatchMode) (at C:\buildslave\unity\build\Modules\UIElements\Panel.cs:190)
UnityEngine.UIElements.UIElementsUtility:DoDispatch(BaseVisualElementPanel) (at C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:255)
UnityEngine.UIElements.UIElementsUtility:ProcessEvent(Int32, IntPtr) (at C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:78)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:\buildslave\unity\build\Modules\IMGUI\GUIUtility.cs:179)
 
(Filename: C:/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs Line: 100)

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes

**Comment by patm1987** [comment] 2019-08-21 17:32
Hi @walaoRIKI ,

This looks like a duplicate of #438 . Can you confirm that the fix there works here?

**Comment by patm1987** [comment] 2019-08-21 17:32
Duplicate of #438

**Comment by walaoRIKI** [comment] 2019-08-22 03:44
> 
> 
> Hi @walaoRIKI ,
> 
> This looks like a duplicate of #438 . Can you confirm that the fix there works here?

**Comment by walaoRIKI** [comment] 2019-08-22 03:46
Hi @patm1987 ,

the solution provided in #438 fixed the build issue

ps: Sorry that accidentally closed the issue

**Comment by patm1987** [comment] 2019-08-23 15:48
No problem, you're simply jumping the gun on me closing this anyway!

If you can, keep additional feedback in #438. Of course, this bug is always here if you think that you actually have a different issue!

**Closed by patm1987** 2019-08-23 15:48 UTC
Labels: duplicate
