### ISSUE TITLE
Firebase Sms Authentication is Not working

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/quickstart-unity#428] opened 2019-07-18 12:36 UTC
## Please fill in the following fields:
Unity editor version: 
Firebase Unity SDK version:  firebase 6.2.0 
Firebase plugins in use (Auth, Database, etc.):
Additional SDKs you are using (Facebook, AdMob, etc.): No
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
I  am working in Firebase SMS. I have downloaded the Firebase quick start unity 2018.3.7f1. I have followed all the methods adding (googleservices.json, sha1 method) While running the app the sms is received in my phone.

But the problem is when i entered the sms and try to authenticate the sms.The firebase displayed the error .

Sign in encounted an error. AuthError:Session Expired Firebase.FirebaseException: The sms code has expired.Please re-send the verification code to try again.

actually entered within the seconds. But it says the above error.

Any one can give the suggestion. How to solve this error.
![Screenshot_2019-07-18-17-40-35-62](https://user-images.githubusercontent.com/39626423/61457770-a9bda280-a986-11e9-86ce-aa09b04850e2.png)
## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

**Comment by alexames** [comment] 2019-07-18 21:33
Hi, CLOUDFIRE, 

I've been able to reproduce this locally and I'll let you know what we find.

**Comment by NAYEK82** [comment] 2019-07-19 04:46
@alexjames thanks for your means. What is means "I've been able to reproduce this locally?"  I did not properly understand. 

I 'll let your know when we have a solution. How long it takes?

Is it a bug in Firebase? or  previously i worked in firebase 5.2.0  in auth. Its works fine and good.

Now 6.2 .0 is problem here. 

Kindly explain what i have do for rectify this error?

Did previous works fine? where i can download firebase 5.2 0 sdk + unity quick start examples..

**Comment by alexames** [comment] 2019-07-19 17:54
@NAYEK82 What I meant was that I was able to run the same test app and observe the bug with my test device, so I've confirmed it's a bug in Firebase and not just an issue with @CLOUDFIRE91's configuration. We are currently investigating what the issue is. I don't have a timeline for the fix yet, but I when we figure out what the issue is I'll post an update.

**Comment by NAYEK82** [comment] 2019-07-20 06:27
@ alexjames thanks for your supply. I have googled for this solutions. Actually Firebase 6.2.0 automatically detected the sms. and the verification is done. I also tried. I think auto detection is going on. So kindly check in your side also. confirm  it is correct or not.

if auto check is working. then how can i populate the sms in  text box? That issue should be addressed?

Kindly check and confirm. Auto detection is working or not.

**Comment by CLOUDFIRE91** [comment] 2019-07-24 12:08
@alexames   Am i correct or not... How can i populate the sms in the textbox?

**Comment by alexames** [comment] 2019-07-24 21:49
@CLOUDFIRE91 When you tap on the text box a keyboard should appear that will allow you to input the SMS you received. Does that not happen when you tap the textbox?

**Comment by NAYEK82** [comment] 2019-07-29 09:34
@alexames ... When i tap the text box   a keyboard  is appearing that is allowing me to input the sms  i received. But Whats the problem.  the current version is automatically detecting?.. After i enter  the sms in populating box.. the sms is not validating... 

So i need received sms.. should automatically populating  ... Like Many apps are doing ... For eg.. if we submit  My No ... After sending Sms.. It asks for permission to read sms.. if i  allow.. it will automatically read and populate the sms in  the box... Like that i needed

is is possible in Firebase...

**Comment by alexames** [comment] 2019-12-10 00:40
Hi @CLOUDFIRE91, we were looking into this issue again (sorry for the long turnaround time on this). I think I made a mistake in my original testing. It looks like what happens is that you actually authenticate when you hit the button, but if the button is accidentally tapped a second time you get the error. Which makes sense, because the code was already consumed while authenticating you the first time you hit it. 

If you look at the log in the screenshot you provide you can see a line that shows that the log in was successful, followed by the error message. I had this same behavior when I tapped the authenticate button twice, and I suspect you made the same mistake when using the testapp as well. 

I'm going to go ahead and close this bug because it appears to be actually working as intended, but if after further testing you still experience an error feel free to reopen it so we can take a closer look.

**Closed by alexames** 2019-12-10 00:40 UTC
Labels: type: bug
