### ISSUE TITLE
Not receiving url data in DynamicLinkReceived

### ISSUE THREAD

**Issue by realworld666** [firebase/quickstart-unity#787] opened 2020-09-22 14:18 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.25f1
  * Firebase Unity SDK version: 6.9.0
  * Source you installed the SDK: unitypackage
  * Problematic Firebase Component: DynamicLinks
  * Other Firebase Components in use: Auth, Database, Messaging, Storage
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I have managed to configure Unity and iOS so that dynamic links now open my app. The callback DynamicLinkReceived does not log out the URL as expected either on first boot is the app is not running or during the app if it is running in the background. The same code works fine on Android and I am getting the URL as expected.
On boot, my openURL function prints out `my.app.identifier://google/link/?dismiss=1&is_weak_match=1`

#### Relevant Code:
In Unity I have this
```
		public void Initialize()
		{
			Debug.Log( "FirebaseManagerMobile Initialize" );

#if UNITY_EDITOR
			// Set this before calling into the realtime database.
			FirebaseApp.DefaultInstance.SetEditorDatabaseUrl(
				FirebaseApp.DefaultInstance.Options.DatabaseUrl.ToString() );
#endif
			
			DynamicLinks.DynamicLinkReceived += OnDynamicLink;

			Debug.Log( "FirebaseManagerMobile CheckAndFixDependenciesAsync" );
			FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread( task =>
			{
				Debug.Log( "FirebaseManagerMobile CheckAndFixDependenciesAsync Done" );

			} );
		}

		private void OnDynamicLink( object sender, ReceivedDynamicLinkEventArgs e )
		{
			Debug.LogFormat("Received dynamic link {0}",
				e.ReceivedDynamicLink.Url.OriginalString);
			DynamicLinkReceived?.Invoke( e.ReceivedDynamicLink.Url );
		}
```
I have my associated domains set in my entitlements applinks:mydomain.com
I have a plist entry FirebaseDynamicLinksCustomDomains which is an array containing https://mydomain.com/deeplink
My test deeplink is https://mydomain.com/deeplink/?afl=&amv=0&apn=my.app.identifier&ibi=my.app.identifier&ifl=&ipfl=&link=https://mydomain.com/account.html?email=myemail@gmail.com

I would expect to get https://mydomain.com/account.html?email=myemail@gmail.com logged out in my app but that is not happening. I have followed the suggestions in here https://github.com/firebase/quickstart-unity/issues/436 and haven't been able to resolve my issue

**Comment by patm1987** [comment] 2020-09-22 17:08
Hi @realworld666 ,

Thanks for reporting this. Can I gather a bit more information on your issue:

- Can you reproduce this in the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/dynamic_links/testapp)?
- Is it just the `Url.OriginalString` that doesn't get sent, or does `OnDynamicLink` fail to trigger entirely?
- Would it be possible for you to verify with the latest Firebase Unity SDK? I don't see any Dynamic Links specific fixes listed since 6.9.0 in the [Unity changelog](https://firebase.google.com/support/release-notes/unity), but there may have been fixes in the underlying iOS SDK as well as fixes to general plumbing in the Firebase SDK since then.

**Comment by realworld666** [comment] 2020-09-23 08:44
* I haven't tried the quickstart. The time involved in setting that up isn't really available right now
* `OnDynamicLink` doesn't get called at all.
* I can't update the SDK at the moment as I'm on a tight deadline with this and I'd prefer not to introduce additional variables
I know that's not especially helpful. I'm hoping there might be an obvious reason for this that I've missed.
One thing that occurred to me was that I have subclassed the UnityAppController and overridden `- (BOOL)application:(UIApplication*)application openURL:(NSURL*)url options:(NSDictionary<NSString*, id>*)options` I don't know if that could be related?

**Comment by patm1987** [comment] 2020-09-24 22:45
For the quickstart: it might be easy if you just update the package id to match the one you're using in your game (ie: no need to setup a new project or anything). This is the best thing you can do to help us debug.

Even if you upgrade in a temporary test project, if that fixes the issue then it at least gives us more information to work on. It's still useful to know. I definitely get wanting to keep your dependencies stable though!

Talking with another iOS expert, there's nothing obvious with what you've reported. Overriding `application:openURL:` shouldn't break anything. The suggestion I got was to make sure that you're using the dynamic link preview page on iOS for exact matching -- which in the example link you don't have the parameter to skip it so this isn't likely the issue.

Since you did override `application:openURL:options:`, it's possible but unlikely that you may be interfering with the plumbing for Dynamic Links (see [this integration guide for iOS](https://firebase.google.com/docs/dynamic-links/ios/receive#objective-c_2)). Perhaps try following those instructions and definitely let us know if that fixes your issue.

Also make sure that [method swizzling is enabled](https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in). You have to explicitly disable it, so as long as you don't have `FirebaseAppDelegateProxyEnabled` set to `NO` in your `Info.plist` file then you're good. I again don't think this would be related, but it's a good "just in case".

Let me know if any of that helps!

**Comment by patm1987** [comment] 2020-09-24 22:55
Another thing that may help: you could try moving `DynamicLinks.DynamicLinkReceived += OnDynamicLink;` into `FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread( task =>`. Technically there's no guarantee that anything works before this returns `DependencyStatus.Available`.

**Comment by realworld666** [comment] 2020-09-27 20:52
Not gotten around to the quickstart yet but here's an interesting thing I noticed. When the app is installed for the first time, if you click the deeplink before opening the app, the URL is parsed by the app correctly. Once the app has been opened at least once, even if it is force closed, the link won't be parsed.

**Comment by realworld666** [comment] 2020-09-28 14:30
I have also now reproduced in the quickstart

**Comment by realworld666** [comment] 2020-09-30 13:05
I have tested my implementation with no overridden UnityAppController and with a modified MyAppController which looks like the below. Neither made any difference to the problem I am facing. I am utterly out of ideas now as to how to fix this. Please advise on how I can proceed.

**Comment by realworld666** [comment] 2020-10-02 14:14
I have also tried updating to the latest Firebase SDK and switched to the package manager way of managing installs and that also did not fix the issue.

**Comment by chkuang-g** [comment] 2020-10-21 18:37
Hi @realworld666 

This looks similar to https://github.com/firebase/quickstart-unity/issues/626#issuecomment-612060018

Does the workaround work for you?
Also, which latest Firebase SDK version did you try? 

Shawn

**Comment by chkuang-g** [comment] 2020-10-22 23:27
As commented in https://github.com/firebase/quickstart-unity/issues/626#issuecomment-714810692, the fix should be included in the latest SDK.

@realworld666 Could you verify if the issue is resolved with latest Unity SDK?

Thank you,
Shawn

**Comment by realworld666** [comment] 2020-10-26 12:32
I have tried the latest SDK and my situation has not improved.
This is logging on application start. 
```
2020-10-26 12:24:22.576998+0000 stressfree[860:341153] 6.32.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2020-10-26 12:24:22.586814+0000 stressfree[860:340812] [Firebase/Crashlytics] Version 4.6.2
2020-10-26 12:24:22.629894+0000 stressfree[860:341153] 6.32.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60802000 started
2020-10-26 12:24:22.630429+0000 stressfree[860:341153] 6.32.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-10-26 12:24:22.744006+0000 stressfree[860:340812] WF: === Starting WebFilter logging for process stressfree
2020-10-26 12:24:22.744060+0000 stressfree[860:340812] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2020-10-26 12:24:22.744100+0000 stressfree[860:340812] WF: _WebFilterIsActive returning: NO
FirebaseManagerMobile CheckAndFixDependenciesAsync
ThriveCore.Core.Firebase.FirebaseManagerMobile:Initialize()
Zenject.InitializableManager:Initialize()
```
then later in the log
```
2020-10-26 12:24:22.867143+0000 stressfree[860:341171] 6.32.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
2020-10-26 12:24:22.867837+0000 stressfree[860:341171] 6.32.0 - [Firebase/Analytics][I-ACS023013] Analytics collection disabled
Setting up 1 worker threads for Enlighten.
  Thread -> id: 16ed5b000 -> priority: 1 
2020-10-26 12:24:23.074626+0000 stressfree[860:341153] 6.32.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=404, type=2, request_id=, content_type=text/html; charset=utf-8}
FirebaseManagerMobile CheckAndFixDependenciesAsync Done
ThriveCore.Core.Firebase.FirebaseManagerMobile:<Initialize>b__28_0(Task`1)
Firebase.Extensions.<ContinueWithOnMainThread>c__AnonStorey9:<>m__0()
Firebase.<RunAsync>c__AnonStorey1`1:<>m__0()
Firebase.ExceptionAggregator:Wrap(Action)
Firebase.Dispatcher:PollJobs()
Firebase.Platform.FirebaseHandler:Update()
 
(Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

FirebaseManagerMobile CheckAndFixDependenciesAsync Success
ThriveCore.Core.Firebase.FirebaseManagerMobile:<Initialize>b__28_0(Task`1)
Firebase.Extensions.<ContinueWithOnMainThread>c__AnonStorey9:<>m__0()
Firebase.<RunAsync>c__AnonStorey1`1:<>m__0()
Firebase.ExceptionAggregator:Wrap(Action)
Firebase.Dispatcher:PollJobs()
Firebase.Platform.FirebaseHandler:Update()
```
When clicking a link and the app opens I can see no logs related to dynamic links at all

**Comment by patm1987** [comment] 2020-11-07 00:23
Hi @realworld666 ,

We've tried to reproduce this in the quickstart app with no luck. Can you verify on your side that this issue happens in the [quickstart app](https://github.com/firebase/quickstart-unity/tree/master/dynamic_links/testapp) (try dropping your credentials into it and doing a local build)?

Can you also share the link that you're generating so we can spot any issues there?

Thanks,
--Patrick

**Comment by realworld666** [comment] 2020-11-12 09:22
As I said earlier in the thread, yes I reproduced with the quickstart. I can send you a copy if you let me know how to send it.
The link I am using is https://dev.deeplink.thrive.uk.com/?afl=&amv=302120000&apn=com.help.stressfree&ibi=com.help.stressfree&ifl=&ofl=https://dev.thrive.uk.com/account.html?email=2809@grr.la&imv=3.2.12&isi=1048928580&ipfl=&link=https://thrive.uk.com/account.html?email=2809@grr.la
It works fine on Android. Only iOS is causing an issue and even then I have seen it work when the app is run for the first time after a clean install. It just never works again after that

**Comment by chkuang-g** [comment] 2020-11-25 20:44
@realworld666 

Sorry this has been going back and forth for months. 

The link you provided looks alright. Tip: you can add `&d=1` at the end of the url to see a flow chart of how it will behave.

Since we are unable to reproduce it (I just tried to build quickstart with Firebase `6.16.0` in Unity 2018.4.23f1 with Xcode 11.7), I suspect this might be related to certain configurations in your specific case. And I suspect it may be related to the custom domain.

Building Dynamic Link sample is a bit tricky since it requires a specific mobile provision file. And you probably do not want to share the provision file and your Firebase console API key to the public.

Here is my recommendation: try to file a ticket to [Firebase Support](https://firebase.google.com/support/troubleshooter/report/bugs) page.  In the ticket, try to provide the following information:
- Url to this Github issue
- Firebase Unity SDK version
- Unity version
- The Unity quickstart project you used to reproduce the issue, including Firebase SDK and your Firebase config file.  You can zip it and share it through Google Drive (or any cloud storage).
- The Xcode project generated from Unity with all the configuration you used including `Associated Domains capability` and `FirebaseDynamicLinksCustomDomains`.  Similarly you can share it through any cloud storage.
- The Dynamic Link url you are using (the point from your last post)

This way, you can not only share your project to us confidentially but also have more eyes on your situation.  I think that will eventually loop back to us but at that point we can have more information to debug for your case.

Shawn

**Comment by realworld666** [comment] 2020-12-03 21:46
Thanks. I've submitted a bug report with a sample project

**Comment by DellaBitta** [comment] 2020-12-09 18:45
Hi @realworld666, 

I'm going to close this issue for now as the support channel is now the main path forward for solving this issue.  Feel free to ping us if anything else comes up.

**Closed** 2020-12-09 18:45 UTC
Labels: api: dynamiclinks
