### ISSUE TITLE
Not all Exceptions reported to Crashlytics[Bug] 

### ISSUE THREAD

**Issue by Karottenrambo** [firebase/quickstart-unity#998] opened 2021-03-16 15:01 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.22F1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics(Auth, Database, etc.)
  * Other Firebase Components in use: Analytics(Auth, Database, etc.)
  * Additional SDKs you are using: none (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android(iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:
Exception thrown in the Start() Method are not reported to Crashlytics.

#### Steps to reproduce:

I used the example from the documentation:
https://firebase.google.com/docs/crashlytics/test-implementation?platform=unity

The original exception gets reported without issues, however, the exception I added in this Start() Methos does not get reported at all.
If I add a 2nd exception in the throwExceptionEvery60Updates() method, only the first exception gets reported.

in the adb log, all exception are displayed correctly.

I have also other exceptions on other start methods, they all fail to report :/

I already made sure that the script execution order is correct.

//code here to reproduce the problem
```
public class CrashlyticsTester : MonoBehaviour
{

    int updatesBeforeException;

    void Start()
    {
        updatesBeforeException = 0;

        //this one is not reported
        throw new Exception("Exception at start");
    }

    void Update()
    {
        throwExceptionEvery60Updates();
    }

    void throwExceptionEvery60Updates()
    {
        if (updatesBeforeException > 0)
        {
            updatesBeforeException--;
        }
        else
        {
            // Set the counter to 60 updates
            updatesBeforeException = 60;

            //This one is reported
            throw new Exception("test exception please ignore");

            //this one is not reported
            throw new Exception("Oh Bother 2");
        }
    }
}

**Comment by paulinon** [comment] 2021-03-16 17:26
Hi @Karottenrambo,

I was able to reproduce the behavior you described. Here are my findings regarding the exceptions not being thrown.

The first one is in the Start() function. It's possible that it's not being reported because the FirebaseApp is not initiated yet. Naturally, the exception cannot be enforced when you instantiate the object during gameplay.

The second exception you observed is the one right below the one that is successfully being reported. It's possible that this is being ignored because the exception before it was successfully reported. For instances like this, I believe that using a try/catch block is the way to go as seen [here](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=unity#log-excepts).

I also suggest that you follow the [quickstart](https://github.com/firebase/quickstart-unity/blob/master/crashlytics/testapp/Assets/Firebase/Sample/Crashlytics/UIHandler.cs) so that you can gather more insights on how Crashlytics is being implemented in a Unity project.

I'll be closing this ticket for now. Feel free to reopen if you have any other questions.

Thanks!

**Closed by paulinon** 2021-03-16 17:26 UTC
Labels: api: crashlytics, new, type: question
