### ISSUE TITLE
WebSocketException during handshake on 2019.1

### ISSUE THREAD

**Issue by michelleran** [firebase/quickstart-unity#386] opened 2019-06-15 14:58 UTC
## Please fill in the following fields:
Unity editor version: 2019.1.3f1
Firebase Unity SDK version: 6.1.1
Firebase plugins in use (Auth, Database, etc.): Analytics, Database
Additional SDKs you are using (Facebook, AdMob, etc.): none
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): editor, iOS, Android

## Please describe the issue here:

Unity project using Firebase SDKs (.NET 4.x) crashes when trying to run in the editor with the following error:

```
6/15/2019 3:06:08 PM [Error] WebSocket: ws_0 - could not connect
System.Net.Sockets.SocketException (0x80004005): No route to host
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remoteEP) [0x00033] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x000ea] in Z:\tmp\tmp.8Sor2bVQK4\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:323 
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.o008zdRzg2/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:19)
Firebase.Unity.UnityLoggingService:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.o008zdRzg2/firebase/app/client/unity/src/Unity/UnityLoggingService.cs:13)
Firebase.Database.Internal.Logging.DefaultLogger:Error(String, String) (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:68)
Firebase.Database.Internal.Logging.DefaultLogger:OnLogMessage(Level, String, String, Int64) (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:32)
Firebase.Database.Internal.Logging.LogWrapper:Error(String, Exception) (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/Logging/LogWrapper.cs:36)
Firebase.Database.Internal.TubeSock.WebSocket:LogError(String, Exception) (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:143)
Firebase.Database.Internal.TubeSock.WebSocket:CreateSocket() (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:325)
Firebase.Database.Internal.TubeSock.WebSocket:RunReader() (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:386)
Firebase.Database.Internal.TubeSock.Runnable101:Run() (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:516)
Google.Sharpen.Thread:InternalRun() (at Z:/tmp/tmp.gUud70lzn5/third_party/dotnet_src/sharpen/Sharpen/Thread.cs:80)
System.Threading.ThreadHelper:ThreadStart()

6/15/2019 3:06:08 PM [Error] WebSocket: ws_0 - WebSocketException during handshake
Firebase.Database.Internal.TubeSock.WebSocketException: unknown host: megasim-9bbf2.firebaseio.com ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remoteEP) [0x00033] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x000ea] in Z:\tmp\tmp.8Sor2bVQK4\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:323 
   --- End of inner exception stack trace ---
  at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x0010c] in Z:\tmp\tmp.8Sor2bVQK4\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:327 
  at Firebase.Database.Internal.TubeSock.WebSocket.RunReader () [0x0001b] in Z:\tmp\tmp.8Sor2bVQK4\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:386 
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.o008zdRzg2/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:19)
Firebase.Unity.UnityLoggingService:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.o008zdRzg2/firebase/app/client/unity/src/Unity/UnityLoggingService.cs:13)
Firebase.Database.Internal.Logging.DefaultLogger:Error(String, String) (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:68)
Firebase.Database.Internal.Logging.DefaultLogger:OnLogMessage(Level, String, String, Int64) (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:32)
Firebase.Database.Internal.Logging.LogWrapper:Error(String, Exception) (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/Logging/LogWrapper.cs:36)
Firebase.Database.Internal.TubeSock.WebSocket:LogError(String, Exception) (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:143)
Firebase.Database.Internal.TubeSock.WebSocket:RunReader() (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:468)
Firebase.Database.Internal.TubeSock.Runnable101:Run() (at Z:/tmp/tmp.8Sor2bVQK4/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:516)
Google.Sharpen.Thread:InternalRun() (at Z:/tmp/tmp.gUud70lzn5/third_party/dotnet_src/sharpen/Sharpen/Thread.cs:80)
System.Threading.ThreadHelper:ThreadStart()
```

Steps to reproduce:
1. Create new Unity project
2. Add iOS and Android config files
3. Update package names accordingly
4. Import Firebase Analytics and Database
5. Create script initializing Firebase app and database and attach to camera
6. Run game in editor

How do I fix this?

**Comment by patm1987** [comment] 2019-06-19 00:38
Hi @michelleran, thanks for reporting this issue!

Can you answer a few more questions for me?
1) does it work on your Android device or is it just broken in the editor
2) if it does only break in the editor, does it break under all network conditions? Desktop support for Realtime Database is beta, and there are some corner cases not handled that usually result from corner cases around corporate firewalls.
3) Try disabling the dll at "Firebase/Plugins/Mono/Firebase.Database.dll" and enabling the one at "Firebase/Plugins/Firebase.Database.dll". If this is successful, make sure that this hack doesn't live into your device builds, as this one will lend to a generally worse (slower) experience on devices.

For more information on what I suspect this is see bug https://github.com/firebase/quickstart-unity/issues/106 . Let me know if that helps (so I can mark this as a duplicate or see if it needs further investigation).

**Comment by alexames** [comment] 2019-06-19 23:11
Hi @michelleran, 

Have you tried running the unity database testapp in this repository? If not, try running it and seeing if you get the same error.

**Comment by michelleran** [comment] 2019-06-20 15:06
@alexames yep, same error (using .NET 4.x SDKs and Unity 2019.1.6f1).

@patm1987 it works on Android, as well as with Mono/Firebase.Database.dll disabled. I don't think it breaking in the editor is because of network conditions since I'm connected to a home network, which, as far as I'm aware, doesn't have any unusual configurations.

**Comment by patm1987** [comment] 2019-06-20 16:18
Duplicate of #106

**Comment by patm1987** [comment] 2019-06-20 16:19
I do think that this is likely a duplicate of bug #106. The callstacks look the same and the same workaround seems to work for you. If you disagree, let me know!

**Comment by stewartmiles** [comment] 2019-06-25 22:31
Closing as a dupe of #106

**Closed by stewartmiles** 2019-06-25 22:31 UTC
Labels: duplicate
