### ISSUE TITLE
FCM Data Messages not being received

### ISSUE THREAD

**Issue by muneebattamindravel** [firebase/quickstart-unity#99] opened 2017-08-10 12:50 UTC
I am not getting the Data Messages. Here is the complete detail of what i am doing and what is happening:

I am using Unity 5.6.1f1 and latest Firebase SDK for Messaging.
I am using a php script to send the messages.
The notification messages are displayed fine. Custom data fields in the "Notification Message" (in t the "data" key) are also retrieved fine in the "OnMessageReceived" method, with the following script:
`<?php
$json_notificationMessage = '{ "data": {
"command": "hit",
"challengeScore": "35"
},
"notification":{
"title":"Hello Title",
"body":"Hello Body",
"sound":"default"
}
"to": "DEVICE_TOKEN",
"priority": "high"
}';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Content-Type: application/json',
'Authorization:key=SERVER_KEY'
));
curl_setopt($ch, CURLOPT_POSTFIELDS, $json_notificationMessage);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$output = curl_exec($ch);
curl_close($ch);
echo $output;
But the PROBLEM WITH THIS is that i have to click on the notification to get the OnMessageReceived function called.

Now i am sending the FCM Data Message so that i don't have to click on the notification to get the OnMessageReceived function called. But i am not receiving the Data Messages when my app is in background or closed (quit). Following is the php script that i am using for sending the Data Message:
$json_dataMessage = '{ "data": {
"command": "hit",
"challengeScore": "35"
},
"to": "DEVICE_TOKEN",
"priority": "high"
}';

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Content-Type: application/json',
'Authorization:key=SERVER_KEY'
));
curl_setopt($ch, CURLOPT_POSTFIELDS, $json_dataMessage);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$output = curl_exec($ch);
curl_close($ch);
echo $output;`

I read the following note from the "About FCM Messages" page of Firebase documentation
"Note: If you want to send messages consisting of only custom key-values to an iOS device when the app is in the background, set custom key-value pairs in the data key and set content_available to true."

so i added the content_available:true so that my jSON now looks like this:

$json_dataMessage = '{ "data": {
"command": "hit",
"challengeScore": "35"
},
"to": "DEVICE_TOKEN",
"priority": "high",
"content_available":true
}';

And i received the Data Message BUT ONLY when my app was in foreground (visible on screen).

My requirement is that i want to get the Data Payload even if a user does not clicks on the notification. According to FCM, Data Message is the way to do this but i am not getting that custom data payload if the app is in background or closed.
Please help in this regard on how can i achieve this functionality.

Thank-you.

**Comment by alexames** [comment] 2017-08-11 00:07
Looking over what you did, it sounds correct. I'm not sure why you're not receiving data messages while the app is in the background or closed. I'll see if I can reproduce the bug internally to see if we have an issue in the library.

I did learn though that there are some cases where messages aren't able to be delivered: If you force close the app (by double tapping home and swiping it away) that tells the OS to not deliver messages at all, at least until you start the app again. Also, if you just turned on the iOS device but have not yet started the app even once, then messages cannot be delivered. I don't think these limitations are mentioned in the documentation, so I'll see to it that those caveats are added. 

In the meantime, can you try running your app, hitting home so that your app is backgrounded, and then sending a data message? This use-case *should* work, and if it doesn't it might be an issue on our end.

**Comment by muneebattamindravel** [comment] 2017-08-11 11:23
Thank-you for the reply. 
When the app is backgrounded (i.e open the app and then press the home button), i can get the Data Message fine (when i open app again). 

But the functionality that i want (and which is specified in the Firebase documentation and also mentioned above by you in the comment) is that i should get the Data Messages even when the app is closed. When i open the app next time, it should give me that Data Message. 

Is this not possible ? Like when the app is quit (force quitted) Data Messages are not received? If not, then how are Data Messages different from Notification Messages?

You mentioned: "If you force close the app (by double tapping home and swiping it away) that tells the OS to not deliver messages at all, at least until you start the app again"

Is there no other way to achieve this functionality? Maybe call some Firebase API function to get the Data Messages that were not delivered (Because the app was force quit)? 

Waiting for your reply. Thanks.

**Comment by alexames** [comment] 2017-08-11 16:43
> Is this not possible ? Like when the app is quit (force quitted) Data Messages are not received? If not, then how are Data Messages different from Notification Messages?

Notifications follow a slightly different code path - iOS has special support for displaying notifications even when the app isn't running. However, sending data to the app itself is only done on a 'best-effort' basis. There are a few situations which can cause the delivery to fail, at least on iOS, and there's not much we can do to solve that since its a limitation of the OS. Data messages are helpful pings saying "content is available", with a chance to retrieve (pre-cache) some information for next app start. On next app start, check the cache, or go fetch whatever you need to fetch

> Is there no other way to achieve this functionality? Maybe call some Firebase API function to get the Data Messages that were not delivered (Because the app was force quit)?

If you absolutely need your app to be aware of all  data messages on iOS, you might need to keep track of the outgoing messages on your server, and have your app query your server to see which ones haven't been delivered yet.

**Comment by muneebattamindravel** [comment] 2017-08-12 09:07
Alright, so basically i will need my own server implementation and discard (not use) FCM Data Messages for this task because they won't ensure the delivery every time and for every case (due to limitations of OS). Correct? 

One question though, doesn't Firebase keeps track of the Sent Data Messages? Is there an API available for that in Firebase SDK which i can call to get all the previous Data Messages? Or the Data Messages that were not delivered?

**Comment by alexames** [comment] 2017-08-23 23:10
Sorry for the delayed reply, I somehow overlooked this message.

> Correct?

Yes, if you need to be absolutely sure that apps receive a message you'll need to have a server on your end that your app can check on for missed messages.

> One question though, doesn't Firebase keeps track of the Sent Data Messages? Is there an API available for that in Firebase SDK which i can call to get all the previous Data Messages? Or the Data Messages that were not delivered?

The FCM servers keep track of pending messages (messages that have not been delivered to the device yet). Once the message is delivered, or the message times out, the message is discarded by the server. If the server had to discard a message that didn't get delivered the app will be notified with a special message informing it that messages were dropped. There's no API to get pending or deleted messages from FCM. If you need that you'll need to keep track of the messages you sent out on your end and set up a way for your app to query those messages.

**Comment by alexames** [comment] 2017-08-24 17:16
I'm going to go ahead and close this issue. If you have additional questions feel free to reopen or create a new issue.

**Closed** 2017-08-24 17:17 UTC

**Comment by timolor** [comment] 2019-07-28 20:04
This worked for me 

`CURL *hnd = curl_easy_init();

curl_easy_setopt(hnd, CURLOPT_CUSTOMREQUEST, "POST");
curl_easy_setopt(hnd, CURLOPT_URL, "https://fcm.googleapis.com/fcm/send");

struct curl_slist *headers = NULL;
headers = curl_slist_append(headers, "cache-control: no-cache");
headers = curl_slist_append(headers, "authorization: key=[SERVER_KEY]");
headers = curl_slist_append(headers, "content-type: application/json");
curl_easy_setopt(hnd, CURLOPT_HTTPHEADER, headers);

curl_easy_setopt(hnd, CURLOPT_POSTFIELDS, "{"notification": {"title": "Hey!","body" : "Check Out This Awesome `Game!"},"registration_ids":` ["USER_TOKEN"]}");

CURLcode ret = curl_easy_perform(hnd);`
