### ISSUE TITLE
Add crash reporting support for Unity

### ISSUE THREAD

**Issue by liortal53** [firebase/quickstart-unity#73] opened 2017-03-30 09:39 UTC
Currently, other services are available as part of the Unity SDK, but crash reporting is not a part of them.

I'd like to integrate crash reporting for our game (iOS and Android), waiting for the official support (maybe it is delayed due to the Fabric acquisition?)

**Comment by stewartmiles** [comment] 2017-03-30 14:48
At the moment Firebase Crash reporting doesn't support C/C++ or C# stack
reporting so the usefulness of the product for game developers is limited
to determining whether a game crashed but not why the game crashed.  If you
need support for crash reporting right now with no real context then I
recommend rolling your own integration for the moment.

Cheers,
Stewart

**Comment by liortal53** [comment] 2017-03-30 14:56
In a normal C# app, when an unhandled exception occurs, the process is quit (crashes). In Unity however, the behavior is different (actually i am not sure it is a defined behavior). An exception occurs, but the game keeps on running.

From what i've seen, crashes that kill the game are only ones that occur in native code (e.g: on Android, in C++ or Java code).

On iOS, since all code is converted to c++, i am not really show what the exact behavior is.

Things i'd like to see (let me know if these *are* currently supported):
allow logging custom errors or exceptions that occur, log native (java, obj-c or native platform crashes).

If these are supported, we are good to go :)

**Comment by stewartmiles** [comment] 2017-03-30 14:58
Neither case is supported at the moment with Firebase Crash reporting as I
mentioned neither C/C++ or C# stack traces are supported.

Crashlytics however does support this so that would be a better way to go
IMHO.

**Comment by liortal53** [comment] 2017-03-30 15:08
I will look into that, though i am not sure what will be of Crashlytics (Fabric) following the acquisition and whether everything will remain as is with the service.

**Comment by stewartmiles** [comment] 2017-03-30 15:18
See
https://fabric.io/blog/fabric-joins-google/
https://firebase.googleblog.com/2017/01/FabricJoinsGoogle17.html

Similar to the Firebase (i.e real-time database) acquisition, Crashlytics
is currently planned to live on within Google.

**Comment by stewartmiles** [comment] 2018-06-22 16:45
Closing as a duplicate of #147

**Closed by stewartmiles** 2018-06-22 16:45 UTC
Labels: enhancement
