### ISSUE TITLE
[Question] How to change the package name of an existing project

### ISSUE THREAD

**Issue by gayanW** [firebase/quickstart-unity#1043] opened 2021-05-09 11:17 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 8018.4.34f1
  * Firebase Unity SDK version: 
  
Not exactly sure. But `Firebase/Editor/AppDependencies.xml` contain following lines:
```
<iosPod name="Firebase/Core" version="5.16.0" minTargetSdk="8.0">
<androidPackage spec="com.google.firebase:firebase-common:16.0.4">
<androidPackage spec="com.google.firebase:firebase-core:16.0.7">
<androidPackage spec="com.google.firebase:firebase-app-unity:5.5.0">
```
  * Source you installed the SDK: unitypackage
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Linux
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

I'm preparing a premium version of an existing android application. And I just need to rename the package name in my Unity Android project.

The steps I followed prior to update the package name in Unity `Player Settings` as follows:

- Created a new Firebase project with the new package name
- Downloaded google-services.json
- While in Unity Editor, backup/renamed the old `google-services.json` -> `google-services-old.json`
- Import the new `google-services.json` file to the assets folder

After importing the new `google-services.json` the following error is shown in the console:
```
Project Bundle ID defaulttm.gravity does not match any bundle IDs in your google-services.json files
This will result in an app that will fail to initialize.

Available Bundle IDs:
gravity.premium

You need to either:
* Fix your app's bundle ID under "Player Settings --> Bundle Identifier"
or:
* Add another app to your firebase project
  Goto https://firebase.google.com/docs/unity/setup#add_firebase_to_your_app_1
  and add the new configuration file to your project.
```

Then in `Player Settings`, I set the package name to the new name. Just after I updated package name, I got a prompt saying,
```
Moving File Failed
Moving Temp/copyassets/google-services.json to Assets/StreamingAssets/google-services-desktop.json
```
The following lines were shown In the Unity Editor logs:

```
*** bb0aae3e21fd6af8dbb001d7e2ab7b71 replaces 4bac85f7aece20724ba43e10e0c3b86b at path assets/streamingassets/google-services-desktop.json 
Updating Assets/StreamingAssets/google-services-desktop.json - GUID: bb0aae3e21fd6af8dbb001d7e2ab7b71...
```
After canceling the 'Move file failed' prompt, Unity starts resolving Android dependencies.

After the resolving is completed, the following files are being changed in the project:

```
Changes not staged for commit:
        modified:   .idea/.idea.gravity-x/.idea/workspace.xml
        modified:   Assets/Plugins/Android/Firebase/res/values/google-services.xml
        deleted:    Assets/Plugins/Android/androidx.arch.core.core-common-2.0.0.jar
        deleted:    Assets/Plugins/Android/androidx.arch.core.core-common-2.0.0.jar.meta
        deleted:    Assets/Plugins/Android/androidx.arch.core.core-runtime-2.0.0.aar
        deleted:    Assets/Plugins/Android/androidx.arch.core.core-runtime-2.0.0.aar.meta
        deleted:    Assets/Plugins/Android/androidx.core.core-1.0.0.aar
        deleted:    Assets/Plugins/Android/androidx.core.core-1.0.0.aar.meta
        deleted:    Assets/Plugins/Android/androidx.versionedparcelable.versionedparcelable-1.0.0.aar
        deleted:    Assets/Plugins/Android/androidx.versionedparcelable.versionedparcelable-1.0.0.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-ads-19.1.0.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-ads-19.1.0.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-ads-base-19.1.0.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-ads-base-19.1.0.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-ads-lite-19.1.0.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-ads-lite-19.1.0.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-base-17.0.0.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-base-17.0.0.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-basement-17.0.0.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-basement-17.0.0.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-gass-19.1.0.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-gass-19.1.0.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-17.4.3.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-17.4.3.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-api-17.4.3.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-api-17.4.3.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-base-17.4.3.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-base-17.4.3.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-impl-17.4.3.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-impl-17.4.3.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-sdk-17.4.3.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-sdk-17.4.3.aar.meta
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-sdk-api-17.4.3.aar
        deleted:    Assets/Plugins/Android/com.google.android.gms.play-services-measurement-sdk-api-17.4.3.aar.meta
        deleted:    Assets/Plugins/Android/com.google.firebase.firebase-analytics-17.4.3.aar
        deleted:    Assets/Plugins/Android/com.google.firebase.firebase-analytics-17.4.3.aar.meta
        modified:   Assets/Plugins/Android/com.google.firebase.firebase-analytics-unity-5.5.0.aar
        modified:   Assets/Plugins/Android/com.google.firebase.firebase-app-unity-5.5.0.aar
        modified:   Assets/Plugins/Android/com.google.firebase.firebase-common-19.3.0.aar
        deleted:    Assets/Plugins/Android/com.google.firebase.firebase-core-17.4.3.aar
        deleted:    Assets/Plugins/Android/com.google.firebase.firebase-core-17.4.3.aar.meta
        deleted:    Assets/Plugins/Android/com.google.firebase.firebase-iid-20.1.5.aar
        deleted:    Assets/Plugins/Android/com.google.firebase.firebase-iid-20.1.5.aar.meta
        deleted:    Assets/Plugins/Android/com.google.firebase.firebase-iid-interop-17.0.0.aar
        deleted:    Assets/Plugins/Android/com.google.firebase.firebase-iid-interop-17.0.0.aar.meta
        deleted:    Assets/Plugins/Android/com.google.firebase.firebase-installations-16.2.1.aar
        deleted:    Assets/Plugins/Android/com.google.firebase.firebase-installations-16.2.1.aar.meta
        modified:   Assets/StreamingAssets/google-services-desktop.json
        modified:   Assets/StreamingAssets/google-services-desktop.json.meta
        modified:   Assets/google-services.json
        modified:   Assets/google-services.json.meta
        modified:   ProjectSettings/AndroidResolverDependencies.xml
        modified:   ProjectSettings/ProjectSettings.asset

Untracked files:
        Assets/Plugins/Android/androidx.arch.core.core-common-2.0.1.jar
        Assets/Plugins/Android/androidx.arch.core.core-common-2.0.1.jar.meta
        Assets/Plugins/Android/androidx.arch.core.core-runtime-2.0.1.aar
        Assets/Plugins/Android/androidx.arch.core.core-runtime-2.0.1.aar.meta
        Assets/Plugins/Android/androidx.core.core-1.2.0.aar
        Assets/Plugins/Android/androidx.core.core-1.2.0.aar.meta
        Assets/Plugins/Android/androidx.lifecycle.lifecycle-service-2.0.0.aar
        Assets/Plugins/Android/androidx.lifecycle.lifecycle-service-2.0.0.aar.meta
        Assets/Plugins/Android/androidx.room.room-common-2.1.0.jar
        Assets/Plugins/Android/androidx.room.room-common-2.1.0.jar.meta
        Assets/Plugins/Android/androidx.room.room-runtime-2.1.0.aar
        Assets/Plugins/Android/androidx.room.room-runtime-2.1.0.aar.meta
        Assets/Plugins/Android/androidx.sqlite.sqlite-2.0.1.aar
        Assets/Plugins/Android/androidx.sqlite.sqlite-2.0.1.aar.meta
        Assets/Plugins/Android/androidx.sqlite.sqlite-framework-2.0.1.aar
        Assets/Plugins/Android/androidx.sqlite.sqlite-framework-2.0.1.aar.meta
        Assets/Plugins/Android/androidx.versionedparcelable.versionedparcelable-1.1.0.aar
        Assets/Plugins/Android/androidx.versionedparcelable.versionedparcelable-1.1.0.aar.meta
        Assets/Plugins/Android/androidx.work.work-runtime-2.1.0.aar
        Assets/Plugins/Android/androidx.work.work-runtime-2.1.0.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-ads-20.1.0.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-ads-20.1.0.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-ads-base-20.1.0.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-ads-base-20.1.0.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-ads-lite-20.1.0.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-ads-lite-20.1.0.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-base-16.0.1.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-base-16.0.1.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-basement-17.6.0.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-basement-17.6.0.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-18.0.3.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-18.0.3.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-api-18.0.3.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-api-18.0.3.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-base-18.0.3.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-base-18.0.3.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-impl-18.0.3.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-impl-18.0.3.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-sdk-18.0.3.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-sdk-18.0.3.aar.meta
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-sdk-api-18.0.3.aar
        Assets/Plugins/Android/com.google.android.gms.play-services-measurement-sdk-api-18.0.3.aar.meta
        Assets/Plugins/Android/com.google.android.ump.user-messaging-platform-1.0.0.aar
        Assets/Plugins/Android/com.google.android.ump.user-messaging-platform-1.0.0.aar.meta
        Assets/Plugins/Android/com.google.firebase.firebase-analytics-18.0.3.aar
        Assets/Plugins/Android/com.google.firebase.firebase-analytics-18.0.3.aar.meta
        Assets/Plugins/Android/com.google.firebase.firebase-core-18.0.3.aar
        Assets/Plugins/Android/com.google.firebase.firebase-core-18.0.3.aar.meta
        Assets/Plugins/Android/com.google.firebase.firebase-iid-17.0.4.aar
        Assets/Plugins/Android/com.google.firebase.firebase-iid-17.0.4.aar.meta
        Assets/Plugins/Android/com.google.firebase.firebase-iid-interop-16.0.1.aar
        Assets/Plugins/Android/com.google.firebase.firebase-iid-interop-16.0.1.aar.meta
        Assets/Plugins/Android/com.google.firebase.firebase-installations-16.3.2.aar
        Assets/Plugins/Android/com.google.firebase.firebase-installations-16.3.2.aar.meta
        Assets/Plugins/Android/com.google.guava.listenablefuture-1.0.jar
        Assets/Plugins/Android/com.google.guava.listenablefuture-1.0.jar.meta
```

Then when I tried to build the project, I get the following error:

```
home/gayanw/Unity/Hub/Editor/2018.4.34f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/OpenJDK/Linux/bin/java -classpath "/home/gayanw/Unity/Hub/Editor/2018.4.34f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-5.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "bundleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bundleReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /home/gayanw/bitbucket/gravity-x/Temp/gradleOut/build/intermediates/bundle_manifest/release/processReleaseManifest/bundle-manifest/AndroidManifest.xml:44: error: unexpected element <queries> found in <manifest>.

BUILD FAILED in 8s
]
stdout[

> Configure project :
WARNING: The option setting 'android.bundle.enableUncompressedNativeLibs=false' is experimental and unsupported.
The current default is 'true'.

> Configure project :Firebase
WARNING: The option setting 'android.bundle.enableUncompressedNativeLibs=false' is experimental and unsupported.
The current default is 'true'.

> Configure project :GoogleMobileAdsPlugin
WARNING: The option setting 'android.bundle.enableUncompressedNativeLibs=false' is experimental and unsupported.
The current default is 'true'.
```
I tried building with target API level set to both 29, and 30 in 'Player Settings'. But it fails the same error. I really appreciate any help.

**Comment by paulinon** [comment] 2021-05-10 13:19
Hi @gayanW,

Adding the config file in your project causes various resource files to be generated. Could you try changing the package name in your Player Settings before adding the new config file and see if this makes a difference?

**Comment by patm1987** [comment] 2021-05-10 20:50
Hi @gayanW,

Can you try the following:
1. close Unity completely (this deletes the `Temp/` folder and makes sure that no automated processes get in your way)
2. delete `Assets/StreamingAssets/google-services-desktop.json` (this is a file auto-generated for desktop support and looks to be getting in your way)
3. delete any "Firebase looking" folders in `Assets/Plugins/Android/` that end in `.androidlib`. The ones I can think of are `FirebaseApp.androidlib` and `FirebaseCrashlytics.androidlib`. (these files are simulating what the PlayServicesPlugin does on normal Android projects and will be auto-re-generated by the Firebase plugin if they're missing)
4. Add your new `google-services.json` file (renaming as before should be fine, but make sure that you only have a single file named `google-services.json` in your entire `Assets/` directory -- the behaviour becomes undefined otherwise)

If you can relaunch and have everything work, this is at least a workaround. If you can isolate which step/steps are necessary for the workaround, that would ensure that we have good visibility into where the actual bug lies and address it accordingly.

**Comment by patm1987** [comment] 2021-05-11 22:28
Reading through your reported dependencies, I see:
```
<androidPackage spec="com.google.firebase:firebase-app-unity:5.5.0">
```

Which would indicate the 5.5.0 SDK (the `-unity` ones are packages that bind C# to C++, so they match the Unity SDK version). If you update to the latest (7.2.0), the issue may resolve itself (this also explains the lack of `androidlib` folders).

Since I can't reproduce the issue locally, it would be useful to know if it's been resolved in subsequent SDKs or is an issue with your configuration that we should continue to track down and patch.

If updating your project is not feasible _or_ you still see the issue after updating to 7.2.0, it would also be helpful to know if you see this issue in the quickstarts in this repo (such as [Analytics](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp)) so I know that I'm looking at the same code as you are.

**Comment by gayanW** [comment] 2021-05-13 03:47
Thanks! I'll try upgrading to 7.2.0, and will let you know the result. Meanwhile, if you've any specific instructions on how to upgrade, please do let me know as well.

**Comment by patm1987** [comment] 2021-05-13 20:30
I'm assuming that you're using `unitypackage` files for integration.

If you look under `Assets/Firebase/Editor` you will see a number `Dependencies.xml` files and possibly `_manifest` files. For the most part, this will tell you which Firebase packages you have installed (some dependencies come in as part of other packages, such as `FirebaseAppDependencies.xml`):
![image](https://user-images.githubusercontent.com/1111611/118183419-53d9aa80-b3f7-11eb-9143-3eb6838a60fa.png)

You'll want to download the latest [Unity zip file](https://firebase.google.com/download/unity) with all of the Firebase plugins or look for just the ones you need from the [online package repository](https://developers.google.com/unity/packages#firebase).

Then just import packages one by one until you've replaced all of your old ones. Note that during this process you might see errors whilst some of your packages are updated and the rest aren't. Just go through everything before you try to resolve anything (going from 5 to 7, there may be some code changes that you have to perform).

**Comment by gayanW** [comment] 2021-05-16 17:41
Upgrading to 7.2.0 fixed it. I have to delete all the old files and directories related to Firebase, before the upgrade. Otherwise, importing the new package while the old files exist, causes:
```
Multiple plugins with the same name 'firebasecppanalytics'
```

Thanks for the help ❤️

**Comment by patm1987** [comment] 2021-05-17 20:09
I'm glad it worked out 😃.

If you continue to see that issue with upgrades in the future (5->7 is a big jump), feel free to open another bug. I'll mark this as closed for now.

**Closed by patm1987** 2021-05-17 20:09 UTC
Labels: api: core, needs-attention, type: question
