### ISSUE TITLE
Don't receive fcm notification when I exit the unity app,only user open the unity app the mobile notifiction list can show the fcm push notification.

### ISSUE THREAD

**Issue by BuKuSiShen** [firebase/quickstart-unity#25] opened 2016-12-12 08:15 UTC
Use the Unity plugins of Messaging on Android.Can't receive push notification on the mobile notifiction list when exit the unity app.

**Comment by BuKuSiShen** [comment] 2016-12-13 02:32
@stewartmiles I use quickstart samples to test.It also not receive push notification on the  notificition list when i exit the sample application.Can receive push notification only when the application is on runtime.

**Comment by BuKuSiShen** [comment] 2016-12-13 02:43
@stewartmiles I means that the fcm service (about the current unity application) isn't always Resident background when user exit app.

**Comment by stewartmiles** [comment] 2016-12-13 16:29
We just tested this again and we are definitely seeing notifications come in when sending to the application when:
- App is running in the foreground
- App is running / resident in the background
- App is not running

To be clear when the app is in the background or not running you don't get a callback when the notification comes in.  The app gets to service the notification when it reopens due to a user clicking on the notification.  Is this the behavior you're seeing?

**Comment by BuKuSiShen** [comment] 2016-12-14 01:29
@stewartmiles I see the behavior is that When App is not running the notification don't comes in.
When App is running in the foreground or App is running / resident in the background my app works fine.

**Comment by stewartmiles** [comment] 2016-12-14 01:48
How are you sending the notification?

Are you using the notification console?
https://firebase.google.com/docs/notifications/android/console-audience#send_a_message_from_the_notifications_console

I just built the sample + the 1.1.0 SDK and verified the following on a Nexus 4 running Android 4.3 (because I like to keep it old skool 👍 ):
* Sending message to the game while it's open, receives the message displays in the log window
* Sending message to the game while it's in the background, notification in the notification tray
* Closed game (swipe away), send message to the topic - notification displayed in the notification tray.

I've attached a screenshot of the message I sent via the notification console.

<img width="373" alt="notification" src="https://cloud.githubusercontent.com/assets/6042948/21166750/50964dc0-c15c-11e6-8d7a-26cfc3f0965b.png">

**Comment by BuKuSiShen** [comment] 2016-12-14 06:39
@stewartmiles Thank you first of all.
I found that:
A: run app on HUAWEI P8. The notification don't comes in.This HUAWEI P8 is made for chinese,the reason may be about this custom system

B: run app on SUMSUNG Galaxy S4.The notification comes in via Topic notification console.But the notification don't comes in via User segment(using the Bundle identifier) notification console.This is also a issue.Do you see this behavior?
The follow is my init code:
        //FCM's init
	public void InitializeFirebase()
	{
		Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
		Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
		Firebase.Messaging.FirebaseMessaging.Subscribe ("TestTopic");
	}

**Comment by MustafaKilci** [comment] 2016-12-28 06:37
Hi, I have the same issue. I sent three types of notifications (User segment, Topic and Unique Device)

The app gets the notification when app is running in the foreground in callbackFunction; when app resident in the background as notification on system tray but cannnot get notification when 
App is not running or killed.

I need urgent support.

**Comment by BuKuSiShen** [comment] 2017-01-10 02:45
@MustafaKilci Sorry,i don't fix this.Just wait the other one or the next release.

**Comment by rutcreate** [comment] 2017-01-11 08:27
Same thing here. When I click Allow on notification request, all buttons and text field won't respond anymore.

**Comment by phpnato** [comment] 2017-01-13 21:47
Hi, I have the same issue

**Comment by stewartmiles** [comment] 2017-01-14 02:27
The details of the expected behavior are here
https://firebase.google.com/docs/cloud-messaging/android/receive:

   - When the app is running in the foreground the notification is routed
   from the service (that handles the notification) to the SDK which then
   fires the callback.
   - When the app is in the background and running we can route the
   notification to the app, as it's running :)
   - When the app isn't running / killed, our service runs which receives
   the notification and caches it.  When the user clicks on the notification
   the notification is routed to the app when it's launched.

If you want to customize what happens in the notification when the app
isn't running you'll need to subclass our service
(com.google.firebase.messaging.cpp.ListenerService which implements
FirebaseMessagingServices
<https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService>)
and replace the reference to it in your Android manifest.  You can then
override the onMessageReceived() method to customize the behavior in your
service.  Obviously, this is not particularly cross platform as there is no
way to do this on iOS.

Cheers,
Stewart

**Comment by stewartmiles** [comment] 2017-01-23 11:18
Closing out as it sounds like we need to clarify our docs on this behavior.

**Closed by stewartmiles** 2017-01-23 11:18 UTC

**Comment by nabeelpkl** [comment] 2018-03-28 12:04
any updates on this ?

**Comment by stewartmiles** [comment] 2018-04-05 17:52
@nabeelpkl if you want to customize messaging handling on Android when the app is in the background (i.e just the messaging service is running) see https://firebase.google.com/docs/cloud-messaging/cpp/client#custom_message_handling_on_android (the Unity SDK uses the C++ SDK under the hood).
