### ISSUE TITLE
Firebase speed in unity editor

### ISSUE THREAD

**Issue by craNich** [firebase/quickstart-unity#442] opened 2019-08-09 19:10 UTC
Unity editor version:
Firebase Unity SDK version: 6.2.2
Firebase plugins in use (Auth, Database, etc.): Auth, Database
Additional SDKs you are using (Facebook, AdMob, etc.): Mapbox
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

Hello, I am experiencing very weird delays recently in unity editor. Almost with every command, setvalue, update etc. It started like 1 day ago and its happening only in unity editor. Every command has delay of like 1 - 10 seconds. When I deploy my app to android device, everything is quick again (using same internet connection). I tried also previous versions of my app, which worked fine, delays occures anyways. Also tried different PCs, different internet connections. Always big delays.

Also when I send same command multipletimes after each other, the others after the 1st one are quick. So the problem is in establishing connection,

Why can this happen? Is there any way how to fix it?

**Comment by cynthiajoan** [comment] 2019-08-09 23:30
Hi @craNich, do you have logs from unity editor to help identify the issue? 
Also would like to clarify a few things:

The operation in unity editor gets slow, but after deploy the app to android devices, the operations in the editor get speed up again?

Does delay also happens in previous version of your app? Does delay also happens with previous version of firebase sdk?

**Comment by craNich** [comment] 2019-08-10 00:37
@cynthiajoan Hi. No, operation are always slow in editor. Only on android devices its quick. Also in editor its very like unstable, sometimes its not so bad, but sometimes the delay is huge. Seems like after time, its getting worse. Not sure about that tho.
Delay occured randomly. I didnt change any version of unity/firebase, not even code. I noticed this issue also like 2 weeks ago, when I was using some query on larger amount of data. ( same issue, android = fast, editor = slow).

**Comment by craNich** [comment] 2019-08-10 13:01
This is an example of the issue: 
Code:
`        Debug.Log("STARTING UPDATE");
        int time = System.DateTime.Now.Second;
        int xtime = System.DateTime.Now.Millisecond;
    
        reference.UpdateChildrenAsync(childUpdates).ContinueWith(task =>
        {
            if (task.IsCanceled)
            {
                Debug.LogError("Firebase update was canceled.");
                _taskFinished = true;
                Debug.Log("!!! ERROR UPDATE");
            }
            if (task.IsFaulted)
            {
                Debug.LogError("Firebase update encountered an error: " + task.Exception);
                _taskFinished = true;
                Debug.Log("!!! ERROR UPDATE");
            }
            //Debug.Log("Firebase data were updated succesfuly.");
            _taskFinished = true;
        });

        yield return new WaitUntil(() => _taskFinished == true);
        int endtime = System.DateTime.Now.Second;
        int xendtime = System.DateTime.Now.Millisecond;
        Debug.Log("ENDING UPDATE, time: " + ((endtime - time)*1000 + (xendtime - xtime)) + " ms");`


Unity log when updating 2 child node values, 1st one, 2nd one, 1st one, 2nd one etc.

![updateunity](https://user-images.githubusercontent.com/53269312/62822090-ebed9480-bb7e-11e9-86ac-c8ebbdad7960.png)

**Comment by DellaBitta** [comment] 2019-08-14 19:50
Hi @craNich,

Have you been using the  _taskFinished mechanic the whole time or just after you noticed a slow down in behavior?  There's a chance that ContinueWith executes on a different thread, and some of the changes to _taskFinished might be lost since its not declared as volatile.

Could you update the code so that you await the task returned from reference.UpdateChildrenAsync directly?  Such as:

```
task = reference.UpdateChildrenAsync(childUpdates)
...
yield return new WaitUntil(()=>task.IsComplete);
...
// {measure time}
```

**Comment by craNich** [comment] 2019-08-14 21:43
@DellaBitta 
Hello, I just tried it. Didnt help at all, same issue.
I also switched to async await for handling asynchronous stuff, issue persists.

**Comment by craNich** [comment] 2019-08-14 22:58
I will try to debug this little bit more and I will let you know. I found out, that when I update, it works fine. I think some write before has to happen, or something like that. Not sure yet.

**Comment by craNich** [comment] 2019-08-15 01:24
Okey. This is what I did and found out:
- I created completly new project with my firebase database.
In firebase database there is a node "users" which stores some stuff, like number of comestics of player, username and some other values.

The issue occures when:
step1) I read the user data: firebaseDbRootRef.Child("users").Child(user.UserId).GetValueAsync();
step2) I write the data to somewhere in users node 
step3) I write or update data somewhere in users node
repeat step 2 and step3 => increasing delay

Also what I found out: The ammount of delay corresponds to "size" of users data. If the users node is almost empty, the delay icrease is realy realy low. If there is more stuff the increase is higher. This is why I didnt notice it earlier.

If I dont do step1 (read the users data) everything works fine.

**Comment by craNich** [comment] 2019-08-15 01:28
I also made this example causing the issue:

```
    private IEnumerator IssueExampleEnum()
    {
        // Read users data
        firebaseDbRootRef.Child("users").Child(user.UserId).GetValueAsync();

        // Just wait
        yield return new WaitForSeconds(5); 

        long someData = 0;

        for(int i=0; i<10; i++)
        {
            Debug.Log("STARTING WRITE");
            int timeSec = System.DateTime.Now.Second;
            int timeMSec = System.DateTime.Now.Millisecond;

            // Write some data to node2
            Task task = firebaseDbRootRef.Child("users").Child(user.UserId).Child("node1").Child("node2").SetValueAsync(someData++);
            yield return new WaitUntil(() => task.IsCompleted == true);

            int endtimeSec = System.DateTime.Now.Second;
            int endtimeMSec = System.DateTime.Now.Millisecond;
            Debug.Log("ENDING WRITE, time: " + ((endtimeSec - timeSec) * 1000 + (endtimeMSec - timeMSec)) + " ms");

            // Write some data to node3
            Task task2 = firebaseDbRootRef.Child("users").Child(user.UserId).Child("node1").Child("node3").SetValueAsync(someData++);
            yield return new WaitUntil(() => task.IsCompleted == true);
        }
    }
```

When the issue doesnt occur:
1) If I write to 
firebaseDbRootRef.Child("users").Child(user.UserId).Child("node1") 
and 
firebaseDbRootRef.Child("users").Child(user.UserId).Child("node2"). 

2) If I dont read the data 

3) If I write same value as it was in the node

**Comment by alexames** [comment] 2019-08-28 21:21
I tried to reproduce this issue, in a testapp. I ran your IssueExampleEnum function 20 times with and without the initial call to GetValueAsync, so I had about 200 samples. I did see about 100ms slower response times when I called GetValueAsync first, but I didn't see the run time increase like you did. It was a pretty steady average of 250ms without GetValueAsync, and 350 with GetValueAsync. 

I'm still confused as to why GetValueAsync mattered at all, but so far I haven't been able to reproduce the slow down. I'll try some more experiments on my end. 

Can you try updating to 6.4.0 and see if that changes anything? There were a few bug fixes in there. Nothing I can think of off the top of my head would cause the behavior you're seeing, but it might be some weird interaction due to a bug that was fixed in newer code maybe.

**Comment by craNich** [comment] 2019-08-29 07:01
I will try it in the next few hours/days.
Dont forget:
To reproduce this issue, you have to have some records (more records = more delay) in the users/user.id node.

**Comment by craNich** [comment] 2019-08-29 07:37
Hello, I just tried the new 6.4.0 version, problem still there.
![testnewfirebase](https://user-images.githubusercontent.com/53269312/63920237-ac5cee80-ca40-11e9-937a-6034de293043.png)

**Comment by chkuang-g** [comment] 2019-10-02 00:12
@craNich 
Sorry I think we were not able to reproduce the delay you saw.
Is it possible for you to send us a minimal project that can reproduce the case you saw?

Thank you,
Shawn

**Comment by craNich** [comment] 2019-10-02 07:48
@chkuang-g 
I created the empty project, with just initialization of firebase and this function:

    private IEnumerator IssueExampleEnum()
    {
        // Read users data
        firebaseDbRootRef.Child("users").Child(user.UserId).GetValueAsync();

        // Just wait so data is read (not neccesary)
        yield return new WaitForSeconds(1); 

        long someData = 0;

        for(int i=0; i<10; i++)
        {
            Debug.Log("STARTING WRITE");
            int timeSec = System.DateTime.Now.Second;
            int timeMSec = System.DateTime.Now.Millisecond;

            // Write some data to node2, increasing delay with every step (never goes lower again, even if I run it 10 minute later)
            Task task = firebaseDbRootRef.Child("users").Child(user.UserId).Child("node1").Child("node2").SetValueAsync(someData++);
            yield return new WaitUntil(() => task.IsCompleted == true);

            int endtimeSec = System.DateTime.Now.Second;
            int endtimeMSec = System.DateTime.Now.Millisecond;
            Debug.Log("ENDING WRITE, time: " + ((endtimeSec - timeSec) * 1000 + (endtimeMSec - timeMSec)) + " ms");
        }
    }

Thats all I have in terms of code. Newest version of firebase, newest version of unity (it does in old ones too).

But, if the database is empty, there is no visible issue. To see the increase, you need a lot of childs here.

**Comment by tywiggs** [comment] 2019-10-04 13:50
I am having the exact same issue! My app database calls 5 months ago running older unity 2018.3, and an older firebase sdk, from the new one are 100% fine. However now some calls are literally 100x slower than before. It is definitely multiplicative based on the children nodes. If I am to call something with lets say 4 children nodes, it is exponentially faster to just call the 4 children nodes individually rather than the parent all at once. However when building to apk or to xcode this doesn't happen. This breaking and slowing down the test process a lot.

It is causing me to believe their are errors in my app then testing it in app and realizing the speed is fine.

**Comment by patm1987** [comment] 2019-10-22 15:50
I don't have any new news on this issue. I just wanted to confirm that this feedback is in the hands of the team (since it's been a couple of weeks since the last comment).

--Patrick

**Comment by steve6t6** [comment] 2019-10-31 11:39
Hi all, we have just run into this issue too, we have done some testing and have a theory. The test involved recording the milliseconds between making a write or remove request to an object in our RTDB and receiving the OnValueChanged callback, If only one object is being written to, the time increase is steady, maybe 10ms per write, but after performing 20 writes to one object we also modified an object in the same container and the time delay increase doubled, then on the third object it was a magnitude longer:
- Object 1, 1st write, 46ms. 
- Object 1, 20th write, 243ms.
- Object 2, 1st write, 411ms.
- Object 3, 1st write, 4359ms.

Our theory is that the Firebase SDK is caching each write command and applying all of them in sequence every time we perform a write (UpdateValueAsync), this transaction queue or log may not be being cleared after a successful write?

**Comment by markchandler-google** [comment] 2019-11-01 21:01
We think we have found the issue causing this (a [incorrect std;:move](https://github.com/firebase/firebase-cpp-sdk/blob/master/database/src/desktop/core/sync_tree.cc#L57) in c++ resulted in writes not being cleaned up properly) and hope to have a fix out soon for it. 

I was able to repo it by just creating a lot of entries over and over again which resulted in the slow down over time and after removing the std::move, the slow down didnt occur.

**Comment by steve6t6** [comment] 2019-11-06 11:49
> We think we have found the issue causing this (a [incorrect std;:move](https://github.com/firebase/firebase-cpp-sdk/blob/master/database/src/desktop/core/sync_tree.cc#L57) in c++ resulted in writes not being cleaned up properly) and hope to have a fix out soon for it.
> 
> I was able to repo it by just creating a lot of entries over and over again which resulted in the slow down over time and after removing the std::move, the slow down didnt occur.

Any news on a patch? this is having an effect on our development time.

Best regards Steve

**Comment by markchandler-google** [comment] 2019-11-19 18:35
Firebase 6.7.0 went live a couple of days ago. Please test it out and let us know if the issue you see has been fixed.

**Comment by a-maurice** [comment] 2019-11-21 02:24
Closing this for now, feel free to reopen if updating to 6.7.0 did not solve your problem.

**Closed by a-maurice** 2019-11-21 02:24 UTC
Labels: type: bug
