### ISSUE TITLE
Cannot setInt nor save PlayerPrefs when retrieving entries from Realtime Database - Silent fail

### ISSUE THREAD

**Issue by michelepanegrossi** [firebase/quickstart-unity#770] opened 2020-09-07 00:46 UTC
### Please fill in the following fields:
Unity editor version: 2019.4.6.f
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Realtime Database
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I am succesfully retrieveing data from the database. However, when I try to set an int value in the PlayerPrefs, the script 'stops' and silently fails without returning any errors.

This is the code I am using, I am calling this method with a button:

```
    public void RetrieveCodes()
    {
        _codeFromUser = _codeInputField.text;

        FirebaseDatabase.DefaultInstance.GetReference("SH_TT").GetValueAsync().ContinueWith(retrieveTask => {
            if (retrieveTask.IsFaulted)
            {
                Debug.Log("No snapshot");
                // Handle the error...
            }
            else if (retrieveTask.IsCompleted)
            {
                DataSnapshot snapshot = retrieveTask.Result;

                foreach (DataSnapshot ds in snapshot.Children)
                {
                 
                    Debug.Log(ds.ChildrenCount);

                    _currentOrder = new Order(ds.Key, ds.Child("Date").Value.ToString(),ds.Child("Email").Value.ToString(), ds.Child("OrderID").Value.ToString(), ds.Child("Redeemed").Value.ToString());

                    _ordersList.Add(_currentOrder);

                    Debug.Log($"_Coderedeemed:= {ds.Key}");
                    Debug.Log($"_Coderedeemed:= {_currentOrder.OrderID}");
                }

                //RETRIEVEAL FINISHED
                //DO STUFF
                foreach(Order o in _ordersList)
                {
                    if (o.OrderID == _codeFromUser)
                    {
                        if (o.Redeemed == "N")
                        {
                            Debug.Log($"Event Date: {o.Date}");
                            reference.Child("SH_TT").Child(o.OrderKey).Child("Redeemed").SetValueAsync("Y");
                            Debug.Log("FOUND TICKET"); //THIS IS THE LAST EXECUTED INSTRUCTION, NOTHING AFTER THIS HAPPENS
                            PlayerPrefs.SetInt("HasRedeemedShow", 1);
                            PlayerPrefs.Save();
                            Debug.Log("SAVED PLAYER");
                        }
                        else
                        {
                            Debug.Log("Ticket Has Already Been redeemed!!!");
                        }
                    }
                }
            }
        });
    }
```
The last line which is executed is `Debug.Log("FOUND TICKET"); `, nothing is executed after that. **However**, if I remove the lines `PlayerPrefs.SetInt("HasRedeemedShow", 1);` and `PlayerPrefs.Save();` then the line `Debug.Log("SAVED PLAYER");` is executed.

No errors appear in the Console. I don't understand what is going on! Any help would be appreciated!

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

N/A

What's the issue repro rate? (eg 100%, 1/5 etc)

100%

**Comment by michelepanegrossi** [comment] 2020-09-10 16:44
This keeps happening with different instructions as well. For instance `_redeemButton.SetActive(true);` is not executed.

So far the only instructions I can execute in that postion of the script include:

- Variable assign
- Debug.Log

Anythign elase silently fails. What is going on??

**Comment by vimanyu** [comment] 2020-09-11 02:13
Hi @michelepanegrossi,
I suspect the issue is how asynchronous tasks are queued up in Unity.
https://firebase.googleblog.com/2019/07/firebase-and-tasks-how-to-deal-with.html

Maybe try with `ContinueWithOnMainThread` instead of `ContinueWith`?

**Comment by michelepanegrossi** [comment] 2020-09-11 06:28
Thanks @vimanyu, using `ContinueWithOnMainThread` instead of `ContinueWith` solved the issue!

Thank you for pointing me towards that blog post, it si extremely useufl and fascinating!

I only have one question / concern. Will using  `ContinueWithOnMainThread` block the execution of the main thread until all entries from the database have been rerieved and could this become an issue when there are a lot of entries to retrieve?

Many thanks

**Comment by vimanyu** [comment] 2020-09-11 16:48
I am glad that this solved the issue.
If you are using `ContinueWithOnMainThread`, Firebase I/O is still happening asynchronously. Once the I/O is done, the continuation happens on the main thread to play nicely with shared resources in Unity. So, the fetching from the database should be fine (and ofcourse the fetch time is dependent on how many entries are there in the DB), but the main thread gets busy only when the fetch is complete. 
I am going to close this ticket as we have a solve for the original issue.

**Closed by vimanyu** 2020-09-11 16:48 UTC
Labels: api: database, needs-attention
