### ISSUE TITLE
Crashlytics + IL2CPP does not work

### ISSUE THREAD

**Issue by nitzanwilnai** [firebase/quickstart-unity#1290] opened 2022-06-24 12:02 UTC
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.25f1
  * Firebase Unity SDK version: 9.1.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics (Auth, Database, etc.)
  * Other Firebase Components in use: None (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Clean project, using Crashlytics quick start. Building with Mono WORKS, building with IL2CPP does not:

Unity   : Disable module 'crashlytics' for 'Firebase.Crashlytics.Crashlytics, Firebase.Crashlytics'

Longer log:
06-24 13:51:45.842  1864  2109 I ActivityTaskManager: Displayed com.fourxp.mergeup/com.unity3d.player.UnityPlayerActivity: +210ms
06-24 13:51:45.844 17707 17738 I Unity   : MemoryManager: Using 'Dynamic Heap' Allocator.
06-24 13:51:45.857 17707 17738 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 5593mb
06-24 13:51:45.857 17707 17738 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0xc0), 6 little (mask: 0x3f)
06-24 13:51:45.857 17707 17738 I Unity   : ApplicationInfo com.fourxp.mergeup version 0.1 build 17014145-bd67-4b23-a737-0c877bff1ecf
06-24 13:51:45.857 17707 17738 I Unity   : Built from '2020.3/staging' branch, Version '2020.3.25f1 (9b9180224418)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
06-24 13:51:45.878 17707 17738 I Unity   : Company Name: DefaultCompany
06-24 13:51:45.878 17707 17738 I Unity   : Product Name: FirebaseClean2
06-24 13:51:47.178   723   723 E TimeStats: [3533]-[SurfaceView[com.fourxp.mergeup/com.unity3d.player.UnityPlayerActivity](BLAST)#0]-timeRecords is at its maximum size[64]. Ignore this when unittesting.
06-24 13:51:48.146 17707 17738 I Unity   : Disable module 'analytics' for 'Firebase.Analytics.FirebaseAnalytics, Firebase.Analytics'
06-24 13:51:48.146 17707 17738 I Unity   : Firebase.FirebaseApp:InitializeAppUtilCallbacks()
06-24 13:51:48.146 17707 17738 I Unity   : Firebase.FirebaseApp:CheckDependenciesAsync()
06-24 13:51:48.146 17707 17738 I Unity   : Firebase.FirebaseApp:CheckAndFixDependenciesAsync()
06-24 13:51:48.146 17707 17738 I Unity   : FirebaseClean:Start()
06-24 13:51:48.146 17707 17738 I Unity   : 
**06-24 13:51:48.148 17707 17738 I Unity   : Disable module 'crashlytics' for 'Firebase.Crashlytics.Crashlytics, Firebase.Crashlytics'**
06-24 13:51:48.148 17707 17738 I Unity   : Firebase.FirebaseApp:InitializeAppUtilCallbacks()
06-24 13:51:48.148 17707 17738 I Unity   : Firebase.FirebaseApp:CheckDependenciesAsync()
06-24 13:51:48.148 17707 17738 I Unity   : Firebase.FirebaseApp:CheckAndFixDependenciesAsync()
06-24 13:51:48.148 17707 17738 I Unity   : FirebaseClean:Start()

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
100% repro rate. Use Crashlytics quick start. Switch to IL2CPP. Crashlytics will not load.

What happened? How can we make the problem occur?
100% repro rate. Use Crashlytics quick start. Switch to IL2CPP. Crashlytics will not load.
Disable module 'crashlytics' for 'Firebase.Crashlytics.Crashlytics

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
Clean new project. Add Crashlytics. Set scripting runtime to IL2CPP.

```
// TODO(you): code here to reproduce the problem
```
https://drive.google.com/file/d/15kHj1rh8SUgrOUaFsxhiSQBBFbCOgB8T/view?usp=sharing

**Comment by nitzanwilnai** [comment] 2022-06-26 12:40
Note - the issue also happens with iOS builds (as they use IL2CPP).
Going back to 8.7.0 FIXES THE ISSUE!

**Comment by paulinon** [comment] 2022-06-27 12:59
Hi @nitzanwilnai,

Thanks for reporting this. While I try to replicate this issue, could you verify if this behavior persists using our [quickstart sample](https://github.com/firebase/quickstart-unity/tree/master/crashlytics/testapp)?

**Comment by nitzanwilnai** [comment] 2022-06-28 08:17
Hi @paulinon  - It seems like 9.1.0 DOES work on the quickstart sample when setting it to IL2CPP. I'll dig into what is different between it and my quickstart. 
Does my sample project work for you? (Or following your quickstart guide)

**Comment by paulinon** [comment] 2022-06-28 08:51
Hi @nitzanwilnai,

I've tried the sample project you provided, and the crashes aren't being reported on the dashboard. What's odd is that this happens in both Mono and IL2CPP. 

I also noticed that you followed along our documentation related to testing crashes, so I did the same thing in a blank project, and I was able to see the crashes being reported using IL2CPP. With that, could you verify if reimporting the SDK makes any difference?

**Comment by Whyser** [comment] 2022-06-28 14:40
Hey,

I had this issue as well. It seems that Unity strips the library (or something). Because if I add this piece of code:
`Debug.Log("Is crashlytics enabled: " + Firebase.Crashlytics.Crashlytics.IsCrashlyticsCollectionEnabled);`
It will then work as intended and enable module (this will NOT enable other libraries, in my case Analytics was disabled also, unless I reference something in FirebaseAnalytics namespace).

Note: I do not use proguard/minify in my project.

**Comment by nitzanwilnai** [comment] 2022-06-29 05:54
@paulinon Re-importing does not solve the problem.

**Comment by nitzanwilnai** [comment] 2022-06-29 05:59
Adding the debug.log *DOES* solve the problem!

**Comment by paulinon** [comment] 2022-06-29 10:03
Thanks for the update, @nitzanwilnai. Glad to hear that you resolved the issue.

I'll be closing this for now. Let me know if an issue arises.

**Comment by Whyser** [comment] 2022-06-29 10:12
@paulinon Uhm, why close the issue unless it has been fixed? Either update documentation to state that we need to reference the library or issue an actual fix? This is quite serious.

**Comment by nitzanwilnai** [comment] 2022-06-29 10:38
@paulinon I second what @Whyser said. I think the documentation needs to be updated and/or the issue fixed. Something changed since 8.9.0 to cause this.

**Comment by nitzanwilnai** [comment] 2022-06-29 10:51
To be clear, adding the line
`Debug.Log("Is crashlytics enabled: " + Firebase.Crashlytics.Crashlytics.IsCrashlyticsCollectionEnabled);`
AFTER
`Firebase.FirebaseApp app = Firebase.FirebaseApp.DefaultInstance;`
Fixes the issue.

**Comment by paulinon** [comment] 2022-06-29 16:45
Hi folks,

Apologies for the misunderstanding. I've tried the workaround you provided, but it had no effect in my implementation. Given this odd behavior, could you verify if the issue persists in the sample project provided? Without using the workaround, are the crashes being reported when using Mono?

**Comment by Whyser** [comment] 2022-06-29 17:10
Not sure what you're asking @paulinon? nitzanwilnai's already said he tested the 'quickstart-sample' and that it did work. And you already tested nitzanwilnai's and confirmed that it didnt work. The difference in these projects seems to be:

quickstart-sample references(/uses) the Crashlytics APIs in the SDK in some scripts. My project didn't (and it seems neither does nitzanwilnais')

**Comment by nitzanwilnai** [comment] 2022-06-30 08:08
Hi @paulinon, adding the line to the sample project (from the google drive link above) DOES fix the issue for me in IL2CPP.
Mono always worked and continues to work.

**Comment by paulinon** [comment] 2022-06-30 09:37
Thanks for the information, folks. I was finally able to observe this behavior in another blank project, and the workaround you provided worked. 

I'll be relaying my observations to the team, and I'll keep this open for future updates.

**Comment by nitzanwilnai** [comment] 2022-06-30 10:41
@Whyser Thanks for providing the fix. You rock!

**Comment by dafeidafei1993** [comment] 2022-07-01 07:38
I have the same problem as you. The project we use is unity2019.4.40f1. That is, crashlytics works normally in mono. In il2cpp, non serious error reports cannot be caught, However, it can be counted that the crash error report (this crash error report is not the official test crash, but the crash generated by [unityengine.diagnostics.utils.forcecrash (forcedcrashcategory.accessviolation (using unityengine. Diagnostics)].
This makes us very confused. We observed in the log that it seems that Google Analytics in the unity project packaged by 2libcc did not initialize successfully as the project packaged by mono.
Similarly, we cannot see the correct symbolic file after symbol uploading.

**Comment by Whyser** [comment] 2022-07-06 22:48
Well, I think it doesn't happen as easily with Analytics since you're most likely referencing some API call like "SendEvent" or similar, while in Crashlytics you never really need to call anything (other than base initialization).

**Comment by a-maurice** [comment] 2022-07-14 21:55
Looking into the Analytics logic, I believe it is fine as is.  The logic doesn't need the Unity side of Analytics to initialize to actually start collecting data, it is only if custom events are being added, at which point the C# code is referenced, so it will initialize.

The latest release, 9.2.0, just came out with the Crashlytics fix, so I'm marking this as closed.  Thanks again for bringing this to our attention.

**Closed by a-maurice** 2022-07-14 21:55 UTC
Labels: type: bug, api: crashlytics
