### ISSUE TITLE
[Bug] [iOS] Firebase App (Core) dependency causes App Store rejection

### ISSUE THREAD

**Issue by bilck** [firebase/quickstart-unity#1010] opened 2021-03-30 21:53 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Any
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firebase Core
  * Other Firebase Components in use: irrelevant, but we use Crashlytics, Remote Config, 
  * Additional SDKs you are using: irrelevant, but: Playfab, DevToDev, Google Play In-App Review
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
`Firebase App (Core)` package from Unity Package Manager has a `Firebase/Core` dependency, which depends on `Firebase Analytics` iOS Pod.

There 2 problems related to that:
1. `Firebase Analytics` has a `GoogleAppMeasurement.framework` dependency, which causes kids-oriented apps to be **rejected** by Apple on App Store submissions. This is a **big** problem by itself but is already contemplated on this iOS SDK issue: https://github.com/firebase/firebase-ios-sdk/issues/7736
2. `Firebase App (Core)` has a `Firebase/Core` pod dependency, which drags along "FirebaseAnalytics" and causes Kids apps to be rejected. We have managed to remove this dependency by processing the generated podfile, but this could be a **major** problem for most developers not used to Unity 3D build processing shenanigans. I have also mentioned that on the issue mentioned in #1.

Overall, this is a really bad situation in which most developers with kids apps will be rejected when submitting to the App Store.
It is bad enough that Firebase Analytics causes that, and it gets worse due to the fact that it's impossible to use Unity Package Manager SDKs without `Firebase App (Core)` package.

**Comment by DellaBitta** [comment] 2021-03-31 14:00
Hi @blick,

Thanks for the report and I'm sorry for the App Store rejection.  As you point out this is a known issue in the Firebase iOS SDK which is being actively worked on as [firebase-ios-sdk Issue #7736](https://github.com/firebase/firebase-ios-sdk/issues/7736).  The thread in that issue also has info on the Firebase Core pod spec.

Once there's a solution in the iOS SDK we will need to create a new release of the Unity SDK which includes the change, which is being tracked in this repo as #994.

I'm going to close this ticket is a duplicate for now so that we can funnel discussions through #994, but please re-open this issue if you feel I've done this in error. Thanks!

**Closed by DellaBitta** 2021-03-31 14:00 UTC
Labels: api: core, type: question

**Comment by DellaBitta** [comment] 2021-03-31 14:03
Duplicate of #994
