### ISSUE TITLE
As today is Realtime Database usable on oculus quest? (no google play services?)

### ISSUE THREAD

**Issue by Ko-Haku** [firebase/quickstart-unity#938] opened 2021-01-21 22:55 UTC
### [READ] Guidelines

When filing a feature request please make sure the issue title starts with "FR:".

A good feature request ideally
* is either immediately obvious (i.e. "Add Sign in with Apple support"), or
* starts with a use case that is not achievable with the existing Firebase API and
  includes an API proposal that would make the use case possible. The proposed API
  change does not need to be very specific.

Once you've read this section, please delete it and fill out the rest of the template.

### Feature proposal

* Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

**Comment by shaagrath** [comment] 2021-01-22 11:42
Checking here https://firebase.google.com/docs/android/android-play-services seems that everything is fine now but still also  I am  struggling to make my project work on the quest 2 (works fine on unity editor) and i cant realize if i have to delete certain dlls or what. If you only need database maybe u can check [here](https://assetstore.unity.com/packages/tools/network/simple-firebase-unity-for-realtime-database-58337#description) and [here](https://github.com/step-up-labs/firebase-database-dotnet) for some rest api wrappers

**Comment by patm1987** [comment] 2021-02-01 17:36
Right now, the underlying Android SDK does work on the quest but the C# one still relies on Google Play Services for some legacy architectural reasons (basically `CheckAndFixDependenciesAsync` will fail and you won't be able to create the necessary C# singletons).

I'll mark this as a duplicate of #223 , but I can suggest a few potential workarounds specifically for Realtime Database.

1. You can more or less follow the [Android instructions](https://firebase.google.com/docs/android/setup) now that Unity [exposes some necessary gradle templates](https://docs.unity3d.com/Manual/android-gradle-overview.html). It might require some back and forth with exporting a project, but you should be able to get everything into place. Then you can use [Unity's JNI interop libraries](https://docs.unity3d.com/ScriptReference/AndroidJNI.html) to interact with the Java SDK directly.
 a. Pros: You get all of the native features of the Firebase Android SDK including local persistence
 b. Cons: It's much more difficult to work in the JNI, and you'll spend a lot of time binding between C# and Java
2. You can try an unofficial plugin (ex: [Simple Firebase Unity (for Realtime-Database)](https://assetstore.unity.com/packages/tools/network/simple-firebase-unity-for-realtime-database-58337)). I see developers favor this in cases similar to yours.
 a. Pros: It's very cross platform, including targets such as the web or non play services Android devices. It's also a Unity API so you're not bouncing between C# and Java
 b. Cons: Since it does use the REST API, it will be slower than what the official SDK can do. There's not as much we can do here to help you if something goes wrong since it's not affiliated with Google and we don't have as much insight into its architecture. Integration with other Firebase APIs (ex: Auth) might not be as complete.
3. You can stand up [Cloud Functions](https://firebase.google.com/docs/functions) in front of Realtime Database. Normal functions you can just call with a [UnityWebRequest](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.Get.html).
 a. Pros: you can move a lot of logic into trusted computing nodes. It's universally callable without any intermediary SDK
 b. Cons: It's a lot of work, especially to authenticate. It will be slower, especially given the cold start times when you have few players. It will be more expensive unless your use case can benefit from [aggressive caching](https://firebase.google.com/docs/hosting/manage-cache).

**Comment by patm1987** [comment] 2021-02-01 17:37
Duplicate of #223

**Closed** 2021-02-01 17:37 UTC
Labels: needs-triage, type: feature request
