### ISSUE TITLE
[Bug] DllNotFoundException: FirebaseCppApp-8_1_0 assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by fruitdrawing** [firebase/quickstart-unity#1130] opened 2021-09-04 09:56 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.2.0b9 (m1 MacBook Air)
  * Firebase Unity SDK version: _8.1.0
  * Source you installed the SDK: _firestore ,auth (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: empty project (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: desktop (iOS, Android, and/or desktop)
  * Scripting Runtime: mono (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I get this error when I call any firebase functions in a project.

DllNotFoundException: FirebaseCppApp-8_1_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:117)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:137)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/AppUtil.cs:64)
Firebase.LogUtil..ctor () (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/FirebaseApp.cs:67)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment] 2021-09-06 09:26
Hi @fruitdrawing,

Thanks for reporting this issue. Since you're on a Mac, could you try going to your **Settings** > **Security and Privacy** and clicking **Allow Anyway** for Firebase to run?

If this didn't resolve your issue, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so that we can identify the cause of this behavior.

**Comment by fruitdrawing** [comment] 2021-09-06 14:10
Thank you for help @paulinon !

I have intel mac and m1 mac. on **Intel mac**, I can solve the issue with your solution.(hit play button and **Allow anyway in Security and Privacy**.)

But on **m1 mac** I cannot click Allow Anyway Firebase button since nothing happen(not like intel mac there is no warning window when I hit play button).

The project is just an empty Unity project with Auth and Firestore sdk. 
and Im calling Firebase by one line of code :

FirebaseFirestore db = FirebaseFirestore.DefaultInstance;

**Comment by paulinon** [comment] 2021-09-07 14:13
Thanks for the clarification that this issue persists using the M1 Mac, @fruitdrawing. This looks like an issue similar to #1100. I'll be closing this as a duplicate for now, but you may visit the mentioned ticket for updates.

**Comment by paulinon** [comment] 2021-09-07 14:13
Duplicate of #1100

**Closed by paulinon** 2021-09-07 14:13 UTC
Labels: type: feature request, unity-editor
