### ISSUE TITLE
Unity Editor crashes when calling SetValueAsync with large string

### ISSUE THREAD

**Issue by Whyser** [firebase/quickstart-unity#689] opened 2020-05-26 14:20 UTC
### Please fill in the following fields:
Unity editor version: 
Firebase Unity SDK version: 2019.3.3f1 (Windows)
Source you installed the SDK (.unitypackage or Unity Package Manager): UPM
Firebase plugins in use (Auth, Database, etc.): Database, Auth
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Unity Editor crashes every time SetValueAsync is called with a large string.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes, open quickstarts-unity project, edit UIHandler.cs script:
Change line 156 from:
      newScoreMap["score"] = score;
to
      newScoreMap["score"] = INSERT_VERY_LONG_STRING HERE (see [pastebin](https://pastebin.com/JKygzpwG));

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

This works as intended Android device but crashes inside Unity Editor.

**Comment by DellaBitta** [comment] 2020-05-27 17:12
Hi @Whyser,

I tried to reproduce locally but I could not.  I was testing on macOS, Unity version 2019.3.14f1, in editor.

First I attempted to copy and paste a large part of your example string but my text editor crashed.  So I attempted a smaller subset, still crashed. Finally I decided to make a loop to assemble a string of length 75k characters through concatenation.  The transaction completes successfully and the score is retreived successfully.

Could this be a problem in the C# Unity runtime with the static string coming from source? Could you test a assembled string of the same length to see if it, too, crashes?

**Comment by Whyser** [comment] 2020-05-27 18:08
Hey Della, thanks for confirming!
I actually didn't have it as a static string initially (and it failed anyway). But I just restarted my computer and now it works as it should :S. 
Really sorry to have wasted your time, but it truly did crash quickstart example and using short string did work as intended.

**Comment by chkuang-g** [comment] 2020-05-30 00:40
Duplicate of #517

Unfortunately we do not have a proper fix for this yet.  But I'll try to escalate for this.

**Comment by chkuang-g** [comment] 2021-02-11 05:47
Duplicate of #517

**Closed by chkuang-g** 2021-02-11 05:47 UTC
Labels: api: database, type: bug
