### ISSUE TITLE
More than one file was found with OS independent path 'lib/x86/libFirebaseCppAnalytics.so

### ISSUE THREAD

**Issue by Mecze** [firebase/quickstart-unity#383] opened 2019-06-10 14:10 UTC
## Please fill in the following fields:
Unity editor version: Unity 2017.4.28f1 (Happened on 2017.4.3f1, our old version too)
Firebase Unity SDK version: **Firebase 6.0.0**
Firebase plugins in use (Auth, Database, etc.): **Analytics**, RemoteConfig, Crashlytics (Happened without crashlytics too)
Additional SDKs you are using (Facebook, AdMob, etc.):  Facebook SDK, GoogleAdmob.
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 10
Platform you are targeting (iOS, Android, and/or desktop):  Android
PlayServicesResolver Version: **v1.2.113** (Happened with other versions)
Grade: 3.2

## Please describe the issue here:
- We Updated from Firebase **4.4.0 to 6.0.0**
- We build using Gradle.
- During our 4.4.0 time, we built using gradle, but dependencies were not being resolved by gradle (like older version of PlayServicesResolver does).
- We also updated Gradle to v3.2 (which implies using v1.2.113, for the "implementation" depency resolution)
- During Build we get this error on a Unity Window:
`More than one file was found with OS independent path 'lib/x86/libFirebaseCppAnalytics.so'. See Console for more Details`
- On the Console:

```
CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_144\bin\java.exe -classpath "C:\Program Files\Unity2017428f1\Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"
stderr[
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task :transformNativeLibsWithMergeJniLibsForRelease.
> More than one file was found with OS independent path lib/x86/libFirebaseCppAnalytics.so
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 3s
]
stdout[
Starting a Gradle Daemon (subsequent builds will be faster)
:checkReleaseClasspath
:preBuild UP-TO-DATE
:Firebase:preBuild UP-TO-DATE
...
```

- Luckily if we do a **Force Resolve** (which we shouldn't) the error is resolved until we **close and reopen the editor**

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

I reproduced the error following this Steps:

1) Create new Unity Project.
2) Import Firebase Analytics 4.4.0
3) Force Resolve your depencies
4) Do all the steps necesary to build APK for Android (keystore, bundle name... etc) using the default custom .gradle (default gradle is 3.2 with my version of Unity)
5) Build -> Build does fine.
6) Update to Firebase Analytics 6.0.0
7) Replace Resolver with v1.2.113, since v.1.2.109 uses "compile"
8) Force Resolve your Dependencies
9) Build -> Build does fine.
10) Close Editor and reopen
11) Build Fails.
... From now on Build will fail everytime you reopen editor and don't Resolve dependencies.

**Comment by Mecze** [comment] 2019-06-10 14:14
It is not a serious bug, since we can build after a Force Resolve.
But I'm worried it could be a sympton of something worse, or something we are not doing correctly.
Also I dislike doing innecesary Force Resolve.

**Comment by Mecze** [comment] 2019-06-10 14:16
I also see it might be related with https://github.com/firebase/quickstart-unity/issues/377 , recently openned. I'm very sorry for spaming.

**Comment by gabetoth-dgh** [comment] 2019-06-11 13:47
Hi @Mecze , 
Your solution works for me, I can build the project with force resolve after each editor launch. Also, I tried to build with 6.1.1, but after importing anything from this version the play services resolver entry from the Assets menu.

**Comment by stewartmiles** [comment] 2019-06-12 18:05
Yep this is a dupe of #377, I'll follow up on there.

**Closed by stewartmiles** 2019-06-12 18:05 UTC
Labels: new

**Comment by MatsuiTantto** [comment] 2019-07-15 19:04
I have a similar problem in build gradle
My project with Firebase Analytics works when i install the SDK and the keys of my firebase , but when i reopen in other computer some file is lost, and a error is shown when i try to build.

Can someone help me?

Thanks for now


_CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -classpath "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformNativeLibsWithMergeJniLibsForRelease'._
**> More than one file was found with OS independent path 'lib/x86/libFirebaseCppAnalytics.so'**

_* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights._
