### ISSUE TITLE
SetAsync stuck when mobile device offline

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#762] opened 2020-08-22 14:39 UTC
### Please fill in the following fields:
Unity editor version: 2019.4.7f1
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity Package Manager
Firebase plugins in use (Auth, Database, etc.): Auth, Crashlytics, Firestore
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, AdMob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS / Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
When using `firestoreDB.DisableNetworkAsync()` or the mobile device is offline, calling `docRef.SetAsync()` never finishes.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by wu-hui** [comment] 2020-08-31 15:36
Hi @Nyankoo 

This is intended behavior, and it is consistent with all other platforms we support. Making the task return when device is offline has couple issues:

* We do not know for sure when a device is offline.
* Developers some times need to know their writes are accepted by the backend, some times they simply want to know if the writes are accepted in the local cache. This should not be tied with offline status of the device, because there will be no way to tell for sure.

For important writes that your App will not move forward without being acknowledged, you should wait for the task, other writes  you don't have to wait. I think current API contract is easier to achieve this than your proposal.

I am closing the issue for now, but please continue to comment if you think I am missing something. 

Thanks for trying out our Unity SDK!

**Closed by wu-hui** 2020-08-31 15:36 UTC
Labels: new
