### ISSUE TITLE
Impossible build messaging app

### ISSUE THREAD

**Issue by tfe2012** [firebase/quickstart-unity#46] opened 2017-01-22 18:09 UTC
Trying build test messaging app I get errors

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_UNUserNotificationCenter", referenced from:
      objc-class-ref in libMessaging.a(messaging_0d72481c6b9f9d4c5456dcb81aa103f1.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by stewartmiles** [comment] 2017-01-23 11:10
This is a duplicate of #42 .  You'll need to use Xcode 8 for the moment, until we release a fix that uses weak references to the notification framework.

**Closed by stewartmiles** 2017-01-23 11:10 UTC
