### ISSUE TITLE
[Question] Correct CocoaPods names are Firebase{Component} or Firebase/{Component} ?

### ISSUE THREAD

**Issue by mrtrizer** [firebase/quickstart-unity#1278] opened 2022-05-19 13:45 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.35f1
  * Firebase Unity SDK version: 8.10.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: All components
  * Other Firebase Components in use: Auth, Analytics, Database, Firestore, Functions, Messaging, Storage
  * Additional SDKs you are using:  No other SDKs on iOS
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

In docs here https://firebase.google.com/docs/ios/setup it's said that the name format is Firebase{Component}.
But in Dependencies.xml I see Firebase/{Component} and pod utility was unable to resolve this dependency. 

```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In Podfile:
    Firebase/Analytics (= 8.15.0)
```

So I replaced dependencies in format Firebase/{Component} with Firebase{Component} is this correct? Because now it works, but I don't understand why the pods with old names are not resolved now. Are these modules the same? What is the right way to solve the problem? Has the format of name changed? Because I can see in diff that the name format `Firebase/{Component}` worked before.

Thank you!

**Comment by paulinon** [comment] 2022-05-19 14:05
Hi @mrtrizer,

In the documentation you provided, it says that the `Firebase{Component}` format is utilized in v9.0 of the iOS SDK. The Unity SDK version you're working with doesn't point to v9.0 of the iOS SDK, so it's best that you don't replace the format of the pods.

I'll be closing this for now. Let me know if an issue arises.

**Closed by paulinon** 2022-05-19 14:05 UTC
Labels: type: question, edm4u

**Comment by paulinon** [comment] 2022-05-19 15:42
Hi @mrtrizer,

Thanks for the clarification. I've tested the Podfile you provided, and it seems that the cause of the issue is the mismatch of your Firebase product versions. Specifically, your Remote Config version is different compared to the other products. Fixing the mismatch resolved the issue for me, but feel free to continue with your current approach if it still works.

**Comment by mrtrizer** [comment] 2022-05-19 16:48
Thank you! 
I've forgotten to update FirebaseRemoteConfig and has been misled by the error message. 
The generated file works correctly when versions of all the components are the same.
The problem is solved.
