### ISSUE TITLE
RunTransaction - mutableData doesnt retrieve on Android 1st time

### ISSUE THREAD

**Issue by craNich** [firebase/quickstart-unity#437] opened 2019-08-02 17:36 UTC
Unity editor version:
Firebase Unity SDK version: 6.2.2
Firebase plugins in use (Auth, Database, etc.): Auth, Database
Additional SDKs you are using (Facebook, AdMob, etc.): Mapbox
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

Hello. I have this code:
ref.Child("child1").Child("child2").Child(child3).RunTransaction(mutableData =>
{
string something = (string)mutableData.Child("childname").Value;
...
}

In Unity editor, everything works fine. But when I try it on my android phone (Honor 10), it works like that:
first call: transaction aborted, since string something is empty
second call: transaction succesfull, value of string something returned correctly

Where can be the issue? Is there any way how to eliminate it except running the transaction again?

Also I am doing same thing somewhere else with a bool value and it works fine. So I dont know.

Edit: tried it on my second android phone. Same issue.

**Comment by alexames** [comment] 2019-08-02 22:14
When the transaction runs, it operates on whatever data is in your local cache of the database. If there is no data there, it will still try to run. This is by design, it will re-run again when the data at that location is updated, and keep trying to run the transaction until it is successful. 

Take a look at [this](https://firebase.google.com/docs/database/unity/save-data#save_data_as_transactions) for more details. 

For this reason, you should make sure that your transaction can be safely run multiple times, and can fail gracefully if there is no data present. If you want to ensure that you have up to date data that your transaction can operate on, you can try setting KeepSynced on the location in the database you want to operate on. This will ensure that the data is kept up to date, so if you run a transaction on that location it should get the most up to date data on the first try. (Note though  that this does not guarantee that your transaction will be called only once - if another client changes that location while you are operating on it, your transaction may need to run a second time)

**Comment by craNich** [comment] 2019-08-03 11:03
I am not sure if I understand correctly. 
I mean there are data in the node, like some string. I run transaction  for the first time, it just return empty string in mutable data, instead of string with some text, which is stored in the node. And on the second time (nothing changes in db), it returns correct string. Also the issue is only on Android devices, not in unity editor. So this behavior can be correct?
So I mean should I like loop that transaction few times then?

**Comment by patm1987** [comment] 2019-08-19 22:17
Hi @craNich,

Part of the design of this is to help you gracefully deal with spotty connections or just users in airplane mode (for me, this is major pain point of developing asynchronous multiplayer games). You can happily shove data into a database in whatever network condition exists, know that your app won't grind to a halt, and be able to still gracefully handle merging data in the transaction once you regain connection.

I can think of two disadvantages of KeepSynced:
1) if your user is offline on the first run, even with KeepSynced set to true, you may still get empty data. You'll still want to be able to handle this case. If setting KeepSynced appears to fix your game, you may actually just be hiding a difficult to trace bug.
2) Realtime Database acts like this so it doesn't pull data down until you absolutely need it. If this is something you'll be accessing often, it might be a good idea to set KeepSynced anyway. If this is something you might only access once a session or once every few sessions, you'll be spending a lot of time keeping something updated that doesn't need to be.

Let me know if this all helps and I can close this thread. Otherwise, feel free to keep asking questions. I'm sure all of this is useful information for anyone else researching Realtime Database behaviour.

--Patrick

**Closed** 2019-09-06 22:32 UTC
Labels: help wanted
