### ISSUE TITLE
Android Library duplicated when using mainTemplate.gradle patching

### ISSUE THREAD

**Issue by kshioring** [firebase/quickstart-unity#375] opened 2019-06-05 04:14 UTC
## Please fill in the following fields:
Unity editor version: 2018.3.12f1
Firebase Unity SDK version: 6.0.0
Firebase plugins in use (Auth, Database, etc.): FCM
Additional SDKs you are using (Facebook, AdMob, etc.):
Admob, Facebook, voxelbuster, googlesignin, 
Platform you are using the Unity editor on (Mac, Windows, or Linux): WIndows
Platform you are targeting (iOS, Android, and/or desktop): Android

sorry for my engilsh.

using build, gradle. multidex.

i cant build project after add fcm.

https://scans.gradle.com/s/hh6ksy4nmgdd2

**Comment by ryanmeier** [comment] 2019-06-06 21:05
Hi @kshioring - sorry you're having trouble with the Firebase Unity SDK!

Are you able to reproduce this issue in our [cloud messaging quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp), using only the Firebase plugin?  If you're able to reproduce the issue in the quickstart and provide us with the steps you took to get there, that would greatly help us try to figure out what might be going wrong.

**Comment by DenizPiri** [comment] 2019-06-09 22:30
We had the same problem. Using multidex.
After doing force resolve, commenting out the following line in the gradle template file seems to be working for us. We have the resolve on build and editor toggles disabled.

> implementation 'com.google.firebase:firebase-messaging-unity:6.1.1' // Assets/Firebase/Editor/MessagingDependencies.xml:22

**Comment by appetizermonster** [comment] 2019-06-10 12:17
I found a solution which is basically very similar with the above solution.

### Cause
If you build using custom gradle template,
- Unity Jar Resolver will write out the dependencies into the gradle script. so Gradle will include some dependencies in the build process.
- At the same time, **Unity will copy the aar files in the project into the temporary `libs` folder which is also used in the build process**.
- Firebase Plugin has some aar files in `Assets/Firebase/m2repository/com/google/...` that is used by both of **gradle and unity** (yeah, it's causing the conflict) 

### Solution
Exclude all Firebase aar files from the Unity's build process by unchecking "Android" from "Include Platforms" like the below picture: 

![image](https://user-images.githubusercontent.com/6244462/59194450-ff52a280-8bc3-11e9-9af0-9181aab0d72b.png)

**Comment by stewartmiles** [comment] 2019-06-25 23:09
Folks this was fixed in the Play Services Resolver [1.2.117](https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.117) though you'll probably want to pull the [latest release](https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.120).  We'll update this bug when the issue the latest Play Services Resolver is redistributed with the Firebase Unity SDK.

**Comment by alexames** [comment] 2019-07-04 00:06
This should be fixed as of the latest release, 6.2.0

**Closed by alexames** 2019-07-04 00:06 UTC
Labels: type: bug
