### ISSUE TITLE
I have find Error after build mo unity project

### ISSUE THREAD

**Issue by aqmalarfi** [firebase/quickstart-unity#640] opened 2020-04-10 10:18 UTC
### Please fill in the following fields:
Unity editor version: 2020.1.0.b4
Firebase Unity SDK version: 6.13.0
Source you installed the SDK (.unitypackage or Unity Package Manager):.unitypackage
Firebase plugins in use (Auth, Database, etc.): FirebaseDatabase.unitypackage
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 10
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Tried both

My Error is :

Firebase.InitializationException: Firebase app creation failed. at Firebase.FirebaseApp.CreateAndTrack (Firebase.FirebaseApp+CreateDelegate createDelegate, Firebase.FirebaseApp existingProxy) [0x000e3] in <1be6193be3e248d495eb52dc2920675d>:0 at Firebase.FirebaseApp.Create () [0x00027] in <1be6193be3e248d495eb52dc2920675d>:0 at Firebase.FirebaseApp.get_DefaultInstance () [0x00017] in <1be6193be3e248d495eb52dc2920675d>:0 at Home.Start () [0x0000a] in :0

Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes, the exact same thing happens here, and it feels worse.

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by patm1987** [comment] 2020-04-14 21:55
Duplicate of #641

**Closed by patm1987** 2020-04-14 21:55 UTC
Labels: new
