### ISSUE TITLE
[Bug] iOS Storage reads are never Auth'd

### ISSUE THREAD

**Issue by ChristianMcFarlaneWork** [firebase/quickstart-unity#1115] opened 2021-08-13 07:57 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.28f
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: .unitypackage 
  * Problematic Firebase Component: Storage
  * Other Firebase Components in use: Auth, Database, Firestore
  * Additional SDKs you are using: Yodo1, Megacool
  * Platform you are using the Unity editor on: Windows + Mac
  * Platform you are targeting: **iOS**, Android (issues happening on iOS)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:
In our current project, we are using a mix of both Firestore and Storage to create a UGC browser. However, on iOS Storage reads always returns the error `Error Code '-13021' 'User' is not authorized to perform the desired action.` Even though we have no problem writing to our storage with the exact same check `allow read, write: if request.auth != null`. Similar rules setup on firestore have no issues running and succeed.

Here's the setup with a Repro project
- [Storage Rules](https://user-images.githubusercontent.com/28091817/129322968-af9af712-f50d-479d-9d7c-b07f89006406.png)
- [Firestore Rules](https://user-images.githubusercontent.com/28091817/129323078-5f2d575d-8da9-475d-9f1b-c70bc4043307.png)
- [Results we get from our tests](https://user-images.githubusercontent.com/28091817/129323130-55526d0a-ced4-4f46-b9e2-292940f4a116.png)

#### Steps to reproduce:

What's the issue repro rate? (eg 100%, 1/5 etc)
100% Reproduction rate

What happened? How can we make the problem occur?
1. Setup a project which will download anything from storage. Can be an image or whatever.
2. Setup your security rules for reading from the database to check if the user is Authenticated `request.auth != null`
3. Authorise the user with any kind of Authentication method. For the repro, we use anonymous authentication.
4. Make an iOS build to test on. *[Editor + Android works as expected]*
5. Once authenticated attempt to download anything from the storage.
6. Note that you get an error noting that the user is not authorized to perform the action. However we should be allowed as the rules allow authorized reads, and the file on the server exists

I've attached a repro with more in-depth instructions which is already set up [here](https://github.com/ChristianMcFarlaneWork/FirebaseAuthRepro).

Let me know if I'm missing anything or need to make anything more clear.
Cheers, Chris.

**Comment by paulinon** [comment] 2021-08-16 09:03
Hi @ChristianMcFarlaneWork,

It appears that the repro you provided only contains a README file and a .gitignore file. It would be great if you provide a full repro so that we can isolate what's causing the issue.

**Comment by ChristianMcFarlaneWork** [comment] 2021-08-16 09:07
Sorry @paulinon.
Forgot to push changes. Everything should be good to go now.

**Comment by npicouet** [comment] 2021-09-07 19:00
Any progress on this issue? Running into the exact same thing as well in latest Unity Firebase (8.1.0).
Write actions are Auth'ed properly, but now Read actions are never Auth'ed. Haven't changed my rules or code since Firebase 7.2.0 and it was working in there.

**Comment by npicouet** [comment] 2021-09-27 15:15
Sorry for double post, but this is a game breaking issue for us. Any updates?
Without being able to Read storage on iOS, some major functionality in our app is broken.

**Comment by PatMiimoAI** [comment] 2021-10-01 12:38
I'm facing this issues too :(

**Comment by PatMiimoAI** [comment] 2021-10-01 16:39
I'm facing this issues too, I have to agree with @npicouet that this one seems to be a game breaking issues since we can't do the auth stuff when uploading/downloading to cloud storage.

**Comment by npicouet** [comment] 2021-11-02 13:56
Was this issue ever resolved?

**Comment by saulo-carranza** [comment] 2021-11-11 20:37
@npicouet unfortunately I don't think it was. We are facing the same issue in our game (Android is working fine, but we're not able to push a new iOS version because of this issue). Just for curiosity, did you find any workaround for your app?

**Comment by npicouet** [comment] 2021-11-15 21:22
@saulo-carranza I actually haven't done any work as we've been waiting for a Firebase fix. Sorry!

**Comment by steve6t6** [comment] 2021-12-06 22:20
We have just encountered this issue as well, we are using Unity 2021.2.5f1 using Firebase Unity SDK 8.6.2, we upgraded the project from Unity 2020 and also updated Firebase SDK from 7.2.0, after the update Editor and Android builds can fetch files from storage, but iOS throws the error "User is not authorized to perform the desired action" 

We also had issues relating to cocoapods (1.11.*) not working, so we rolled back to (1.10.*) but ran pod update in the xcode project, not sure if this is related.

This issue is preventing us from being able to deploy to iOS.

**Comment by PatMiimoAI** [comment] 2021-12-07 00:32
I hope they gonna deploy the fix soon, release date is closer and closer :(

**Comment by saulo-carranza** [comment] 2021-12-07 15:15
Well, a similar thing happened to us. After upgrading Unity (from 2018 to 2020), we started having issues with firebase in iOS. We tried upgrading firebase, from 7.0.2 to 8.1.0, but then these auth issues started happening. After several weeks of different tests and a contact with the firebase support team, unfortunately the issue was not solved for our project, so we ended up rolling back to 7.0.2 and using [this patch ](https://github.com/firebase/quickstart-unity/issues/862#issuecomment-771546659) to fix our original issue in the meantime. 

Idk if that could work for you as well, but maybe give it a try until we have a new version with a final fix.

**Comment by a-maurice** [comment] 2022-04-08 00:17
Hi all,

We've been struggling to reproduce this issue (including the repro case that you've provided).  We did recently ship a new version, 8.9.0, which contains a fix to EDM4U, the tool we use to manage iOS dependencies, to properly handle source Cocoapods.  I'm not sure if that will resolve the problem though, as we haven't been able to reproduce it on older versions either.

To confirm, this only seems to be happening on Read, not on Write?

**Comment by a-maurice** [comment] 2022-05-19 23:16
We've released a new version of the Firebase for Unity SDK, 9.0.0, available here: https://github.com/firebase/firebase-unity-sdk/releases/tag/v9.0.0, that includes the fix for this.

The problem seems to have been in how the C++ SDK was interacting with the iOS SDK, but the iOS SDK was rewritten into swift, so there isn't a PR on the Unity side that reflects the fix, but from personal testing, I wasn't able to reproduce it after updating. Thanks for flagging this, and sorry it took a while to fix.

**Closed by a-maurice** 2022-05-19 23:16 UTC
Labels: type: bug, api: storage
