### ISSUE TITLE
[Question] Weird analytics data for Android 7-9

### ISSUE THREAD

**Issue by abogarsukov-braingames** [firebase/quickstart-unity#997] opened 2021-03-15 16:45 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Unity 2019.4.22
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: Auth, Database, Messaging, Crashlytics
  * Additional SDKs you are using: Facebook, IronSource (AdMob, FB Audience, Unity Ads adapters), Adjust
  * Platform you are using the Unity editor on: Mac, Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

We observe weird data losses (?) on Firebase Analytics starting from 11th of March. It seem to happen on devices running Android 7-9 (iOS and Android 10-11 are fine). It seems Firebase analytics stopped reporting activity for some of the users with these devices (other analytic platforms we use report different numbers starting the mentioned date). We didn't release updates to the app at that period of time.

Is it possible that some data from 11th of March is still not shown in Firebase console? Any other possible reasons for such behavior?

**Comment by paulinon** [comment] 2021-03-16 08:13
Hi @abogarsukov-braingames,

Could you verify if the SDK is successfully logging the events by providing your debug logs or screenshots from your Analytics DebugView?

Thanks.

**Comment by MayisGM** [comment] 2021-03-16 11:52
Unity editor version: Unity 2019.3.13
Firebase Unity SDK version: 7.1.0
Source you installed the SDK: Firebase SDK packages direct import
Problematic Firebase Component: Analytics
Other Firebase Components in use: Auth, Database, Messaging, Crashlytics, Storage, Functions
Additional SDKs you are using: Facebook, GoogleMobileAds (IronSource, Unity Ads adapters)
Platform you are using the Unity editor on: Windows
Platform you are targeting: iOS, Android
Scripting Runtime: IL2CPP

We have exact same problem starting from March 9. In our case big portion of android 10 and android 11 devices stopped to report data, which affected on metrics like DAU, Retention etc. Two other analytics tools showing same metrics which differs from Firebase metrics and we insist that we get incorrect analytical data in the firebase. What could be the reason?

**Comment by abogarsukov-braingames** [comment] 2021-03-16 17:38
@paulinon this is a problem we have in production. We do receive Firebase events, the problem is we seem to not receive all of them. Here's a screenshot of our dashboard, you can clearly see that we had events from Firebase at the dates mentioned:
![image](https://user-images.githubusercontent.com/68687154/111354662-399d7d80-868f-11eb-931a-803d1d5d1505.png)

**Comment by paulinon** [comment] 2021-03-17 09:18
Hi @abogarsukov-braingames, 

It appears that the issue is isolated to the Firebase backend and not the SDK. With that, I'll be closing this ticket for now.

You may get in touch with [Firebase Support](https://firebase.google.com/support) where the team can shed some more light on this issue.

Thanks!

**Closed by paulinon** 2021-03-17 09:18 UTC
Labels: api: analytics, needs-attention, type: question
