### ISSUE TITLE
Firebase Auth issue: Losing connection

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#914] opened 2020-12-29 21:20 UTC
While beta-testing our app using Firestore in combination with Auth, we noticed that a handful of users lose their Auth connection after some time. This results in our app treating them as "new users", creating a new anonymous Auth user and a new database entry in Firestore.

We're unable to determine what exactly is causing the connection loss, but it could be a result of these users not using the app for a while.

Is something like this behavior known and/or what would be the best path to prevent this from happening?

**Comment by chkuang-g** [comment] 2021-01-15 00:57
Hi @Nyankoo 

Could you provide a bit more information using [the template](https://github.com/firebase/quickstart-unity/issues/new?assignees=&labels=new&template=issue.md)?  This can really save us time to go back and forth.

Thank you,
Shawn

**Comment by Nyankoo** [comment] 2021-01-15 01:09
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.17f1
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: Firestore, Analytics, Crashlytics, Remote Config
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

See above.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Not reproducible on our end. See above.

What happened? How can we make the problem occur?
See above.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

**Comment by chkuang-g** [comment] 2021-01-19 04:21
@Nyankoo 

Just to double check, this happens to both iOS and Android, correct?

Also, could you elaborate a bit on "`This results in our app treating them as "new users", creating a new anonymous Auth user and a new database entry in Firestore.`" part? How does your code determine if it is a "new users"? Did you use something like `FirebaseAuth.CurrentUser`? Could you include include some code about how you handle Auth and new database entry in Firestore?

Thanks,
Shawn

**Comment by Nyankoo** [comment] 2021-01-19 10:02
@chkuang-g 

We're currently only beta-testing on Android, so I can't say for sure if it is also happening on iOS.

On app start (and after initializing Firebase), we check if the `FirebaseAuth.CurrentUser` is null. When it is null, we treat this as a new installation and create a new anonymous user with `FirebaseAuth.SignInAnonymouslyAsync()`.

Now we have a new user account in auth with a new user ID. When we access Firestore, it checks if this user ID already exists to get the user's entries. As this is a new ID, it creates a new "user" entry in Firestore.

The code is roughly like this:
```
if(FirebaseAuth.CurrentUser == null)
{
FirebaseAuth.SignInAnonymouslyAsync();
getAccountData();
}
else
{
getAccountData();
}
```

**Comment by vimanyu** [comment] 2021-01-22 23:54
Hi @Nyankoo,
Before we ask the Android team about this, could you try setting up your app like the code in our quickstart.
https://github.com/firebase/quickstart-unity/blob/241b0e5f527fb0b2088709a16e747d080853ca89/auth/testapp/Assets/Firebase/Sample/Auth/UIHandler.cs#L92

This will register an Auth State Listener which should fire to refresh the auth token periodically.

**Comment by Nyankoo** [comment] 2021-01-23 23:06
@vimanyu 
Thank you for the code snippet!

Does this automatically refresh the auth token, or do I need to do something inside the Auth State Listener callback? From the snippet in the sample, I can't really tell if more steps are needed.

**Comment by paradizIscool** [comment] 2021-01-25 07:47
Can we force the token refresh to test the behavior?

**Comment by vimanyu** [comment] 2021-01-26 23:42
@Nyankoo,
Am following up internally on this. Wanted to clarify some more things,
- Is the problem observed only after app startup? Is it that the app doesn't remember the user from a previous session?
- `we noticed that a handful of users lose their Auth connection after some time` - did this mean that auth is lost in the same session if its running for a while? Also by connection, do you mean the connection to a database or do you mean something else?

**Comment by Nyankoo** [comment] 2021-01-27 11:41
@vimanyu 
We don't have any details about your two questions, as it only happend to some of our beta testers and not on our devices.

We _assume_ that Firebase forgets about the Auth User from previous sessions.
Also, when I wrote `after some time`, I meant that after days of use, not in the same session. But I can't rule this behavior out, as we don't have any data on our devices to prove any of that.

**Comment by vimanyu** [comment] 2021-01-29 00:03
Hi @Nyankoo,
I understand that the issue isn't easily reproducible. 
I spoke to the Firestore team, and the mobile implementations (Android/iOS) should automatically handle token refreshing. At this point, we can try to gather more information by turning on Debug logging on your user's end and obtaining a logcat dump. 
Will that be possible? You could turn on Debug logging for app and firestore by,
```
FirebaseApp.LogLevel = Firebase.LogLevel.Debug;
FirebaseFirestore.LogLevel = Firebase.LogLevel.Debug;
```

**Comment by Nyankoo** [comment] 2021-01-29 00:10
@vimanyu 
We will try this and see if we can get some more details from one of our users.

On another, maybe related note: how is the current Firebase Auth User saved on the device of the user (or how does Auth keeps Auth data after an app restart)? Would any checks at app startup maybe help with this, too?

**Comment by vimanyu** [comment] 2021-01-29 20:22
On the device, data is stored in platform dependent persistent storage and on app startup, this data is used to retrieve a token without requiring the user to sign in again.

**Comment by Nyankoo** [comment] 2021-01-29 20:55
@vimanyu 
Is there a way to check if the persistent storage files are present at app start to catch this issue?

**Comment by vimanyu** [comment] 2021-02-04 20:24
@Nyankoo,
So the check for persistent data is in the Android implementation and `CurrentUser` should be initialized properly if there is persistent data. Since it is all local, this should be a quick synchronous call. 
https://github.com/firebase/firebase-cpp-sdk/blob/dev/auth/src/android/auth_android.cc#L540

Lets hope we can get some more info from the debug logs and trace what might be happening here.

**Comment by vimanyu** [comment] 2021-03-04 19:43
Hi @Nyankoo,
Just wanted to check if you were able to enable debug logging and if we have any more logs. 
If not, can we close this issue and reopen once we have more information?

**Comment by Nyankoo** [comment] 2021-03-10 09:56
@vimanyu Sadly no more details as of yet, so you can go ahead and close the issue and just reopen it when something comes up! Thank you for your help!

**Comment by vimanyu** [comment] 2021-03-11 01:27
Thanks for confirming! Feel free to re-open/create a new one if we have more information.

**Closed by vimanyu** 2021-03-11 01:27 UTC
Labels: api: auth, needs-attention, type: question
