### ISSUE TITLE
Gradle failed to fetch dependencies.

### ISSUE THREAD

**Issue by tianzexin** [firebase/quickstart-unity#443] opened 2019-08-10 06:43 UTC
## Please fill in the following fields:
Unity editor version: Unity 2018.3.14f1 (64-bit)
Firebase Unity SDK version: 6.2.2
Firebase plugins in use (Auth, Database, etc.):Auth, Database
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, AdMob
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
when i importthis version to my project，it is stop in the Reaolving Android Dependencies，the error is：
Gradle failed to fetch dependencies.

Failed to run 'C:\Work\small_1-1_client\trunk_skin\Temp\PlayServicesResolverGradle\gradlew.bat -b "C:\Work\small_1-1_client\trunk_skin\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" --no-daemon "-PANDROID_HOME=H:/tools/android-sdk-windows" "-PTARGET_DIR=C:\Work\small_1-1_client\trunk_skin\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/Work/small_1-1_client/trunk_skin/Assets/Firebase/m2repository" "-PPACKAGES_TO_COPY=com.android.support:support-v4:25.3.1;com.android.support:appcompat-v7:25.3.1;com.android.support:cardview-v7:25.3.1;com.android.support:customtabs:25.3.1;com.google.firebase:firebase-analytics:16.5.0;com.google.firebase:firebase-core:16.0.9;com.google.firebase:firebase-iid:[17.1.2];com.google.firebase:firebase-analytics-unity:5.6.0;com.google.firebase:firebase-common:18.0.0;com.google.firebase:firebase-analytics:17.0.0;com.google.firebase:firebase-app-unity:6.2.2;com.google.firebase:firebase-auth:18.0.0;com.google.firebase:firebase-auth-unity:6.2.2;com.google.firebase:firebase-database:17.0.0;com.google.firebase:firebase-database-unity:5.6.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=3.2.0"'
stdout:
Unzipping C:\Users\Tzx\.gradle\wrapper\dists\gradle-5.1.1-bin\90y9l8txxfw1s2o6ctiqeruwn\gradle-5.1.1-bin.zip to C:\Users\Tzx\.gradle\wrapper\dists\gradle-5.1.1-bin\90y9l8txxfw1s2o6ctiqeruwn

stderr:
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:103)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:929)
GooglePlayServices.<GradleResolution>c__AnonStorey1:<>m__4(Result) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/GradleResolver.cs:878)
GooglePlayServices.<GradleResolution>c__AnonStorey3:<>m__0() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/GradleResolver.cs:995)
Google.RunOnMainThread:ExecuteNext() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:377)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:408)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
Google.RunOnMainThread:Run(Action, Boolean) (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
GooglePlayServices.<GradleResolution>c__AnonStorey1:<>m__5(Result) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/GradleResolver.cs:995)
GooglePlayServices.ProgressReporter:SignalComplete() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:116)
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:107)
GooglePlayServices.<RunAsync>c__AnonStorey1:<>m__0() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/CommandLine.cs:136)
Google.RunOnMainThread:ExecuteNext() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:377)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:408)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
yes，is error like my project

**Comment by stewartmiles** [comment] 2019-08-13 17:47
This is a duplicate of https://github.com/firebase/quickstart-unity/issues/359#issuecomment-520123215 . In future, it would be great to avoid posting duplicate messages or mentioning that you've posted a duplicate or another issue to track something.

See my answer on:
https://github.com/firebase/quickstart-unity/issues/359#issuecomment-520619530

**Closed by stewartmiles** 2019-08-13 17:47 UTC
Labels: new
