### ISSUE TITLE
Subscribing/Unsubscribing to topics doesn't work on Android [Bug] 

### ISSUE THREAD

**Issue by OrionDev23** [firebase/quickstart-unity#1098] opened 2021-07-21 01:06 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.14f
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Cloud messaging
  * Other Firebase Components in use: Auth, Database, installations, storage,crashalytics,analytics
  * Additional SDKs you are using: Facebook,google sign in
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android (works on iOS)
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

When i try to subscribe to a topic, and wait for the operation to finish, it ends in endless loop as the operation doesn't seem to work, same thing when unsubscring, it was working using 7.2.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? yes
What's the issue repro rate? 80% (only works for the first run (when the app is installed)

What happened? How can we make the problem occur?
Try subscribing / usubscring to a topic in a task and wait for the operation to finish then do something else

**Comment by OrionDev23** [comment] 2021-07-21 11:40
it may be the same problem mentioned [here](https://github.com/firebase/quickstart-unity/issues/1088) :

**Comment by ModischFabrications** [comment] 2021-07-21 14:37
Just encountered the same problem, which both prevents new notifications and prevents us from unregistering old ones. 

The first log is always printed, the second one never. 
```
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task =>
        {
            var dependencyStatus = task.Result;
            if (dependencyStatus == Firebase.DependencyStatus.Available)
            {
                [...]
                Debug.Log($"Trying to subscribe to {Topic}...");
                FirebaseMessaging.SubscribeAsync(Topic).ContinueWithOnMainThread(t =>
                {
                    if (t.IsFaulted) throw t.Exception;
                    Debug.Log($"Firebase subscribed successfully");
                });
          [...]
```

Clearing all data from app settings seems to allow a singular `SubscribeAsync`, as do reinstalls.

**Comment by paulinon** [comment] 2021-07-22 10:13
Hi @OrionDev23,

Thanks for reporting the issue. It's possible that this is related to #1088. In order to confirm this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the steps you've taken before facing this behavior?

**Comment by chkuang-g** [comment] 2021-07-23 00:15
@OrionDev23 @ModischFabrications 

Thanks for reporting this and the sample code.

@ModischFabrications 
For this part of the code
```
                FirebaseMessaging.SubscribeAsync(Topic).ContinueWithOnMainThread(t =>
                {
                    if (t.IsFaulted) throw t.Exception;
                    Debug.Log($"Firebase subscribed successfully");
                });
```
The exception you threw in the continuation block will be stored in the `Task` returned by the `ContinueWithOnMainThread()`.  I suspect something went wrong and an exception was thrown.  Could you try to log it before you rethrow it and see what it says?

 Also, did you override `firebase_messaging_auto_init_enabled` like @maniaks1 did in #1088?

@OrionDev23 
You case does seem similar to #1088.  Did you override `firebase_messaging_auto_init_enabled` like @maniaks1 did in #1088?

I'll add more details in #1088

**Comment by OrionDev23** [comment] 2021-07-23 00:47
@chkuang-g 
Thanks for the reply.
No i didn't 

So i guess i'll stick up with 7.2 for android for now and 8.1 for ios as it doesn't have any problem.

**Comment by chkuang-g** [comment] 2021-07-23 00:57
Got it.  As I described in https://github.com/firebase/quickstart-unity/issues/1088#issuecomment-885321988, `firebase_messaging_auto_init_enabled` probably does not matter here.

Since this is a duplicated bug, I will close this and move the conversation to #1088 for issue management sake. I will escalate this issue to the team.

Thanks for the reporting.

**Comment by chkuang-g** [comment] 2021-07-23 00:57
Duplicate of #1088

**Closed by chkuang-g** 2021-07-23 00:57 UTC
Labels: api: messaging, needs-attention, type: question
