### ISSUE TITLE
FMOD failed to initialize the output device.: "Error initializing output device. " 

### ISSUE THREAD

**Issue by chenhuo2** [firebase/quickstart-unity#343] opened 2019-04-03 04:06 UTC
## Please fill in the following fields:
Unity editor version: 2018.2.13f1
Firebase Unity SDK version: 5.6.0
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): IOS

## Please describe the issue here:
No Sound!  
ReportException: UnityLogError FMOD failed to initialize the output device.: "Error initializing output device. " 
when i import FirebaseSDK and Build to iphone.  Has anyone had the same problem??

**Comment by chkuang-g** [comment] 2019-04-03 22:14
@chenhuo2 
This does not seem to related to Firebase SDK at all.  FMOD is a SFX engine and our Firebase SDK do not generate sounds at all.

Are you seeing this Exception from our quickstart project?  If so, please give us detail how to reproduce it.

Otherwise, I would recommend you to remove Firebase SDK, try to play the potential problematic sounds, build to iphone and try to troubleshoot from there.

**Comment by ryanmeier** [comment] 2019-04-18 17:17
Closing this issue as there haven't been any updates in a few weeks and the problem seems to be unrelated to Firebase.  Feel free to open a new issue if you run into additional problems!

**Closed by ryanmeier** 2019-04-18 17:17 UTC
Labels: help wanted
