### ISSUE TITLE
How to use the same Anonymous user?

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#246] opened 2018-11-12 00:30 UTC
I want a guest user to login, and create only 1 new user on my auth db.
Problem- 
-**On Unity editor**- A new anonymous user is created with each launch of the app 
**On Android** the guest user stays logged in but when the app is uninstalled- then another new anonymous user is created 

My db is just full of anonymous users.

Note- I do use- and check monitoring authentication state 

How can I prevent it from creating multiple users?  I was even thinking about login with a custom token, and save it on the user's device-  but then I need to create my own uid on the admin side and not sure if it's reliable or even a good solution?

The web has so many similar questions and frustrated developers and it seems like Firebase doesn't give a proper solution for that. You'd think it's basic. Am I missing something?

**Comment by alexames** [comment] 2018-11-13 00:05
Can you tell me a little more about your use case? 

On Android, do you want a person to always use the same anonymous account, even across uninstalls and re-installs? If so, I don't think there's a good solution built in for this. Persisting an anonymous account across uninstalls would be difficult to do. If you really want this you'd need to have a way of uniquely identifying a device. If your goal is to avoid creating a new anonymous accounts when testing your unity app, I'm pretty sure that installing over the existing APK without uninstalling it first will preserve the anonymous account you've already created (assuming you're signing with the same key). If Unity is uninstalling the existing APK during the upload process there's also the option of using the adb command line tool to install the APK. 

And for unity, you want the unity editor to always use the same anonymous user? Unfortunately the Unity Editor version doesn't support persistence right now. It's something that we'd like to have but I don't have a timeline for if/when it will be available. In the mean time, you can just have it log in with a test account when run from the editor if you want to prevent new anonymous accounts every time you run it.

**Comment by stewartmiles** [comment] 2019-05-06 16:44
Closing this as a duplicate of #253

**Closed by stewartmiles** 2019-05-06 16:44 UTC
Labels: type: feature request
