### ISSUE TITLE
Crash on application close firebase SDK 6.2.0

### ISSUE THREAD

**Issue by maalfaro** [firebase/quickstart-unity#411] opened 2019-07-08 13:40 UTC
Unity editor version: Unity 2107.4.28f1
Firebase Unity SDK version: SDK 6.2.0
Firebase plugins in use (Auth, Database, etc.): Analytics, Crashlytics, Remote Config.
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

When i close the app i receive a window with a crash message.

In the console i have the next trace:

FATAL EXCEPTION: UnityMain
07-08 15:31:06.970 20361 20420 E AndroidRuntime: Process: com.theangrykraken.trivial, PID: 20361
07-08 15:31:06.970 20361 20420 E AndroidRuntime: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
07-08 15:31:06.970 20361 20420 E AndroidRuntime: Build fingerprint: 'motorola/cedric/cedric:8.1.0/OPPS28.85-13-4/41d8e:user/release-keys'
07-08 15:31:06.970 20361 20420 E AndroidRuntime: Revision: 'p500'
07-08 15:31:06.970 20361 20420 E AndroidRuntime: pid: 20361, tid: 20433, name: Thread-137  >>> com.theangrykraken.trivial <<<
07-08 15:31:06.970 20361 20420 E AndroidRuntime:     r0 00000000  r1 9520e280  r2 91aab648  r3 94fec2f0
07-08 15:31:06.970 20361 20420 E AndroidRuntime:     r4 91aab648  r5 9520e280  r6 00000000  r7 94fec2d0
07-08 15:31:06.970 20361 20420 E AndroidRuntime:     r8 00004f89  r9 00004fc4  sl 91784628  fp 94fec318
07-08 15:31:06.970 20361 20420 E AndroidRuntime:     ip 804aa658  sp 94fec2d0  lr 803f31bb  pc 803f44b6  cpsr 0000000b
07-08 15:31:06.970 20361 20420 E AndroidRuntime:
07-08 15:31:06.970 20361 20420 E AndroidRuntime:        at libFirebaseCppApp-6.firebase::crashlytics::Crashlytics::LogException(char const*, char const*, std::__ndk1::vector<firebase::crashlytics::Frame, std::__ndk1::allocator<firebase::crashlytics::Frame> >)(crashlytics:5)
07-08 15:31:06.970 20361 20420 E AndroidRuntime:        at libFirebaseCppApp-6.Firebase_Crashlytics_CSharp_FirebaseCrashlyticsInternal_LogException(Firebase_Crashlytics_CSharp_FirebaseCrashlyticsInternal_LogException:54)
07-08 15:31:06.970 20361 20420 W System.err: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
07-08 15:31:06.970 20361 20420 W System.err: Build fingerprint: 'motorola/cedric/cedric:8.1.0/OPPS28.85-13-4/41d8e:user/release-keys'
07-08 15:31:06.970 20361 20420 W System.err: Revision: 'p500'
07-08 15:31:06.970 20361 20420 W System.err: pid: 20361, tid: 20433, name: Thread-137  >>> com.theangrykraken.trivial <<<
07-08 15:31:06.971 20361 20420 W System.err:     r0 00000000  r1 9520e280  r2 91aab648  r3 94fec2f0
07-08 15:31:06.971 20361 20420 W System.err:     r4 91aab648  r5 9520e280  r6 00000000  r7 94fec2d0
07-08 15:31:06.971 20361 20420 W System.err:     r8 00004f89  r9 00004fc4  sl 91784628  fp 94fec318
07-08 15:31:06.971 20361 20420 W System.err:     ip 804aa658  sp 94fec2d0  lr 803f31bb  pc 803f44b6  cpsr 0000000b
07-08 15:31:06.971 20361 20420 W System.err:    at libFirebaseCppApp-6.firebase::crashlytics::Crashlytics::LogException(char const*, char const*, std::__ndk1::vector<firebase::crashlytics::Frame, std::__ndk1::allocator<firebase::crashlytics::Frame> >)(crashlytics:5)
07-08 15:31:06.971 20361 20420 W System.err:    at libFirebaseCppApp-6.Firebase_Crashlytics_CSharp_FirebaseCrashlyticsInternal_LogException(Firebase_Crashlytics_CSharp_FirebaseCrashlyticsInternal_LogException:54)

**Comment by a-maurice** [comment] 2019-07-09 23:00
Hi @maalfaro,

Thanks for the bug report.  I believe we tracked it down, and will have a new version of the SDK available with a fix shortly.  In the meantime, if you would like to try it, you can unzip the following file: 
[Firebase.Crashlytics.dll.zip](https://github.com/firebase/quickstart-unity/files/3375046/Firebase.Crashlytics.dll.zip), and replace the Firebase.Crashlytics.dll file that should be in Assets/Firebase/Plugins.

**Comment by maalfaro** [comment] 2019-07-10 07:55
Hi @a-maurice 
I replaced the Firebase.Crashlytics.dll file but issue persist, i attach my new log maybe could help to solve it.
[crash error unity new dll.txt](https://github.com/firebase/quickstart-unity/files/3376345/crash.error.unity.new.dll.txt)

**Comment by a-maurice** [comment] 2019-07-10 22:01
Seems like a very similar log, unfortunately.  I haven't been able to reproduce the crash on my end in 6.2.0, but looking through the code there was a problem with LogException that could potentially have caused the crash.  We've released a hotfix, 6.2.1, available [here](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_6.2.1.zip), if you could try that out.

How are you triggering the app closing?  Like, the app calling Quit or Exit itself, or are you swiping away the app from the Android app view?

**Comment by cynthiajoan** [comment] 2019-08-07 22:04
@maalfaro would like to ping to see if new SDK fixed your issue, thanks!

**Comment by stewartmiles** [comment] 2019-09-11 22:25
@maalfaro as @a-maurice and @cynthiajoan mentioned, this should have been fixed since 6.2.1.  If you are still having issues please open a new bug.

**Closed by stewartmiles** 2019-09-11 22:25 UTC
Labels: type: bug
