### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PedjaSOZAP** [firebase/quickstart-unity#1169] opened 2021-11-02 08:54 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.7f1
  * Firebase Unity SDK version: 8.4.0
  * Source you installed the SDK: .unityoackage 
  * Problematic Firebase Component: check attached files
  * Other Firebase Components in use: Firebase Analytics, Remote Config, firebase-messaging, firebase-crashlytics
  * Additional SDKs you are using: fyber,facebook
  * Platform you are using the Unity editor on: windows
  * Platform you are targeting: iOS/Android
  * Scripting Runtime: Mono, IL2CPP

### [REQUIRED] Please describe the issue here:

Hello, in crashlytics window we started to see the crashes pthread_mutex_lock that may be related to firebase and are causing issues to number of users. Please double check the attached files below. Thank you

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Unfortunately we don't have any more information than ones that you can see in files attached below

What happened? How can we make the problem occur?
Unfortunately we don't have any more information than ones that you can see in files attached below

If you have a downloadable sample project that reproduces the bug you're reporting, you will
Unfortunately we don't have any more information than ones that you can see in files attached below

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
[pthread_mutex_lock line 4.txt](https://github.com/firebase/quickstart-unity/files/7459193/pthread_mutex_lock.line.4.txt)
[pthread_mutex_lock line 2.txt](https://github.com/firebase/quickstart-unity/files/7459194/pthread_mutex_lock.line.2.txt)
[pthread_mutex_lock line 8.txt](https://github.com/firebase/quickstart-unity/files/7459195/pthread_mutex_lock.line.8.txt)
[pthread_mutex_lock.txt](https://github.com/firebase/quickstart-unity/files/7459197/pthread_mutex_lock.txt)

**Comment by Jack37** [comment] 2021-11-02 09:20
Probably the same as #1160 and  #1166

**Comment by PedjaSOZAP** [comment] 2021-11-02 09:41
I've read both issues but I didn't see any clear solution to this problem. Am i missing something?

**Comment by Jack37** [comment] 2021-11-02 09:58
The only solution so far seems to be removing multiple calls of CheckAndFixDependencies, if you have more of them, but if not then we need to wait for a fix.

**Comment by paulinon** [comment] 2021-11-02 16:59
Hi @PedjaSOZAP,

It's possible that you're calling the `CheckAndFixDependenciesAsync()` method more than once in your implementation, and this creates and destroys the default app once to check for dependencies. Could you try if removing the excess `CheckAndFixDependenciesAsync()` calls makes a difference? 

If it doesn't, it would be great if you could provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so that we can identify what's causing this behavior. You may also try our quickstart to verify the issue persists there as well.

**Comment by PedjaSOZAP** [comment] 2021-11-04 07:47
CheckAndFixDependenciesAsync() is called only once, at when Firebase actually gets initialized. Issue with this that we were unable to reproduce the bug in our test environment, it only happened on the live version of the project.

**Comment by aroman** [comment] 2021-11-04 08:27
I'm also hitting this crash — I also cannot repro in a minimal example, and I can confirm that I too am not calling `CheckAndFixDependenciesAsync()` more than once.

**Comment by paulinon** [comment] 2021-11-04 16:33
Thanks for the additional information, @PedjaSOZAP and @aroman. It's unusual for the crash to appear in just one version of your project. Could you provide a minimal, reproducible example of your implementation so that we can analyze this behavior?

**Comment by aroman** [comment] 2021-11-07 06:32
This bug is a dupe of #1170

**Comment by chkuang-g** [comment] 2021-11-11 02:03
@PedjaSOZAP 

Your callstack fit this profile https://github.com/firebase/quickstart-unity/issues/1160#issuecomment-965920265

Please try to upgrade to the latest and see if this fixes your issue.

**Comment by AjayC-Bsw** [comment] 2021-11-11 17:39
Here is the minimum reproducible code  https://github.com/AjayC-Bsw/FirebaseCrashRepro

Tested with both mono / IL2CPP.
Firebase SDK version - 8.6.1

Steps to reproduce -
1.  Make a Apk and install
2.  Open the Apk
3.  Close app and clear app data open app again
4.  Repeat steps 2-3 few time 

Application crashes when open, on some devices first time on some devices when come again after clearing data , Repeat these steps 5-6 times crash occurs.

I have tested those steps for our production application and able to repro.

This sample does have only firebase analytics , messaging . 

Crash Logs with MONO is different -

          #00 (wrapper managed-to-native) Firebase.AppUtilPINVOKE:FirebaseApp_ReleaseReferenceInternal (System.Runtime.InteropServices.HandleRef)
          #01 Firebase.FirebaseApp:ReleaseReferenceInternal (Firebase.FirebaseApp) <0x23>
          #02 Firebase.FirebaseApp:RemoveReference () <0xf3>
          #03 Firebase.FirebaseApp:Dispose () <0x63>
          #04 Firebase.FirebaseApp:CheckDependenciesInternal () <0x10f>
          #05 Firebase.FirebaseApp/<CheckDependencies>c__AnonStorey2:<>m__0 () <0xf>
          #06 Firebase.FirebaseApp:TranslateDllNotFoundException (System.Action) <0x23>
          #07 Firebase.FirebaseApp:CheckDependencies () <0x8b>
          #08 Firebase.FirebaseApp:<CheckDependenciesAsync>m__2 () <0x1f>
          #09 System.Threading.Tasks.Task`1<Firebase.DependencyStatus>:InnerInvoke () <0x53>

**Comment by PedjaSOZAP** [comment] 2021-11-17 07:54
I've tried updating to latest version of firebase (8.6.1) and issue is still there, it now makes more than 50% of our crashes on crashlytics

**Comment by a-maurice** [comment] 2021-11-19 22:24
We haven't been able to completely reproduce the problem on our end, but we just released 8.6.2, which contains a potential fix for the issue.

**Comment by AjayC-Bsw** [comment] 2021-11-24 10:17
I can confirm we are not getting this issue after updating to 8.6.2

**Comment by PedjaSOZAP** [comment] 2021-11-24 11:41
Hi, I downgraded plugin back to 8.1.0, and I can confirm that we didn't get any issues with that version of the plugin, but I will try on the next update updating firebase to latest version, and I will let you know how that goes. Issue was that we couldn't get the issue in our testing environment o

**Comment by paulinon** [comment] 2021-11-26 14:48
Thanks for letting us know, @PedjaSOZAP. In the event that you encounter an issue with the latest SDK, let us know by leaving a comment so that we can reopen this ticket and continue our investigation.

With that, I'll be closing this for now.

**Closed by paulinon** 2021-11-26 14:48 UTC
Labels: type: question, needs-attention, api: core
