### ISSUE TITLE
Firebase analytics issue with Google Play Games Services plugin

### ISSUE THREAD

**Issue by waqasbhattii** [firebase/quickstart-unity#214] opened 2018-09-13 14:19 UTC
I am unable to see Google Play sign in screen when i use the following package https://github.com/playgameservices/play-games-plugin-for-unity with firebase unity plugin. Its working fine without using firebase analytics https://firebase.google.com/download/unity . 
Please help why these two plugins are conflicting.

**Comment by stewartmiles** [comment] 2018-09-18 22:39
What conflicts are you seeing?

Could you try updating the Play Services Resolver https://github.com/googlesamples/unity-jar-resolver latest version [here](https://github.com/googlesamples/unity-jar-resolver/raw/master/play-services-resolver-1.2.89.0.unitypackage) ?

**Comment by stewartmiles** [comment] 2018-09-19 15:12
To confirm you're doing the following?
* Import Play Games Plugin
* Import Firebase Analytics
* Import Latest Play Services Resolver
* Run Force Resolution menu option for the Android Resolver and verify no errors occur in the console.

**Comment by stewartmiles** [comment] 2018-09-19 19:22
After you've completed the steps you've described you need to install the latest Play Services Resolver plugin [here](https://github.com/googlesamples/unity-jar-resolver/raw/master/play-services-resolver-1.2.89.0.unitypackage) which *may* fix the resolution conflict.

**Comment by waqasbhattii** [comment] 2018-09-20 14:53
I am doing this right now.
1- Importing Play Games Plugin
2- Importing Google Mobile Ads Plugin
3- Importing latest Play Services Resolver

After doing this i am getting the following error when i press force resolve.
Please let me know what to do. Thanks

<img width="555" alt="screen shot 2018-09-20 at 7 51 40 pm" src="https://user-images.githubusercontent.com/43206618/45826942-decd7a00-bd0e-11e8-887a-12f04f01025b.png">

**Comment by waqasbhattii** [comment] 2018-09-21 10:05
@stewartmiles  can you help me in this regard?

The message says "Resolution failed, your application will not run". How to solve this issue?

Thanks

**Comment by stewartmiles** [comment] 2018-09-21 22:32
I just pushed an update to https://github.com/googlesamples/unity-jar-resolver which may fix this issue for you with Google Play Games Services (GPGS).  Could you give the latest [release](https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.90.0.unitypackage) a try?

**Comment by waqasbhattii** [comment] 2018-09-22 08:17
@stewartmiles i did the following again with latest package [https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.90.0.unitypackage](here) : 

1- Importing Play Games Plugin
2- Importing Google Mobile Ads Plugin
3- Importing latest Play Services Resolver

After doing this i am getting the following error when i press force resolve.
<img width="669" alt="screen shot 2018-09-22 at 1 12 57 pm" src="https://user-images.githubusercontent.com/43206618/45915162-c45be380-be69-11e8-864c-c0d747181509.png">
<img width="617" alt="screen shot 2018-09-22 at 1 13 11 pm" src="https://user-images.githubusercontent.com/43206618/45915163-c4f47a00-be69-11e8-9125-57b6bd6e5ed9.png">

**Comment by stewartmiles** [comment] 2018-09-24 16:48
I just gave this a try and it appears to work ok.

I did the following:
* Open Unity (close and reopen if it's already open)
* Open the Firebase Analytics sample
* Import Google Play Games plugin
* Import Firebase Analytics plugin
* Import latest Play Services Resolver plugin
* Switch platform to Android
* Let resolution run (takes a long time to search for non-conflicting packages as Google Play Games hasn't been updated in a while)
* Reports the following issue when resolution is complete:
  ```
  Some conflicting dependencies were found.
  The following dependency versions were modified:
  com.google.android.gms:play-services-base:15.0.1 --> com.google.android.gms:play-services-base:+
  com.google.firebase:firebase-analytics:16.0.1 --> com.google.firebase:firebase-analytics:+
  com.google.firebase:firebase-common:16.0.1 --> com.google.firebase:firebase-common:+
  com.google.firebase:firebase-core:16.0.1 --> com.google.firebase:firebase-core:+
  com.google.games:gpgs-plugin-support:0.9.50 --> com.google.games:gpgs-plugin-support:+
  ```

It seems to be working, since the Gradle resolution script is cached perhaps you could close and reopen Unity to clear the temporarily cached file?

In order to speed up resolution, you'll need to hack `Assets/GooglePlayGames/Editor/m2repository/com/google/games/gpgs-plugin-support/0.9.50/gpgs-plugin-support-0.9.50.pom` to depend upon google play services 15.+ instead (I've attached a replacement file [gpgs-plugin-support-0.9.50.pom.zip](https://github.com/firebase/quickstart-unity/files/2411960/gpgs-plugin-support-0.9.50.pom.zip) for this).

**Comment by Tanek81** [comment] 2018-10-02 15:28
For future readers (and to avoid giving work to the awesome @stewartmiles ), there was another workaround to do on this topic because of this: https://issuetracker.unity3d.com/issues/android-read-phone-state-permission-is-added-in-the-androidmanifest-dot-xml-file-using-latest-26-dot-0-2-sdk
(which in my opinion is an insanely mad "by design" choice)

So the flow was:
1) Update Firebase to 5.3.0
2) Workaround in #192 to download latest Android SDK Tools
3) Fix GPG 0.9.50 by updating `Assets/GooglePlayGames/Editor/m2repository/com/google/games/gpgs-plugin-support/0.9.50/gpgs-plugin-support-0.9.50.pom` file avoiding the conflicting dependencies
4) Fix GPG 0.9.50 by updating to the latest PlayServiceResolver (1.2.90)
5) As now you have the latest 26.X.X Android Build tools (26.1.1 in my case), this ( https://issuetracker.unity3d.com/issues/android-read-phone-state-permission-is-added-in-the-androidmanifest-dot-xml-file-using-latest-26-dot-0-2-sdk ) must be fixed by checking every AndroidManifest and ensuring that each includes at least a `<uses-sdk android:minSdkVersion="X" />` (X can be set to the minSdkVersion set in the ProjectSettings).

Wow, this was a chain of workarounds I'll surely remember for years ;) Testing the Firebase update on our test devices right now.

**Comment by VGMFR** [comment] 2018-10-06 15:02
Hello guys, thanks a million times for the gpgs-plugin-support-0.9.50.pom edit fix!
I've been digging during 2 days to understand first why the app was crashing at start with no readable Stacktrace when adding Google Play Services. Two days lost because gpgs-plugin-support is not up-to-date, damn. Anyway, for whose who will have the same problem (i.e. just trying to have both Firebase and GPS), changing pom dependencies to 15.+ fixed it for me.

**Comment by waqasbhattii** [comment] 2018-10-24 21:51
Hi @stewartmiles 

I have done the following and apk builds successfully. But when i install apk on phone, its says app keeps stopping.

I am doing the following : 

1- Import Google Mobile SDK without Play services resolver from [here](https://github.com/googleads/googleads-mobile-unity)

2- Import Google Play Game Services without Play services resolver from [here](https://github.com/playgameservices/play-games-plugin-for-unity)

3- Import latest Play Services Resolver from [here](https://github.com/googlesamples/unity-jar-resolver)

I press force resolve and everything works fine till successful build. When i install the apk on phone, it crashes. I am using Unity 2018.2.13f1 and my **MacOS** is **Mojave**. My JDK and SDK is fully updated. Please help why my app crashes. Here is the log attached:

[lognew.txt](https://github.com/firebase/quickstart-unity/files/2512459/lognew.txt)

**Comment by stewartmiles** [comment] 2018-10-24 21:56
As shown in the log, this is a problem with the latest AdMob Unity SDK...

```
10-25 02:47:52.258: E/AndroidRuntime(29345): ******************************************************************************
10-25 02:47:52.258: E/AndroidRuntime(29345): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
10-25 02:47:52.258: E/AndroidRuntime(29345): * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
10-25 02:47:52.258: E/AndroidRuntime(29345): * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
10-25 02:47:52.258: E/AndroidRuntime(29345): * follow instructions here: https://goo.gl/h17b6x.                           *
10-25 02:47:52.258: E/AndroidRuntime(29345): ******************************************************************************
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6575)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6127)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6037)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at android.os.Looper.loop(Looper.java:164)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at java.lang.reflect.Method.invoke(Native Method)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
10-25 02:47:52.258: E/AndroidRuntime(29345): Caused by: java.lang.IllegalStateException: 
10-25 02:47:52.258: E/AndroidRuntime(29345): ******************************************************************************
10-25 02:47:52.258: E/AndroidRuntime(29345): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
10-25 02:47:52.258: E/AndroidRuntime(29345): * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
10-25 02:47:52.258: E/AndroidRuntime(29345): * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
10-25 02:47:52.258: E/AndroidRuntime(29345): * follow instructions here: https://goo.gl/h17b6x.                           *
10-25 02:47:52.258: E/AndroidRuntime(29345): ******************************************************************************
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at com.google.android.gms.internal.ads.zzmn.attachInfo(Unknown Source:17)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(Unknown Source:3)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6572)
10-25 02:47:52.258: E/AndroidRuntime(29345): 	... 10 more
```

I recommend opening an issue on the AdMob issue tracker.  I've already informed them off this problem, I think they're working on a Unity guide for this.

If you want to fix this now, well the log message provides the answer at https://goo.gl/h17b6x

**Closed** 2019-01-23 21:03 UTC
Labels: help wanted
