### ISSUE TITLE
Firebase not working on mobile but working on Editor

### ISSUE THREAD

**Issue by aymankoo** [firebase/quickstart-unity#709] opened 2020-06-13 05:32 UTC
### Please fill in the following fields:
Unity editor version: 2020.1.0b7
Firebase Unity SDK version: 6.14.0
Source you installed the SDK (.unitypackage or Unity Package Manager):  Unity Package Manager
Firebase plugins in use (Auth, Database, etc.): Auth 
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Windows
Platform you are targeting (iOS, Android, and/or desktop):  Android
Scripting Runtime (Mono, and/or IL2CPP): 

### Please describe the issue here:
I tried every thing to make Firebase works on android, No success. 
I downloaded the firebase example quick start sample not working. I tried very simple app with almost nothing inside except the following code:
     void Start()
    {
          FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task =>
            {
                if (dependencyStatus == Firebase.DependencyStatus.Available)
                {
                        Firebase.Auth.FirebaseAuth auth = Firebase.Auth.FirebaseAuth.DefaultInstance;
                      // It crashes here
                }
            });
      }
The exccpetion
InitializationException: Firebase app creation failed.
at Firebase.FirebaseApp.CreateAndTrack (Firebase.FirebaseApp+CreateDelegate createDelegate, Firebase.FirebaseApp existingProxy) [0x000e3] in <255216fc307d4a59a4e7a32dc7c6a1b3>:0
at Firebase.FirebaseApp.Create () [0x00027] in <255216fc307d4a59a4e7a32dc7c6a1b3>:0
at Firebase.FirebaseApp.get_DefaultInstance () [0x00017] in <255216fc307d4a59a4e7a32dc7c6a1b3>:0
at Firebase.Auth.FirebaseAuth.get_DefaultInstance () [0x00000] in :0
### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)

I found the following in  logcat.
E/firebase(25573): Failed to read Firebase options from the app's resources. Either make sure google-services.json is included in your build or specify options explicitly.

I searched a lot nothing helped me. 
When I opened the APK I found  google-services-desktop.json  and there is no google-services.json 

In My project I am sure my google-services.json  exists in my assets. 
How to solve this problem

**Comment by patm1987** [comment] 2020-06-15 22:15
Hi @aymankoo ,

I'm sorry that you're running into issues.

It would really help if you reproduced the issue in one of the quickstarts, such as the [auth](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp) one.

Also, if possible, can you upgrade to the [latest Unity SDK](https://firebase.google.com/support/release-notes/unity) (currently 6.15.0)? It should be really easy to do since you're using the Unity Package Manager:
![image](https://user-images.githubusercontent.com/1111611/84710454-7cc09980-af21-11ea-8e15-ab2bac84839f.png)

Now once you've verified that the quickstarts are working on your machine and you're update to date, we need to figure out why `google-services.json` is not being properly processed. Notably, the games SDK should not be looking for this file (rather, it should be processed at build time by the Unity SDK directly). If you export the project, you should see `google-services.xml` under `res/values`:
![image](https://user-images.githubusercontent.com/1111611/84711187-f73de900-af22-11ea-81da-2723bf0a4271.png)

Make sure that you _do not_ follow the [android instructions](https://firebase.google.com/docs/android/setup) - even if you're using gradle. The relevant instructions are all contained in the [Unity getting started guide](https://firebase.google.com/docs/unity/setup). If you've done anything with `apply plugin` in a gradle file, you should undo that work.

The typical next step would be to force resolve the Android dependencies by going to "Assets/External Dependency Manager/Android Resolver/Force Resolve" then building again:
![image](https://user-images.githubusercontent.com/1111611/84710889-55b69780-af22-11ea-9590-63db351f01c8.png)

This will simply force the Firebase plugin in Unity to do its work. If this does fix your issue, you may want to verify that you do have auto-resolution turned on in the future:
![image](https://user-images.githubusercontent.com/1111611/84710996-92828e80-af22-11ea-94d5-da92a66b8ebf.png)

Once you've gone through these steps, let us know and we can do some further debugging. If [you can replicate your issue in the quickstart](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp), then we can investigate unexpected interactions with your machine. If not, we can try to figure out how your setup differs from our reference setup.

Cheers!
--Patrick

**Comment by aymankoo** [comment] 2020-06-24 17:08
Sorry for late response.
    Well I managed to make it work on emu emulator after upgrading the SDK to 6.15 and downgrading the editor to 2109.40.f1,I did a lot of things so i don't remember any more what I did to make it work. 
I did tried the  quick starts and same issue happen with me. 

however after the SDK upgrade this works fine on emulator but not on mobile. I tried to trace the issue  logcat give no error.

**Comment by chkuang-g** [comment] 2020-07-25 00:40
Duplicate of #677

@aymankoo Could you try the workaround suggested here?
https://firebase.google.com/docs/unity/setup#missing_firebase_android_config_file_in_unity_2020

Thanks

**Closed** 2020-07-25 00:40 UTC
Labels: needs attention
