### ISSUE TITLE
Firebase 6.2.0 not initializing on Android and giving errors

### ISSUE THREAD

**Issue by maherahmedraza** [firebase/quickstart-unity#414] opened 2019-07-09 19:04 UTC
Unity 2019.1.9f1
Firebase SDK 6.2.0
.NET 4.x
I wanted to use Firebase for Authentication and when I used it on Android it just suck somewhere in the loop and doesn't proceed. When I saw the log there are error in app initialization.
![firebase errors](https://user-images.githubusercontent.com/29910442/60915444-4e642400-a2a5-11e9-83ef-df357386d10b.PNG)

I have added json file in the StreamingAssets directory and also assign APIkey, AppID and projectID to Firebase.AppOptions as well. The login system work inside the editor but when I build on Android it doesn't work.
![Firebase Start](https://user-images.githubusercontent.com/29910442/60915725-fe399180-a2a5-11e9-8e0d-e59de21d636f.PNG)
![Firebase Init](https://user-images.githubusercontent.com/29910442/60915727-0265af00-a2a6-11e9-991b-0b48dc958900.PNG)

**Comment by a-maurice** [comment] 2019-07-10 01:02
Hi @maherahmedraza 

Can you try putting the google-services.json file not in the StreamingAssets folder, but instead just under Assets (or a subdirectory of that).  Sometimes putting it in StreamingAssets prevents it from being found during the Android startup, when it is needed.

**Comment by maherahmedraza** [comment] 2019-07-10 11:21
> Hi @maherahmedraza
> 
> Can you try putting the google-services.json file not in the StreamingAssets folder, but instead just under Assets (or a subdirectory of that). Sometimes putting it in StreamingAssets prevents it from being found during the Android startup, when it is needed.

I have done that but it didn't work. I also put it both inside streaming assets folder and in the Asset folder but nothing works.

**Comment by maherahmedraza** [comment] 2019-07-10 12:34
When I put the google-services.json file in Streaming Assets Folder it automatically make another file with name oogle-services-desktop.json. So i put the original one out in the Asset folder and export the project to Android. In the Android studio I seeing the same errors.
![Firebase Deprecated](https://user-images.githubusercontent.com/29910442/60969229-6d5fc600-a338-11e9-87b8-02eed08bd566.PNG)
![err1](https://user-images.githubusercontent.com/29910442/60969235-751f6a80-a338-11e9-88b8-8d31b1d19aca.PNG)
![err2](https://user-images.githubusercontent.com/29910442/60969278-9bdda100-a338-11e9-91d4-1ee146d53b8d.PNG)

AS you can see in the logs it is saying to add  APIkey and APPID but I already have it . You can see I am printng this in the picture .

**Comment by maherahmedraza** [comment] 2019-07-10 12:54
I am attaching a picture in which you can see that when I put the google-services.json  file in Asset folder it is not appearing in Android Studio Project Hierarchy.Only the desktop version is showing which is in Streaming Folder.
![Firebase-json](https://user-images.githubusercontent.com/29910442/60970631-ced56400-a33b-11e9-8539-ac607f2bad06.PNG)

**Comment by alexames** [comment] 2019-07-17 21:03
This is really perplexing. Does this issue occur when you try it in the quickstart testapp?

**Comment by idamaeng** [comment] 2019-07-20 14:19
same issue in Version 6.2.1, its preventing our release. Any workaround or hint to solve this issue is very appreciated.

**Comment by chkuang-g** [comment] 2019-07-27 01:19
Hi @maherahmedraza
Does this happen if you just build Android apk directly from Unity instead of exporting to an Android project?
Also, it would be really helpful if you can reproduce with our [QuickStart](https://github.com/firebase/quickstart-unity) project and the steps to reproduce the issue.

@idamaeng 
Could you provide more detail about your project setting, ex. Unity version, build process (ex. did you export to Android project as well?)

Thank you
Shawn

**Comment by mcrvaz** [comment] 2019-07-30 02:17
Same happening here on 6.2.2, iOS and Android.

**Comment by patm1987** [comment] 2019-08-19 20:00
Hi everybody!

I don't want to sound too much like a broken record, but I really don't want to see so many people stuck. It helps way more than you can imagine if you can reproduce the issue with the quickstart project @chkuang-g linked above.

I just wanted to drop the following tidbits to shed a little light on the build process. I want to make sure we all have the same mental model of how Firebase hooks up on the off-chance that it helps us all debug this problem.

The google-services.json on Android is only needed during the build time, some more details are available here: https://medium.com/@samstern_58566/how-to-use-firebase-on-android-without-the-google-services-plugin-93ecc7dc6c4
So, as mentioned above, keeping it in Assets (I like to put it in Assets/Data, which Data is also where I keep things like ScriptableObjects) helps the plugin out the most. When you export, if it worked, it should show up as google-services.xml in res/values:
![image](https://user-images.githubusercontent.com/1111611/63294758-59d54280-c288-11e9-9010-b0c021a19e55.png)

Now, this step is totally automated in Unity, but the google-services-desktop.json is auto-generated from google-services.json for desktop support (as you probably guessed). Notes on that are here: https://firebase.google.com/docs/cpp/setup#desktop_workflow.

So, let us know if you've resolved the issue (and if so, how). And if you haven't, if you can repro the issue on our quickstart apps that again helps a ton.

**Comment by cynthiajoan** [comment] 2019-10-10 20:56
Close this for now since it's been a while. If anyone still runs into this feel free to reopen.

**Closed by cynthiajoan** 2019-10-10 20:56 UTC
Labels: help wanted
