### ISSUE TITLE
firestore: Failed to get document from server.

### ISSUE THREAD

**Issue by ashokdamani** [firebase/quickstart-unity#752] opened 2020-08-16 11:51 UTC
### Please fill in the following fields:
Unity editor version: **2019.2.11f1**
Firebase Unity SDK version: **6.15.0**
Source you installed the SDK (.unitypackage or Unity Package Manager): **Unity Package Manager**
Firebase plugins in use (Auth, Database, etc.): **Auth, Firestore, Analytic, Functions (installed, not using it)**
Additional SDKs you are using (Facebook, AdMob, etc.): **Not yet**
Platform you are using the Unity editor on (Mac, Windows, or Linux): **Windows** 
Platform you are targeting (iOS, Android, and/or desktop):  **Android**
Scripting Runtime (Mono, and/or IL2CPP): **Mono**

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I am facing some strange issue, I have integrated firebase in my unity android app, it was working till yesterday, but today suddenly it stopped working in mobile while fetching document from server, it keeps throwing below error:
**failed to get document because the client is offline**

Even though mobile has internet connectivity, but its unable to connect to firebase cloud on mobile, I have tried installing the app in different phones and using different networks such as 4G and WIFI, also I have even removed all the rules, though the issue is not related to rules. But nothing is working.
**Update**
It does not work on specific phone network, like its not working on Airtel, which I and my brother are using, the app is not working on both our phones, but when I installed same app on my wife's phone, it was working, she is using different network named as Idea.

In unity editor also, it wasn't working, but when I ran it in visual studio debug mode, it started working. To get the document from the server, I am running below code:

```
var UId = {value of user id};
var snap = await Firestore.Collection('Players').Document(UId)  .GetSnapshotAsync(Source.Server);
```

Also I tried to calculate its latency as shown below, it only waits for around 10 seconds, after then it gets failed.
![image](https://user-images.githubusercontent.com/6870472/90394301-11757e00-e0b0-11ea-9da2-fb810461c089.png)

ADB Logs
![image](https://user-images.githubusercontent.com/6870472/90597183-2d8f3180-e20e-11ea-9857-8a952573b264.png)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Not tried yet.

What's the issue repro rate? (eg 100%, 1/5 etc)
80%

**Comment by thebrianchen** [comment] 2020-08-19 17:51
Closing since it's a duplicate of #756.

**Closed by thebrianchen** 2020-08-19 17:51 UTC
Labels: new
