### ISSUE TITLE
Generation of the Firebase Android resource file google-services.xml from Assets/google-services.json failed. If you have not included a valid Firebase Android resources in your app it will fail to initialize.

### ISSUE THREAD

**Issue by abasov90** [firebase/quickstart-unity#539] opened 2019-12-19 13:47 UTC
### Please fill in the following fields:
Unity editor version: Unity 2019.2.15f1 (64-bit)
Firebase Unity SDK version: firebase_unity_sdk_6.8.1
Firebase plugins in use (Auth, Database, etc.): FirebaseAnalytics
Additional SDKs you are using (Facebook, AdMob, etc.): AdMob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 8.1 
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
When adding a file google-services.json to folder Assets

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by stewartmiles** [comment] 2019-12-19 17:49
Like duplicate of #540

**Closed by stewartmiles** 2019-12-19 17:49 UTC
Labels: duplicate
