### ISSUE TITLE
error: Unable to read Google Service plist at path

### ISSUE THREAD

**Issue by a314266177** [firebase/quickstart-unity#911] opened 2020-12-28 07:47 UTC
use Firebase 7.0.1 ,admob and facebook ,this is a problem with packaging Xcode
### [READ] Guidelines

When filing a feature request please make sure the issue title starts with "FR:".

A good feature request ideally
* is either immediately obvious (i.e. "Add Sign in with Apple support"), or
* starts with a use case that is not achievable with the existing Firebase API and
  includes an API proposal that would make the use case possible. The proposed API
  change does not need to be very specific.

Once you've read this section, please delete it and fill out the rest of the template.

### Feature proposal

* Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

**Comment by hlongvu** [comment] 2020-12-29 02:39
We have the same issue.
The export to Xcode project process not adding Google Service plist file into Target membership. 
You can fix this by checking Target membership for this file manually.
Still, our automated build process is breaking because of this. Please fix it.

**Comment by Whyser** [comment] 2021-01-05 10:12
Probably duplicate of: https://github.com/firebase/quickstart-unity/issues/902 and https://github.com/firebase/quickstart-unity/issues/862

But still an issue that really should be fixed asap @DellaBitta

**Comment by alexames** [comment] 2021-01-07 23:19
I think @Whyser is right, this looks like a duplicate of #862. Can you verify that that's what you're seeing? If so I'll go ahead and mark this as a duplicate so we can track it in #862.

**Comment by a314266177** [comment] 2021-01-08 04:04
@alexames @Whyser  I want to ask if you have solved it yet? Do you have any solutions to share

**Comment by Whyser** [comment] 2021-01-08 09:18
@a314266177 check the suggested solution at the bottom here: https://github.com/firebase/quickstart-unity/issues/862

**Comment by a314266177** [comment] 2021-01-11 03:07
@Whyser I guess I'm a little different from it 
![image](https://user-images.githubusercontent.com/18459275/104144009-acbf1500-53fc-11eb-801b-efb6d0832396.png)
![image](https://user-images.githubusercontent.com/18459275/104144156-163f2380-53fd-11eb-8418-4fce5a1c1c99.png)

**Comment by Whyser** [comment] 2021-01-11 10:20
Hmm, might not be same issue then. Have you checked this: https://github.com/firebase/quickstart-unity/issues/557 ?

**Comment by a314266177** [comment] 2021-01-12 06:45
@Whyser Thank you very much! I have now solved the problem that my project name was caused by a space

**Comment by chkuang-g** [comment] 2021-01-15 03:32
@a314266177  Glad to know it is resolved.  I'll close this issue for now.

**Closed by chkuang-g** 2021-01-15 03:32 UTC
Labels: type: question
