### ISSUE TITLE
[Bug] Database URL required in Google Services config files.

### ISSUE THREAD

**Issue by artoonie** [firebase/quickstart-unity#1038] opened 2021-04-30 17:49 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.2f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: All
  * Other Firebase Components in use: Any
  * Additional SDKs you are using: google-signin-unity
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS, debugging via Editor
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:

In order to generate `google-services-desktop.json`, one must have `google-services.json`. It does not seem to auto-generate from `GoogleService-Info.plist`.

#### Steps to reproduce:

1. Follow instructions here, but only for iOS and not for Android builds: https://firebase.google.com/docs/unity/setup#register-app
2. Build any demo app for iPhone. Note that it works fine.
3. Run the same app in the editor by hitting the play button. You will get errors that `google-services.json` is not found.

Workaround: register an Android app, add  `google-services.json` to Assets.

I am not sure if this is a bug, or the documentation should be updated to reflect this. (Or if I did something else wrong and this workaround shouldn't have been necessary.)

#### Relevant Code:

N/A - not a code problem

**Comment by paulinon** [comment] 2021-05-03 13:31
Hi @artoonie,

Could you verify if your `GoogleService-Info.plist` file has a `DATABASE_URL` key? If it doesn't, scroll down to the bottom before:

 ```
</dict>
</plist>
```
and then write write

 ```
	<key>DATABASE_URL</key>
	<string>https://empty-project-95e84.firebaseio.com</string>
</dict>
</plist>
```
replacing empty-project-95e84 with your project ID.

Let me know if this works or if your scenario is different from what I described. Thanks.

**Comment by artoonie** [comment] 2021-05-03 14:43
I have:
1. Deleted `google-services.json`
2. Confirmed that `google-services-desktop.json` is not generated
3. Added `DATABASE_URL` as you suggested
4. Confirmed that `google-services-desktop.json` is correctly generated

So yes, adding `DATABASE_URL` seems to address the issue.

**Comment by paulinon** [comment] 2021-05-03 15:11
Glad to hear that it worked. With that, I'll be closing this ticket. Let me know if you have any other questions.

**Comment by artoonie** [comment] 2021-05-03 16:13
Hi, I'm not convinced this resolves the issue. The documentation does not include this piece of information: https://firebase.google.com/docs/unity/setup#register-app

I believe an acceptable fix would be to either:
1. Ensure GoogleService-Info.plist always contains DATABASE_URL when downloaded, or 
2. Add details in Step 3 of the docs linked above that suggest all users do what you have recommended to me here

**Comment by DellaBitta** [comment] 2021-05-04 19:11
I'm going to re-open this issue and mark it as a bug to track it internally. There was a time when all of the Firebase Console Google Service files had a default DATABASE_URL entry, but now they are optional.  We need to go through the Firebase C++ and Unity SDKs to remove any assumptions that these strings exist.

**Comment by DellaBitta** [comment] 2021-05-10 20:53
Sorry for the back and forth -- when triaging this issue we realized that it's a Duplicate of #946 .  I'm going to close this issue as a duplicate since #946 has more information about how we might fix it.   Thanks for the report!

**Closed by DellaBitta** 2021-05-10 20:53 UTC
Labels: api: core, type: bug
