### ISSUE TITLE
Firebase 6.15, Dynamic Links triggering when resuming app without clicking link.

### ISSUE THREAD

**Issue by npicouet** [firebase/quickstart-unity#707] opened 2020-06-10 19:47 UTC
### Please fill in the following fields:
Unity editor version: Unity 2019.3.13f1
Firebase Unity SDK version: 6.15
Source you installed the SDK: Package Manager
Firebase plugins in use: Everything from package manager, except InstanceID
Additional SDKs you are using: Facebook, Apple Sign In, Google Sign In
Platform you are using the Unity editor on: Mac
Platform you are targeting: iOS and Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
1. Click on a created dynamic link when the app is suspended in background.
2. Dynamic link received gets called properly.
3. Suspend app again.
4. Open app without clicking the dynamic link this time.
5. Dynamic link received gets called again, and uses data from the first dynamic link, even though app was not opened through link.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Haven't Tried Yet

What's the issue repro rate? 100%

**Comment by DellaBitta** [comment] 2020-06-11 15:26
Hi @npicouet,

Does this happen on both Android and iOS? Thanks!

**Comment by npicouet** [comment] 2020-06-11 17:26
> Hi @npicouet,
> 
> Does this happen on both Android and iOS? Thanks!

Oh sorry about that!
iOS: Does not occur. (iOS 13.5, iPhone X)
Android: 100% occurance. (Android 8.0.0, LG G7 ThinQ)

**Comment by patm1987** [comment] 2020-06-19 20:40
Since this is getting tracked internally, I'm marking this as a bug.

**Comment by Xii55** [comment] 2020-06-25 13:02
Any ETA about the fix?

**Comment by pixeption** [comment] 2020-07-10 16:57
Happens on Unity 2019.4.3f1 + Firebase 6.15.1 as well.
I don't use other SDK except for AdMob.

@Xii55 What is the exact implementation of your workaround? I tried to clear clipboard after receiving dynamic link and on app resume but didn't work

**Comment by realworld666** [comment] 2020-09-28 12:48
I've just encountered the same issue on Android DynamicLinks.DynamicLinkReceived is called every time the app regains focus, passing through the same link every time

**Comment by HiddenStar0412** [comment] 2021-01-13 06:41
I have same errors.
There is no way?

**Comment by chkuang-g** [comment] 2021-03-09 02:41
Duplicate of #565

**Closed by chkuang-g** 2021-03-09 02:41 UTC
Labels: api: dynamiclinks, type: bug
