### ISSUE TITLE
Push notifications not working in background and when is in closed state

### ISSUE THREAD

**Issue by devesh2605** [firebase/quickstart-unity#146] opened 2018-03-28 10:18 UTC
Hello,

I have created a plugin in Android for push notification services and using that plugin i am sending push notification. Push notifications is working when I am sending the data inside notification JSON but it's not working when I am sending data inside data JSON like this:

var message = {
"data" : 
  { "extraTitle": "App opened title", 
    "extraMessage" : "App opened message",
    "imageUrl":"https://about.twitter.com/content/dam/about-twitter/company/brand-resources/en_us/OTB_Company_Blue.png.img.fullhd.medium.png"
  },
    topic:topic
}

I went through this document:
https://firebase.google.com/docs/cloud-messaging/unity/client#note_for_android 
but it's not clear. Any help is appreciated.

Thanks,
Devesh V

**Comment by DevJoseWeb** [comment] 2018-04-03 19:46
Where is your project?

**Comment by devesh2605** [comment] 2018-04-05 11:43
@DevJoseWeb Sorry I cannot share the original project. However, I can create a sample project and share with you, works?

**Comment by stewartmiles** [comment] 2018-04-05 14:50
@devesh2605 did you check out https://firebase.google.com/docs/cloud-messaging/unity/client#note_about_message_delivery_on_android ?

Also, you mentioned that you _created_ a plugin, does that mean you're not using the Firebase Unity SDK?

**Comment by devesh2605** [comment] 2018-04-05 15:06
@stewartmiles Hello,

I have created plugin for notification manager  to send push notifications to android devices, I am using firebase unity SDK, once the message is received i am using the plugin to delegate the push notification services. 

I have already checked the link you have sent, but there is no clear documentation provided for the below methods:

/**
 * Workaround for when a message is sent containing both a Data and Notification payload.
 *
 * When the app is in the background, if a message with both a data and notification payload is
 * receieved the data payload is stored on the Intent passed to onNewIntent. By default, that
 * intent does not get set as the Intent that started the app, so when the app comes back online
 * it doesn't see a new FCM message to respond to. As a workaround, we override onNewIntent so
 * that it sends the intent to the MessageForwardingService which forwards the message to the
 * FirebaseMessagingService which in turn sends the message to the application.
 */
@Override
protected void onNewIntent(Intent intent) {
  Intent message = new Intent(this, MessageForwardingService.class);
  message.setAction(MessageForwardingService.ACTION_REMOTE_INTENT);
  message.putExtras(intent);
  message.setData(intent.getData());
  startService(message);
}

/**
 * Dispose of the mUnityPlayer when restarting the app.
 *
 * This ensures that when the app starts up again it does not start with stale data.
 */
@Override
protected void onCreate(Bundle savedInstanceState) {
  if (mUnityPlayer != null) {
    mUnityPlayer.quit();
    mUnityPlayer = null;
  }
  super.onCreate(savedInstanceState);
}

I have to use the above methods in unity?

Thanks,
Devesh V

**Comment by stewartmiles** [comment] 2018-04-05 15:39
https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_an_android_entry_point_activity contains the documentation for the Activity entry point on Android.  If you don't override the default behavior of the activity for the application you will not receive messages in your Unity application's callbacks when the app is closed or in the background.  I suggest starting with our sample and the Firebase Messaging plugin and ensuring that all components are present in our sample are present in your plugin / test application.

**Comment by devesh2605** [comment] 2018-04-06 06:59
@stewartmiles Hello,

I followed the exact same method but still I am not able to receive the messages when the app is in background or killed state.

I am attaching the files for your reference.
[UnityPlayerActivity.java.txt](https://github.com/firebase/quickstart-unity/files/1883007/UnityPlayerActivity.java.txt)

[AndroidManifest.xml.txt](https://github.com/firebase/quickstart-unity/files/1883009/AndroidManifest.xml.txt)

Thanks,
Devesh V

**Comment by stewartmiles** [comment] 2018-04-13 23:54
@devesh2605 you should open a ticket with Firebase Support and share your project, they'll be able to help you debug.

**Comment by stewartmiles** [comment] 2018-04-25 00:56
@devesh2605 I'll assume you opened a ticket with support, so I'm closing this out.

**Closed by stewartmiles** 2018-04-25 00:56 UTC
Labels: help wanted

**Comment by stewartmiles** [comment] 2018-05-15 15:19
@wg-mblazin when you close / kill the application are you swiping it away so that it is no longer running?  If so, since the process is no longer running it will not receive a callback.  Instead the notification - assuming you're sending a notification - is handled by the system.

If you're simply pressing home (i.e the application is in the background) if the app is paused by Unity then you will not get a callback because you're code isn't running.  The callback is queued up though which is why when the application resumes - comes to the foreground - you end up seeing the callback.  We use a MonoBehaviour derived class (you'll see it in your behaviour list as FirebaseHandler) to enqueued on the main thread, if that behaviour is stopped (e.g the game is paused) then you won't see the message until it resumes.

**Comment by wg-mblazin** [comment] 2018-05-15 16:03
So just to clear the misconceptions, I get the same behaviour whether I kill the app or pressing home (putting it in the background). Another misconception is that I am sending a Notification ... I am not, I am sending a Data message (see the payload pasted above). According to the Unity SDK https://firebase.google.com/docs/cloud-messaging/unity/client
when a pure Data message arrives, the Firebase.Messaging.FirebaseMessaging.MessageReceived must be called in all states of the application.

To clarify my use case, I want to display a title, body and image to the user when he is not actively using the app. To do so I must pass in a data message, Firebase needs to wake up the app in the background so I can download the image and show the notification. For this purpose I need to send a pure Data message. I got this perfectly working with the quickstart-android example, I am just porting my code to the Unity SDK.

Hope this helps clarify things.

**Comment by stewartmiles** [comment] 2018-05-15 16:30
@wg-mblazin this section describes how a data message is received by the app:
https://firebase.google.com/docs/cloud-messaging/unity/client#note_about_message_delivery_on_android

In both foreground and background Firebase.Messaging.FirebaseMessaging.MessageReceived will be called, although - as I mentioned before - if the app is paused you won't receive the message until it resumes as the FirebaseHandler MonoBehaviour will not forward the message to your application since it's also paused.  If the app is killed you will not receive the message until it starts, instead the message is received by our implementation of the [FirebaseMessagingService](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService) and queued until the application starts.

The Firebase Unity SDK is built on top of the C++ SDK which uses the Android (Java) SDK under the covers.  If you really want to handle the message as soon as it's received on Android regardless of whether the application is running you'll need to customize the [ListenerService](https://firebase.google.com/docs/cloud-messaging/cpp/client#custom_message_handling_on_android) to intercept the messages before they're queued where you can then do fancy Android specific stuff like create an [expandable rich notification](https://developer.android.com/training/notify-user/expanded).

**Comment by wg-mblazin** [comment] 2018-05-16 08:39
Thanks @stewartmiles for the explanation of the functionality and pointing out the path forward, I think I will definitely need to find another approach, maybe using the Unity Java SDK directly instead.

Could you explain if this behaviour of queueing up messages is due to a technical limitation of the Unity Player or The Firebase Unity SDK design? I find it hard to believe that is actually the desired behaviour since push notifications make most sense when the app is not running, and I seem to not be the only one thinking that.

**Comment by stewartmiles** [comment] 2018-05-16 16:19
@wg-mblazin using the Firebase Android SDK isn't really going to simplify this for you.  For your behavior you'll definitely need to write some Java though as the behavior you're after is very Android specific.

Messages are received by a service which can run when the main activity of the app (i.e the Unity player) isn't running.  So while the main activity isn't up we queue up messages.  As I mentioned if you want to deal with just the background case you can unpause / update the FirebaseHandler MonoBehaviour to pump the Firebase event queue which will retrieve messages and send them to the event handlers you have registered.

**Comment by wg-mblazin** [comment] 2018-05-25 14:09
Just to clear it up for any future reference, I ended up ditching the Firebase Unity SDK and instead using the native Android and iOS SDK, it works like a charm. I actually do not need any Unity code at all and it works.

**Comment by novyd** [comment] 2018-09-21 20:50
@wg-mblazin Would you happen to have a sample project or code that shows how you used the native Android and iOS SDKs to do this?  We are running into the same issue.

**Comment by wg-mblazin** [comment] 2018-09-24 08:12
@novyd No not really, what I did is just take a simple Unity project and export it as Android gradle build and Xcode project and then follow the standard instructions for Android/iOS Firebase setup. There were no real issues with this.

**Comment by utkarshparasarampuria** [comment] 2019-01-29 07:37
@wg-mblazin @stewartmiles  I have the same requirement and the problem is that I had already imported the FCM SDK for Unity. I am trying to remove the SDK from my Unity project by deleting the files that were imported, and reimported all other SDKs to ensure I'm not breaking them. But my app build is crashing as soon as I open the app. Maybe its looking for the MessagingUnityPlayerActivity? How do I remove the Unity SDK safely?

**Comment by wg-mblazin** [comment] 2019-01-29 09:12
@utkarshparasarampuria I don't know of any automated way to do that, you would basically need to delete all the files. You can check which are in there by trying to import the package again.

**Comment by utkarshparasarampuria** [comment] 2019-01-29 10:01
@wg-mblazin I did exactly that. But the builds that I make after it crash as soon as I open the app. Do you know of any other changes that I might need to do?

**Comment by wg-mblazin** [comment] 2019-01-29 10:08
Not much else you can do will need to debug it.

**Comment by stewartmiles** [comment] 2019-01-29 15:47
@utkarshparasarampuria the AndroidManifest.xml that ships with the FCM plugin is what launches the FCM activity.  If that's still in your project but you're missing the jar with the activity your app will crash on launch.  Essentially, what @wg-mblazin said, you'll need to read the adb logcat output to see what's going on.
