### ISSUE TITLE
[Bug] FirebaseInstanceId: Failed to get FIS auth token

### ISSUE THREAD

**Issue by anhdung31793** [firebase/quickstart-unity#1172] opened 2021-11-03 02:40 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.36f1
  * Firebase Unity SDK version: 8.5.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Installations
  * Other Firebase Components in use: Analytics, Crashlytics, Messaging
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Hi,
I imported the Firebase Unity SDK to an empty project and only integrated Firebase Analytics, Crashlytics, Messaging.
I built for Android Platform, disable the internet connection, and open the app.
Then I got this error, and I think it occur ANR for my app.

`FirebaseInstanceId: Failed to get FIS auth token
    java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
        at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@17.2.1:5)
        at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.2.1:8)
        at com.google.firebase.iid.GmsRpc.setDefaultAttributesToBundle(com.google.firebase:firebase-iid@@21.1.0:11)
        at com.google.firebase.iid.GmsRpc.startRpc(com.google.firebase:firebase-iid@@21.1.0:1)
        at com.google.firebase.iid.GmsRpc.getToken(com.google.firebase:firebase-iid@@21.1.0:1)
        at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$2$FirebaseInstanceId(com.google.firebase:firebase-iid@@21.1.0:1)
        at com.google.firebase.iid.FirebaseInstanceId$$Lambda$3.start(Unknown Source:10)
        at com.google.firebase.iid.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-iid@@21.1.0:7)
        at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$3$FirebaseInstanceId(com.google.firebase:firebase-iid@@21.1.0:5)
        at com.google.firebase.iid.FirebaseInstanceId$$Lambda$0.then(Unknown Source:6)
        at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.6.0:2)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
        at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:213)
        at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:533)
        at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:388)
        at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2$FirebaseInstallations(FirebaseInstallations.java:377)
        at com.google.firebase.installations.-$$Lambda$FirebaseInstallations$SC1awUtshakVcZWKWh8TCfIkd4g.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923) `

I uploaded the stack trace below. 
Please check it.
Thank you!

[crash.txt](https://github.com/firebase/quickstart-unity/files/7464987/crash.txt)

**Comment by paulinon** [comment] 2021-11-03 19:17
Hi @anhdung31793,

Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so we can identify what's causing this? I haven't been able to replicate this issue so far.

**Comment by anhdung31793** [comment] 2021-11-04 07:39
Hi @paulinon,
Thank you for your response.
I uploaded the sample project to google drive. 
Please download and check it.
Thank you!

Steps to reproduce:
- Install the game.apk to Google Pixel 4 (android 11) or Xiaomi Redmi Note 7 Pro (android 10)
- Disable the internet connection
- Open the app.
[https://drive.google.com/file/d/1VIUzYkTS_gT5g7w4KfJ8WAhhrGQsJHhm/view?usp=sharing](url)

**Comment by paulinon** [comment] 2021-11-04 15:01
Hi @anhdung31793,

I'm unable to access the file you provided. Since you provided a Google Drive link, could you try sharing this with dps-firebase-files@google.com?

**Comment by anhdung31793** [comment] 2021-11-05 03:11
Hi @paulinon,
I shared my project with dps-firebase-files@google.com.
Please check your email.
Thank you!

**Comment by paulinon** [comment] 2021-11-05 14:14
Hi @anhdung31793,

I was able to replicate your issue. Could you try if updating your google-services.json file by deleting the old one and re-downloading the new google-services.json file from `Firebase console > Project Settings` resolves the issue?

**Comment by anhdung31793** [comment] 2021-11-08 02:11
Hi @paulinon,
The google-services.json that I imported into the project I shared with you is the newest one.
Could you please tell me what the problem is with this file?

**Comment by paulinon** [comment] 2021-11-08 09:27
Hi @anhdung31793,

It's possible that API restrictions you may have applied to API keys used by your app may have to be updated to allow your apps to call the Firebase Installations API.

If re-downloading the file doesn't work, could you try these [steps](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/API_KEY_RESTRICTIONS.md#what-do-i-need-to-do) and see if the issue has been resolved?

**Comment by anhdung31793** [comment] 2021-11-08 17:06
Hi @paulinon,

I followed the steps you sent, you can check the image below. And I checked that the API key is right.
Should I create a new API key or something?

![image_2021_11_08T11_48_10_497Z](https://user-images.githubusercontent.com/33241913/140785061-ee40f79f-a609-452a-904c-715be50cf070.png)

**Comment by anhdung31793** [comment] 2021-11-09 04:13
Hi @paulinon,

I updated Firebase Unity SDK version 8.6.0 and still got this error.
I think the problem occurs when I disable the internet connection then open the app the first time.
If I enable the internet connection, then open the app for the first time, everything works fine even disable the internet next time.
Our game is an offline game. So users usually disable the internet connection when playing the game. This error may reduce our game's retention rate.

[log.txt](https://github.com/firebase/quickstart-unity/files/7501847/log.txt)

**Comment by paulinon** [comment] 2021-11-09 09:03
Hi @anhdung31793,

It look likes the Firebase Installations API isn't in your list of permitted APIs. Simply select "Restrict key" then add the Firebase Installations API to the list of permitted APIs, and click Save. 

Let me know if these steps made a difference.

**Comment by anhdung31793** [comment] 2021-11-09 10:04
Hi @paulinon,

I did it, but still did not work.

![image_2021_11_09T10_02_14_108Z](https://user-images.githubusercontent.com/33241913/140903769-f35fef4c-f798-48cb-bb76-faf4d9df4d8b.png)

**Comment by paulinon** [comment] 2021-11-10 16:49
Hi @anhdung31793,

After discussing this with the team, it appears that your use case wouldn't be able to avoid this issue. Anything generated on the client alone would be insecure, and Firebase would have no idea what it is to validate it against anything or know it's for a certain API. In order for Firebase to function properly. it's important that you have an internet connection. With that, I'll be closing this for now.

**Closed by paulinon** 2021-11-10 16:49 UTC
Labels: type: question, needs-attention, api: instanceid
