### ISSUE TITLE
Queries in Realtime-database (using LimitToLast) are very very slow

### ISSUE THREAD

**Issue by kaibimouez** [firebase/quickstart-unity#478] opened 2019-09-27 14:54 UTC
I'm using RealTime-database(Firebase 7.3.2) and Unity.

When I'm using the LimitToLast() method the query takes a long time (1,5 to 2 minutes) to return a reponse.

But when I load the whole data or execute this query without the **LimitToLast** method this takes not a long time.

I want to ask if everyone has this problem during his development with realtime firebase database.

My database contains 1700 rooms.
this is the query : 
`var result = await FirebaseDatabase.DefaultInstance.GetReference("Rooms")
    .OrderByChild("CreationDate").LimitToLast(10).GetValueAsync();`

And that is the structur of rooms collection in database:
`{
  "Rooms" : {
    "-Lp860kFH8TjdAsPpar1" : {
      "CreationDate" : -14400,
      "Title" : "Room 1",
      ...,
    },
    "-Lp860kFH8TjdAsPpbr2" : {
      "CreationDate" : -14402,
      "Title" : "Room 2",
      ...,
    },
    ...
    "-Lp860kFH8TjdAsPpar3" : {
      "CreationDate" : -14404,
      "Title" : "Room 1700",
      ...,
    }
  }
}`
Thank you in advance

**Comment by ColorTwist** [comment] 2019-09-27 15:38
I also encounter a long slowdown in queries like: 
`.GetReference("users").Child(userid).Child("challenges/members").GetValueAsync();`
Also this one: 
` GetReference("users").OrderByChild("stat/score").LimitToLast(100).GetValueAsync();`

Note: that it happens only in Unity editor, while on Android it works fine.

Using firebase 6.6. also happen with 6.5,
I think before 6.5 it was fine.

**Comment by alexames** [comment] 2019-09-27 18:28
Hi, thanks for the report. I've seen reports of slowness in some other cases that I'm still trying to pin down, so this might be related. 

I have some questions to narrow down the issue, if you don't mind. Does the slowness seem to be only related whether LimitToLast is present in the query? Does LimitToFirst have the same issue? If you re-run the same query twice, are both calls slow? Does the size of the data being queried seem to matter?

**Comment by ColorTwist** [comment] 2019-09-27 20:45
For me, it also happens without LimitToLast and in Unity Editor as i mentioned.
Not sure regarding the size of the data, but I don't have much data anyway.
Regarding calling twice, I need to check, but I think it has the same result.

**Comment by luciofncnd** [comment] 2019-10-18 15:35
Hi, the same is happening to us. The queries start ok, but slowdown terribly after a couple of calls. Specially in OSX. In the Editor but also on the Build. 
We are working in a big art/technology project, based on mobility and maps, and depend heavily on FIrebase to show the data created. Can you help us out ? Thanks in advance.
My query:
Task task1 = Router.Beams().OrderByKey().StartAt(tsQuery).LimitToFirst(1000).GetValueAsync().ContinueWith(task =>

**Comment by luciofncnd** [comment] 2019-10-18 15:40
> Hi, thanks for the report. I've seen reports of slowness in some other cases that I'm still trying to pin down, so this might be related.
> 
> I have some questions to narrow down the issue, if you don't mind. Does the slowness seem to be only related whether LimitToLast is present in the query? Does LimitToFirst have the same issue? If you re-run the same query twice, are both calls slow? Does the size of the data being queried seem to matter?

Hi, I'm using LimitToFirst and happens sometimes in Windows Editor and very frequently in Mac Editor and Build.
We Execute the same query over and over just changing the timestamp to get. And when it  starts to delay , the next query also delays, and so on.
We tried with different quantities of records (50, 200, 1000) and the problem remains the same.
Hope it helps !!

My query:
Task task1 = Router.Beams().OrderByKey().StartAt(tsQuery).LimitToFirst(1000).GetValueAsync().ContinueWith(task =>

@luciofncnd

**Comment by markchandler-google** [comment] 2019-10-30 16:10
We are still looking into this issue.

**Comment by stewartmiles** [comment] 2019-11-06 23:32
We found the root cause of the issue, it will land in our next release which is still running through QA.  This release was a little rocky due to some changes in our testing infrastructure and an upgrade to curl, we'll have it out soon.

**Comment by itmhz2020** [comment] 2019-11-08 07:42
Any update or solution for this problem.

**Comment by markchandler-google** [comment] 2019-11-19 18:37
Firebase 6.7.0 was released a couple of days ago. Please update and recheck to see if the issue has been fixed.

**Comment by a-maurice** [comment] 2019-11-21 02:25
Closing this for now, but feel free to reopen if updating to 6.7.0 does not solve your problem.

**Closed by a-maurice** 2019-11-21 02:25 UTC
Labels: type: bug
