### ISSUE TITLE
How was the state of firestore for unity?

### ISSUE THREAD

**Issue by Thaina** [firebase/quickstart-unity#381] opened 2019-06-10 04:16 UTC
I have waiting for firestore for so long. My project using firestore since it was released yet the unity SDK just not support it for more than a year. I want real time capability like realtimeDB. Why it don't have any news update about it at all?

**Comment by cynthiajoan** [comment] 2019-06-10 23:22
Hi @Thaina, we have this in our list of thing to do.

**Comment by Thaina** [comment] 2019-06-11 01:33
@cynthiajoan Have you done anything with it at all so far? Because I would just make it myself from the start if it not because you people always say it will come soon, you people will do it. If you just be honest that it would take 2 years just for an SDK I will not waste my time waiting hpoelessly like this

Stop the false promise and please be honest. How was the state of firestore for unity?

**Comment by stewartmiles** [comment] 2019-06-11 16:44
@Thaina the Firestore iOS SDK is being ported to C++ https://github.com/firebase/firebase-ios-sdk/tree/master/Firestore and we currently have an internal set of C# bindings for the library.  If you would like to port it yourself, of course you're free to do so but it's a very large task indeed.  If you would like to contribute to the effort, it's ongoing in https://github.com/firebase/firebase-ios-sdk/tree/master/Firestore .

**Comment by Thaina** [comment] 2019-06-11 16:57
@stewartmiles Because it was a large task that's why I want a time frame that I could know it will not waste my time to do

If you cannot release it for another year then it will be worth for me, I could try to hack it in tome. But if you will release it in 2 months then it will waste my time to compete a wrapping process

And I really wonder why you just not opensource that C# binding already

**Comment by stewartmiles** [comment] 2019-06-11 17:14
@Thaina the C# bindings are pretty complicated involving a load of build and test infrastructure.  We're  still working on [our open source C++ SDK](https://github.com/firebase/firebase-cpp-sdk) build & test (CI) infrastructure at the moment, when that's ready we'll start moving our C# bindings to open source as well.

**Comment by Thaina** [comment] 2019-06-12 01:38
@stewartmiles OK, sorry that I might be too straghtforward

Do we have any hope that you might release C# binding for unity in 3 months? It seem very unlikely because you still work on C++ sdk and don't really work on C# itself much as of now?

**Comment by Thaina** [comment] 2019-06-14 08:57
@stewartmiles OK, seem like we have no hope even in this year anymore

**Comment by stewartmiles** [comment] 2019-06-14 19:39
@wilhuff any thoughts for @Thaina ?

**Comment by wilhuff** [comment] 2019-06-14 19:56
Our hands are tied on how much we can pre-announce, unfortunately. I can't say when this will be generally available.

We will be soon be running an early access program to gather feedback on how well our Unity SDK works. If you're interested in this, please send me an email at mcg@firebase.com and I'll get you connected to the right people.

Even if you're not interested in the EAP, what I can say is that it's my team that's working on this and it's our highest priority project. Completing the port of our iOS implementation to C++ is only required for desktop workflow support. Support for mobile platforms is coming along nicely.

**Comment by Thaina** [comment] 2019-06-15 07:38
@wilhuff My point is it not that I need the actual release the GA or even beta

But just some time frame that we could know it worth to implement our own

Because I have believed the word `soon` from firebase feature request (in website UI) since January 2018. Yes, just after it gone beta my company already use firebase in the hope that it will support realtime capability in unity in just 6 or at most 9 months. But now it was whole year and a half and we still struggle on server/client and that was consumed our server and mobile latency on everything. Instead our unity app could be made to response to realtime capability we need to polling for change to the server

All in all I am very frustrated with your word `soon`, it's like you people are and elf that live forever and the word `soon` could be ten years or so. While the project I am working with might be end it lifetime in 2 years, by using firebase but never taste the realtime capability of it at all

**Comment by wilhuff** [comment] 2019-06-15 19:54
@Thaina I understand your frustration and I'm sorry for what you're going through. We're highly constrained in what we can promise publicly so I can't give you a definite answer on timelines. I wish it were different.

Please do note that this isn't an automated response to a feature request :-). When I say it's our highest priority project and that we're close to having it working it should mean something different.

If you enter the early access program we can share more details with you and collaborate on getting this right.

**Comment by Thaina** [comment] 2019-07-03 02:58
@wilhuff I have sent the early access request and now it just make me sign something and got silent again

Could you please just release the sdk as beta. And actually it just a wrapper to android/ios anyway isn't it

**Comment by pshtif** [comment] 2019-07-09 17:31
Exactly my thoughts, I keep hearing about it being done "soon" on every Firebase summit yet still there is nothing even on the horizon. We are getting pushed by Google guys to use Firebase for everything to connect it to our user acquisition but the unavailability of Firestore is a no go as it is the major part we actually need to start implementing the core as a whole on Firebase.

**Comment by Thaina** [comment] 2019-07-18 11:08
Half a month and I still don't have any response

please just release the sdk as beta

**Comment by haywirephoenix** [comment] 2019-07-23 01:28
I am interested in porting my unity app to use Cloud Firestore databases. Is there any news on this or workaround?

**Comment by bhavinpanara22** [comment] 2019-07-23 06:11
After fighting a lot (with inner me) about Firebase or AWS for my next game. I decided to choose Firebase & then I discovered that Firestore on Unity is not officially supported. Highly disappointed.

**Comment by haywirephoenix** [comment] 2019-07-23 06:25
> After fighting a lot (with inner me) about Firebase or AWS for my next game. I decided to choose Firebase & then I discovered that Firestore on Unity is not officially supported. Highly disappointed.

I went through the same process. It's not clearly stated in the documentation so I spent some time trying to get unity to connect aswell.

**Comment by bhavinpanara22** [comment] 2019-07-23 06:39
> > After fighting a lot (with inner me) about Firebase or AWS for my next game. I decided to choose Firebase & then I discovered that Firestore on Unity is not officially supported. Highly disappointed.
> 
> I went through the same process. It's not clearly stated in the documentation so I spent some time trying to get unity to connect aswell. You can use Firebase just fine in Realtime Database mode for now.

Realtime Database is really expensive for storing massive data & specially when you are sure that your ARPU is going to be low. Anyway, I hope firebase team will come up with official Unity support for firestore asap.

**Comment by Thaina** [comment] 2019-07-23 06:40
Yeah and it totally nonsense that the SDK should just opensource so we can use from the get go. But no, they just close it like they don't want us to use

And now @stewartmiles and @wilhuff don't answer anymore

**Comment by bhavinpanara22** [comment] 2019-07-23 06:53
They should have started developing Firestore unity plugin from the day when they completed Firestore for Android & iOS. In fact, Firestore & ML Kit are the only things, that are not supported in Unity officially. We can understand that ML Kit is in beta. So, there is no point of official Unity plugin for ML Kit. But, Firestore came out of beta almost 6 months ago & still not officially supported for Unity. This is not what we can expect from an internet giant Google.
Anyway, I think that we can use the Firestore in Unity by invoking cloud functions. Though this is just suggestion. I have not tested this yet.

**Comment by bhavinpanara22** [comment] 2019-07-23 09:41
NuGet package for Firestore came out of beta, just 7 days ago. So, we can expect a Unity supported version very soon.
[https://www.nuget.org/packages/Google.Cloud.Firestore/](url)

**Comment by Thaina** [comment] 2019-07-23 09:43
@bhavinpanara22 I don't think we can expect

Firestore nuget has been there for 6 months. But unity firestore don't even have a glimpse of beta

**Comment by bhavinpanara22** [comment] 2019-07-23 09:50
I have to be an optimistic in this case. Because our project is entering in development phase very soon.

**Comment by Thaina** [comment] 2019-07-23 10:44
@bhavinpanara22 I used to be optimistic for a whole year. I think you should consider wrapping native firestore in your platform or else you will frustrate like me now

**Comment by wilhuff** [comment] 2019-07-23 16:35
Just a quick update here: we are reading and listening to everything here and in other forums on this topic. However, at this point I don't have much more to offer publicly besides we're working on this and it's still our top priority. Thanks for your continued patience.

**Comment by bhavinpanara22** [comment] 2019-07-24 03:58
@wilhuff Occasional message with "it's in the top priority", hurts more than a complete silence. 😄😄😄

**Comment by radi-cho** [comment] 2019-08-14 22:30
I think easier workaround until official support comes will be to write your API logic in NodeJS inside Cloud Functions communicate with Unity via HTTP requests. The lack of some classes may be a bumper but you can initialize the most important of them by hand and use primitive data types for the rest.

**Comment by Thaina** [comment] 2019-08-15 01:47
@radi-cho It's not acceptable workaround. What we need from firestore is realtime capability. Else I just could use any other database

**Comment by radi-cho** [comment] 2019-08-15 07:28
Totally agree with that.

**Comment by Thaina** [comment] 2019-08-15 07:31
@radi-cho Actually one acceptable workaround might be using GRPC API with GRPC for unity

But I don't have try that yet and don't know that did the GRPC for unity could really support subscription. Or are there any hidden issue

**Comment by bhavinpanara22** [comment] 2019-08-15 09:38
I have already developed some basic things using REST API. And it's working fine. But it's slower than it should be. So I decided to try GRPC API. Though it's too complex. So no luck with that yet.

**Comment by Thaina** [comment] 2019-08-15 09:45
There was another approach that I heard my friend are trying. He just wrapping android/ios firestore SDK with normal wrapping process of unity. Still not hearing anymore progress from him though

**Comment by bhavinpanara22** [comment] 2019-08-15 10:06
That's actually easy to create, but will not work on Unity editor.

**Comment by Thaina** [comment] 2019-08-15 10:18
@bhavinpanara22 That could be emulated with firestore from nuget I think

**Comment by bhavinpanara22** [comment] 2019-08-15 11:40
Then you have to deal with lots of things.
- Android Firestore
- Android to Unity
- iOS Firestore
- iOS to Unity
- Nuget
All things together can create lots of complexity.
When you use REST or GRPC, you have to deal with just one thing.

**Comment by Thaina** [comment] 2019-08-15 12:23
@bhavinpanara22 Sure I just state that there was someone doing it. But I don't actually know what is actually be the most efficient approach

**Comment by qbit86** [comment] 2019-09-19 07:59
@Thaina @bhavinpanara22
It's **Sep 19 2019** now, and Cloud Filestore is still not available for Unity in `firebase_unity_sdk_6.5.0.zip`.

@wilhuff @stewartmiles
Any updates on this?

**Comment by Thaina** [comment] 2019-09-19 08:17
@qbit86 Actually right now some people could get the hand on the beta version of firestore unitypackage, the `not-actually-stable` beta version

We need to register and wait for their acception and also sign some agreement to not expose it to anyone

In other word. It usable but not really stable enough to release as public beta

**Comment by wilhuff** [comment] 2019-09-19 15:17
The Cloud Firestore Unity SDK is currently available in a pre-alpha state for early feedback. We have a number of features to add before we'll do a wider beta release. What's there should be stable though there may be bugs.

If you're interested in trying it out and giving feedback on your experience, please send me an email at mcg@firebase.com and I'll get you set up.

**Comment by colinmacleod** [comment] 2019-12-21 17:21
@wilhuff It's been a few months. Is there any update or, fingers crossed, an ETA?

**Comment by wilhuff** [comment] 2019-12-21 19:48
We've made several releases through the early access program. We've stopped taking new testers temporarily because the overwhelming feedback we've gotten is that while the mobile support we have is working, lack of desktop workflow support is a major blocker to adoption. That's been our focus. I can't share timelines publicly, unfortunately.

**Comment by colinmacleod** [comment] 2019-12-21 19:49
Understood - very much appreciate your getting right back to me with this info. Thank you very much.

**Comment by habitoti** [comment] 2020-01-01 20:29
It‘s really a shame that Google cancels GPGS multiplayer services end of March, pushes devs to Firebase in that announcement, but then has no SDK ready at the same time for a major game dev platform like Unity (or just for Realtime, at the same time discouraging more or less using it — which to me is an indicator for the next deprecation to come, so why bother jumping on that?).

**Comment by dimitar-mihov** [comment] 2020-01-26 15:38
Any news?

**Comment by yanghansyuan** [comment] 2020-01-27 11:34
Waiting for The Cloud Firestore Unity SDK...

**Comment by yakirbu** [comment] 2020-01-27 12:37
![image](https://user-images.githubusercontent.com/12374325/73175231-5c2ea900-4112-11ea-9579-8811be84c57e.png)
They released the firestore in almost every possible language. Can't understand why is it taking years to release even a beta version for Unity.

**Comment by habitoti** [comment] 2020-01-27 13:09
> They released the firestore in almost every possible platform/language. Can't understand why is it taking years to release even a beta version for Unity.

Especially as there is already a C# wrapper. Would just require to implement that on the Unity networking stack.

**Comment by Thaina** [comment] 2020-01-27 13:37
> > They released the firestore in almost every possible platform/language. Can't understand why is it taking years to release even a beta version for Unity.
> 
> Especially as there is already a C# wrapper. Would just require to implement that on the Unity networking stack. They did it already for Realtime DB, so technology-wise it should be rather a no-brainer...

There is a problem. I have already play with beta a bit and argue with firebase person for such times. The main problem is that server SDK is not like mobile SDK at all. In the server they could freely use GRPC and other REST feature natively. In the mobile, however, firebase sdk for unity are wrapper over ios and android SDK, because there is too many mobile OS specific implementation that couldn't simulated with only unity API

I have remember they was talking about some struggle, they try to made native unity SDK for firestore first, but then they give up to make a wrapper instead, that contribute to the delay of this project

Currently now I don't know what are their problem internally but firestore SDK also stuck at `6.7.0` since November

**Comment by habitoti** [comment] 2020-01-27 15:39
Probably two different parties at Google that are responsible for Firestore and Realtime SDK for Unity, and they just don't talk to each other and don't share their experience/code. Technically it should be pretty much the same.

**Comment by manwithsteelnerves** [comment] 2020-01-29 07:36
Can someone list out the use-cases how you want to use firestore in your unity projects?

**Comment by Thaina** [comment] 2020-01-29 08:13
@manwithsteelnerves I use firestore just like normal database in the backend. But whenever there is anything changed, such as another user do something that affect other user, I could let active client listen to that changed and update data/ui/gamestate without the need to polling or even request the data

**Comment by habitoti** [comment] 2020-01-29 08:21
@manwithsteelnerves If you are from Google, then this question really requires steel nerves ;-) I hope it doesn't mean nobody bothered so far...

Realtime DB is not required for most games (I doubt someone would actually use it for "real realtime" applications...), and using it for leaderboards and other lists of all sorts and of course to implement Turn Based gaming it's just too tedious to use with all the query constraints. The pricing of Firestore is also more straightforward and better plannable. And it's honestly beyond me to understand what the issue is in providing such an API, given that the C# implementation (and so the API semantics) already exists, and the implementation technique on the mobile network stacks could be "stolen" from the Realtime SDK.

**Comment by samuelmorais** [comment] 2020-01-29 20:39
> Can someone list out the use-cases how you want to use firestore in your unity projects?

In my case, I develop an AR app (not a game) in Unity that uses Firebase as backend.
Since there is no other Firebase database alternative (because Realtime Database is deprecated), my only option is to use the Firestore  REST HTTP API (which is not very comfortable because of the parsing JSON hard work), and Firestore beta SDK. 

In my case, I need only the regular functionality to just read from the database and present the data to the user. I don't need it to be realtime, although it is very "cool" and I like the idea.

**Comment by wilhuff** [comment] 2020-01-30 00:14
@samuelmorais Note that RTDB is definitely not deprecated.

@habitoti Despite superficial API similarities, Firestore and RTDB are very, very different under the hood. The network protocol employed by RTDB is optimized for the way its backend works, but Firestore deliberately did not follow this model because of its inherent limitations.

As to timing, the Firestore client is quite complex. The iOS implementation is more than [100k LOC with tests](https://github.com/firebase/firebase-ios-sdk/tree/master/Firestore). We're a small team and just porting that to Unity would have radically increased our support burden in a way that wouldn't be sustainable. Instead we've opted to create a shared core used for our iOS, C++, and Unity SDKs. This probably took more time than the shortest path to releasing something just for Unity, but our resources are limited and this choice was better for the long-term health of our team and the product.

We're committed to shipping a Unity SDK (and a C++ SDK), and I realize that every day we spend on this before release is a day you're not able to use the product the way you want. Nobody wants to get this released more than I do :-).

**Comment by Thaina** [comment] 2020-01-30 01:39
@wilhuff And I think I have request many time that you should just opensource it already. It should really be opensourced as beta sรnce 6.5 and don't even necessary to make a unitypackage

And so we could fix it or even contribute with pull request whenever we face the problem

I also thinking that, sometimes later, firebase should release as UPM when git dependency would be supported by UPM. Which means the git repo itself is the release and we could import package as source code directly

**Comment by yanghansyuan** [comment] 2020-01-30 16:25
@manwithsteelnerves In my case for Firestore demand is for users to post text content and receive comments. No really realtime needed I guess.  

@wilhuff Thanks for the information. We know you guys are dealing with hard works. I appreciate it and looking forward to the SDK in the nearly future.

**Comment by manwithsteelnerves** [comment] 2020-01-30 16:34
I'm not from Google but just wanted to know how you would like to use it.

Currently, we are working on a port to get the firestore ready for Unity and will be available pretty soon.

On this regard, wanted to collect some feedback if devs are interested on the same.

**Comment by Danisme1** [comment] 2020-02-03 23:47
@manwithsteelnerves Do you have an approximation for when it is going to be released?

**Comment by jamshiadalam** [comment] 2020-02-05 09:03
@manwithsteelnerves I am Unity Developer. I am trying to develop dating app which I finished it almost but its slow. because i used php and mysql as backend. I wanted to get hands on Firestore and I am pretty much sure my app will be faster with Firestore. So I am waiting for Firestore support. Thanks You :)

**Comment by Thaina** [comment] 2020-02-05 09:14
I too don't know when it would be publicly released but since yesterday I could say it still have some progress and we still have some hope. Wish everyone here can get accepted on alpha program soon

**Comment by samuelmorais** [comment] 2020-02-07 15:29
@wilhuff Thanks for your feedback.
I thought RTDB was deprecated because of [this article](https://firebase.google.com/docs/database/rtdb-vs-firestore?hl=en-us). Sorry about his mistake.

But, anyway, looks like the Firestore is more recommended by you from Firebase than RTDB, so that is the reason why, thinking of a long term development, the most viable solution is to use Firestore, if I understood correctly.

**Comment by wilhuff** [comment] 2020-02-07 16:06
Both databases are fully supported. There are places where RTDB is better (as highlighted by the article) but it's our belief that Firestore is more likely to be the better solution for most developers.

**Comment by ShadedMelee** [comment] 2020-02-13 11:35
We are eagerly waiting for this too. It took too long. 
I hope you may release it soon.

**Comment by tenkiX** [comment] 2020-02-14 18:45
Yes we are all hyped for it. :) Would like to try it out too when it is possible

**Comment by martiener1** [comment] 2020-02-16 16:47
I want to use firestore in my current Unity project.
What could I use as a substitute to continue working on the project?

**Comment by Guidanel** [comment] 2020-02-16 16:49
Personnally I'm using Real Time Database and it works like a charm

**Comment by Eji4h** [comment] 2020-03-06 07:51
Thank for Firestore in Firebase Unity SDK Release.

**Comment by ekotanjyan** [comment] 2020-03-06 11:56
After importing Firestore sdk, Unity just closes when I start the game. (Windows)

I have also used Firebase auth and analytics pakages. (from firebase_unity_sdk_6.11)

Any ideas ?

**Comment by ShadedMelee** [comment] 2020-03-06 12:23
> After importing Firestore sdk, Unity just closes when I start the game. (Windows)
> 
> I have also used Firebase auth and analytics pakages. (from firebase_unity_sdk_6.11)
> 
> Any ideas ?

firestore is added in 6.12. I think you should upgrade all of your firebase packages to 6.12 before importing firestore.

**Comment by ekotanjyan** [comment] 2020-03-06 12:34
> > After importing Firestore sdk, Unity just closes when I start the game. (Windows)
> > I have also used Firebase auth and analytics pakages. (from firebase_unity_sdk_6.11)
> > Any ideas ?
> 
> firestore is added in 6.12. I think you should upgrade all of your firebase packages to 6.12 before importing firestore.

Yes, was going to post that it helped. Thanks.

**Comment by wilhuff** [comment] 2020-03-06 16:22
As some of you have noticed, yesterday we released [Firebase Unity SDK 6.12](https://firebase.google.com/support/release-notes/unity#version_6120_-_march_5_2020) which includes an alpha release of Firestore. This release is _experimental_:

  * We expect there will be breaking changes to the API
  * Some features are missing (for example: IN queries)
  * You may uncover issues for which we can't supply an immediate resolution

Please try it out and let us know how it goes. Read more about how to get this release in [Add Firebase to your Unity project](https://firebase.google.com/docs/unity/setup).

We're very excited to (finally) get this in your hands and hear how it works for you!

**Comment by yanghansyuan** [comment] 2020-03-08 06:14
@wilhuff Thank you guys for your hard work!! It helps a lot!

**Closed** 2020-03-20 07:55 UTC
Labels: type: feature request
