### ISSUE TITLE
6.1.1 fails in-editor on 2019.2.0b5 with DllNotFoundException

### ISSUE THREAD

**Issue by magik-chorne** [firebase/quickstart-unity#380] opened 2019-06-09 20:16 UTC
## Please fill in the following fields:
Unity editor version: 2019.2.0b5
Firebase Unity SDK version:  6.1.1
Firebase plugins in use (Auth, Database, etc.): Auth, DB, Storage
Additional SDKs you are using (Facebook, AdMob, etc.):
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS

## Please describe the issue here:
When hitting play in the editor - I get a "DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6.1.1' error in the console and all of my services fail. My ios build (oddly?) worked just fine (though it builds on 2019.2.0b3).

I just rolled my editor back to 2019.1.5f1 and everything worked fine as well - so it seems to be a localized issue.

**Comment by cynthiajoan** [comment] 2019-06-11 17:55
Hi @magik-chorne, this issue usually caused by different versions of multiple SDKs. Can you try the following steps to see if it solves your issue.
1) Upgrade Auth, DB, Storage all to 6.1.1, or
2) re-import these SDKs from 6.1.1
Thanks!

**Comment by cynthiajoan** [comment] 2019-06-11 18:01
Also would like to see if your call stack looks similar to #362 ?

**Comment by magik-chorne** [comment] 2019-06-11 23:54
Hey Cynthia - 
It's a fresh install of 6.1.1 (delete all the firebase files. import 6.1.1) Literally the only difference between working and failure for me is 2019.1 vs 2019.2.

I saw in that thread that  trying to force a resolve might fix it - but that's only available for android. As I'm building for ios this didn't really apply. My stack did seem somewhat similar to the one referenced in 362 - failing on logutil.

**Comment by ernesernesto** [comment] 2019-06-13 12:12
Hi @cynthiajoan 
This also happens on Unity 2018.3.13f1, on Unity Editor iOS or Editor Android.

We also get DllNotFoundException: FirebaseCppApp-6.0.0
Followed your suggestions to update to 6.1.1, deleted all firebase files and did a fresh unity package import of 6.1.1 but the error still persist.

We got the same call stack with issue #362 the only different is the part in bold Z:/tmp/tmp.**IBVQRwCCZa** which maybe related to the version of firebase that is used.

No other log on console shows even on verbose.

Strange thing though, not everyone on the team gets the error. Tried on two different mac with a same repo, one is failing on run and one is not.

**Comment by magik-chorne** [comment] 2019-06-14 05:10
Quick update: Project is working in 2019.1 - did the upgrade to 2019.2 and it fails again.

Opened that same project on a mac in 2019.2 and it works just fine. Stack now looks like this:

DllNotFoundException: FirebaseCppApp-6.1.1
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at Z:/tmp/tmp.j4XBEIPMsN/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:118)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at Z:/tmp/tmp.j4XBEIPMsN/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:138)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at Z:/tmp/tmp.j4XBEIPMsN/firebase/app/client/unity/proxy/AppUtil.cs:45)
Firebase.LogUtil..ctor () (at Z:/tmp/tmp.j4XBEIPMsN/firebase/app/client/unity/proxy/LogUtil.cs:69)
Firebase.LogUtil..cctor () (at Z:/tmp/tmp.j4XBEIPMsN/firebase/app/client/unity/proxy/LogUtil.cs:30)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at Z:/tmp/tmp.j4XBEIPMsN/firebase/app/client/unity/proxy/FirebaseApp.cs:56)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
FirebaseService..ctor () (at FirebaseService.cs:41)
App+<InitApp>d__28.MoveNext () (at Assets/XXXXX/code/App.cs:81)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <23c160f925be47d7a4fd083a3a62c920>:0)
App+<Awake>d__27.MoveNext () (at Assets/XXXXXX/code/App.cs:62)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <23c160f925be47d7a4fd083a3a62c920>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:115)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by magik-chorne** [comment] 2019-06-17 21:21
Dropped in 1.2.117 and ran in-editor on my windows pc. Still failed.

I attempted to run the Android resolver - but since I'm ios it refuses to let me run it.

**Comment by patm1987** [comment] 2019-06-18 06:46
Hi @magik-chorne:

Thanks a ton for reaching out, and I apologize if it seems like we're walking in circles. I just want to make sure I dot all my i's and cross all my t's for this bug.

So, for the simplest thing. On broken installations, can you just search for the missing dll (FirebaseCppApp) and tell us if it's there and setup to run in the editor: 
![image](https://user-images.githubusercontent.com/1111611/59658621-0dbb3400-9159-11e9-9e2a-d530bb4706ba.png)
Perhaps if you've seen the issue between two different Unity versions, if you can let us know if that's changed at all (ie: different number of libraries or one not marked for use in Editor), that hugely reduces the problem space (and maybe if you play with those a bit, you can find a workaround? Although we'll definitely love to know what you did in that case as clearly the intended user experience is not to have to randomly click checkboxes until it works).

I notice that you're using a beta version, which can be themselves unstable (in fact, the known issues for b6 include the editor crashing for an Android build). If you would be so kind, can you confirm whether or not you run into the issue on b6 and if you've seen the issue on any stable build?

I also notice that you mention that you've tried this on two macs. Can you tell me the Unity Editor versions on that as well?

My intention here is to narrow down the problem space. Running on Windows and building for iOS seems like issues could slip through, but you seem to have eliminated that possibility (correct me if I'm wrong with that call-out). My next goal is to see if the issues are isolated in the beta version of Unity and, if they are, see if there's a trend line that indicates that they're staying broken or could be a temporary instability.

The interesting bits in your callstack are the PINVOKE and SWIG keywords embedded in there. Both would indicate that the issue has something to do with the transition between Unity specific C# and platform specific native code. So anything else strange about that barrier and any other information about your project there (does it run in editor for Android targets? What about a Windows target on Windows?) would be of use. b6 is also specifically interesting as the line "iOS: Can now select architecture for native plugins on iOS & TvOS." indicates that they have been hammering on this very interface.

One last thing we're going to really want to see is a minimum reproducible example. Since your reported issue is `FirebaseCppApp`, I assume that any one of the plugins will cease to function in your setup. If you can confirm that, say, you get this exception in the authentication sample app in the Windows Unity editor targeting iOS on the latest 2019.2 beta but not stable (for instance) that helps us all out a ton.

Thanks for your patience!

**Comment by ernesernesto** [comment] 2019-06-18 11:02
hi @patm1987 so sorry I've missed that reporting part

Unity editor version: 2018.3.13f1,
Firebase Unity SDK version: 6.0.0
Firebase plugins in use (Auth, Database, etc.): Analytics, Remote Config, Crashlytics, InstanceId, Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS & Android

Ios and android both are failing when runs on Unity editor, I've double check your screenshot and for us it seems to have the same checkboxes ticked, the only difference is that we're using 6.0.0.

Different mac that we use, one that is working and one that is not, both using the same Unity Editor, and freshly checked out repo. Tried deleting library folder, restarting unity, no luck.
At this point the above condition is only an illustrations, since it's failing only on some of our artist workstation (we're an osx shop), while on our dev machine it works fine.

Already tried updating play service resolver, got the libs to automatically downloaded to use 6.1.1 but still failing.

More information that we tried to crosscheck:
- Doesn't seem related to osx version that is used (some is mojave, and el capitan)
- Doesn't seem related to installing multiple unity on same workstation

Attached our screenshot for reference
<img width="1434" alt="Screen Shot 2019-06-18 at 5 49 22 PM" src="https://user-images.githubusercontent.com/3048906/59676901-d13c1680-91f2-11e9-8333-2179c5646758.png">

**Comment by patm1987** [comment] 2019-06-19 00:23
Interesting.

Can you check another thing for me? In addition to deleting the library folder, can you try (obviously with Unity closed) deleting all the Firebase related artifacts on a failing computer and re-adding the plugin? This would be:
Assets/Editor Default Resources/Firebase
Assets/Firebase
Assets/Parse
Assets/Play Services Resolver
Assets/Plugins/*/Firebase
(* in my case being Android, iOS, and x86_64)
And definitely try doing this on one of the computers that isn't working (vs your dev machine then checking it after pulling down your repository). We've seen the issue most in the past when you've had two different versions of the Firebase plugin installed. If files were somehow just untracked and not deleted on some local machines or not all of the deletions were pushed into VCS, then problematic artifacts might still be around (another test along these lines would be to delete the repo on a failing machine and re-checkout, although if this _doesn't_ fix the issue I'd just ask for these steps anyway).

Since it sounds like you're using version control to keep all of this in sync (therefore it would be easy to create a diff). IF deleting these then re-importing the plugin fixes the issue, can you let us know what the changes are between what you have in VCS and what you've included on your local machine? If there are no changes, can you check your gitignore (including global) or your VCS's equivalent to see if anything like dll's might be excluded?

And again, something that will help us a ton is if you see this behaviour on one of the quick starts in this repository.

If nothing resolves the matter, I would definitely love to see the detailed log on a failed run in the editor. On MacOS, these normally live in ~/Library/Logs/Unity/Editor.log (you can find it quickly in Console.app). If you really want to make sure you've provided all the feedback necessary, checking the "Verbose Logging" checkbox should spit out pretty much everything you can tell us about the current state of the resolver and the plugin (make sure you capture this all from a session where it breaks).
![image](https://user-images.githubusercontent.com/1111611/59727794-042edc00-91ec-11e9-839c-8cd63309d9e8.png)

And, of course, if you're concerned about any private keys leaking out in the logs, you can always be selective in what you post, go through [firebase support](https://firebase.google.com/support) and make sure you mention this bug (shouldn't be an issue with Firebase's SDKs), or just get us super solid repro steps on one of the quickstart samples.

Thanks for all your help so far!

**Comment by magik-chorne** [comment] 2019-06-19 01:53
Hey @patm1987 -

Flipped a bunch of the switches on the dll. Nothing worked. The settings look the same between 2019.2 and 2019.1.

I don't see the issue on 2019.1. Only on 2019.2. My assumption is that they have mucked with the interface and it's breaking something on the firebase side.

In general I don't have issues with running my ios app in-editor on windows. It's how I've been working for close to a year.

It doesn't run in-editor when the build target is set to either ios or windows (I didnt try android)

The editor version is 2019.2 for the macs and windows machines that I've tested it on where this breaks.

I'm heading out in a few minutes so I won't have a chance to test the sample app and see if I have the same issue.

**Comment by magik-chorne** [comment] 2019-06-21 20:48
Tried the Auth sample app in 2019.2

It failed. Same error.

**Comment by wagenheimer** [comment] 2019-06-24 14:32
For me it's working on Editor but is failing on Windows Standalone builds (Mono and IL2CPP)!

I'm using Firebase Database only.

**Comment by kingfahad777** [comment] 2019-06-25 21:31
I am facing issue of  firebase-analytics-unity.jar missing even I have. re-added plugin but still issue is same any help?

<img width="983" alt="Screen Shot 2019-06-26 at 1 29 31 AM" src="https://user-images.githubusercontent.com/52221017/60135053-ee07b980-97b1-11e9-8d2e-e3a5e0439c79.png">

**Comment by stewartmiles** [comment] 2019-06-25 22:43
@magik-chorne is still something we haven't reproduced.  Any chance you could recreate the failing scenario with one of our sample applications (e.g Remote Config) then zip up the project and post it to this thread?  That will allow us to inspect the .meta files to see what is going on.

@wagenheimer you're right we currently only build DLLs / shared libraries for x64-64 targets on desktop platforms.

@kingfahad777 looks like you're commenting on the wrong issue as this is about running on desktop / in-editor.  It's likely your issue is resolved by using release 1.2.120 of the Play Services Resolver available [here](https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.120).  If you're still having issues please open a bug on the https://github.com/googlesamples/unity-jar-resolver repo.

**Comment by kingfahad777** [comment] 2019-06-25 23:09
@stewartmiles Thank you, my issue resolved.

**Closed** 2019-06-28 23:13 UTC
Labels: help wanted

**Comment by yakirbu** [comment] 2019-07-10 10:42
Issue still occurs after upgrading from 2019.1.0x to 2019.2.0b7
DllNotFoundException: FirebaseCppApp-6.1.1

**Comment by magik-chorne** [comment] 2019-07-10 19:34
@stewartmiles I got a zip for ya of the project here: https://drive.google.com/file/d/1g3rCP6msf5YwIsZWA9me-vLmN-CROJRX/view?usp=sharing

I imagine y'all mostly use Macs - but I'm on Windows 10. My hunch is that could be the source of the repro trouble.

**Comment by raulpereztangelo** [comment] 2019-07-16 08:58
I had this issue and fixed it by updating play services resolver and updating all of my firebase components (Analytics and Crashlytics) to the same version. Not sure which one of them fixed it.

**Comment by chkuang-g** [comment] 2019-07-25 21:12
@magik-chorne 

I downloaded your sample and built it with Unity 2019.2.0b10 and I did not see DllNotFoundException.

I did noticed that you did not include google-services.json in the project.  Were you able to reproduce the issue with google-services.json?

Otherwise, please make you tried the following:

- Asset > Play Services Resolver > Android Resolver > Force Resolve
- Make sure you are importing Firebase SDK from the same version.  For example, if you imported Database and Auth from 6.0.0 before, when you upgrade to 6.2.0, import both Database and Auth.

Please let us know if this resolved your issue.

Shawn

-

**Comment by acoale** [comment] 2019-09-06 14:04
Was this issue ever resolved? I am running Unity 2019.2.3f1 and Firebase 6.1.1. Fresh install of Firebase. I did a force resolve and everything looked good, I did find the files FirebaseCppApp-6.1.1 and it was enabled for editor. google-services.json is in the file. Every time I hit play on editor I get 3 errors of this type.

**Comment by yakirbu** [comment] 2019-09-06 14:43
> Was this issue ever resolved? I am running Unity 2019.2.3f1 and Firebase 6.1.1. Fresh install of Firebase. I did a force resolve and everything looked good, I did find the files FirebaseCppApp-6.1.1 and it was enabled for editor. google-services.json is in the file. Every time I hit play on editor I get 3 errors of this type.

The error remains after removing the Temp, Library and Obj folders?
Make sure you backup your project beforehand, also remove all Firebase files from your project.
After the removing all of these, re-import Firebase plugin.

**Comment by acoale** [comment] 2019-09-06 14:52
Everything was a fresh build of the project.

**Comment by stewartmiles** [comment] 2019-09-07 00:52
Folks, the issue was closed because as far as we're aware it was resolved by the Android Resolver update.  If you're able to reproduce this in one of our sample projects in this repo share it with us and we'll take a look.

**Comment by acoale** [comment] 2019-09-09 14:57
I reverted back to 2018.4.8f1 and Firebase 5.4.4. .dll errors are gone. Firebase Database is giving me permission errors now though.

As far as closing, you said the guy that got it resolved with the resolver was commenting on the wrong issue. Plus diagnosis was still ongoing with the original poster as he continued to post AFTER it was closed. The issue was closed mistakenly.

**Comment by stewartmiles** [comment] 2019-09-09 17:47
@acoale the topic of this bug is `6.1.1 fails in-editor on 2019.2.0b5 with DllNotFoundException` which was related to the Android Resolver not running correctly.  If you're seeing a different issue then I recommend opening up a new issue with a detailed description of what's happening with the latest SDK and we'll take a look.

**Comment by magik-chorne** [comment] 2019-09-10 23:53
OP here

FWIW - I tried again a few days ago and wasn't able to resolve the issue. All I'm hearing is that it's an issue on my end given that nobody can repro with the project I posted.

Since 2019.2 ended up causing other unrelated issues for me - I've decided against investing further time into fixing this particular issue. As it stands - I have no idea whats wrong with my setup/process that causes it to fail.
