### ISSUE TITLE
Unable to load DLL 'FirebaseCppApp-6_15_0':

### ISSUE THREAD

**Issue by realworld666** [firebase/quickstart-unity#706] opened 2020-06-10 19:19 UTC
### Please fill in the following fields:
Unity editor version: 2018.4.22f
Firebase Unity SDK version: 6.15
Source you installed the SDK (.unitypackage or Unity Package Manager): UPM
Firebase plugins in use (Auth, Database, etc.): Auth, Analytics, Storage, EDM, Messaging, Crashlytics, Realtime Database
Additional SDKs you are using (Facebook, AdMob, etc.): Unity Services Analytics, 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
After building the app for Android, the app runs and then throws an exception when attempting to initialise Firebase

```
2020-06-10 19:58:10.834 31321-31371/com.help.myapp D/Unity: Unable to lookup library path for 'advapi32.dll', native render plugin support disabled.
2020-06-10 19:58:10.834 31321-31371/com.help.myapp E/Unity: Unable to find advapi32.dll
2020-06-10 19:58:10.867 31321-31383/com.help.myapp D/Unity: Uploading Crash Report
2020-06-10 19:58:10.867 31321-31383/com.help.myapp E/Unity: DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6_15_0': The specified module could not be found.
      at Firebase.AppUtilPINVOKE.SetLogFunction (Firebase.LogUtil+LogMessageDelegate jarg1) [0x00000] in <00000000000000000000000000000000>:0 
      at Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) [0x00000] in <00000000000000000000000000000000>:0 
      at Firebase.LogUtil.Finalize () [0x00000] in <00000000000000000000000000000000>:0 
     
    (Filename: currently not available on il2cpp Line: -1)
```

The app continues to run but I am not able to sign in to the app. I have switched from the unitypackage method where I was using v6.9 to the UPM version performing the transition using the EDM tool. I've run the Android Resolver and it has created all of the aar files and updated my gradle file. The build succeeds but the app throws the error above.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? YES 

What's the issue repro rate? (eg 100%, 1/5 etc) 100%

My AndroidManifest.xml
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="${applicationId}"
          android:versionCode="1"
          android:versionName="1.0">
  <application 	android:name="androidx.multidex.MultiDexApplication" 
				android:label="@string/app_name"
				android:icon="@drawable/app_icon"
				android:theme="@android:style/Theme.NoTitleBar.Fullscreen">
    
		<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/smallicon" />
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		
		<activity android:label="@string/app_name"
				  android:screenOrientation="portrait"
				  android:launchMode="singleInstance"
                  android:name="com.help.native.MyUnityPlayerActivity">

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>

			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="feelstressfree"/>
			</intent-filter>

			<intent-filter android:autoVerify="true">
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="http" android:host="pn.fsf.com"/>
				<data android:scheme="https" android:host="pn.fsf.com"/>
			</intent-filter>

			<meta-data android:name="unityplayer.UnityActivity" android:value="true" />
		</activity>
		
    <service android:name="com.google.firebase.messaging.MessageForwardingService"
             android:exported="false"/>
  </application>

</manifest>
```
mainTemplate.gradle
```
// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
**BUILD_SCRIPT_DEPS**}
}

allprojects {
    repositories {
        google()
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
}

// Android Resolver Repos Start
([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }
}
([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url "https://maven.google.com"
        }
        maven {
            url (unityProjectPath + "/Assets/GeneratedLocalRepo/Firebase/m2repository") // Packages/com.google.firebase.storage/Firebase/Editor/StorageDependencies.xml:20, Packages/com.google.firebase.auth/Firebase/Editor/AuthDependencies.xml:20, Packages/com.google.firebase.messaging/Firebase/Editor/MessagingDependencies.xml:20, Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:20, Packages/com.google.firebase.database/Firebase/Editor/DatabaseDependencies.xml:20, Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:18
        }
        mavenLocal()
        jcenter()
        mavenCentral()
    }
}
// Android Resolver Repos End
apply plugin: 'com.android.application'
**APPLY_PLUGINS**

dependencies {
	implementation 'androidx.multidex:multidex:2.0.1'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'androidx.appcompat:appcompat:1.0.2' // Assets/PlayServicesResolver/Editor/AndroidDependencies.xml:3
    implementation 'com.google.firebase:firebase-analytics:17.4.1' // Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:13
    implementation 'com.google.firebase:firebase-analytics-unity:6.15.0' // Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-auth:19.3.1' // Packages/com.google.firebase.auth/Firebase/Editor/AuthDependencies.xml:13
    implementation 'com.google.firebase:firebase-auth-unity:6.15.0' // Packages/com.google.firebase.auth/Firebase/Editor/AuthDependencies.xml:20
    implementation 'com.google.firebase:firebase-crashlytics:17.0.0' // Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:13
    implementation 'com.google.firebase:firebase-crashlytics-unity:6.15.0' // Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:20
    implementation 'com.google.firebase:firebase-database:19.3.0' // Packages/com.google.firebase.database/Firebase/Editor/DatabaseDependencies.xml:13
    implementation 'com.google.firebase:firebase-database-unity:6.15.0' // Packages/com.google.firebase.database/Firebase/Editor/DatabaseDependencies.xml:20
    implementation 'com.google.firebase:firebase-messaging:20.1.7' // Packages/com.google.firebase.messaging/Firebase/Editor/MessagingDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging-unity:6.15.0' // Packages/com.google.firebase.messaging/Firebase/Editor/MessagingDependencies.xml:20
    implementation 'com.google.firebase:firebase-storage:19.1.1' // Packages/com.google.firebase.storage/Firebase/Editor/StorageDependencies.xml:13
    implementation 'com.google.firebase:firebase-storage-unity:6.15.0' // Packages/com.google.firebase.storage/Firebase/Editor/StorageDependencies.xml:20
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.2.71' // Assets/PlayServicesResolver/Editor/AndroidDependencies.xml:4
// Android Resolver Dependencies End
**DEPS**}

// Android Resolver Exclusions Start
android {
  packagingOptions {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        applicationId '**APPLICATIONID**'
        ndk {
            abiFilters **ABIFILTERS**
        }
		multiDexEnabled true
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb'**STREAMING_ASSETS**]
    }**SIGN**

    buildTypes {
        debug {
            //minifyEnabled **MINIFY_DEBUG**
            //useProguard **PROGUARD_DEBUG**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD**
            jniDebuggable true
        }
        release {
            //minifyEnabled **MINIFY_RELEASE**
            //useProguard **PROGUARD_RELEASE**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD****SIGNCONFIG**
        }
    }**PACKAGING_OPTIONS****SPLITS**
**BUILT_APK_LOCATION**
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
}**SPLITS_VERSION_CODE****REPOSITORIES****SOURCE_BUILD_SETUP**

```

**Comment by realworld666** [comment] 2020-06-11 10:39
I've reproduced with the Auth sample app. An upload of the project is here https://drive.google.com/file/d/1r_z7KcJ4kleQaahYEeJ3UioJmnMbvXJF/view?usp=sharing
The only thing I've not included in the archive is the google-services.json but hopefully, that's not the cause of my problems :)

**Comment by DellaBitta** [comment] 2020-06-11 15:24
Hello @realworld666,

Unfortunately we're not allowed to download 3rd party projects for testing, but I just tried out the auth testapp with FirebaseAuth installed via UPM.  Installing Firebase Auth installed both FirebaseAuth and Firebase App (Core) which includes the dll that is reportedly missing:

> <img width="299" alt="Screen Shot 2020-06-11 at 10 50 13 AM" src="https://user-images.githubusercontent.com/8961614/84405178-cd5c8d80-abd5-11ea-9751-4dba636fbfeb.png">

I then created an Android build and everything worked properly. 

Since you were able to reproduce it with the Auth test app, could you write a series of steps it took to reproduce the issue?  Please be as specific as possible about how you imported the Auth packages, etc, as I think the problem might be an issue in the import process itself.   Thanks!

**Comment by realworld666** [comment] 2020-06-11 16:08
When I opened the Auth test project, I installed the EDM unitypackage. 
Nothing happened after that because of compile errors, presumably the missing firebase libraries.
I downloaded and installed the auth unitypackage
After that imported, EDM auto ran its migration script and asked me to add the google repo to the packagemanager.
I did that and it asked me to migrate the auth package to UPM which I accepted
The log window then started spitting out logs about uninstalling the auth package. There was a popup with a progress bar in it but the progress didn't move forward. It was a non blocking popup so I quit unity and reloaded it. I force resolved the packages and here we are :)

**Comment by realworld666** [comment] 2020-06-11 16:28
If I manually add the core library in package manager I can get the app to run fine. Thanks

**Comment by DellaBitta** [comment] 2020-06-11 19:50
Ah sounds like there was a problem with the migration hanging mid process.  We're continuing to work on improvements in that area.  

I'm glad you got it to work finally - great news.   Let me know if that's a incorrect assumption, but for now I'm going to close this issue. Thanks!

**Closed** 2020-06-11 19:50 UTC
Labels: needs attention

**Comment by pengsuyu** [comment] 2020-06-16 02:22
We also have the same issues. Can you show us the way you manually add the core library?

**Comment by pengsuyu** [comment] 2020-06-16 05:01
> We also have the same issues. Can you show us the way you manually add the core library?

We resolved it! by manually adding the firebase core library in package manager. The migrating progress is blocked and interrupted so that the External Dependency Manager did't work properly
