### ISSUE TITLE
[Bug] Cocoapods errors when building to iOS  (No workspace file in project)

### ISSUE THREAD

**Issue by DanarKayfi** [firebase/quickstart-unity#1149] opened 2021-09-28 13:48 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.1.22f1
  * Firebase Unity SDK version: 8.3.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics (Any)
  * Other Firebase Components in use: Firestore (ANY)
  * Additional SDKs you are using: none
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
Getting this error when exporting (building) iOS build and will not create a workspace file in the project:

-Error-
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `unicode_normalize'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `installation_root'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in `podfile_path'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:30:in `report'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in `report_error'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
	from /Users/danarkayfi/.gem/ruby/2.6.0/bin/pod:23:in `load'
	from /Users/danarkayfi/.gem/ruby/2.6.0/bin/pod:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `unicode_normalize'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `installation_root'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in `podfile_path'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:205:in `podfile'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:46:in `run'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
	from /Users/danarkayfi/.gem/ruby/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
	from /Users/danarkayfi/.gem/ruby/2.6.0/bin/pod:23:in `load'
	from /Users/danarkayfi/.gem/ruby/2.6.0/bin/pod:23:in `<main>'

pod repo update output:

    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m

UnityEngine.Debug:LogError (object)
Google.Logger:Log (string,Google.LogLevel) (at Z:/tmp/tmp.Nlnzl6oV7C/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:136)
Google.IOSResolver:Log (string,bool,Google.LogLevel) (at Z:/tmp/tmp.rutJAca4y0/third_party/unity/unity_jar_resolver/source/IOSResolver/src/IOSResolver.cs:1159)
Google.IOSResolver:OnPostProcessInstallPods (UnityEditor.BuildTarget,string) (at Z:/tmp/tmp.rutJAca4y0/third_party/unity/unity_jar_resolver/source/IOSResolver/src/IOSResolver.cs:2567)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
-End Error-

#### Steps to reproduce:
- New project with Unity
- Switch Platform to iOS
- Import the firebase package (ex: analytics)
- Import the Info.plist
- Install Cocoapods by iOS Resolver
- Build the iOS version

**Comment by paulinon** [comment] 2021-09-28 15:07
Hi @DanarKayfi,

This is a rather unusual issue. It's possible that this is caused by your pods setup. Could you try if running this makes a difference:

`pod install LANG=en_US.UTF-8`

**Comment by DanarKayfi** [comment] 2021-09-28 22:50
> Hi @DanarKayfi,
> 
> This is a rather unusual issue. It's possible that this is caused by your pods setup. Could you try if running this makes a difference:
> 
> `pod install LANG=en_US.UTF-8`

Same Issue :(

**Comment by tkoki** [comment] 2021-09-28 23:51
Hi @DanarKayfi,

I had same issue. it seems that newer version of cocapods has some problem.
I tried this then works fine.

`sudo gem install cocoapods -n /usr/local/bin -v 1.10.1`

**Comment by paulinon** [comment] 2021-09-29 07:56
Thanks for the additional information, @tkoki. Hoping this would help with @DanarKayfi's issue.

It looks like the cause of the issue is related to the CocoaPods setup. If the issue persists or if a new issue arises, you may file a ticket in their [GitHub tracker](https://github.com/CocoaPods/CocoaPods/issues).

With that, I'll be closing this issue for now.

**Closed by paulinon** 2021-09-29 07:56 UTC
Labels: type: question, needs-attention, api: core

**Comment by dconeybe** [comment] 2021-11-09 01:47
Another workaround is to add `export LANG=en_US.UTF-8` to `~/.bash_profile`
