### ISSUE TITLE
Firestore listener freezes Unity Editor on second launch (works on 6.15?)

### ISSUE THREAD

**Issue by scascar** [firebase/quickstart-unity#859] opened 2020-11-07 00:04 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.14
  * Firebase Unity SDK version: 6.16.1 . Then downgraded to 6.15.2 and it worked 
  * Source you installed the SDK: Package manager
  * Problematic Firebase Component: Firestore (DocumentReference.Listen)
  * Other Firebase Components in use: Auth, Storage, Functions
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Hello, so I spent the last 5hours trying to resolve this bug, and the only way for me was to downgrade the sdk to 6.15.2.
This happened the first time i used the listener for firestore. On the first run, everything runs smoothly, but if i try to recompile or restart the project a second time, the editor hangs indefinitely.
The issue the closest to mine was #638 . 
Seeing that there was a fix for 6.15.1, i gave it a chance, downgraded to 6.15.2 and apparently that solved my issue.

The editor logs were frozen on “Begin MonoManager ReloadAssembly”.
Sorry if thats not very detailed, I tried so many things ask me any question for explanation.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? No I used an existing firebase project.
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
Just call a .Listen on a DocumentReference, quit play mode and try to restart.

#### Relevant Code:

```
//Basically call this anywhere in the project, on an existing DocumentReference object.
docRef.Listen(snap => TestFunc());
```

**Comment by dconeybe** [comment] 2020-11-09 14:47
Unfortunately, this is a known issue and a fix is actively being worked on. Please see https://github.com/firebase/quickstart-unity/issues/845 for full details and a suggested workaround. I'm going to close this issue since it looks like an exact duplicate of #845, but feel free to re-open if you feel that it is a distinct issue.

**Closed by dconeybe** 2020-11-09 14:47 UTC
Labels: new
