### ISSUE TITLE
[6.16.1] Firebase not working on iOS device 

### ISSUE THREAD

**Issue by EdreHM** [firebase/quickstart-unity#903] opened 2020-12-18 21:12 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.15f1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics and Messaging
  * Other Firebase Components in use: Auth
  * Additional SDKs you are using: Facebook 8.1.1 and Maxst 5.0.2
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I am currently migrating my augmented reality project. My project is working on Unity 2019.2.21f1 and uses the following SDKs: Firebase 5.6.1, Facebook 7.15.0 and Maxst 4.1.x. Using this configuration my project works correctly in Unity Editor and on devices (Android and iOS). But if I update the SDKs to: Firebase 6.16.1 and Facebook 8.1.1. It's not working right. It works on UnityEditor and Android, but not on iOS. I've been working on this bug for a long time and I can't find the problem. I have tried different configurations from Firebase 6.14.0 onwards as with Facebook but have not been successful.
 
One of the tests that I have done has been to comment on various parts of my code where I use Messaging, Auth and Analytics. In addition to removing Firebase 6.16.1. of my project. Doing this my AR project works (Cloud Recognition), but if I leave Firebase and the parts of my code that implement Messaging, Auth and Analytics. My AR project doesn't work on iOS (Cloud Recognition and Firebase). It only happens on iOS. On Android it works correctly.
 
I would greatly appreciate your help.

**My Pod File:** 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'FBSDKCoreKit', '~> 8.0'
  pod 'FBSDKGamingServicesKit', '~> 8.0'
  pod 'FBSDKLoginKit', '~> 8.0'
  pod 'FBSDKShareKit', '~> 8.0'
  pod 'Firebase/Analytics', '6.32.2'
  pod 'Firebase/Auth', '6.32.2'
  pod 'Firebase/Core', '6.32.2'
  pod 'Firebase/Messaging', '6.32.2'
end
target 'Unity-iPhone' do
end
use_frameworks!
```

**Here are some of the errors from the Console:**

```
6.32.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
```

**Note:**
``` 
I have followed the steps of the initial firebase setup for iOS (https://goo.gl/ctyzm8). But I don't know how to go to Step 5. **"Initialize Firebase in your app"**. I don't know how to add the lines of code that are mentioned and in which file they go. I am using cocoapods.
```

**Comment by DellaBitta** [comment] 2020-12-21 16:43
Hi @EdreHM,

This seems to be a Duplicate of #862 in which we're tracking failures when !useFrameworks is defined in the podfile. I'm going to close this issue as duplicate and link this issue to that one for further support.

If you feel I've closed this issue in error the please @ me and I'll re-open it! Thanks.

**Closed** 2020-12-21 16:44 UTC
Labels: duplicate, edm4u, type: bug
