### ISSUE TITLE
Crash in editor after FirebaseApp is garbage collected

### ISSUE THREAD

**Issue by IsnaniWidhiHidayat** [firebase/quickstart-unity#200] opened 2018-08-26 20:24 UTC
I Have been using firebase version 4.4.3 and it working without error, but when iam upgrade to version 5.2.1 i got some error just log false to console and nothing informasion i can get from that error. And because of this error when i next play in editor it make editor crash not responding.

`false
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String)
Firebase.FirebaseApp:LogMessage(LogLevel, String)
Firebase.AppUtilPINVOKE:delete_FirebaseApp(HandleRef)
Firebase.FirebaseApp:RemoveReference()
Firebase.FirebaseApp:Dispose()
Firebase.FirebaseApp:Finalize()`

**Comment by jonsimantov** [comment] 2018-08-28 18:12
Which Firebase plugins are you using? (e.g. Auth, Database, Messaging, etc.)

And what is your Unity editor version? Finally, are you using .Net 3.0 or .Net 4.6? (in the player settings)

**Comment by IsnaniWidhiHidayat** [comment] 2018-09-01 19:11
iam using unity 2018.1.2f1 and firebase version 5.2.1 , .net 3.5 equivalent , service : auth, realtime database, and storage

**Comment by stewartmiles** [comment] 2018-10-24 16:49
Closing as this is a duplicate of https://github.com/firebase/quickstart-unity/issues/191

**Closed by stewartmiles** 2018-10-24 16:49 UTC
Labels: bug
