### ISSUE TITLE
[Bug] Could not find com.google.firebase:firebase-analytics-unity:8.7.0

### ISSUE THREAD

**Issue by smakarov** [firebase/quickstart-unity#1210] opened 2021-12-20 18:33 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.2.7f
  * Firebase Unity SDK version: 8.7.0
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Analytics and others (Auth, Database, etc.)
  * Other Firebase Components in use: Crashlytics, FCM, Installations, DynamicLinks, RemoteConfig (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

Trying to make Android build. Got gradle errors stack https://pastebin.com/LqepE7VK

#### Steps to reproduce:

Open project and try to build.
https://yadi.sk/d/m8ltee_ffnacFA

**Comment by paulinon** [comment] 2021-12-21 10:10
Hi @smakarov,

This issue seems similar to #1205 where the cause appears to be a regression from the Unity side. A workaround for this can be found [here](https://github.com/firebase/quickstart-unity/issues/1205#issuecomment-998233434). 

You can follow along the thread I mentioned for more updates about the issue. That said, I'll be closing this for now (duplicate of #1205).

**Closed by paulinon** 2021-12-21 10:10 UTC
Labels: type: question, api: analytics
