### ISSUE TITLE
[Bug]  iOS Push Notification data is not received on reopening of app

### ISSUE THREAD

**Issue by HarrisonShort** [firebase/quickstart-unity#1019] opened 2021-04-08 07:16 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.13f1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Cloud Messaging, 
  * Other Firebase Components in use: App (Core), Auth, Dynamic Links, Instance ID, Realtime Database, Cloud Storage, Cloud Functions
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Windows and MacOS
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Our app uses notifications in order to transfer data between users. We are finding an issue where data sent in a Firebase Notification is not received by our app when the app is opened by unlocking the device, pressing the app icon on the home screen or selecting the app from the "Multitasking" screen (double click home button/flick bottom bar upwards). This only occurs on iOS, the Android version of our app works as intended. 

The strange thing is that if you select the notification that appears on the screen and reopen the app that way, the data will actually be received and processed on the receiving device. 

Is this intended functionality? I think reopening the app not using the notification itself is quite common.

#### Steps to reproduce:

1. Open app.
2. Navigate to section of our app that is registered to receive these notifications.
2. Lock phone using device button OR go back to home screen.
3. Send notification to device - in our case, this is from a different user.
4. Navigate back to app in any way that is _not_ via the notification UI.
5. Data sent in notification will not be processed when the app reopens.

Thanks! Hope to hear back soon.

**Comment by paulinon** [comment] 2021-04-08 12:15
Hi @HarrisonShort,

Could you verify if this issue persists using the latest SDK version (7.1.0)? If so, I'd like you to confirm if [method swizzling](https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in) is not disabled in your implementation as this is required by the SDK so that its features can function properly.

Let me know how it goes.

**Comment by HarrisonShort** [comment] 2021-04-13 06:40
Hi @paulinon, thanks for your reply!

I have done the following:
1. Updated each Firebase component to 7.1.0 from Unity Package Manager.
2. Fixed some errors occurring from obsolete/removed Firebase code.
3. Fixed an issue with cocoapods not being a high enough version to build successfully from Unity.
4. Fixed an issue with linking in XCode (solution found here: https://github.com/facebook/facebook-sdk-for-unity/issues/504).
5. Verified that method swizzling is not disabled (`FirebaseAppDelegateProxyEnabled` does not appear in the Info.plist file). 
6. Followed the steps listed in the original post.

The issue persists in the updated version of Firebase - opening the app via any method that is not directly interacting with the received notification UI will not load the sent notification data.

I'm not sure how relevant it is, but I did find the `FirebaseMessagingAutoInitEnabled` flag set to 0 in the Info.plist file. Wondering if this may cause any issues?

Unsure where we go from here, but hope to hear back from you soon!

**Comment by paulinon** [comment] 2021-04-13 12:20
Hi @HarrisonShort,

It's possible that this flag may cause the issue because FCM automatic initialization is enabled by default. Could you try setting it to 1 and see if this resolves your issue?

**Comment by HarrisonShort** [comment] 2021-04-14 01:13
Hi @paulinon,

Unfortunately setting this to 1 did not solve the issue.

**Comment by paulinon** [comment] 2021-04-14 12:00
Thanks for confirming this, @HarrisonShort. In order to identify what's causing the issue, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the steps you've taken before encountering the issue?

**Comment by HarrisonShort** [comment] 2021-04-16 04:41
Hey @paulinon, I'm just in the process of creating a minimal, reproducible example of this issue. 

However, I am unsure how exactly to share this with you, as it is possible that the project could contain potentially sensitive data as I have opted to use the existing bundle ID and APNs certificate for our app. Furthermore, to build to an iOS device would require one of our Signing Certificates and I am unsure whether as a general rule of thumb these should be shared. 

I am also using our Firebase Console to send test notifications to the FCM Registration Token directly, so I'm not seeing how the project would work regardless?

For context however:
1. I have grabbed the [Firebase Messaging Quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp) project.
2. Updated it according to the readme, with our bundle ID.
3. All code in this project has remained untouched, other than adding the Firebase Messaging component.
4. Sent the device a test notification from the Firebase Console > Cloud Messaging > Compose notification page.
5. (if app is open) Notification is received.
6. (if app is minimized/phone is locked and opened by pressing notification) Notification is received.
7. (if app is minimized/phone is locked and opened by any other method) Notification is **not** received.

Apologies if I'm being slightly pedantic, I'm just hoping for some clarification as I have not ever had to provide a test project with this information in it to developers of Firebase (or any other company for that matter) in the past. Would appreciate some guidance here! 

Thanks again, hope to hear back soon.

**Comment by paulinon** [comment] 2021-04-16 14:24
Thanks for the additional information, @HarrisonShort. I was able to reproduce the behavior you're facing. With that, I've filed an internal bug report for this. I can't provide any timelines at the moment, so I'll be leaving this open for now.

**Comment by HarrisonShort** [comment] 2021-04-19 01:12
Awesome, thanks for that update and your help here @paulinon, we really appreciate it!

**Comment by chliangGoogle** [comment] 2021-05-04 20:51
@HarrisonShort So seems like you are handling some data through notification and you open the app not by notification, in that case the app is not aware of the data from notification because you need to trigger it through either open a notification or a notification happens to be in the foreground. So for your use case, it's in the nature of the system that does not support.

**Comment by DellaBitta** [comment] 2021-05-05 12:34
Hi @HarrisonShort,

Thanks for all of the info and bearing with. us. The Firebase iOS SDK. team has confirmed that this expected behavior so I'm going to close this issue for now.  If you would like to petition a feature request then I think the best avenue is [Contacting Firebase Support](https://firebase.google.com/support/troubleshooter/contact).  Thanks!

**Closed by DellaBitta** 2021-05-05 12:34 UTC
Labels: api: messaging, type: bug
