### ISSUE TITLE
Unity Editor Freeze after playing the app for ~10 seconds.

### ISSUE THREAD

**Issue by khindemit** [firebase/quickstart-unity#667] opened 2020-05-04 18:22 UTC
### Please fill in the following fields:
Unity editor version: **2019.3.12f1**
Firebase Unity SDK version: **6.14.0**
Source you installed the SDK (.unitypackage or Unity Package Manager): **Unity Package Manager**
Firebase plugins in use (Auth, Database, etc.): **Analytics, Auth, Database, Firestore, Storage**
Additional SDKs you are using (Facebook, AdMob, etc.): **Facebook**
Platform you are using the Unity editor on (Mac, Windows, or Linux): **Windows 10**
Platform you are targeting (iOS, Android, and/or desktop): **iOS, Android**
Scripting Runtime (Mono, and/or IL2CPP): **IL2CPP**

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Hi!
After importing Firestore back in February 2020 (6.12.0 version) I noticed that every time I start the app in Unity Editor (hit play button) **after first frame of running the app Unity Editor freeze for ~10 seconds.**
I tried to update our git version to the revision before importing Firestore, the Unity Editor freeze disappeared.
Today I completely removed 6.12.0 version and installed 6.14.0 version from Unity Package Manager. The freeze at app startup in Unity Editor is still there.
It happens only on Windows machines. I tried to profile Unity Editor (profile the editor, not the player).
Here is a screenshot:

![Snapshot 2020-05-04 20 13 06](https://user-images.githubusercontent.com/5675979/80999056-500a6400-8e44-11ea-880a-5d41cafc8aaa.png)

**It seems that in GenerateXmlFromGoogleServicesJson.RunResourceGenerator() method the PythonExecutor.Run() is called and it takes ~8 seconds.**

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Have not tried.
What's the issue repro rate? (eg 100%, 1/5 etc)
0

**Comment by igor84** [comment] 2020-05-05 17:04
I can confirm this is also happening with Firebase 6.12.0 on the same version of Unity and same environment as above.

**Comment by tutipeti** [comment] 2020-05-13 15:20
I see the same using 6.14.0 and on a mac.

**Comment by WileyCorning** [comment] 2020-05-15 18:11
I'm having the same issue. Windows PC, Firebase SDK version 6.12, installed via the `.unitypackage` download in Unity 2019.3.11f1.

My profiler looks the same as @khindemit's, with a ~6s freeze while waiting for PythonExecutor.Run on the main thread. This happens every time I enter play mode in the editor.

I will also note that this freeze seems to prevent the Windows Mixed Reality plugin from initializing correctly.

**Comment by mikeypdev** [comment] 2020-05-16 21:17
Same freeze issue on macOS, Unity 2019.3.5f1, SDK 6.14 installed from UPM (migrated from earlier .unitypackage installs). In my case, the issue is caused by EDM, not by the python generator script. The workaround with deleting the EDM Editor folder works, along with the noted side-effects.

I found a more reliable workaround using the new "Enter Play Mode Settings" option introduced in Unity 2019.3. [https://blogs.unity3d.com/2019/11/05/enter-play-mode-faster-in-unity-2019-3/](https://blogs.unity3d.com/2019/11/05/enter-play-mode-faster-in-unity-2019-3/)

In the Edit menu, Player Settings, Editor section, I enabled "Enter Play Mode Options (Experimental)". For my project, I disabled the "Reload Domain" option, and enabled the "Reload Scene" option.

![Screenshot_5_16_20__2_13_PM](https://user-images.githubusercontent.com/26722177/82130341-64712980-977f-11ea-8b0f-d15091d2bee1.png)

Play mode starts within a second or so for me now. Note that this feature could introduce other bugs, depending on your project. I seem to have good luck so far.

**Comment by igor84** [comment] 2020-05-17 12:27
@mikeypdev if the issue is that long running code is executed by [InitializeOnLoad] attribute like with the Python script, then this code will be run after every compile, extending compile time as well as entering play mode time. By disabling Reload Domain you mitigate the problem when entering the play mode but you still get longer "compile" time because of it.

**Comment by mikeypdev** [comment] 2020-05-17 17:32
@igor84 Thanks, makes sense. And my apologies, I intended to post this workaround on another issue (#639) about slow Play Mode start times. I'll tidy that up now.

**Comment by chkuang-g** [comment] 2020-05-28 19:23
Hi folk,

Please watch #639 instead of this one.  There are several improvement under development and will update #639 soon.

Thank you for reporting the issue.

**Comment by chkuang-g** [comment] 2020-05-28 19:24
Duplicate of #639

**Closed** 2020-05-28 19:45 UTC
Labels: duplicate
