### ISSUE TITLE
[7.0.1] Firebase can not read GoogleService-Info.plist when the project has Facebook SDK 8.1.1

### ISSUE THREAD

**Issue by pixeption** [firebase/quickstart-unity#902] opened 2020-12-18 14:52 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.16f1
  * Firebase Unity SDK version: 7.0.1
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firebase Core
  * Other Firebase Components in use: Analytics, Crashlytics, Messaging, RemoteConfig, InstanceID
  * Additional SDKs you are using: Facebook v8.1.1 , AdMob v5.4.0
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
  * Build Unity project to Xcode project
  * Build Xcode project and run on device
  * Exception throws with this log
```
2020-12-18 20:46:51.329535+0700 freecell[10904:664933] ERROR: Failed to read Firebase options from the app's resources (). Either make sure GoogleService-Info.plist is included in your build or specify options explicitly.
2020-12-18 20:46:51.329942+0700 freecell[10904:664933] ERROR: Failed to read Firebase options from the app's resources (). Either make sure GoogleService-Info.plist is included in your build or specify options explicitly.
2020-12-18 20:46:51.330083+0700 freecell[10904:664933] ERROR: App ID, API key, and Project ID must be specified in App options.
2020-12-18 20:46:51.332682+0700 freecell[10904:664818] 7.0.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
2020-12-18 20:46:51.334279+0700 freecell[10904:664818] 7.0.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure]; (FirebaseApp.configure() in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
Failed to read Firebase options from the app's resources (). Either make sure GoogleService-Info.plist is included in your build or specify options explicitly.
Firebase.AppUtil:PollCallbacks()
Firebase.Platform.FirebaseHandler:Update()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Failed to read Firebase options from the app's resources (). Either make sure GoogleService-Info.plist is included in your build or specify options explicitly.
Firebase.AppUtil:PollCallbacks()
Firebase.Platform.FirebaseHandler:Update()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

App ID, API key, and Project ID must be specified in App options.
Firebase.AppUtil:PollCallbacks()
Firebase.Platform.FirebaseHandler:Update()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

#### Steps to reproduce:

**Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?**
Yes, I can reproduce with analytics testing app. Just add Facebook SDK v8.1.1 and build. Make sure you added additional Firebase SDKs (just to be sure)

**What's the issue repro rate? (eg 100%, 1/5 etc)**
100%

**What happened? How can we make the problem occur?**
One thing I noticed is the pod file structures are different.

**Firebase only**
```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '7.0.0'
  pod 'Firebase/Core', '7.0.0'
  pod 'Firebase/Crashlytics', '7.0.0'
  pod 'Firebase/DynamicLinks', '7.0.0'
  pod 'Firebase/Messaging', '7.0.0'
  pod 'Firebase/RemoteConfig', '7.0.0'
  pod 'FirebaseInstanceID', '7.0.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.68'
end
```

**Firebase + Facebook**
```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'FBSDKCoreKit', '~> 8.0'
  pod 'FBSDKGamingServicesKit', '~> 8.0'
  pod 'FBSDKLoginKit', '~> 8.0'
  pod 'FBSDKShareKit', '~> 8.0'
  pod 'Firebase/Analytics', '7.0.0'
  pod 'Firebase/Core', '7.0.0'
  pod 'Firebase/Crashlytics', '7.0.0'
  pod 'Firebase/DynamicLinks', '7.0.0'
  pod 'Firebase/Messaging', '7.0.0'
  pod 'Firebase/RemoteConfig', '7.0.0'
  pod 'FirebaseInstanceID', '7.0.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.68'
end
target 'Unity-iPhone' do
end
use_frameworks!
```

**Workaround**
Select GoogleService-Info.plist, tick to Unity-iPhone target should fix the issue temporarily.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/10240918/102628195-e4c79500-417b-11eb-9d35-f4557a948615.png">

**Comment by andreyfaraponov** [comment] 2020-12-18 20:10
The same problem, I have a project with Firebase Analytics, Crashlytics, Facebook.

Unity editor version: 2019.3.8f1
Firebase Unity SDK version: 7.0.1
Source you installed the SDK: unitypackege
Problematic Firebase Component: Firebase Core
Other Firebase Components in use: Analytics, Crashlytics
Additional SDKs you are using: Facebook v8.1.1 , IronSource
Platform you are using the Unity editor on: Mac
Platform you are targeting: iOS
Scripting Runtime: IL2CPP

**Comment by pelevinma** [comment] 2020-12-19 11:09
same problem

**Comment by novavision** [comment] 2020-12-20 07:56
same here,
Using IronSource, AdMob, Facebook SDKs

**Comment by a314266177** [comment] 2020-12-21 09:08
same problem

**Comment by DellaBitta** [comment] 2020-12-21 16:41
Hi all,

This seems to be a duplicate of issue #862 in which we're tracking failures when !useFrameworks is defined in the podfile.  I'm going to close this issue as duplicate and link this issue to that one for further support. 

If you feel I've closed this issue in error the please @ me and I'll re-open it!  Thanks.

**Comment by DellaBitta** [comment] 2020-12-21 16:41
Duplicate of #862

**Closed** 2020-12-21 16:42 UTC
Labels: duplicate, edm4u
