### ISSUE TITLE
Folks we fixed issues with this as best in 6.9.0 (latest rev is 6.10.0) as we can at the moment by adding python 3 support, changing pyinstaller and adding a fallback to launch the .py script if the .exe is causing issues.

### ISSUE THREAD

**Issue by Nicokkam** [firebase/quickstart-unity#893] opened 2020-12-11 00:25 UTC
Folks we fixed issues with this as best in 6.9.0 (latest rev is 6.10.0) as we can at the moment by adding python 3 support, changing pyinstaller and adding a fallback to launch the .py script if the .exe is causing issues.

Could folks give this a try and if there are issues we can reopen the bug?

_Originally posted by @stewartmiles in https://github.com/firebase/quickstart-unity/issues/540#issuecomment-584838115_

[REQUIRED] Please fill in the following fields:

Unity editor version: _____2020.1.0f1
Firebase Unity SDK version: _____ latest .unitypackage (don't know where to see the version)
Source you installed the SDK: _____ latest .unitypackage (don't know where to see the version)
Problematic Firebase Component: _____ Android Resource File Database URL
Other Firebase Components in use: _____ Auth and Analytics
Additional SDKs you are using: _____ None
Platform you are using the Unity editor on: _____ Mac
Platform you are targeting: _____ iOS and Android
Scripting Runtime: _____ .NET 4x deactivates changing scripting runtime
[REQUIRED] Please describe the issue here:

Got the following error:

Generation of the Firebase Android resource file google-services.xml from Assets/Firebase/GoogleService-Info.plist failed.
If you have not included a valid Firebase Android resources in your app it will fail to initialize.

Could not find key in plist file: [DATABASE_URL]

Followed every step of the link bellow and it didn't work! Maybe It's because I own a Mac. I'm desperate for help!!
#540

UnityEngine.Debug:LogError(Object)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:RunResourceGenerator(IEnumerable`1, String, Boolean) (at Z:/tmp/tmp.DPw5MV1I7c/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:542)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:ReadBundleIds(String) (at Z:/tmp/tmp.DPw5MV1I7c/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:407)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:UpdateConfigFileDirectory() (at Z:/tmp/tmp.DPw5MV1I7c/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:295)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:CheckConfiguration() (at Z:/tmp/tmp.DPw5MV1I7c/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:246)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:m__1() (at Z:/tmp/tmp.DPw5MV1I7c/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:103)
Google.c__AnonStorey0:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:332)

**Comment by DellaBitta** [comment] 2020-12-11 14:24
Marking this as a duplicate of #892.  Please let me know if that's not the case!  Thanks.

**Closed** 2020-12-11 14:24 UTC
Labels: api: database, duplicate
