### ISSUE TITLE
[Bug] iOS stopped tracking custom events, only the standard events are showing

### ISSUE THREAD

**Issue by nvdg** [firebase/quickstart-unity#1206] opened 2021-12-15 09:13 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.20f1
  * Firebase Unity SDK version: 8.6.2
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: Remote Config, Messaging
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

My custom events on iOS used to work up until October 21. From that date, I have not received any custom events.
I do receive the standard events (screen_view, user_engagement, session_start)

I did an app update around that time but I double-checked the change list and the update only contained new content, nothing Firebase or SDK-related changed. Also, it's weird that all events drop so instantly from one day to the other, an update roll-out always takes a while.

When it started I still used Firebase SDK 7.1.0 but by now I updated to 8.6.2 but I still don't receive any custom events.
(At least not visible in any dashboard)

**Comment by paulinon** [comment] 2021-12-15 17:48
Hi @nvdg,

Thanks for reporting this. In order to identify what's causing this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the [debug logs](https://firebase.google.com/docs/analytics/get-started?platform=ios#start_logging_events) you're getting after triggering custom events?

**Comment by nvdg** [comment] 2021-12-15 18:25
Sorry, I found that there actually already was a thread for this issue: https://github.com/firebase/quickstart-unity/issues/1099

If you want you can close this one and re-open the other. It looks like no one posted a solution there yet.

As for the steps to reproduce, it should just be adding the firebase to unity and making an ios build.
I'm not able to look a logs because it's on iOS and I don't own a mac myself. The builds are made on a build server.

**Comment by tienhagioi** [comment] 2021-12-16 09:18
> Sorry, I found that there actually already was a thread for this issue: #1099

That thread locked , have you solved it ?

**Comment by paulinon** [comment] 2021-12-16 14:05
Hi @nvdg,

We can continue our thread here since the thread you mentioned is locked. With that, it would be helpful if you could provide the logs so that we can analyze if the issue is caused by the backend or the SDK. 

If you're unable to provide a minimal, reproducible example, could you verify if custom events aren't being tracked from the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp)?

**Comment by nvdg** [comment] 2021-12-16 14:40
@paulinon 

Here are the log files:
[log.txt](https://github.com/firebase/quickstart-unity/files/7728171/log.txt)

Sorry, but running a new project from the quickstart would take me way too much time. Especially since I have to setup and build from a build server.

**Comment by paulinon** [comment] 2021-12-17 13:07
Thanks for that, @nvdg. I was able to reproduce the issue as well using the quickstart, but this appears to be related to the backend rather than the SDK. You may contact [Firebase Support](https://firebase.google.com/support) where one of our agents will get in touch with you. That being said, I'll be closing this for now.

**Closed by paulinon** 2021-12-17 13:07 UTC
Labels: type: question, needs-attention, api: analytics
