### ISSUE TITLE
im using firebase with unity to do my login screen everything works fine but when i build it to android it just doesnt work i tried putting a debug panel to give me the errors in android but i got nothing it works perfectly fine in the unity editor[Bug] my unity version is 2020.3.1f1 and my firebase unity sdk version 7.1.0 i used the unity package manager to install this version the problematic component is the firebase login in general im not using any other sdk with this project and im exporting to android/windows both dont work unless i do it in the unity editor i think im using Mono for my scripts

### ISSUE THREAD

**Issue by XdKoro** [firebase/quickstart-unity#1016] opened 2021-04-03 19:23 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment] 2021-04-05 15:56
Hi @XdKoro,

I see that you've filed #1015 as well, and it talks about an issue similar to this one. With that, I'll be closing this ticket as a duplicate of it so that our discussion can be tracked in the original ticket you filed.

Thanks!

**Comment by paulinon** [comment] 2021-04-05 15:56
Duplicate of #1015

**Closed by paulinon** 2021-04-05 15:56 UTC
Labels: api: database, type: question
