### ISSUE TITLE
Firebase Messaging Android: Adaptive icons cannot be used in notifications error message

### ISSUE THREAD

**Issue by dioniguerra** [firebase/quickstart-unity#1036] opened 2021-04-27 08:45 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.13f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Firebase Messaging
  * Other Firebase Components in use: none
  * Additional SDKs you are using: none
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

Hi guys, I have integrated latest FirebaseMessaging.unitypackage to our Unity project, and when testing a Message via the Firebase Console, the Push Notification arrives (phone vibrates), badge is displayed, but the message does not appear. Looking at the logs, I do see this error message:

2021-04-27 09:40:34.105 11580-11617/? W/FirebaseMessaging: Notification Channel set in AndroidManifest.xml has not been created by the app. Default value will be used.
2021-04-27 09:40:34.130 11580-11617/? E/FirebaseMessaging: Adaptive icons cannot be used in notifications. Ignoring icon id: 2131361792
2021-04-27 09:40:34.132 11580-11617/? E/FirebaseMessaging: Adaptive icons cannot be used in notifications. Ignoring icon id: 2131361792 

Checking my notifications on device, I can see the notification in the but with the default android icon. 

Any thoughts?

Dioni

**Comment by dioniguerra** [comment] 2021-04-28 14:34
Hi @paulinon yes, I can confirm that this is 100% repro using the quickstart firebasemessaging sample. The error I get on the console is:

2021-04-28 15:34:41.188 5755-5798/? E/FirebaseMessaging: Adaptive icons cannot be used in notifications. Ignoring icon id: 2131230720

Could it be because the way we set up icons in Unity 2019?

**Comment by paulinon** [comment] 2021-04-28 16:01
Hi @dioniguerra,

It's possible that an old Unity version could be causing this to happen, so let's try to rule this out. Could you try updating your Unity editor to an updated version and see if the issue persists? If so, it would be great if you list the complete steps you've taken before facing this issue so that I can identify the cause of this.

**Comment by dioniguerra** [comment] 2021-05-05 07:16
My apologies, is been pretty hectic here, but I will get to it later today. Please stand by.

**Comment by dioniguerra** [comment] 2021-05-05 14:19
Hi @paulinon I have updated to Unity 2020.3.5f1 LTS, and ran the quickstart firebasemessaging project and got same result. My steps were:

* Clone the project: 
* Open in Unity 2020.3.5f1
* Set API Compatibility to .NET 4x and import the dotnet4/FirebaseMessaging.unitypackage into the project. 
* Add a 1024x1024 PNG to my default Icon in ProjectSettings/Player. 
* Build and Run. 
* Using the Firebase Console Send a Test Messaging using the Received Registration Token from the app. 
* Have the app in the background, the notification arrives, device vibrates, badge is displayed in app icon, but Notification is not shown. 

The error shown is: 
E/FirebaseMessaging: Adaptive icons cannot be used in notifications. Ignoring icon id: 2131230720

Thanks
Dioni

**Comment by DellaBitta** [comment] 2021-05-05 14:56
Hi @dioniguerra,

The Firebase Android SDK detects and prevents the use of icons dervied from the [AdaptiveIconDrawable](https://developer.android.com/reference/android/graphics/drawable/AdaptiveIconDrawable) class.  If you believe that the Icon isn't dervied from this class, or if you need more support debugging the issue as to why it might be, I recommend reaching out to the Firebase Android SDK experts directly via their [Github Quickstart Issue Forum](https://github.com/firebase/quickstart-android/issues), or by [Contacting Firebase Support](https://firebase.google.com/support/troubleshooter/contact) which will allow support engineers to help debug your current App configuration.  

I'm going to close this issue for now, but feel free to re-open it if you feel I've closed it in error.  Thank you!

**Closed by DellaBitta** 2021-05-05 14:56 UTC
Labels: api: messaging, needs-attention, type: question
