### ISSUE TITLE
Firebase SDK doesn't support Windows x86 builds, mention in docs

### ISSUE THREAD

**Issue by DenizPiri** [firebase/quickstart-unity#183] opened 2018-07-11 14:27 UTC
I couldn't find this mentioned in docs anywhere. X86 builds fine, however when running the app, you get 1 error log per frame, complaining about the missing Firebase dll file. I understand the reasons for not supporting X86 builds.

It would be great if this was mentioned in docs and on top of that somehow detected in runtime and generate 1 error message instead of 1 error message per frame.

**Comment by stewartmiles** [comment] 2018-07-11 15:24
Hi @DenizPiri yep this is something we need to support, need to get 32-bit DLLs out of our build system to support Windows x86 and OSX 32-bit apps (e.g Unity 4).  It's on the list.  Closing this out as it's a duplicate of #89

**Closed by stewartmiles** 2018-07-11 15:24 UTC
