### ISSUE TITLE
Crashlytics reports come in, but are not shown in FB Dashboard

### ISSUE THREAD

**Issue by habitoti** [firebase/quickstart-unity#824] opened 2020-10-15 07:51 UTC
### [REQUIRED] Please fill in the following fields:

 * Unity editor version: 2019.4.12f1 (LTS)
 * Firebase Unity SDK version: 6.16.0
 * Source you installed the SDK: Unity Package Manager
 * Problematic Firebase Component: DB
 * Other Firebase Components in use: Auth, Crashlytics, Analytics
 * Additional SDKs you are using: none
 * Platform you are using the Unity editor on: Mac
 * Platform you are targeting: iOS
 * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I deployed a mobile app to iOS and Android user base. On both platforms a few issues are reported in the FB dashboard/console, but only iOS actually shows according data. For Android, the dashboard still just shows the "Welcome" initial screen saying it's waiting for the first reports to come in. I've waited more than 48h now, but still no data. I don't see anything I could have missed on Android. Any advice what could be missing for Android?
(Screenshots in German, sorry. But you should know those patterns... ;-) )

Android
![image](https://user-images.githubusercontent.com/220421/96092659-75a79900-0ecb-11eb-818d-a805b6ee26a7.png)

![image](https://user-images.githubusercontent.com/220421/96092450-2eb9a380-0ecb-11eb-8223-eb1e4a6e739a.png)

iOS
![image](https://user-images.githubusercontent.com/220421/96092549-53ae1680-0ecb-11eb-9891-a9e590b27a53.png)

#### Steps to reproduce:

n/a

#### Relevant Code:

Code is the same for both platforms, so as it works for iOS (and also Android reports incoming issues) it should not be related to coding.

**Comment by habitoti** [comment] 2020-10-16 07:05
So as of today, 24h later, the Dashboard made up its mind and is now not showing any more issues for Android (which would then now be consistent with the Crashlytics entry screen and also with the Playstore console, which doesn't show any crashes). 
Is there any indication at what point in time certain data is reliable? Especially when it comes to crash reporting I think it would be important to alway have the right data (per platform and per app version).

**Comment by kairi81** [comment] 2020-10-16 10:41
I also recently changed from Firebase Unity SDK 6.14.0 to 6.16.0
I'm having a similar problem.

Looking at my android log

I'm getting the error "FirebaseCrashlytics: Failed to retrieve settings from ..."

In FirebaseApp.CheckAndFixDependenciesAsync() function
"Disable module'crashlytics' for'Firebase.Crashlytics.FirebaseCrashlytics, Firebase.Crashlytics' "
This log is showing up.

[Android_Fabric_6_16_0.txt](https://github.com/firebase/quickstart-unity/files/5390919/Android_Fabric_6_16_0.txt)

**Comment by kairi81** [comment] 2020-10-19 05:15
Even though I haven't edited any further
Android DashBoard, which was not available all week, has been activated today.

I no longer see the "FirebaseCrashlytics: Failed to retrieve settings from ..." message on the same build from which I extracted the logs last time.
However, if you directly access the file path in the message, the json format is displayed as "{}" the same as the last time.

"Disable module'crashlytics' for'Firebase.Crashlytics.FirebaseCrashlytics, Firebase.Crashlytics' "
The message is still being printed.

Test Exception is received successfully.

**Comment by mrichards** [comment] 2020-10-19 21:07
@habitoti We discovered a backend issue late last week that was preventing new Unity Android apps from getting registered properly in our system, which is why you saw the green screen with the spinner even after causing a crash as instructed. That issue was resolved late Friday, so you can finish onboarding your Android app by sending a crash. Please let us know if you are still experiencing the issue.

@kairi81 it appears you may have had the same issue? Based on your most recent message it seems the problem is resolved, correct?

**Comment by kairi81** [comment] 2020-10-20 09:57
@mrichards 

Crashlytics Dashboard has been activated.
Reporting is also being confirmed normally.

But "Disable module'crashlytics' for'Firebase.Crashlytics.FirebaseCrashlytics, Firebase.Crashlytics"
The log is still being printed.

Is there any problem even if this log is printed?

**Comment by chkuang-g** [comment] 2020-10-20 18:59
Hi @kairi81 

In short, this message is harmless, but this message is incorrectly generated.

A longer explanation: When `CheckAndFixDependenciesAsync()` is called, it would try to "initialize" each module, like database or analytics, and try to prepare the requirements of the module. It is actually mostly doing nothing with some exceptions:
- Analytics will try to initialize itself so that it can be used in anytime.
   https://github.com/firebase/firebase-cpp-sdk/blob/1d13237b37dcecdc3a48ccd882337e03d4ac5bf0/analytics/src/analytics_common.cc#L33
- Some modules, like Database and Storage, would try to make sure Play Services is available on the device.
   https://github.com/firebase/firebase-cpp-sdk/blob/1d13237b37dcecdc3a48ccd882337e03d4ac5bf0/database/src/common/database.cc#L46

Crashlytics is actually doing absolutely nothing right now.  (Unfortunately that part of the code is not public yet so that I cannot show it to you.

`CheckAndFixDependenciesAsync()` try to initialize module based on checking if the C# class exist.  In this case, it checked `Firebase.Crashlytics.FirebaseCrashlytics`.  However, this class actually does not exist because the correct class name is `Firebase.Crashlytics.Crashlytics`.  Therefore you saw this message.

This seems to be a minor issue and will not affect the functionality of Crashlytics.

**Comment by swap-mpl** [comment] 2020-10-21 05:07
Hi @mrichards 

I tried the lastest version of Firebase Unity SDK(6.16.1). Firebase initialises but we dont see any error logs in the firebase console. Attached are my logs for the app run.
[Crashlytics-log.txt](https://github.com/firebase/quickstart-unity/files/5413375/Crashlytics-log.txt)

<img width="1445" alt="Screenshot 2020-10-21 at 10 34 14 AM" src="https://user-images.githubusercontent.com/73164247/96675679-10e7b500-1389-11eb-9015-c34d994390c7.png">

We are stuck at this problem since past two days. Help would be much appreciated.

**Comment by laminhtruong** [comment] 2020-10-21 11:04
Same here, with newest SDK 6.16.1 and Unity 2019.4.12.
[log.txt](https://github.com/firebase/quickstart-unity/files/5415394/log.txt)

**Comment by laminhtruong** [comment] 2020-10-23 07:36
Install the unity package download will resolve this problem. That issue only occurs if we use the package manager from Unity

**Comment by paradizIscool** [comment] 2021-02-10 16:23
Same issue and we use Package Manager, can you reopen this bug?

6.16.1 (other issues with 7.xx)

**Comment by mrichards** [comment] 2021-07-20 20:35
Hi folks, I'm cleaning up old tickets and I am fairly sure this issue was due to the the version of OkHttp used by Crashlytics being incompatible with an OkHttp dependency pulled in by the app or another SDK. Crashlytics recently removed the dependency on OkHttp entirely, so the issue should be resolved for customers on the latest version of the Firebase Unity plugin.

I'm going to close this issue; please reopen if the problem persists with the latest version.

**Closed by mrichards** 2021-07-20 20:35 UTC
Labels: api: crashlytics, type: bug
