### ISSUE TITLE
Did Firebase Supports ios10 version for Signing up with Apple Option

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/quickstart-unity#1224] opened 2022-01-25 11:01 UTC
Hi All 

  In my project i have  to enable Signing up with Apple option.  I have enabled Apple Developer program and try to start integrate with Firebase. I have doubt . While reading    i found that Signing up with Apple option  supports only ios 12 or greater. 
My ipads are only  have ios 10 version only. My project also supports from ios 10 only.

I have  downloaded this project. 

https://github.com/lupidan/apple-signin-unity

But It says metal api is not supported in your ipad.  So you cant install it . 

Did metal api is needed for  Signing Up with Apple option?

Is it possible to enable Signing Up with Apple option in firebase using ios 10???

**Comment by paulinon** [comment] 2022-01-25 14:24
Hi @CLOUDFIRE91,

Based on the repository you provided, you have to mark the `AuthenticationServices.framework` library as `Optional` after importing it for iOS 12 and earlier as these iOS versions cannot directly access Sign in with Apple JS framework.

Unfortunately, Metal API is beyond my scope of expertise, but I'm guessing this is caused by your configuration or device specifications.

I'll be closing this for now. Let me know if you're facing any issues with the SDK. You may get in touch with [Firebase Support](https://firebase.google.com/support) if you're facing issues related to the backend.

**Closed by paulinon** 2022-01-25 14:24 UTC
Labels: type: question, api: auth

**Comment by CLOUDFIRE91** [comment] 2022-01-27 10:56
@paulinon   I have enabled AuthenticationServices.Framwork in 10.2 .. But my app was not opened... It opens and close.
I did n't use metal api..

DId Sign in with Apple JS   is possible in unity 2019.4.30 with Firebase Support????

How can i do it. Did firebase Supports 10.2 version for signing with  Apple...

or i have to shift for ios  12  greater versions????

Did unity 2019.4.30 supports Apple JS... ?
