### ISSUE TITLE
App initializer installations not found, failed to enable.

### ISSUE THREAD

**Issue by WikyWu** [firebase/quickstart-unity#1244] opened 2022-03-18 09:26 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.27f1
  * Firebase Unity SDK version: 8.8.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: installations
  * Other Firebase Components in use: Analytics、Messaging、Crashlytics、RemoteConfig
  * Additional SDKs you are using:  No Others
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

Hello!  Firebase components in use run correct, but when i use the installations, firebsae log print "Enable module 'installations' for 'Firebase.Installations.FirebaseInstallations, Firebase.Installations'" and "App initializer installations not found, failed to enable",  thanks for your reply.

**Comment by WikyWu** [comment] 2022-03-21 02:08
> In order to identify the cause of this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) along with the complete steps to replicate the issue?

Hi@paulinon,  in order to replicate the issue, i  just create a empty unity project and import the installations.unitypackage, could i need to call some initiate method?

**Comment by paulinon** [comment] 2022-03-21 12:58
Thanks for the additional information, @WikyWu. Did you remember to [add the `google-services.json` file](https://firebase.google.com/docs/unity/setup#add-config-file) for your app in your Unity project? It's possible that this is the cause of your issue. After performing this step on my end, the initialization became successful.

**Comment by WikyWu** [comment] 2022-03-22 01:38
> Thanks for the additional information, @WikyWu. Did you remember to [add the `google-services.json` file](https://firebase.google.com/docs/unity/setup#add-config-file) for your app in your Unity project? It's possible that this is the cause of your issue. After performing this step on my end, the initialization became successful

**Comment by WikyWu** [comment] 2022-03-22 02:04
> Thanks for the additional information, @WikyWu. Did you remember to [add the `google-services.json` file](https://firebase.google.com/docs/unity/setup#add-config-file) for your app in your Unity project? It's possible that this is the cause of your issue. After performing this step on my end, the initialization became successful.

Thanks for your attention. The json file i have put in the unity project, also i have added the SHA1 certificate fingerprint, unfortunately, the same log has printed.

**Comment by paulinon** [comment] 2022-03-22 08:53
HI @WikyWu,

To be more specific, I was able to encounter logs saying that initialization was unsuccessful, but after a few seconds, new logs appeared saying that initialization was successful. Are you facing this similar behavior?

**Comment by WikyWu** [comment] 2022-03-23 02:13
@paulinon, i print the all logs in the log.txt, hope it can be used. Thanks!
[log.txt](https://github.com/firebase/quickstart-unity/files/8329064/log.txt)

**Comment by paulinon** [comment] 2022-03-23 17:45
Thanks for the additional information, @WikyWu. It's possible that one or more of your libraries were disabled or deleted from your project. Could you verify if your `FirebaseCppInstallations.dll` is present and has both Editor and Standalone selected? Additionally, are these logs the output of just having the Installations package in an empty Unity project?

**Comment by WikyWu** [comment] 2022-03-24 07:19
> Thanks for the additional information, @WikyWu. It's possible that one or more of your libraries were disabled or deleted from your project. Could you verify if your `FirebaseCppInstallations.dll` is present and has both Editor and Standalone selected? Additionally, are these logs the output of just having the Installations package in an empty Unity project?

Hi @paulinon, i just import the installations package in an empty unity project, both Editor and Standalone selected. . Thank you very much！
![1648106304947](https://user-images.githubusercontent.com/92432345/159862994-52d4665a-b8df-4370-992f-2367aa971175.jpg)

**Comment by paulinon** [comment] 2022-03-24 13:55
Hi @WikyWu,

Could you try if updating the Unity editor makes a difference (latest LTS Release is version 2020.3.32f1)? If it doesn't, please share the steps you've taken in retrieving your logs.

**Comment by WikyWu** [comment] 2022-03-25 02:31
> please share the steps you've taken in retrieving your logs.

Hi @paulinon, i use the 2019.4.27.f1 LTS Release Unity editor to program, updating will cause much problem. The steps i have taken:
1. Get the json file and put in unity asssets
2. Import the Installations.unitypackage
3. Android -> force resolve -> resolution succeed
4. Call method FirebaseApp.LogLevel = LogLevel.Verbose and FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith
5. Run the unity project will get the logs
6. Import android project- > tag:firebase -> also get the logs

**Comment by paulinon** [comment] 2022-03-25 15:21
Thanks for the additional context, @WikyWu. I was able to replicate the issue you're facing using the steps you've listed. I'll let the team know about this, and you may refer to this thread for updates. For now, I'll be marking this as a bug.

**Comment by WikyWu** [comment] 2022-03-28 10:18
> Thanks for the additional context, @WikyWu. I was able to replicate the issue you're facing using the steps you've listed. I'll let the team know about this, and you may refer to this thread for updates. For now, I'll be marking this as a bug.

Thank you very much @paulinon , looking forward to your reply！

**Comment by cynthiajoan** [comment] 2022-03-28 18:09
Hi @WikyWu, I'd like to check is there any functional affect to your app besides the log info?

**Comment by WikyWu** [comment] 2022-03-29 02:58
> I'd like to check is there any functional affect to your app besides the log info?

Hello @cynthiajoan , i can't get the installations token with the follow method:

public class Sample : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        // Initialize Firebase
        FirebaseApp.LogLevel = LogLevel.Verbose;
        FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
            var dependencyStatus = task.Result;
            if (dependencyStatus == DependencyStatus.Available)
            {
                // Create and hold a reference to your FirebaseApp,
                // where app is a Firebase.FirebaseApp property of your application class.
                FirebaseApp app = FirebaseApp.DefaultInstance;
                Debug.Log("this ensures that Firebase is initialized");
                // Set a flag here for indicating that your project is ready to use Firebase.
                FirebaseInstallations.DefaultInstance.GetTokenAsync(true).ContinueWith(
                    task1 =>
                    {
                        if(task1.IsCompleted){
                            Debug.Log($"The token is {task1.Result}");
                        }     
                    });
            }
            else
            {
                Debug.LogError(String.Format("Could not resolve all Firebase dependencies: {0}",dependencyStatus));
                // Firebase Unity SDK is not safe to use here.
            }
        });
    }
}

The Log print

**Comment by WikyWu** [comment] 2022-03-29 03:19
Hello@cynthiajoan @paulinon, i just create an new firebase project and replace the json file and package name, surprised me that the project gets succeed result and i can get the installations token,  but the log "App initializer installations not found, failed to enable" also printed, i am confused and don't know why.

**Comment by WikyWu** [comment] 2022-03-29 03:35
Thank you very much! @cynthiajoan @paulinon

**Closed** 2022-03-31 01:49 UTC
Labels: type: bug, needs-attention, api: core
