### ISSUE TITLE
ANR's in Google Play Developer Console related to com.google.firebase.cpp.RegistrationIntentService

### ISSUE THREAD

**Issue by Vesterix** [firebase/quickstart-unity#939] opened 2021-01-22 10:27 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.29f1
  * Firebase Unity SDK version: 7.0.0
  * Source you installed the SDK: Unity Package Manager)
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use: Crashlytics, Dynamic Links, Remote Config
  * Additional SDKs you are using: Facebook, AdMob, IronSource, Applovin SDK, Helpshift, OneSignal
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime:  IL2CPP

### [REQUIRED] Please describe the issue here:

Google Play Developer Console has a lot of ANRs. Most of them happened on Android v7, but not all. 

#### Steps to reproduce:
Unfortunately I don't know exactly how to reproduce it. It's not reproducing on test devices only in users
![завантаження](https://user-images.githubusercontent.com/77834247/105478956-8f1b6680-5cac-11eb-831c-ab4302b2ee2d.png)

![завантаження (1)](https://user-images.githubusercontent.com/77834247/105479040-a78b8100-5cac-11eb-8ce8-0befeadbee0f.png)
![Screenshot_5](https://user-images.githubusercontent.com/77834247/105479246-ea4d5900-5cac-11eb-98f3-e2a6c461170f.png)

**Comment by DellaBitta** [comment] 2021-01-26 16:50
Hi @Vesterix,

We haven't had any other issues reported with the RegistrationIntentService but there was a known issue last week with Cloud Messaging not working properly on Androd due to a backend configuration problem. That issue has now since been resolved. 

I'm not sure if your issue is related but could ou check if issues continue to to occur for your users?   Thanks!

**Comment by Vesterix** [comment] 2021-02-02 13:23
We still continue to receive reports about crashes
![image](https://user-images.githubusercontent.com/77834247/106605927-219fed80-656a-11eb-8bbd-624b1e94029c.png)
![image](https://user-images.githubusercontent.com/77834247/106606106-675cb600-656a-11eb-81dc-5ce1ef5e48fa.png)
![image](https://user-images.githubusercontent.com/77834247/106606164-780d2c00-656a-11eb-8509-09ce53fafd89.png)

**Comment by chkuang-g** [comment] 2021-03-04 04:34
@Vesterix 

Did some digging and here is my understanding for your situation.

Seems like you have ANR for both [RegistrationIntentService](https://github.com/firebase/firebase-cpp-sdk/blob/main/messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java) and `MessagingUnityPlayerActivity`, which is another class delivered in Unity SDK.

The ANR for `MessagingUnityPlayerActivity` might be related to #543 and #877. We were using `IntentService` instead of `JobIntentService` for [MessageForwardingService](https://github.com/firebase/firebase-cpp-sdk/blob/main/messaging/src/android/java/com/google/firebase/messaging/MessageForwardingService.java) which is causing some issue with Android O (API level 26+).  See [this](https://www.google.com/url?q=https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten&sa=D&usg=AFQjCNGiwiLVHML6Ltxh41bf-4yhTwiE9g). 
And unfortunately `MessagingUnityPlayerActivity` is using `MessageForwardingService`. We have implemented a patch, and another patch for the regression.  Both should be included in the latest Firebase `7.1.0`.

The ANR for [RegistrationIntentService](https://github.com/firebase/firebase-cpp-sdk/blob/main/messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java) seems very similar to the problem `MessageForwardingService`, and we should upgrade it to `JobIntentService` as well.

However, your crashes seems to occur only on Android M and N (API 23, 24, 25), which is coincidentally right before Android O.  Seems slightly different behavior but I think they are related.

Is there any chance that you can get the stacktrace of either ANR?

Also, this seems to be an legit issue.  I will mark it as a bug for now.

**Comment by Vesterix** [comment] 2021-03-05 10:44
Thanks for your reply. Yes we don't configure a custom entry point Activity. Also we have upgraded version to 7.1.0 and wait for new reports from play console. But with new version we have additional crashes i am not sure that this problem relates to this issue or need create else. 

Here is some reports from Crashlytics:
[crash_report_4.txt](https://github.com/firebase/quickstart-unity/files/6089941/crash_report_4.txt)
[crash_report_2.txt](https://github.com/firebase/quickstart-unity/files/6089942/crash_report_2.txt)
[crash_report_1.txt](https://github.com/firebase/quickstart-unity/files/6089943/crash_report_1.txt)
[crash_report_3.txt](https://github.com/firebase/quickstart-unity/files/6089944/crash_report_3.txt)

**Comment by chkuang-g** [comment] 2021-03-06 01:05
Yikes, that line `libFirebaseCppApp-7_1_0.Firebase_App_CSharp_StringStringMap_ContainsKey(Firebase_App_CSharp_StringStringMap_ContainsKey` looks very concerning to me.

This looks like a different issue.  For issue management sake, could you open an new ticket, include your latest configurations and these logs in it?

Thank you and have a good weekend.

Shawn

**Comment by wesclarkemag** [comment] 2021-03-24 21:14
Hello. We're also seeing a cluster of these in our ANR and Crash reports via the Google Play Console that just rolled out. 

Unity editor version: 2019.4.15f1
Firebase Unity SDK version: 7.1.0
Source you installed the SDK: Unity Package Manager)
Problematic Firebase Component: Messaging
Other Firebase Components in use: Crashlytics, Dynamic Links, Cloud Messaging, Google Analytics for Firebase
Additional SDKs you are using: Facebook, IronSource
Platform you are using the Unity editor on: MacOS, building via CI
Platform you are targeting: Android
Scripting Runtime: IL2CPP

We're also seeing this in conjunction with reports of No Loads from our users. We're not 100% sure if these are related right now, but the timing and devices line up. In our case, this occurs after the splash screen has completed and initialisation begins.

![Screenshot 2021-03-24 at 20 56 41](https://user-images.githubusercontent.com/62353443/112382544-e4dbb180-8ce3-11eb-8e0c-d7dad0e4a394.png)

Following is stack trace of a MessagingUnityPlayerActivity not responding event:

![Screenshot 2021-03-24 at 21 02 13](https://user-images.githubusercontent.com/62353443/112382866-49970c00-8ce4-11eb-84eb-09a0cdae3dab.png)

We're also getting instances of RegistrationIntentService problem

![Screenshot 2021-03-24 at 21 07 50](https://user-images.githubusercontent.com/62353443/112383577-333d8000-8ce5-11eb-9e2e-3d685e323b28.png)

The following is the stack trace

[registrationintent_anr_log.txt](https://github.com/firebase/quickstart-unity/files/6200495/registrationintent_anr_log.txt)

@chkuang-g 

Thanks

**Comment by Vesterix** [comment] 2021-03-29 07:58
@wesclarkemag We upgraded to 7.1.0 version, but I have not information from publisher about ANR, so it can be fixed or publisher just not informed me yet.

**Comment by hpanahloo** [comment] 2021-04-07 04:50
We have Upgraded to 7.1.0 but still having these ANRs.
Unity editor version: 2019.4.12f1
Firebase Unity SDK version: 7.1.0
Source you installed the SDK: Unity Package Asset
Problematic Firebase Component: Messaging
Other Firebase Components in use: Crashlytics, Analytic, Remote Config
Additional SDKs you are using: Facebook, Appodeal, Appsflyer
Platform you are using the Unity editor on: Windows
Platform you are targeting: Android
Scripting Runtime: IL2CPP
<img width="741" alt="chrome_nloNA2b74D" src="https://user-images.githubusercontent.com/12455980/113811337-4a6a7c00-9781-11eb-9f24-06a003815f40.png">
[ANR Logs.txt](https://github.com/firebase/quickstart-unity/files/6269056/ANR.Logs.txt)

**Comment by nanddo** [comment] 2021-04-21 13:05
**Project information**

- Unity editor version: 2019.4.21f1
- Firebase Unity SDK version: 7.1.0
- Source you installed the SDK: Unity Package Manager
- Problematic Firebase Component: Cloud Messaging
- Other Firebase Components in use: Analytics, Crashlytics, Remote Config
- Additional SDKs you are using: Facebook, IronSource, DeltaDNA, AdMob, EDM4U, BestHttp Pro, Google Play Games, Kochava, TapJoy, Unity IAP, Unity Local Notifications
- Platform you are using the Unity editor on: Windows/Mac
- Platform you are targeting: Android & iOS
- Scripting Runtime: IL2CPP

**Issue here:**
We're observing a pretty similar behavior on our side too. Starting on March 22nd, we observed a huge spike on ANRs related to Firebase Cloud Messaging. Since that day, the ANR rate is above bad behavior. The main spike was between March 22nd and 25th. After that, the numbers went down, but always above or too close to the bad behavior. The peers median is consistent with the behavior we're seeing.
![Time Series](https://user-images.githubusercontent.com/9734119/115557767-6ba29080-a288-11eb-9813-08312e95a287.png)

The problem is affecting only Android 8 and 9 (SDKs 26, 27 and 28). Here's amount of ANRs related to Firebase:
1. com.google.firebase.MessagingUnityPlayerActivity (39 in the last 7 days)
2. com.google.firebase.iid.FirebaseInstanceIdReceiver (17 in the last 7 days)
We also observed that each occurrence is directly related to the push notification times schedule on Firebase Console.
![Android versions](https://user-images.githubusercontent.com/9734119/115557827-79f0ac80-a288-11eb-8b62-ae5f4c63a74b.png)

The ANR logs are nearly identical to the ones present in the thread.

Any help or guidance will be much appreciated.

**Comment by alexames** [comment] 2021-06-15 06:18
Hi Vesterix,

Based on the call stacks you've showed us, and after talking with someone on the FCM team to help diagnose this, we suspect that there might be more than one issue causing you issues at the same time.

As chkuang-g mentioned a while back, [we've upgraded the RegistrationIntentService to a JobIntentService](https://github.com/firebase/firebase-cpp-sdk/pull/436). Even though this is mainly done to support Android O, we suspect it may also fix the issue you're seeing with the ANRs related to the RegistrationIntentService.

As for the crashes, I'm not convinced it's related. It's a little hard to tell what's going on from the call stack alone though, and without a reproduction case it's hard to debug. If you can find a reproduction case, that would really help us get to the root of the issue.

Try upgrading to the latest version of FCM and seeing if that reduces or eliminates the number or errors you're getting.

**Comment by alexames** [comment] 2021-06-18 06:05
I'm going to go ahead and close this for now, if you see this still happening after updating your library feel free to reopen it. As I mentioned before, it looks like there may have been a second issue at play here too, so if you still see that as well open a new issue so we can track that separately.

**Closed by alexames** 2021-06-18 06:05 UTC
Labels: api: messaging, needs-info, type: bug
