### ISSUE TITLE
[Bug] Crashed after calling FirebaseApp.CheckAndFixDependenciesAsync()

### ISSUE THREAD

**Issue by keepup** [firebase/quickstart-unity#1181] opened 2021-11-18 09:01 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.22f1c1 /  2019.4.24.f1c1
  * Firebase Unity SDK version: v8.6.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use: None
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Crashed after calling FirebaseApp.CheckAndFixDependenciesAsync() when network is terrible.

[firebasedemo_logs.txt](https://github.com/firebase/quickstart-unity/files/7561229/firebasedemo_logs.txt)

#### Steps to reproduce:

I have created a demo project here: https://github.com/keepup/FirebaseDemo
APK file: https://github.com/keepup/FirebaseDemo/tree/main/Output-Android

1. Install FirebaseDemo.apk on phone;
2. Simulate a bad network environment or turn off phone WiFi and Cellular network;
3. Open FirebaseDemo;

If not crashed, please reinstall FirebaseDemo.apk or clear data and cache in the application setting for FirebaseDemo.
Then repeat the above steps.

#### Similar issues:
#1170 
#1169 
#1160 
#1166

**Comment by paulinon** [comment] 2021-11-18 14:11
Hi @keepup,

It appears that your issue is similar to #1169. With that, I'll be closing this and marking this as a dupe for now. You may check out #1169 for any updates as we are currently investigating this behavior.

**Comment by paulinon** [comment] 2021-11-18 14:11
Duplicate of #1169

**Closed by paulinon** 2021-11-18 14:11 UTC
Labels: type: question, api: messaging
