### ISSUE TITLE
Firebase(v6.2.1) Crash on Crashlytics Set custom key

### ISSUE THREAD

**Issue by Vah94** [firebase/quickstart-unity#421] opened 2019-07-16 08:26 UTC
## Please fill in the following fields:
Unity editor version: 
Firebase Unity SDK version: 6.2.1 
Firebase plugins in use (Analytics, Crashlytics):
Additional SDKs you are using (null): 
Platform you are using the Unity editor on (Windows): 
Platform you are targeting (Android): 

## Please describe the issue here:
Build for android platform and just run 

##Unity project
[FirebaseTest.zip](https://github.com/firebase/quickstart-unity/files/3396029/FirebaseTest.zip)

##Crash report
07-16 11:21:30.458 19618-19665/? E/CRASH: 	#00  pc 000ea018  /data/app/com.companyname.gamename-8cdvRNGrxSrfrFfgDIshUA==/lib/arm/libFirebaseCppApp-6.2.1.so (firebase::crashlytics::internal::CrashlyticsInternal::SetCustomKey(char const*, char const*)+15)
#01  pc 00013ea4   ( (wrapper managed-to-native) Firebase.Crashlytics.CrashlyticsInternalPINVOKE:FirebaseCrashlyticsInternal_SetCustomKey (System.Runtime.InteropServices.HandleRef,string,string) {0xbc157500} + 0x7c (0xe8e38e28 0xe8e38f04) [0xe8d8ef00 - Unity Root Domain]+81572)
                    memory near r2:

**Comment by alexames** [comment] 2019-07-16 23:59
It's not clear from your description what the bug is. It sounds like you are calling SetCustomKey, and it is crashing when you do so, is that correct?

Have you tried running the Crashlytics testapp? Does the problem occur there as well?

**Comment by samedson** [comment] 2019-07-31 18:14
Taking a look at reproing this right now

**Comment by samedson** [comment] 2019-07-31 21:33
Hey @Vah94 I'm not able to reproduce the issue. Can you list what version of Unity and what Android version / device you're using? In addition, can you try to reproduce on the newest Firebase Unity SDK?

**Comment by Vah94** [comment] 2019-08-02 11:00
Hey @samedson . 
Unity version 2018.4.4f1
Android version 9
Project for test in description.

**Comment by Vah94** [comment] 2019-08-02 14:18
08-02 18:16:42.066 30515-30616/? E/MessageQueue: IdleHandler threw exception
    java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
    Build fingerprint: 'samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXU5DSFB:user/release-keys'
    Revision: '10'
    pid: 30515, tid: 30616, name: UnityMain  >>> com.companyname.gamename<<<
        r0 00000000  r1 00000001  r2 bec8e100  r3 bec8e100
        r4 b88a87f0  r5 b88a9918  r6 bed6a630  r7 bec8e100
        r8 bed6a630  r9 c4a7b6c0  sl bfe2db50  fp d0229518
        ip bf4a9700  sp d02294f8  lr ecc8f660  pc bf3f264c  cpsr 00007798
    
        at libFirebaseCppApp-6_2_2.firebase::crashlytics::internal::CrashlyticsInternal::SetCustomKey(char const*, char const*)(crashlytics:15)
        at Unknown.0000c65c(Unknown Source:0)

**Comment by samedson** [comment] 2019-08-02 16:09
Thanks - I was able to recreate the crash on a Samsung Galaxy S6.

Also tried using Unity 2019.2.0f1, and there was no crash. If you need to get unblocked in the meantime, then upgrading your Unity version might help.

**Comment by Vah94** [comment] 2019-08-05 10:44
@samedson https://github.com/firebase/quickstart-unity/issues/435

**Comment by alexames** [comment] 2019-08-14 20:56
This issue has been resolved in the latest release of the SDK, version 6.3.0.

**Closed by alexames** 2019-08-14 20:56 UTC
Labels: type: bug
