### ISSUE TITLE
Firebase SMS Verification is not working

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/quickstart-unity#1241] opened 2022-03-17 12:19 UTC
Hi All 

 I am working in firebase SMS. I am using Unity quick start master.  I am implementing SMS  in my project. 

When i try to send to my indian phone number. It is working. Sms is receiving. But  when i try to validate sms . the validation is not 

working.   But When i try with test phone number given in Firebase console. The Test SMS password is  validating. 

Some times OnCodeSent is also not called. 

Is it any restriction given by firebase SMS for live validation.  when i am going  for alive  our team  needs to test with live phone 

number.  SMS is  receiving  but   validation is not happening.

What are the condition for live checking my firebase project?  Can any one guide   me???

**Comment by paulinon** [comment] 2022-03-17 12:49
Hi @CLOUDFIRE91,

Based on your description, it seems that there's an issue with SMS validation. Given that the cause of this behavior lies in the backend, kindly reach out to [Firebase Support](https://firebase.google.com/support/troubleshooter/auth/phone) where one of our agents can identify what's causing this. That being said, I'll close this for now.

**Closed by paulinon** 2022-03-17 12:49 UTC
Labels: type: question, api: auth

**Comment by CLOUDFIRE91** [comment] 2022-03-17 13:08
@paulinon  I have a Question. Did firebase prevent  checking because it may  be spam.. is  there any kind of checking  is going on  firebase?
Or it will work any length of time????
