### ISSUE TITLE
File google-services.json is missing. But it added to project

### ISSUE THREAD

**Issue by kapyar** [firebase/quickstart-unity#852] opened 2020-11-05 08:31 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.2.19f1
  * Firebase Unity SDK version: 6.14.1
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Auth, Database, FCM, Dynamic Links, Real Time Db
  * Additional SDKs you are using: Admob
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Here is the deal, I am trying to set up 
```
firebaseCrashlytics {
                    mappingFileUploadEnabled true
                  }

```
I have a custom Gradle template for my project (I will attach at the end). Before adding mappingFileUploadEnabled true, the project work ok and I was able to build apk. 
To make the thing work I added the following lines to my project
```
buildscript {
    dependencies {
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.3.0'
        classpath 'com.google.gms:google-services:4.3.0'  // Google Services plugin
    }
}

apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.gms.google-services'  // Google Services plugin

....
release{
 firebaseCrashlytics {
                    mappingFileUploadEnabled true
                  }
}
```

#### Steps to reproduce:

When I tried to build the project I got a message. '> File google-services.json is missing. The Google Services Plugin cannot function without it. ' but I have it in my project.

#### Relevant Code:

Here is my Gradle file
```
// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN

buildscript {
    repositories {**ARTIFACTORYREPOSITORY**
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.3.0'
        classpath 'com.google.gms:google-services:4.3.0'  // Google Services plugin
**BUILD_SCRIPT_DEPS**}
}

allprojects {
    repositories {**ARTIFACTORYREPOSITORY**
        google()
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
}

// Android Resolver Repos Start
([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }
}
([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url "https://maven.google.com"
        }
        maven {
            url "https://maven.google.com/" // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
        }
        maven {
            url "https://jcenter.bintray.com/" // Assets/GoogleMobileAds/Editor/UnityMediationDependencies.xml:7
        }
        maven {
            url (unityProjectPath + "/Assets/GeneratedLocalRepo/Firebase/m2repository") // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:20, Packages/com.google.firebase.auth/Firebase/Editor/AuthDependencies.xml:20, Packages/com.google.firebase.messaging/Firebase/Editor/MessagingDependencies.xml:20, Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:20, Packages/com.google.firebase.dynamic-links/Firebase/Editor/DynamicLinksDependencies.xml:20, Packages/com.google.firebase.instance-id/Firebase/Editor/InstanceIdDependencies.xml:20, Packages/com.google.firebase.database/Firebase/Editor/DatabaseDependencies.xml:20, Packages/com.google.firebase.remote-config/Firebase/Editor/RemoteConfigDependencies.xml:20, Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:18
        }
        mavenLocal()
        jcenter()
        mavenCentral()
    }
}
// Android Resolver Repos End
apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.gms.google-services'  // Google Services plugin
**APPLY_PLUGINS**


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9' // Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:15
    implementation 'com.google.ads.mediation:unity:3.3.0.0' // Assets/GoogleMobileAds/Editor/UnityMediationDependencies.xml:7
    implementation 'com.google.android.gms:play-services-ads:18.2.0' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.android.gms:play-services-appinvite:18.0.0' // Packages/com.google.firebase.dynamic-links/Firebase/Editor/DynamicLinksDependencies.xml:13
    implementation 'com.google.firebase:firebase-analytics:17.3.0' // Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:13
    implementation 'com.google.firebase:firebase-analytics-unity:6.14.1' // Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-app-unity:6.14.1' // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:20
    implementation 'com.google.firebase:firebase-auth:19.3.0' // Packages/com.google.firebase.auth/Firebase/Editor/AuthDependencies.xml:13
    implementation 'com.google.firebase:firebase-auth-unity:6.14.1' // Packages/com.google.firebase.auth/Firebase/Editor/AuthDependencies.xml:20
    implementation 'com.google.firebase:firebase-common:19.3.0' // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-config:19.1.3' // Packages/com.google.firebase.remote-config/Firebase/Editor/RemoteConfigDependencies.xml:13
    implementation 'com.google.firebase:firebase-config-unity:6.14.1' // Packages/com.google.firebase.remote-config/Firebase/Editor/RemoteConfigDependencies.xml:20
    implementation 'com.google.firebase:firebase-crashlytics-unity:6.14.1' // Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:20
    implementation 'com.google.firebase:firebase-database:19.2.1' // Packages/com.google.firebase.database/Firebase/Editor/DatabaseDependencies.xml:13
    implementation 'com.google.firebase:firebase-database-unity:6.14.1' // Packages/com.google.firebase.database/Firebase/Editor/DatabaseDependencies.xml:20
    implementation 'com.google.firebase:firebase-dynamic-links-unity:6.14.1' // Packages/com.google.firebase.dynamic-links/Firebase/Editor/DynamicLinksDependencies.xml:20
    implementation 'com.google.firebase:firebase-iid:20.1.5' // Packages/com.google.firebase.instance-id/Firebase/Editor/InstanceIdDependencies.xml:13
    implementation 'com.google.firebase:firebase-instance-id-unity:6.14.1' // Packages/com.google.firebase.instance-id/Firebase/Editor/InstanceIdDependencies.xml:20
    implementation 'com.google.firebase:firebase-messaging:20.1.5' // Packages/com.google.firebase.messaging/Firebase/Editor/MessagingDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging-unity:6.14.1' // Packages/com.google.firebase.messaging/Firebase/Editor/MessagingDependencies.xml:20
// Android Resolver Dependencies End
    implementation 'com.google.firebase:firebase-crashlytics-ndk:17.2.2'

**DEPS**}

// Android Resolver Exclusions Start
android {
  packagingOptions {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {

     sourceSets {
        main {
            def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
            res.srcDirs += (unityProjectPath +  '/Assets/Configs/google-services.json')
        }
    }
    
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        applicationId '**APPLICATIONID**'
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb'**STREAMING_ASSETS**]
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**SIGN**

    buildTypes {
        debug {
        //NOTE(kaplya):added
            multiDexEnabled true
            minifyEnabled **MINIFY_DEBUG**
            useProguard **PROGUARD_DEBUG**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD****SIGNCONFIG**
            jniDebuggable true
            firebaseCrashlytics {
                    mappingFileUploadEnabled false
                  }
        }
        release {
        //TODO(kaplya): added
            multiDexEnabled true
            minifyEnabled **MINIFY_RELEASE**
            useProguard **PROGUARD_RELEASE**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD****SIGNCONFIG**
            firebaseCrashlytics {
                    mappingFileUploadEnabled true
                  }
        }
    }**PACKAGING_OPTIONS****SPLITS**
**BUILT_APK_LOCATION**
**EXTERNAL_SOURCES**
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
}**SPLITS_VERSION_CODE****REPOSITORIES****SOURCE_BUILD_SETUP**

```

**Comment by patm1987** [comment] 2020-11-05 18:23
Unfortunately, native crash reports are not supported in the Unity plugin. See #745, and I'd recommend tracking that for that feature.

The error you're looking at is that the google play services plugin (`apply plugin: 'com.google.gms.google-services'`) is looking for `google-services.json`, which it intends to use to generate `res/values/google-services.xml`. This would duplicate work done by the Firebase Google Play, and you should probably avoid adding it there. You can likely remove it, I don't think it's necessary for the Crashlytics plugin, but you'd still be in an unsupported configuration.

**Comment by patm1987** [comment] 2020-11-05 18:24
Duplicate of #745

**Closed** 2020-11-05 18:24 UTC
Labels: api: crashlytics
