### ISSUE TITLE
[Bug] Remote config fetch seems to hang forever after SDK update.

### ISSUE THREAD

**Issue by pihels** [firebase/quickstart-unity#1198] opened 2021-12-01 13:00 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.1.24f1
  * Firebase Unity SDK version: 8.5.0, 8.1.0, 7.2.0
  * Source you installed the SDK: Added .tgz archives to Packages folder and manifest.json
  * Problematic Firebase Component: Remote Config (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Analytics, Firestore, Messaging, Crashlytics
  * Additional SDKs you are using: Google Sign-In 
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS 
  * Scripting Runtime: IL2CPP 

### [REQUIRED] Please describe the issue here:

After updating Firebase Unity libraries from 6.15.2 (everything works fine here) to 8.1.0 fetching the remote config values does not complete. There are no errors in console that I noticed. 
The issue seems to happen when I start the fetch task:
` System.Threading.Tasks.Task fetchTask = Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.FetchAsync (new TimeSpan (12, 0, 0));`
Seems like this fetch hangs indefinitely, doesn't give an error and doesn't complete successfully. When I tried to do another fetch a few seconds later, I got the error about duplicate fetches (can't recall the exact error).

#### Steps to reproduce:

The issue seems to happen randomly (works half the time, doesn't work the other half) on all our iOS test devices (my device has iOS 14). Everything works on Android.

I attached device logs for the successful and unsuccessful fetches. For the success you can see "Fetching firebase remote config data successful." logged in the end.

#### Relevant Code:

Below is the code I use for Firebase setup and fetching. I noticed that with the new libraries I have to use FirebaseRemoteConfig.DefaultInstance. So maybe I am missing some crucial step about setting the DefaultInstance? I looked through the tutorials and quickstart examples and can't see anything missing.

Firebase initialization script:

```
using Firebase;
using UnityEngine;
using UnityEngine.Events;
public class FirebaseInitializer : MonoBehaviour {
    public UnityEvent onInitialized = new UnityEvent ();
    public FirebaseApp app;

    void Start () {
        UnityEngine.Debug.Log ("Trying to initialize firebase...");
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync ().ContinueWith (task => {
            var dependencyStatus = task.Result;
            if (dependencyStatus == Firebase.DependencyStatus.Available) {
                // Create and hold a reference to your FirebaseApp,
                // where app is a Firebase.FirebaseApp property of your application class.
                app = FirebaseApp.DefaultInstance;

                // Set a flag here to indicate whether Firebase is ready to use by your app.

                // Analytics
                Firebase.Analytics.FirebaseAnalytics.SetAnalyticsCollectionEnabled (true);
                Firebase.Analytics.FirebaseAnalytics.LogEvent (Firebase.Analytics.FirebaseAnalytics.EventAppOpen);

                // Messaging (Push Notifications)
                Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
                Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
                UnityEngine.Debug.Log ("Firebase initialized!");
                onInitialized.Invoke ();
            } else {
                UnityEngine.Debug.LogError (System.String.Format (
                    "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
            }
        });

    }
}
```

Remote config script

   ```
public class FirebaseRemoteConfigManager : MonoBehaviour {

    public UnityEvent onConfigLoaded = new UnityEvent ();
    public UnityEvent onConfigInitialized = new UnityEvent ();
    public bool AreValuesLoaded { get; private set; }
    public FirebaseInitializer firebaseInitializer;

    void Start () {
        firebaseInitializer.onInitialized.RemoveListener (InitializeRemoteConfig);
        firebaseInitializer.onInitialized.AddListener (InitializeRemoteConfig);
        Debug.Log (LOGGER_PREFIX + "Waiting for firebase initialization...");
    }

    private void InitializeRemoteConfig () {
        Debug.Log (LOGGER_PREFIX + "Initializing firebase remote config...");
        
        Dictionary<string, object> defaults = new Dictionary<string, object> ();
        // These are the values that are used if we haven't fetched data from the
        // server yet, or if we ask for values that the server doesn't have:
        defaults.Add ("test_key", false);

        Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.SetDefaultsAsync (defaults).ContinueWithOnMainThread (task => {
            Debug.Log (LOGGER_PREFIX + LOGGER_PREFIX + "Fetching firebase remote config data...");
            onConfigInitialized.Invoke ();
            FetchRemoteConfigAsync ();
        });

    }

    // Start a fetch request.
    // FetchAsync only fetches new data if the current data is older than the provided
    // timespan.  Otherwise it assumes the data is "recent enough", and does nothing.
    // By default the timespan is 12 hours, and for production apps, this is a good
    // number. For this example though, it's set to a timespan of zero, so that
    // changes in the console will always show up immediately.
    public void FetchRemoteConfigAsync () {
        System.Threading.Tasks.Task fetchTask = Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.FetchAsync (new TimeSpan (12, 0, 0)); //change to TimeSpan.Zero only for dev testing purposes

        fetchTask.ContinueWith (task => {
            if (task.Exception != null) {
                Debug.LogError (LOGGER_PREFIX + "Fetching firebase remote config data failed. " + task.Exception.Message);
                return;
            }
            if (task.IsCanceled) {
                Debug.LogError (LOGGER_PREFIX + "Fetching firebase remote config data canceled.");
                return;
            }

            var info = Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.Info;
            Debug.Log (LOGGER_PREFIX + "Info last fetch status " + info.LastFetchStatus);
            System.Threading.Tasks.Task activateTask = Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.ActivateAsync ();
            activateTask.ContinueWith (task => {
                Debug.Log (LOGGER_PREFIX + "Fetching firebase remote config data successful. Activated " + activateTask.Status.ToString ());
                OnFetchComplete ();
            });

        });
    }

    private void OnFetchComplete () {
        UnityMainThread.wkr.AddJob (() => {
            onConfigLoaded.Invoke ();
            AreValuesLoaded = true;
        });
    }

 }

```
[remoteconfigfailure(1).txt](https://github.com/firebase/quickstart-unity/files/7634001/remoteconfigfailure.1.txt)
[remoteconfigsuccess(1).txt](https://github.com/firebase/quickstart-unity/files/7634002/remoteconfigsuccess.1.txt)

**Comment by paulinon** [comment] 2021-12-02 12:35
Hi @pihels,

Thanks for reporting this issue. While I try using your sample code, could you verify if this behavior also persists when using our quickstart?

**Comment by Nyankoo** [comment] 2021-12-09 14:40
@paulinon Where you able to reproduce this with the code above?

**Comment by pihels** [comment] 2021-12-28 17:00
Sorry for the late reply, but I have now tested with the sample app and managed to repro the issue. I took the remote config sample app from this repo, added all the firebase libraries I use in my own project to the Packages folder and loaded them via the manifest.json file and then built the app using my own firebase configuration. Managed to reproduce the issue on the same device and again it didn't happen every time, but maybe like 1 out of 5 times. 

I opened the app and the sample scene showed "RemoteConfig configured and ready". I clicked the "Fetch Remote Data" button and a couple of times it showed "Fetching data.." and nothing happened after that (waited for about a minute). When I clicked the button again it fetched the values with no problems. I have also added a log file with one such incident - you can see "Fetching data..." is logged twice in a row but only completes once. What is strange is that I didn't get the duplicate fetch error here like I did with my own app even though code wise it seems the same.

Also keep in mind that this issue does not happen every time I try to fetch, but rather randomly. I had to close and open the sample app and try 5 times before I could repro it.

[firebase_fetch_hang.txt](https://github.com/firebase/quickstart-unity/files/7785672/firebase_fetch_hang.txt)

**Comment by Nyankoo** [comment] 2021-12-29 01:13
@paulinon Please re-open. Thank you!

Maybe related to #1138, so pinging @DellaBitta to confirm.

**Comment by paulinon** [comment] 2021-12-29 13:30
Hi folks,

I was able to replicate the issue using the quickstart with the latest SDK version (8.7.0), although I should point out that I had imported Remote Config, Analytics, and FCM based on your original code. This happens the first time I fetch data after the app is launched, and this behavior doesn't occur on Android builds.

I'll be marking this as a bug for now. We'll let you know of any updates.

**Comment by spikyworm5** [comment] 2022-01-22 05:33
@paulinon Any updates on this issue? It has been 24 days since this bug was reported and still no solution. The SDK is considered completely broken due to this bug. We can't rely on the framework in a production version of our game as configs fail to load on iOS most of the time. Thanks.

We're using the latest version 8.7.0

**Comment by Nyankoo** [comment] 2022-01-27 14:56
@paulinon Any updates?

**Comment by tinyrickguy** [comment] 2022-02-02 14:01
For those who are having this issue, we were able to resolve it by making sure that there are ZERO calls to the Firebase SDK before it has finished initializing. In our case, we were calling FirebaseRemoteConfig.DefaultInstance.Keys before CheckAndFixDependenciesAsync has finished calling its callback, which was the trigger to the broken behaviour described here.
Not sure that it's the exact same issue others are having, but it did help us.

**Comment by Nyankoo** [comment] 2022-02-02 14:16
We're awaiting CheckAndFixDependenciesAsync and initiate all other calls to the Firebase SDK after it returns with DependencyStatus.Available, so it seems this is unrelated.

**Comment by tinyrickguy** [comment] 2022-02-02 14:19
@Nyankoo also make sure you are calling all Firebase SDK method only on the main thread, for a MonoBehaviour event method and that you are not using ContinueWithOnMainThread, but rather simply "await" the response. 
It's possible these are unrelated issues, but the above are also can help.

**Comment by spikyworm5** [comment] 2022-02-02 14:27
@tinyrickguy That's interesting. Here is a snippet of our initialization code:
`FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task =>
{
  ReadyAction?.Invoke();
}
`

Then, the listener of `ReadyAction` calls `FetchAndActivateAsync`. Is this a problem?
By *await* you mean literally call use `await` or using Unity coroutine?

**Comment by tinyrickguy** [comment] 2022-02-02 14:30
@spikyworm5 try rewriting it to run like this:
var dependencyStatus = await FirebaseApp.CheckAndFixDependenciesAsync();
...
await FirebaseRemoteConfig.DefaultInstance.FetchAsync(TimeSpan.Zero);
...
await FirebaseRemoteConfig.DefaultInstance.ActivateAsync();

the point being to avoid using ContinueWithOnMainThread and making sure you only call the SDK from the main thread to begin with.

**Comment by Nyankoo** [comment] 2022-02-02 14:31
@tinyrickguy That's exactly how we're doing it and it's still broken.

**Comment by spikyworm5** [comment] 2022-02-02 18:50
I tried this ugly code as a test and got the same result. The task never completes.
```
...
task = FirebaseApp.CheckAndFixDependenciesAsync();
...

void Update()
{
  if (task != null && task.IsCompleted)
    ReadyAction?.Invoke();
}
```

I can also add that it looks like it works when app data is clear = no cache = no remote request to wait for?

**Comment by tinyrickguy** [comment] 2022-02-03 06:05
@spikyworm5 
while that should probably work, the proper async way to do this is:
await FirebaseApp.CheckAndFixDependenciesAsync(); 
ReadyAction?.Invoke();

Regarding the "no cache", "data is clear" - we had a similar situation where a clean instal would behave differently from a 2nd run, it turned out to be due to different loading times in our app between a clean run and a 2nd run which resulted in a race condition between the Firebase init code and other code that accessed the Firebase SDK before it was fully initialized.

**Comment by spikyworm5** [comment] 2022-02-03 06:17
This was just a test. To see if it somehow related to code running from a different thread than Unity's main thread. It's not how we implemented this.
I couldn't identify any Firebase code that is running before (or during) `CheckAndFixDependenciesAsync`. I believe that in our case it fails when no remote config cache exists. I'll try to verify this and post if I have a clear conclusion.

**Comment by spikyworm5** [comment] 2022-02-03 16:56
@tinyrickguy We did another test. We created a scene that does nothing but initialize Firebase and then load the next scene in which we do the Remote Config fetch. Same behavior. Fetch never completes. 

Did anyone test it 8.8.0? I see a vague change log line: 

> "Fixed an issue where the TimeSpan field of FetchDataAsync was being used incorrectly."

Can this be related? I will try to test it soon and update.
https://firebase.google.com/support/release-notes/unity

**Comment by spikyworm5** [comment] 2022-02-04 16:48
Tested with 8.8.0. Same result.

It's worth mentioning that we're using Firebase Auth, Database, Analytics and Remote Config. 
We noticed that for Analytics automatic reporting was enabled and we thought that disabling it would solve the issue but it didn't. We couldn't find any evidence for anything else that touches Firebase before the initialization.

**Comment by jonsimantov** [comment] 2022-02-15 19:17
Hi all,

Thanks for your patience as we track this down. We believe we have found the issue. 

When your app initializes, you may see some lines in the log that look like this:
> `objc[81146]: Class FIRAAdExposureReporter is implemented in both /private/var/containers/Bundle/Application/487A8505-DF2E-44A8-A373-7E60A6376650/FirebaseRemoteConfigUnityTestapp.app/FirebaseRemoteConfigUnityTestapp (0x100c21358) and /private/var/containers/Bundle/Application/487A8505-DF2E-44A8-A373-7E60A6376650/FirebaseRemoteConfigUnityTestapp.app/Frameworks/UnityFramework.framework/UnityFramework (0x107f91b08). One of the two will be used. Which one is undefined.`

This is because the iOS app is referencing the `Firebase/Core` framework from multiple locations, with dynamic frameworks enabled, which causes an intermittent hang when Remote Config looks up the device's Analytics properties (if the wrong FIRAnalytics instance is used). This should be changed to use `Firebase/Analytics`, with static frameworks enabled, which ensures there is only one FIRAnalytics instance present.

A proper fix will be coming soon, but until then, here is a workaround:

### Workaround
1. In your Unity project's directory, edit `Assets/Firebase/Editor/AppDependencies.xml` and change `Firebase/Core` to `Firebase/Analytics`.
2. In Unity, go to *Assets > External Dependency Manager > iOS Resolver > Settings* and enable the **Link Frameworks Statically** option, then export your iOS project again.
3. If you are using any Swift-based pod dependencies (e.g. Facebook), you may need to add a placeholder Swift file to your Xcode project, with the following as its only line:
           `import Foundation`

Please let us know if this workaround solves the issue for you. There should be an officially-released fix soon.

**Comment by techyworm10** [comment] 2022-02-15 20:18
Thanks @jonsimantov for looking into it!

We tried your suggested workaround, but it didn't help.

It looks like our log is till full of these:
```objc[5044]: Class FIRAAdExposureReporter is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa1358) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de1350). One of the two will be used. Which one is undefined.
objc[5044]: Class FIRAConditionalUserProperty is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa13a8) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de13a0). One of the two will be used. Which one is undefined.
objc[5044]: Class FIRAConditionalUserPropertyController is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa13f8) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de13f0). One of the two will be used. Which one is undefined.
objc[5044]: Class FIRAEvent is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa1448) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de1440). One of the two will be used. Which one is undefined.
objc[5044]: Class FIRAIdentifiers is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa1498) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de1490). One of the two will be used. Which one is undefined.
objc[5044]: Class FIRAMeasurement is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa14c0) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de14b8). One of the two will be used. Which one is undefined.
objc[5044]: Class FIRAnalytics is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa1510) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de1508). One of the two will be used. Which one is undefined.```

In total, we have 156 lines similar to those above.
I must also add that this issue is more frequent on a clean install.

I hope this helps track down the problem.

Many thanks!

**Comment by jonsimantov** [comment] 2022-02-15 21:26
> Thanks @jonsimantov for looking into it!
> 
> We tried your suggested workaround, but it didn't help.
> 
> It looks like our log is still full of these:
> 
> ```
> objc[5044]: Class FIRAAdExposureReporter is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa1358) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de1350). One of the two will be used. Which one is undefined.
> objc[5044]: Class FIRAConditionalUserProperty is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa13a8) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de13a0). One of the two will be used. Which one is undefined.
> objc[5044]: Class FIRAConditionalUserPropertyController is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa13f8) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de13f0). One of the two will be used. Which one is undefined.
> objc[5044]: Class FIRAEvent is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa1448) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de1440). One of the two will be used. Which one is undefined.
> objc[5044]: Class FIRAIdentifiers is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa1498) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de1490). One of the two will be used. Which one is undefined.
> objc[5044]: Class FIRAMeasurement is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa14c0) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de14b8). One of the two will be used. Which one is undefined.
> objc[5044]: Class FIRAnalytics is implemented in both /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/AppName (0x100aa1510) and /private/var/containers/Bundle/Application/2F817C64-118F-4644-BC7B-95FECB5FCAEB/AppName.app/Frameworks/UnityFramework.framework/UnityFramework (0x109de1508). One of the two will be used. Which one is undefined.
> ```
> 
> In total, we have 156 lines similar to those above. I must also add that this issue is more frequent on a clean install.
> 
> I hope this helps track down the problem.
> 
> Many thanks!

Could you please paste a copy of the Podfile from the iOS project directory generated by Unity?

**Comment by techyworm10** [comment] 2022-02-16 03:35
This is the Podfile contents:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '8.11.0'
  pod 'Firebase/Auth', '8.11.0'
  pod 'Firebase/Core', '8.11.0'
  pod 'Firebase/Database', '8.11.0'
  pod 'Firebase/RemoteConfig', '8.11.0'
end
target 'Unity-iPhone' do
end
use_frameworks!
```

**Comment by jonsimantov** [comment] 2022-02-16 21:41
When you set static linking on, it should be adding a flag to the end of the Podfile. Can you make sure the iOS project was regenerated after setting that flag?

**Comment by techyworm10** [comment] 2022-02-17 07:32
It looks like the Podfile wasn't updated previously.
I rebuilt the project (after deleting the build folder completely)
This is the updated contents of the file:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '8.11.0'
  pod 'Firebase/Auth', '8.11.0'
  pod 'Firebase/Database', '8.11.0'
  pod 'Firebase/RemoteConfig', '8.11.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
```

Now there are no errors at all! and after many tests, it looks like it's working perfectly.

Thanks @jonsimantov!

When do expect the official fix to be released?

**Comment by chkuang-g** [comment] 2022-02-17 18:31
@techyworm10 

EDM4U regenerates `Podfile` during build time.  Therefore, flipping the flag will not cause the `Podfile` to be regenerated immediately.

There are some additional works to be done to use `:linkage => :static` by default.  Since this is starting to be an annoyance to many, we are planning to take action on this soon.

Shawn

**Comment by jonsimantov** [comment] 2022-02-23 19:18
FYI, this is caused by the same EDM4U issue as #1178. Until the fix is released, if you are encountering any issues with Firebase Analytics (or Remote Config) on iOS, please follow the workaround listed in https://github.com/firebase/quickstart-unity/issues/1198#issuecomment-1040690857.

**Comment by jonsimantov** [comment] 2022-04-08 16:47
Firebase SDK for Unity 8.9.0 is now live, which contains a fix for this issue, and you can download it directly [here](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_8.9.0.zip), or through the usual places like the package manager.

If the problem persists on iOS, please:
- Confirm that the generated Podfile has the ':linkage => :static' flag in it
- If it doesn't, do the following: In Unity, go to Assets > External Dependency Manager > iOS Resolver > Settings and enable the Link Frameworks Statically option, then export your iOS project again (into a new folder). Confirm that the generated Podfile has ':linkage => :static'
- If the issue persists even with the static flag set, please re-open this issue.

**Closed by jonsimantov** 2022-04-08 16:47 UTC
Labels: type: bug, api: remoteconfig
