### ISSUE TITLE
SDK Functionalities not working on the device (Only when built, in editor works fine)

### ISSUE THREAD

**Issue by Nicokkam** [firebase/quickstart-unity#901] opened 2020-12-18 02:45 UTC
### [REQUIRED] Please fill in the following fields:

Unity editor version: _____2020.1.0f1
Firebase Unity SDK version: _____Latest
Source you installed the SDK: _____ .unitypackage
Problematic Firebase Component: _____ Database
Other Firebase Components in use: _____ Auth, Database and Analytics
Additional SDKs you are using: _____ Facebook
Platform you are using the Unity editor on: _____ Mac
Platform you are targeting: _____ iOS, Android
Scripting Runtime: _____ IL2CPP

### [REQUIRED] Please describe the issue here:

I am having so much trouble with this SDK! I just came across another bug that I cannot solve.

So, I added the Firebase and Facebook SDK's in my unity project and something weird happened.

My code works perfectly in the Unity Editor (Email/Password and Facebook Login) with no errors whatsoever. BUT, when I build it into iOS and try it out on my code, nothing regarding the SDK works, not even the button that makes the login (It should activate a message that says that I have to fill out the email field, etc..). Even if I fill out the information it doesn't do anything.
The facebook button does trigger the login process, but when it comes to the end and starts to return from the facebook app to mine, it just returns to the login screen as if nothing had happened (It should go to the main screen instead).

As I said in the beginning, everything IS WORKING PERFECTLY in the editor, so I'm guessing It's something not very complex but specific that I don't have to knowledge solve on my own, given that I have dedicated all day on this matter.

Would really appreciate some help and please don't hesitate to ask for information that will help to accelerate this process.

Here are the other posts I made (don't know if I modified something I shouldn't:
https://github.com/firebase/quickstart-unity/issues/898#issuecomment-746039039
https://github.com/firebase/quickstart-unity/issues/892

### Here are some of the errors from the Xcode:

`CrashReporter: initialized
2020-12-17 19:49:32.185064-0300 zzzz[23059:8122575] Built from '2020.1/staging' branch, Version '2020.1.0f1 (2ab9c4179772)', Build type 'Release', Scripting Backend 'il2cpp'
-> applicationDidFinishLaunching()
2020-12-17 19:49:32.257870-0300 zzzz[23059:8122575] Metal GPU Frame Capture Enabled
2020-12-17 19:49:32.258456-0300 zzzz[23059:8122575] Metal API Validation Enabled
-> applicationDidBecomeActive()
[Subsystems] Discovering subsystems at path /private/var/containers/Bundle/Application/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY/Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Initializing Metal device caps: Apple A13 GPU
Initialize engine version: 2020.1.0f1 (2ab9c4179772)
CrashReporter: Could not parse crash report: Could not decode truncated crash log
2020-12-17 19:49:33.811029-0300 moovyn[23059:8122924] [Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 92 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 92 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
2020-12-17 19:49:33.814584-0300 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[23059:8122575] Unbalanced calls to begin/end appearance transitions for <UnityViewControllerStoryboard: 0x103487ac0>.
2020-12-17 19:49:33.823953-0300 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[23059:8122919] [tcp] tcp_input [C2.1:3] flags=[R] seq=265141129, ack=0, win=0 state=CLOSED rcv_nxt=265141129, snd_una=1607627885
2020-12-17 19:49:33.824001-0300 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[23059:8122919] [tcp] tcp_input [C2.1:3] flags=[R] seq=265141129, ack=0, win=0 state=CLOSED rcv_nxt=265141129, snd_una=1607627885
2020-12-17 19:49:33.849809-0300 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[23059:8122923] FBSDKLog: fb-messenger-share-api is missing from your Info.plist under LSApplicationQueriesSchemes and is required.
2020-12-17 19:49:33.858905-0300 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[23059:8122924] [tcp] tcp_input [C3.1:3] flags=[R] seq=2668679344, ack=0, win=0 state=CLOSED rcv_nxt=2668679344, snd_una=1421442049
2020-12-17 19:49:33.858980-0300 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[23059:8122924] [tcp] tcp_input [C3.1:3] flags=[R] seq=2668679344, ack=0, win=0 state=CLOSED rcv_nxt=2668679344, snd_una=1421442049
2020-12-17 19:49:34.978091-0300 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[23059:8122919] [tcp] tcp_input [C4.2:3] flags=[R] seq=4236490899, ack=0, win=0 state=CLOSED rcv_nxt=4236490899, snd_una=2789091866
2020-12-17 19:49:34.978937-0300 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[23059:8122919] [tcp] tcp_input [C4.2:3] flags=[R] seq=4236490899, ack=0, win=0 state=CLOSED rcv_nxt=4236490899, snd_una=2789091866
UnloadTime: 4.260792 ms
Setting up Firebase Auth
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AuthManager:InitializeFirebase()
AuthManager:<Awake>b__12_0(Task`1)
System.Action`1:Invoke(T)
System.Threading.Tasks.ContinuationTaskFromResultTask`1:InnerInvoke()
System.Threading.Tasks.Task:Execute()
System.Threading.Tasks.Task:ExecutionContextCallback(Object)
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.Tasks.Task:ExecuteWithThreadLocal(Task&)
System.Threading.Tasks.Task:ExecuteEntry(Boolean)
System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue:Dispatch()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Using Facebook Unity SDK v8.1.1 with FBiOSSDK/8.2.0
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Facebook.Unity.DebugLogger:Info(String)
Facebook.Unity.FacebookLogger:Info(String)
Facebook.Unity.FB:LogVersion()
Facebook.Unity.CompiledFacebookLoader:Start()

#### [NORMAL LOGIN BUTTON]

Autoconnected Player NullReferenceException: Object reference not set to an instance of an object.
  at AuthManager.Login (System.String _email, System.String _password) [0x00000] in <00000000000000000000000000000000>:0 
  at AuthManager.LoginButton () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityAction.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.InvokableCall.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at Lean.Gui.LeanButton.DoClick () [0x00000] in <00000000000000000000000000000000>:0 
  at Lean.Gui.LeanButton.OnPointerUp (UnityEngine.EventSystems.PointerEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerUpHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1].Invoke (T1 handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchPress (UnityEngine.EventSystems.PointerEventData pointerEvent, System.Boolean pressed, System.Boolean released) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchEvents () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.Process () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.EventSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: currently not available on il2cpp Line: -1)

#### [FACEBOOK LOGIN BUTTON]

Autoconnected Player NullReferenceException: Object reference not set to an instance of an object.
  at AuthManager.loginviaFirebaseFacebook (Facebook.Unity.AccessToken accessToken) [0x00000] in <00000000000000000000000000000000>:0 
  at FacebookInit.authStatusCallback (Facebook.Unity.ILoginResult result) [0x00000] in <00000000000000000000000000000000>:0 
  at Facebook.Unity.FacebookDelegate`1[T].Invoke (T result) [0x00000] in <00000000000000000000000000000000>:0 
  at Facebook.Unity.CallbackManager.TryCallCallback[T] (System.Object callback, Facebook.Unity.IResult result) [0x00000] in <00000000000000000000000000000000>:0 
  at Facebook.Unity.CallbackManager.CallCallback (System.Object callback, Facebook.Unity.IResult result) [0x00000] in <00000000000000000000000000000000>:0 
  at Facebook.Unity.CallbackManager.OnFacebookResponse (Facebook.Unity.IInternalResult result) [0x00000] in <00000000000000000000000000000000>:0 
  at Facebook.Unity.FacebookBase.OnAuthResponse (Facebook.Unity.LoginResult result) [0x00000] in <00000000000000000000000000000000>:0 
  at Facebook.Unity.Mobile.MobileFacebook.OnLoginComplete (Facebook.Unity.ResultContainer resultContainer) [0x00000] in <00000000000000000000000000000000>:0 
  at Facebook.Unity.FacebookGameObject.OnLoginComplete (System.String message) [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

**Comment by Nicokkam** [comment] 2020-12-18 02:59
I Decided to add the codes I am using too. Here they are:

## AuthManager
`using System.Collections;
using UnityEngine;
using Firebase;
using Firebase.Auth;
using TMPro;
using Facebook.Unity;

public class AuthManager : MonoBehaviour
{
  //Firebase variables
  [Header("Firebase")]
  public DependencyStatus dependencyStatus;
  public FirebaseAuth auth;
  public FirebaseUser User;

  //Login variables
  [Header("Login")]
  public TMP_InputField emailLoginField;
  public TMP_InputField passwordLoginField;
  public TMP_Text warningLoginText;
  public TMP_Text confirmLoginText;

  //Register variables
  [Header("Register")]
  public TMP_InputField usernameRegisterField;
  public TMP_InputField emailRegisterField;
  public TMP_InputField passwordRegisterField;
  public TMP_InputField passwordRegisterVerifyField;
  public TMP_Text warningRegisterText;

  void Awake()
  {
    //Check that all of the necessary dependencies for Firebase are present on the system
    FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
    {
      dependencyStatus = task.Result;
      if (dependencyStatus == DependencyStatus.Available)
      {
        //If they are avalible Initialize Firebase
        InitializeFirebase();
      }
      else
      {
        Debug.LogError("Could not resolve all Firebase dependencies: " + dependencyStatus);
      }
    });
  }

  private void InitializeFirebase()
  {
    Debug.Log("Setting up Firebase Auth");
    //Set the authentication instance object
    auth = FirebaseAuth.DefaultInstance;
    auth.StateChanged += AuthStateChanged;
    AuthStateChanged(this, null);
  }

  private void OnDestroy()
  {
    auth.StateChanged -= AuthStateChanged;
    auth = null;
  }

  public void LoginButton()
  {
    Login(emailLoginField.text, passwordLoginField.text);
  }

  public void RegisterButton()
  {
    StartCoroutine(Register(emailRegisterField.text, passwordRegisterField.text, usernameRegisterField.text));
  }

  public void Login(string _email, string _password)
  {
    var LoginTask = auth.SignInWithEmailAndPasswordAsync(_email, _password);
    LoginTask.ContinueWith(task =>
     {
       if (task.IsCanceled || task.IsFaulted)
       {
         Firebase.FirebaseException e =
           task.Exception.Flatten().InnerExceptions[0] as Firebase.FirebaseException;
         GetErrorMessage((AuthError)e.ErrorCode, warningLoginText);
         return;
       }

       if (task.IsCompleted)
       {
         User = LoginTask.Result;
         Debug.LogFormat("User signed in successfully: {0} ({1})", User.DisplayName, User.Email);
         warningLoginText.text = "";
         confirmLoginText.text = "Logged In";
         UIControllerLogin.instance.MainScreenScene();
       }
     });
  }

  public IEnumerator Register(string _email, string _password, string _username)
  {
    if (_username == "")
    {
      //If the username field is blank show a warning
      warningRegisterText.text = "Missing Username";
    }
    else if (passwordRegisterField.text != passwordRegisterVerifyField.text)
    {
      //If the password does not match show a warning
      warningRegisterText.text = "Password Does Not Match!";
    }
    else
    {
      //Call the Firebase auth signin function passing the email and password
      var RegisterTask = auth.CreateUserWithEmailAndPasswordAsync(_email, _password);
      //Wait until the task completes
      yield return new WaitUntil(predicate: () => RegisterTask.IsCompleted);

      if (RegisterTask.Exception != null)
      {
        //If there are errors handle them
        FirebaseException e =
            RegisterTask.Exception.Flatten().InnerExceptions[0] as FirebaseException;
        GetErrorMessage((AuthError)e.ErrorCode, warningRegisterText);
      }
      else
      {
        //User has now been created
        //Now get the result
        User = RegisterTask.Result;

        if (User != null)
        {
          //Create a user profile and set the username
          UserProfile profile = new UserProfile { DisplayName = _username };

          //Call the Firebase auth update user profile function passing the profile with the username
          var ProfileTask = User.UpdateUserProfileAsync(profile);
          //Wait until the task completes
          yield return new WaitUntil(predicate: () => ProfileTask.IsCompleted);

          if (ProfileTask.Exception != null)
          {
            //If there are errors handle them
            Debug.LogWarning(message: $"Failed to register task with {ProfileTask.Exception}");
            FirebaseException firebaseEx = ProfileTask.Exception.GetBaseException() as FirebaseException;
            AuthError errorCode = (AuthError)firebaseEx.ErrorCode;
            warningRegisterText.text = "Username Set Failed!";
          }
          else
          {
            //Username is now set
            //Now return to login screen
            UIControllerLogin.instance.LoginScreenActive();
            warningRegisterText.text = "";
          }
        }
      }
    }
  }

  void AuthStateChanged(object sender, System.EventArgs eventArgs)
  {
    if (auth.CurrentUser != User)
    {
      bool signedIn = User != auth.CurrentUser && auth.CurrentUser != null;
      if (!signedIn && User != null)
      {
        Debug.Log("Signed out " + User.UserId);
        UIControllerLogin.instance.LoginScene();
      }
      User = auth.CurrentUser;
      if (signedIn)
      {
        Debug.Log("Signed in " + User.UserId);
        UIControllerLogin.instance.MainScreenScene();
        string displayName = User.DisplayName ?? "";
        string emailAddress = User.Email ?? "";
        // string photoUrl = User.PhotoUrl ?? "";
        string uid = User.UserId ?? "";
      }
    }
  }

  void GetErrorMessage(AuthError errorCode, TMP_Text INFText)
  {
    string msg = "";
    msg = errorCode.ToString();

    switch (errorCode)
    {
      case AuthError.InvalidEmail:
        INFText.text =
          Lean.Localization.LeanLocalization.GetTranslationText($"Login/InvalidEmailOrPSW");
        print(Lean.Localization.LeanLocalization.GetTranslationText($"Login/InvalidEmailOrPSW"));
        break;

      case AuthError.WrongPassword:
        INFText.text =
          Lean.Localization.LeanLocalization.GetTranslationText($"Login/InvalidEmailOrPSW");
        print(Lean.Localization.LeanLocalization.GetTranslationText($"Login/InvalidEmailOrPSW"));
        break;

      case AuthError.AccountExistsWithDifferentCredentials:
        INFText.text =
          Lean.Localization.LeanLocalization.GetTranslationText($"Login/DiffCredentials");
        print(Lean.Localization.LeanLocalization.GetTranslationText($"Login/DiffCredentials"));
        break;

      case AuthError.MissingPassword:
        INFText.text =
          Lean.Localization.LeanLocalization.GetTranslationText($"Login/MissingPSW");
        print(Lean.Localization.LeanLocalization.GetTranslationText($"Login/MissingPSW"));
        break;

      case AuthError.MissingEmail:
        INFText.text =
          Lean.Localization.LeanLocalization.GetTranslationText($"Login/MissingEmail");
        print(Lean.Localization.LeanLocalization.GetTranslationText($"Login/MissingEmail"));
        break;

      case AuthError.EmailAlreadyInUse:
        INFText.text =
          Lean.Localization.LeanLocalization.GetTranslationText($"Login/EmailInUse");
        print(Lean.Localization.LeanLocalization.GetTranslationText($"Login/EmailInUse"));
        break;

      case AuthError.TooManyRequests:
        INFText.text =
          Lean.Localization.LeanLocalization.GetTranslationText($"Login/ManyRequests");
        print(Lean.Localization.LeanLocalization.GetTranslationText($"Login/ManyRequests"));
        break;

      case AuthError.SessionExpired:
        INFText.text =
                  Lean.Localization.LeanLocalization.GetTranslationText($"Login/SessionExpired");
        print(Lean.Localization.LeanLocalization.GetTranslationText($"Login/SessionExpired"));
        break;

      case AuthError.WeakPassword:
        INFText.text =
          Lean.Localization.LeanLocalization.GetTranslationText($"Login/WeakPSW");
        print(Lean.Localization.LeanLocalization.GetTranslationText($"Login/WeakPSW"));
        break;

      case AuthError.UserNotFound:
        INFText.text =
          Lean.Localization.LeanLocalization.GetTranslationText($"Login/UserNotFound");
        print(Lean.Localization.LeanLocalization.GetTranslationText($"Login/UserNotFound"));
        break;

      default:
        print($"errorCode: {msg}");
        break;
    }

  }

  public void loginviaFirebaseFacebook(AccessToken accessToken)
  {
    Firebase.Auth.Credential credential =
        Firebase.Auth.FacebookAuthProvider.GetCredential(accessToken.TokenString);
    auth.SignInWithCredentialAsync(credential).ContinueWith(task =>
    {
      if (task.IsCanceled)
      {
        Debug.LogError("SignInWithCredentialAsync was canceled.");
        warningLoginText.text = "SignInWithCredentialAsync was canceled";
        return;
      }
      if (task.IsFaulted)
      {
        Debug.LogError($"SignInWithCredentialAsync encountered an error: {task.Exception}");
        warningLoginText.text = $"SignInWithCredentialAsync encountered an error: {task.Exception}";

        return;
      }

      User = task.Result;
      Debug.LogFormat("User signed in successfully: {0} ({1})", User.DisplayName, User.UserId);
      UIControllerLogin.instance.MainScreenScene();
    });
  }

}
`

## FBManager

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Firebase.Auth;
using Facebook.Unity;

public class FacebookInit : MonoBehaviour
{
  private AuthManager AuthManagercs;

  // Start function from Unity's MonoBehavior
  void Start()
  {
    AuthManagercs = GetComponent<AuthManager>();

    if (!FB.IsInitialized)
    {
      FB.Init(initCallback, onHideUnity);
    }
    else
    {
      // Already initialized
      FB.ActivateApp();
    }
  }

  private void initCallback()
  {
    if (FB.IsInitialized)
    {
      // Signal an app activation App Event
      FB.ActivateApp();
      // Continue with Facebook SDK
      // ...
    }
    else
    {
      Debug.Log("Something went wrong to Initialize the Facebook SDK");
    }
  }

  private void onHideUnity(bool isGameScreenShown)
  {
    if (!isGameScreenShown)
    {
      // Pause the game - we will need to hide
      Time.timeScale = 0;
    }
    else
    {
      // Resume the game - we're getting focus again
      Time.timeScale = 1;
    }
  }

  public void FacebookButton()
  {
    // Permission option list https://developers.facebook.com/docs/facebook-login/permissions/
    var permissons = new List<string>()
        {"email",
        // "user_birthday",
        // "user_friends",
        "public_profile"};
    FB.LogInWithReadPermissions(permissons, authStatusCallback);
  }

  private void authStatusCallback(ILoginResult result)
  {
    if (FB.IsLoggedIn)
    {
      // AccessToken class will have session details
      AccessToken accessToken = Facebook.Unity.AccessToken.CurrentAccessToken;
      // current access token's User ID : aToken.UserId
      AuthManagercs.loginviaFirebaseFacebook(accessToken);
    }
    else
    {
      Debug.Log("User cancelled login");
    }
  }

}
`

**Comment by paradizIscool** [comment] 2020-12-18 08:28
From my experience, everything is in the main thread in editor, but not on devices, so ensure you're in the main thread with ContinueWithOnMainThread for example. 
Next, use sdk 6.16.1.
And finally, use the debugger to know what is null and understand what's happening on the device and what is null exactly.

**Comment by Nicokkam** [comment] 2020-12-18 13:27
@paradizIscool

This is very confusing to me. Where can I see the SDK version? I downloaded it from the Firebase website as I was following the tutorial, so it must be in the last version.

I have no idea how that function works, so I'll start researching it to try to understand. In the meanwhile, if you have some time, could you explain it to me?

For the last suggestion you made, that is the problem. Even if I find what is null, it only happens in the device, so I have no idea what to do in order to fix it....

**Comment by paradizIscool** [comment] 2020-12-18 15:44
This is very confusing for me too :)

Release notes are here [https://firebase.google.com/support/release-notes/unity](url)

But some releases are unusable. Just take a look at bug reports.

I haven't test 7.0.1  but I see lots of regression in the bug report. I tested 7.0.0 which did not compile, 6.16.0 did not compile either, 6.16.1 did compile, but I had to find some workarounds and report a couple of bugs (fixed now but not released).

**Comment by EdreHM** [comment] 2020-12-18 16:10
@Nicokkam
 
For download old versions:
https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_a.b.c.zip
 
For example:
https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_6.16.1.zip

**Comment by DellaBitta** [comment] 2020-12-21 15:36
When it comes to library interdependencies on auth login flows I find it easier to create building blocks in isolated apps.  There are a couple of things that stand out to me as a good way to move forward debugging this issue. 

1. Is there any chance that you're moving between scenes?  I've noticed that the Firebase init code is in `Awake()`.  I recommend following [patm1987@'s example of a safe way to this](https://github.com/firebase/quickstart-unity/issues/429#issuecomment-523121932).

1. I notice in the Facebook login flow that the logged errors seem entirely in their SDK. It might be worth isolating usage of that SDK (create a standalone flow without importing any Firebase dependencies) and see if it returns an error-free token back on iOS.  Additionally log the token so that you can visually validate it.  If any errors occur in this process then it would be worth sending them to Facebook support since we don't have much visibility into their SDK.
 
1. For the Firebase Login via Email, I likewise recommend creating a stand alone example without importing the Facebook SDK into your project.  Additionally it's worth logging the email and password just before invoking `SignInWithEmailAndPasswordAsync()` to ensure they're the values you expect. Also put a log at the top of the continuation to see if it's ever invoked.  If you have any issues there then please post them here.

1. After that, it would be interesting to try to isolate any conflicts between the SDKs.  That is, if you are able to get a Facebook token back from their SDK then the next step would be to import the Firebase Auth unity package  -- but don't invoke any Firebase APIs directly yet.  Simply import it.  Does the Facebook SDK still return a valid token?  Also vice versa: with the Firebase login with email and password standalone app.  Does simply importing the Facebook SDK have any side effects on the Firebase app?

I hope this helps!

**Comment by DellaBitta** [comment] 2020-12-21 17:54
Hi @Nicokkam,

Also, I wonder if this is all related to the use_frameworks! issue for iOS #862.  

Are you only ever experiencing the problem on iOS, and do you see a `use_frameworks!` the podfile of your XCode project?

Thanks.

**Comment by Nicokkam** [comment] 2020-12-23 02:20
Hello @DellaBitta,

Sorry for the delay of answering this thread. I'll be looking into the point's you listed above and will provide you a feedback of the results!

**Comment by Nicokkam** [comment] 2020-12-23 03:42
> 1. Is there any chance that you're moving between scenes?  I've noticed that the Firebase init code is in `Awake()`.  I recommend following [patm1987@'s example of a safe way to this](https://github.com/firebase/quickstart-unity/issues/429#issuecomment-Y23121932).

Yes, I am moving between scenes. I have just implemented Patrick's example to my project and it continued working as it was on my editor (will build it and test it on my iPhone and add an EDIT) but it started to point out one error to both login methods (email and facebook) only when I logged in one time, logged out and then tried to login again:
 
**NullReferenceException: Object reference not set to an instance of an object.**

I believe it is because I commented out the following part of my code and used the OnFirebaseInitialized UnityEvent within Patrick's code to call the InitializeFirebase() method within my code (described above).

void Awake() 
 {
  FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
   {
    dependencyStatus = task.Result;
    if (dependencyStatus == DependencyStatus.Available)
     {
      InitializeFirebase();
      }
    else 
     {
      Debug.LogError("Could not resolve all Firebase dependencies: " + dependencyStatus);
      }
});
}

**Comment by Nicokkam** [comment] 2020-12-23 03:47
> Hi @Nicokkam,
> 
> Also, I wonder if this is all related to the `use_frameworks!` issue for iOS #862.
> 
> Are you only ever experiencing the problem on iOS, and do you see a `use_frameworks!` the podfile of your XCode project?
> 
> Thanks.

I was just focusing on iOS for now, given that I have an iPhone. I am going to test it out on an Emulator within Android Studio and then I will let you know.

**Comment by vimanyu** [comment] 2020-12-30 19:00
Hi @Nicokkam,
Is it possible for you to create a simple minimal reproducible sample for this?
It will be awesome and will help us debug faster if you can try this out in our Unity quickstart examples and build on top of that.

**Comment by chkuang-g** [comment] 2021-01-08 01:21
@Nicokkam 

I wonder if your problem can be resolved with this workaround.
https://github.com/firebase/quickstart-unity/issues/862#issuecomment-752945417

I've been looking into issues related to `use_frameworks!` and `target 'Unity-iPhone'`, and seems like Firebase Unity SDK does not handle well with them. Those lines are added by [Facebook SDK here](https://github.com/facebook/facebook-sdk-for-unity/blob/4456caa9d40f31568297d7b5c92b354a9380da71/Facebook.Unity.Editor/FacebookPostprocess.cs#L33).

Please let us know.  This would help us to resolve these series of issues related to Xcode.

**Comment by Nicokkam** [comment] 2021-01-12 19:29
> Hi @Nicokkam,
> Is it possible for you to create a simple minimal reproducible sample for this?
> It will be awesome and will help us debug faster if you can try this out in our Unity quickstart examples and build on top of that.

Hello @vimanyu and @chkuang-g,

I am dedicating my time on other issues for the time being because this was taking a lot of my development time. I intend to return to this soon and I will let you know.
What I can say is that I added Firebase and Facebook SDK's (both in the latest version) in my project and followed the manual of both providers. Regarding Firebase packages, I had imported the Analytics and the Auth one's.

**Comment by chkuang-g** [comment] 2021-01-12 19:52
No problem.

I posted a slightly long comment here https://github.com/firebase/quickstart-unity/issues/862#issuecomment-758893827 about my findings.  I think this is the cause of your issue.

Please take a look when you have time.

For management purpose, I will close this issue for now.  Please follow #862 for future updates!

**Closed** 2021-01-12 19:52 UTC
Labels: api: core, edm4u, needs-info
