### ISSUE TITLE
Buggy connection to Firebase server.

### ISSUE THREAD

**Issue by criistii** [firebase/quickstart-unity#166] opened 2018-06-04 12:43 UTC
Hi,
I am struggling with a very weird bug:
On both iOS and Android devices, the connection to the Firebase fails. I am getting no error message, and is seems kind of random.
One way I managed to reproduce the issue: Exactly after a successful transfer, I disable and re-enable the WIFI connection. When I try the same call again, everything seams dead for 2-3 minutes. After that the data is retrieved.
I had similar issues in the editor, and they got fixed after resetting the Router.
My guess is that the issue is a Socket issue or something similar. Firebase gets stuck in an invalid connection to the server.

My questions are:
1. Is there a fix for this?
2. Is there a way to get a better debug log on a device so I can figure out what is going on?

Thanks,

**Comment by stewartmiles** [comment] 2018-06-04 16:09
@criistii is this a duplicate of #106 ?  We don't have a workaround yet, though we should have a replacement for the mobile implementation of the RT DB very soon that uses native (i.e system rather than .NET) networking, we're debugging the last few issues.

**Comment by criistii** [comment] 2018-06-04 16:14
Yes, it seems to be the same issue. The lack of connectivity is pretty random. It both worked and failed on WIFI and 4G.

**Comment by stewartmiles** [comment] 2018-06-04 16:15
Ok I'll close this as a duplicate of #106 .  We don't have any solutions at the moment.

**Closed by stewartmiles** 2018-06-04 16:15 UTC
