### ISSUE TITLE
Firebase cloud message not work with google play games services plugin

### ISSUE THREAD

**Issue by mtoanhcm** [firebase/quickstart-unity#188] opened 2018-07-19 08:14 UTC
Hi everyone, I used Firebase analytics, firebase remote config with google play services plugin in my game and everything worked well. But when I implemented Firebase clouse message, it did not work (cannot receive any tokenId or message from firebase). 

I created an empty project, only use firebase message and it work well, but when i add google play services plugin, it did not work anymore.

I'm using google player services 0.9.50 and firebase 5.1.1. All dependency libraries (only Google play services plugin and Firebase cloud message plugin) are:
com.google.firebase.firebase-app-unity-5.1.0n
com.google.firebase.firebase-common-16.0.0
com.google.firebase.firebase-iid-16.2.0
com.google.firebase.firebase-messaging-unity-5.1.0
com.google.games.gpgs-plugin-support-0.9.50
android.arch.core.common-1.0.0
android.arch.lifecycle.common-1.0.0
android.arch.lifecycle.runtime-1.0.0
com.android.support.support-annotations-26.1.0
com.android.support.support-compat-26.1.0
com.android.support.support-core-ui-26.1.0
com.android.support.support-core-utils-26.1.0
com.android.support.support-fragment-26.1.0
com.android.support.support-media-compat-26.1.0
com.android.support.support-v4-26.1.0
com.google.android.gms.play-services-ads-identifier-15.0.1
com.google.android.gms.play-services-auth-15.0.1
com.google.android.gms.play-services-auth-api-phone-15.0.1
com.google.android.gms.play-services-auth-base-15.0.1
com.google.android.gms.play-services-base-15.0.1
com.google.android.gms.play-services-basement-15.0.1
com.google.android.gms.play-services-drive-15.0.1
com.google.android.gms.play-services-games-15.0.1
com.google.android.gms.play-services-measurement-base-16.0.0
com.google.android.gms.play-services-nearby-15.0.1
com.google.android.gms.play-services-stats-15.0.1
com.google.android.gms.play-services-tasks-15.0.1
com.google.firebase.firebase-analytics-16.0.1
com.google.firebase.firebase-analytics-impl-16.1.1
com.google.firebase.firebase-core-16.0.1
com.google.firebase.firebase-iid-interop-16.0.0
com.google.firebase.firebase-measurement-connector-16.0.0
com.google.firebase.firebase-measurement-connector-impl-16.0.1
com.google.firebase.firebase-messaging-17.1.0
libmessaging_unity_player_activity

**Comment by stewartmiles** [comment] 2018-07-19 21:48
@mtoanhcm what is the Google Play Services plugin you're referring to?

**Comment by mtoanhcm** [comment] 2018-07-20 02:11
@stewartmiles I'm using plugin from this:
[https://github.com/playgameservices/play-games-plugin-for-unity](url)
with lastest version 0.9.50

**Comment by stewartmiles** [comment] 2018-07-20 14:37
@claywilkinson FYI

@mtoanhcm when you say it isn't working, what isn't working?  Is there a build error, does the application when built not run?   Could you share some logs?

**Comment by mtoanhcm** [comment] 2018-07-21 05:52
@stewartmiles I fixed all dependency libraries issue when use both goolg play plugin and fire base cloud message plugin, my game build and run success with no error in logcat. But I cannot receive any token or message (I received it success when use only Firebase cloud message plugin)

**Comment by stewartmiles** [comment] 2018-07-23 21:31
@DeusExMachina1993 and @mtoanhcm if you're using Unity 2018 it's possible this is related a regression we had in AndoridManifest.xml variable replacement in 5.1.0, give the Firebase Unity [5.2.0](https://firebase.google.com/support/release-notes/unity#5.2.0) SDK a try.

w.r.t conflicting dependencies, we now will pin all explicitly specified dependencies to the specified version in the [Android Resolver](https://github.com/googlesamples/unity-jar-resolver) which is going to break some folks who are using plugins with conflicting components and fix others with conflicting transitive dependencies.  In your case for any library that is specified multiple times (i.e by both Firebase and Google Play Games Services) it will pick the most recent version of the two and try resolving again, which *may* work depending upon whether any breaking API changes have been applied to either Android SDK. @claywilkinson any idea when the Google Play Games Services plugin will be updated?

**Comment by mtoanhcm** [comment] 2018-07-24 13:38
Greate, Firebase version 5.2.0 fixed my issues, very thanks for your support @stewartmiles

**Closed** 2018-07-24 23:52 UTC
Labels: help wanted

**Comment by ImranZahid** [comment] 2018-09-12 09:45
@mtoanhcm Hello guys, I am having similar issue. I am using Firebase cloud messaging 5.2.1 with GPGS 0.9.5 in unity 4.7.2. My app is getting Firebase registration token and signing in in GPGS properly but the moment I add this line 'RequestServerAuthCode(false)' to request server auth code it crashes

`FATAL EXCEPTION: main
                                                 Process: com.appname, PID: 2924
                                                 java.lang.Error: FATAL EXCEPTION [main]
                                                 Unity version     : 4.7.2f1
                                                 
                                                 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/signin/internal/SignInHubActivity;
                                                     at com.google.android.gms.auth.api.signin.internal.zzh.zzc(Unknown Source)
                                                     at com.google.android.gms.auth.api.signin.internal.zzf.getSignInIntent(Unknown Source)
                                                     at com.google.games.bridge.TokenFragment$2.onResult(TokenFragment.java:304)
                                                     at com.google.games.bridge.TokenFragment$2.onResult(TokenFragment.java:295)
                                                     at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage(Unknown Source)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

If I remove Firebase from project then it works and I get server auth code as well. Any idea?

**Comment by pancar** [comment] 2018-11-20 21:35
@stewartmiles how can i download firebase old builds?

**Comment by stewartmiles** [comment] 2018-11-20 21:42
@pancar old builds are available via https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_VERSION.zip e.g https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_5.4.2.zip
