### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6.1.1': The specified module could not be found.

### ISSUE THREAD

**Issue by Vah94** [firebase/quickstart-unity#395] opened 2019-06-24 12:08 UTC
Unity editor version: 2018.4.0f1
Firebase Unity SDK version: 6.1.1
Firebase plugins in use (Analytics, Crashlytics):
Additional SDKs you are using (Facebook, Applovin):
Platform you are using the Unity editor on (Mac, Windows):
Platform you are targeting (Android):

**

> On turn on Stripting backend from "Mono" to"IL2CPP" and set ARM64 also. On start it crashed.

**

`DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6.1.1': The specified module could not be found.

Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil (Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate applicationDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate arithmeticDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate divideByZeroDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate indexOutOfRangeDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate invalidCastDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate invalidOperationDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate ioDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate nullReferenceDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate outOfMemoryDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate overflowDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate systemExceptionDelegate) (at <00000000000000000000000000000000>:0)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at <00000000000000000000000000000000>:0)
Firebase.AppUtilPINVOKE..cctor () (at <00000000000000000000000000000000>:0)
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at <00000000000000000000000000000000>:0)
Firebase.LogUtil..cctor () (at <00000000000000000000000000000000>:0)
Firebase.FirebaseApp..cctor () (at <00000000000000000000000000000000>:0)
GameName.Controllers.FireBaseAnalyticsManager..ctor () (at <00000000000000000000000000000000>:0)
GameName.Controllers.AnalyticsManager..ctor (GameName.Controllers.DataManager dataManager, System.Boolean isEnabled) (at <00000000000000000000000000000000>:0)
GameName.Controllers.GameController.CreateManagers () (at <00000000000000000000000000000000>:0)
GameName.Controllers.GameController.Awake () (at <00000000000000000000000000000000>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE.SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at <00000000000000000000000000000000>:0)
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at <00000000000000000000000000000000>:0)
Firebase.LogUtil..cctor () (at <00000000000000000000000000000000>:0)
Firebase.FirebaseApp..cctor () (at <00000000000000000000000000000000>:0)
GameName.Controllers.FireBaseAnalyticsManager..ctor () (at <00000000000000000000000000000000>:0)
GameName.Controllers.AnalyticsManager..ctor (GameName.Controllers.DataManager dataManager, System.Boolean isEnabled) (at <00000000000000000000000000000000>:0)
GameName.Controllers.GameController.CreateManagers () (at <00000000000000000000000000000000>:0)
GameName.Controllers.GameController.Awake () (at <00000000000000000000000000000000>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at <00000000000000000000000000000000>:0)
Firebase.LogUtil..cctor () (at <00000000000000000000000000000000>:0)
Firebase.FirebaseApp..cctor () (at <00000000000000000000000000000000>:0)
GameName.Controllers.FireBaseAnalyticsManager..ctor () (at <00000000000000000000000000000000>:0)
GameName.Controllers.AnalyticsManager..ctor (GameName.Controllers.DataManager dataManager, System.Boolean isEnabled) (at <00000000000000000000000000000000>:0)
GameName.Controllers.GameController.CreateManagers () (at <00000000000000000000000000000000>:0)
GameName.Controllers.GameController.Awake () (at <00000000000000000000000000000000>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.

Firebase.FirebaseApp..cctor () (at <00000000000000000000000000000000>:0)
GameName.Controllers.FireBaseAnalyticsManager..ctor () (at <00000000000000000000000000000000>:0)
GameName.Controllers.AnalyticsManager..ctor (GameName.Controllers.DataManager dataManager, System.Boolean isEnabled) (at <00000000000000000000000000000000>:0)
GameName.Controllers.GameController.CreateManagers () (at <00000000000000000000000000000000>:0)
GameName.Controllers.GameController.Awake () (at <00000000000000000000000000000000>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
GameName.Controllers.FireBaseAnalyticsManager..ctor () (at <00000000000000000000000000000000>:0)
GameName.Controllers.AnalyticsManager..ctor (GameName.Controllers.DataManager dataManager, System.Boolean isEnabled) (at <00000000000000000000000000000000>:0)
GameName.Controllers.GameController.CreateManagers () (at <00000000000000000000000000000000>:0)
GameName.Controllers.GameController.Awake () (at <00000000000000000000000000000000>:0)`

`DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6.1.1': The specified module could not be found.

Firebase.AppUtilPINVOKE.SetLogFunction (Firebase.LogUtil+LogMessageDelegate jarg1) (at <00000000000000000000000000000000>:0)
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at <00000000000000000000000000000000>:0)
Firebase.LogUtil.Finalize () (at <00000000000000000000000000000000>:0)`

How it used.
`using System;
using System.Collections.Generic;
using System.Linq;
using Firebase;
using UnityEngine;
using UnityEngine.Purchasing;

namespace Cats.Controllers
{
    public class FireBaseAnalyticsManager : BaseAnalyticsManager
    {
        public FireBaseAnalyticsManager()
        {
            if (FirebaseApp.CheckDependencies() != DependencyStatus.Available)
            {
                FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => { Initialize(); });
            }
            else
            {
                Initialize();
            }
        }

        private void Initialize()
        {
            var dependencyStatus = FirebaseApp.CheckDependencies();
            if (dependencyStatus == Firebase.DependencyStatus.Available)
            {
                IsInitialized = true;
                Firebase.Analytics.FirebaseAnalytics.LogEvent(Firebase.Analytics.FirebaseAnalytics.EventAppOpen);
            }
            else
            {
                UnityEngine.Debug.LogError($"Could not resolve all Firebase dependencies: {dependencyStatus}");
            }
        }

        protected override void FireLogEvent(string eventName = "")
        {
            Firebase.Analytics.FirebaseAnalytics.LogEvent(eventName);
        }

        protected override void FireTrackPurchase(PurchaseEventArgs args)
        {
            FireLogEvent(args.purchasedProduct.definition.id);
        }

        protected override void FireHardCurrencyProfit(string eventName, double hardCurrency)
        {
            Firebase.Analytics.FirebaseAnalytics.LogEvent(
                eventName,
                Firebase.Analytics.FirebaseAnalytics.ParameterValue,
                hardCurrency);
        }

        protected override void FireLogEventWithParameter(string eventName, Dictionary<string, string> eventParams)
        {
            List<KeyValuePair<string, string>> paramList = eventParams.ToList();
            var par = new Firebase.Analytics.Parameter[paramList.Count];

            for (int i = 0; i < paramList.Count; i++)
            {
                par[i] = new Firebase.Analytics.Parameter(paramList[i].Key, paramList[i].Value);
            }

            Firebase.Analytics.FirebaseAnalytics.LogEvent(eventName, par);
        }
    }
}`

**Comment by SameelNawaz** [comment] 2019-06-24 16:24
https://github.com/googlesamples/unity-jar-resolver
Try updating to newer Version Resolver and do Force Resolve.

**Comment by stewartmiles** [comment] 2019-06-25 22:16
As @takaaptech discovered there was a bug in the Android Resolver when using the mainTemplate.gradle patching method that caused local repos to be ignored if the path to the Unity project contained characters that needed to be URI escaped.  See https://github.com/googlesamples/unity-jar-resolver/issues/240

This is fixed in v1.2.120 available [here](https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.120), please ping this bug if updating the Play Services Resolver plugin doesn't fix your issue.

**Comment by Vah94** [comment] 2019-07-03 10:39
DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6.2.0': The specified module could not be found.

**Comment by stewartmiles** [comment] 2019-07-03 15:56
@Vah94 before posting partial logs, could you reproduce the issue with a sample project in this repository.  There are loads of reasons why this could be failing for you, e.g if your project doesn't compile in editor mode the editor plugins can't run.  You should also set the Version Handler, Android Resolver and iOS Resolver plugins to their default settings via the settings menu under `Assets > Play Services Resolver`.

**Comment by moathab** [comment] 2019-07-09 00:20
I am facing the same error when i first run my authentication script. then when i try to log in i receive an error saying:
 NullReferenceException: Object reference not set to an instance of an object
Firebase.Sample.Auth.LoginHandler.SigninWithEmailAsync () (at Assets/Scripts/LoginHandler.cs:308).......

**Comment by chkuang-g** [comment] 2019-07-25 21:15
@Vah94 It has been awhile since we last heard from you.
I will close this issue.  Please let us know if this issue is still happening.

**Closed by chkuang-g** 2019-07-25 21:15 UTC
Labels: help wanted
