### ISSUE TITLE
OnMessageReceived not called when app in background

### ISSUE THREAD

**Issue by nodexpertsdev** [firebase/quickstart-unity#316] opened 2019-02-19 09:04 UTC
## Please fill in the following fields:
Unity editor version: 2018.2.7.f1
Firebase Unity SDK version: 5.4.4
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
When the app is in background, OnMessageReceived event is not fired. As soon as we bring the app back to foreground, OnMessageReceived gets fired.
My scenario is "I wanted to customize the notification before sending it". When I use "notification" instead of "data", the notification appears in the tray but I want to use "OnMessageReceived" (which gets fired only when we use "data" in the payload I think)

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes, I just downloaded the sample app from "quickstart-unity/messaging" and it doesn't fire OnMessageReceived event when the app is in background but fires when app is brought back to foreground.

Please help!

**Comment by chkuang-g** [comment] 2019-02-21 19:09
Duplicate of #311

**Comment by stewartmiles** [comment] 2019-02-26 22:59
@alexames FYI

OnMessageReceived is called from the main thread (via the "Firebase Services" mono behavior) which isn't executed while the app is in the background unless you unpause the application.

If you want to customize the message you should do so by overriding the Android messaging service.

It's not clear from the [Unity guide](https://firebase.google.com/docs/cloud-messaging/unity/client) but the Unity SDK is built on top of the C++ SDK.  You can therefore customize message handling by following these instructions:
https://firebase.google.com/docs/cloud-messaging/cpp/client#custom_message_handling_on_android

**Closed by stewartmiles** 2019-02-26 22:59 UTC
Labels: help wanted
