### ISSUE TITLE
-[FIRRemoteConfig activateWithCompletionHandler:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by ChinaChong** [firebase/quickstart-unity#871] opened 2020-11-18 13:30 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.8f1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: RemoteConfig
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: AdMob v7.67.1
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Firebase/RemoteConfig Unity SDK version: 6.16.1 call the method -[FIRRemoteConfig activateWithCompletionHandler:] no longer support in the Firebase iOS SDK Version 7.x

2020-11-18 16:07:03.913954+0800 myApp[33919:7097676] Uncaught exception: NSInvalidArgumentException: -[FIRRemoteConfig activateWithCompletionHandler:]: unrecognized selector sent to instance 0x283350320
(
	0   CoreFoundation                      0x00000001882ba5c0 52963DBA-FA89-36C2-8262-28B9776F8C12 + 1185216
	1   libobjc.A.dylib                     0x000000019c3a842c objc_exception_throw + 60
	2   CoreFoundation                      0x00000001881c4a2c 52963DBA-FA89-36C2-8262-28B9776F8C12 + 178732
	3   CoreFoundation                      0x00000001882bd130 52963DBA-FA89-36C2-8262-28B9776F8C12 + 1196336
	4   CoreFoundation                      0x00000001882bf420 _CF_forwarding_prep_0 + 96
	5   myApp                           0x000000010689c564 _ZN8firebase13remote_config15ActivateFetchedEv + 188
	6   myApp                           0x000000010689cfbc Firebase_RemoteConfig_ActivateFetched + 12
	7   myApp                           0x0000000106e09dec FirebaseRemoteConfig_ActivateFetched_m3175890215DD50AFAF69949FE316CD0F91AABC4A + 84
	8   myApp                           0x0000000106c5ef08 CrashlyticsInit_U3CStartU3Eb__0_0_m89F92C95E73D908822A9869CBE6B5B93F41731AE + 1084
	9   myApp                           0x0000000106f1fd6c Action_1_Invoke_mB86FC1B303E77C41ED0E94FC3592A9CF8DA571D5_gshared + 300
	10  myApp                           0x0000000107539f34 Task_Execute_mF91032F33896912C3A3CC6A568220EBC5D439CFF + 152
	11  myApp                           0x000000010752cd00 ContextCallback_Invoke_m76E65E7A67AA99858554F451E0F78E22B6478998 + 440
	12  myApp                           0x000000010752dfac ExecutionContext_RunInternal_m5BF955CE8B04D9A7C959B9011579CC0FABD5FC56 + 316
	13  myApp                           0x000000010753a5e8 Task_ExecuteWithThreadLocal_mFF23F3F9C0796B0EE2AC70CB51AD7D2A2867D733 + 348
	14  myApp                           0x000000010753a428 Task_ExecuteEntry_mA04E6FA3370CA2AB19B6AB209E44E993B14621F1 + 300
	15  myApp                           0x0000000107543578 ThreadPoolWorkQueue_Dispatch_mCDF7415E4C9D02B34761CAE8EA15CD33DDF85ADF + 732
	16  myApp                           0x0000000104c94480 _Z67RuntimeInvoker_FalseSByte_t9070AEA2966184235653CB9B4D33B149CDA831DFPFvvEPK10MethodInfoPvPS4_ + 32
	17  myApp                           0x00000001068529f0 _ZL13worker_threadPv + 276
	18  myApp                           0x0000000106874de4 _ZN6il2cpp2vmL11ThreadStartEPv + 80
	19  myApp                           0x0000000106853d38 _ZN6il2cpp2os6Thread10RunWrapperEPv + 88
	20  myApp                           0x0000000106856044 _ZN6il2cpp2os10ThreadImpl18ThreadStartWrapperEPv + 40
	21  libsystem_pthread.dylib             0x00000001d01a9ca8 _pthread_start + 320
	22  libsystem_pthread.dylib             0x00000001d01b2788 thread_start + 8
)

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Use Firebase/RemoteConfig Unity SDK version: 6.16.1，and export Xcode project，update the RemoteConfig to v7.x

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

Update the Firebase/RemoteConfig Unity SDK，do not call -[FIRRemoteConfig activateWithCompletionHandler:] anymore，it was deprecated.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by cynthiajoan** [comment] 2020-11-18 19:02
Duplicate of #846 , will close this one, please refer to the other issue for update.

**Closed by cynthiajoan** 2020-11-18 19:02 UTC
Labels: api: remoteconfig, new

**Comment by ChinaChong** [comment] 2020-11-19 03:38
> Duplicate of #846 , will close this one, please refer to the other issue for update.

It is not a problem of version dependency. The methods in the iOS SDK have been deprecated but the Unity SDK is still calling the deprecated methods.

**Comment by ChinaChong** [comment] 2020-11-19 03:44
It is not a problem of version dependency. The methods in the iOS SDK have been deprecated but the Unity SDK is still calling the deprecated methods.

**Comment by ChinaChong** [comment] 2020-11-19 03:46
> Duplicate of #846 , will close this one, please refer to the other issue for update.

It is not a problem of version dependency. The methods in the iOS SDK have been deprecated but the Unity SDK is still calling the deprecated methods.

**Comment by cynthiajoan** [comment] 2020-11-20 22:34
Hi @ChinaChong, it depends on if you did anything specifically to upgrade ios sdk or relies on resolving to find the dependent ios sdk version. We are aware of the sdk deprecation and the next Unity release will address the issue. However, based on the dup issue #846 , we are not expecting the resolver to upgrade to more advanced version that contains breaking change with the current unity sdk.
