### ISSUE TITLE
[Bug] Please remove errors & warning about DATABASE_URL when we don't use Realtime Database

### ISSUE THREAD

**Issue by Morgan-6Freedom** [firebase/quickstart-unity#1105] opened 2021-08-05 14:59 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: UnityPackage
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: Auth
  * Platform you are using the Unity editor on: Windows 
  * Platform you are targeting: Android
   * Scripting Runtime: Il2CPP
   
### [REQUIRED] Please describe the issue here:

If I don't use a Realtime Database, I have 2 warnings & 1 Error when I press play or recompile or open the project.

![image](https://user-images.githubusercontent.com/49686866/128372866-fdcd7e08-1ac7-435c-9211-82358ebe8c0d.png)
![image](https://user-images.githubusercontent.com/49686866/128372148-a2e6fcd1-3261-4a8b-bb91-bb21077bf9ac.png)
![image](https://user-images.githubusercontent.com/49686866/128372167-d6d9cfd6-5b2d-4793-8732-01845338d006.png)
![image](https://user-images.githubusercontent.com/49686866/128372839-30c8d8e6-07ee-47db-8f98-3c8310e07ae6.png)

I think thoses Log are confusing and shouldn't warn the user if they doesn't use a firebase realtime database. because, actually, it is totally fine to have a GoogleService-info without a database URL if you don't use Realtime Database.

#### Steps to reproduce:
1) have a project on Firebase Console
2) Do not use a Realtime Database
3) Download the google-services & info
4) put them on an empty unity project
5) press play

100%.

**Comment by DellaBitta** [comment] 2021-08-05 16:16
Hi @Morgan-6Freedom, 

I believe this is a duplicate of #892 which we're already tracking. I'm going to close this issue but feel free to re-open it if you think I've done so in error.  Thanks!

**Closed** 2021-08-05 16:16 UTC
Labels: duplicate, type: question, api: database
