### ISSUE TITLE
build with 6.0.0 fails with More than one file was found with OS independent path 'lib/armeabi-v7a/libFirebaseCppApp-6.0.0.so'

### ISSUE THREAD

**Issue by gabetoth-dgh** [firebase/quickstart-unity#377] opened 2019-06-07 09:59 UTC
## Please fill in the following fields:
Unity editor version: 2018.2.21f1
Firebase Unity SDK version: 6.0.0
Firebase plugins in use (Auth, Database, etc.): Auth, Messaging, Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): IronSource
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
Add Firebase to project, target architectures: armv7, arm64. 5.6.1 worked, but had [this bug](https://github.com/firebase/quickstart-unity/issues/374).

Error: 
`CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_181\bin\java.exe -classpath "C:\Program Files\Unity_18.2.21f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.2.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformNativeLibsWithMergeJniLibsForRelease'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libFirebaseCppApp-6.0.0.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
]
stdout[
Starting a Gradle Daemon, 3 stopped Daemons could not be reused, use --status for details
Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
:preBuild UP-TO-DATE
:Firebase:preBuild UP-TO-DATE
:Firebase:preReleaseBuild UP-TO-DATE
:Firebase:checkReleaseManifest
:Firebase:processReleaseManifest
:GooglePlayGamesManifest.plugin:preBuild UP-TO-DATE
:GooglePlayGamesManifest.plugin:preReleaseBuild UP-TO-DATE
:GooglePlayGamesManifest.plugin:checkReleaseManifest
:GooglePlayGamesManifest.plugin:processReleaseManifest
:IronSource:preBuild UP-TO-DATE
:IronSource:preReleaseBuild UP-TO-DATE
:IronSource:checkReleaseManifest
:IronSource:processReleaseManifest
:unity-android-resources:preBuild UP-TO-DATE
:unity-android-resources:preReleaseBuild UP-TO-DATE
:unity-android-resources:checkReleaseManifest
:unity-android-resources:processReleaseManifest
:preReleaseBuild
:Firebase:compileReleaseAidl
:GooglePlayGamesManifest.plugin:compileReleaseAidl
:IronSource:compileReleaseAidl
:unity-android-resources:compileReleaseAidl
:compileReleaseAidl
:Firebase:packageReleaseRenderscript NO-SOURCE
:GooglePlayGamesManifest.plugin:packageReleaseRenderscript NO-SOURCE
:IronSource:packageReleaseRenderscript NO-SOURCE
:unity-android-resources:packageReleaseRenderscript NO-SOURCE
:compileReleaseRenderscript
:checkReleaseManifest
:generateReleaseBuildConfig
:prepareLintJar
:generateReleaseResValues
:generateReleaseResources
:Firebase:compileReleaseRenderscript
:Firebase:generateReleaseResValues
:Firebase:generateReleaseResources
:Firebase:packageReleaseResources
:GooglePlayGamesManifest.plugin:compileReleaseRenderscript
:GooglePlayGamesManifest.plugin:generateReleaseResValues
:GooglePlayGamesManifest.plugin:generateReleaseResources
:GooglePlayGamesManifest.plugin:packageReleaseResources
:IronSource:compileReleaseRenderscript
:IronSource:generateReleaseResValues
:IronSource:generateReleaseResources
:IronSource:packageReleaseResources
:unity-android-resources:compileReleaseRenderscript
:unity-android-resources:generateReleaseResValues
:unity-android-resources:generateReleaseResources
:unity-android-resources:packageReleaseResources
:mergeReleaseResources
:createReleaseCompatibleScreenManifests
:processReleaseManifest
X:\Projects\[...]\Temp\gradleOut\src\main\AndroidManifest.xml:24:9-31:50 Warning:
	activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present
:splitsDiscoveryTaskRelease
:Firebase:platformAttrExtractor
:GooglePlayGamesManifest.plugin:platformAttrExtractor
:IronSource:platformAttrExtractor
:unity-android-resources:platformAttrExtractor
:Firebase:processReleaseResources
:Firebase:generateReleaseBuildConfig
:Firebase:prepareLintJar
:Firebase:generateReleaseSources
:Firebase:javaPreCompileRelease
:Firebase:compileReleaseJavaWithJavac
:Firebase:processReleaseJavaRes NO-SOURCE
:Firebase:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:GooglePlayGamesManifest.plugin:generateReleaseBuildConfig
:GooglePlayGamesManifest.plugin:prepareLintJar
:GooglePlayGamesManifest.plugin:javaPreCompileRelease
:GooglePlayGamesManifest.plugin:processReleaseJavaRes NO-SOURCE
:IronSource:generateReleaseBuildConfig
:IronSource:prepareLintJar
:IronSource:javaPreCompileRelease
:IronSource:processReleaseJavaRes NO-SOURCE
:unity-android-resources:generateReleaseBuildConfig
:unity-android-resources:prepareLintJar
:unity-android-resources:javaPreCompileRelease
:unity-android-resources:processReleaseJavaRes NO-SOURCE
:compileReleaseNdk NO-SOURCE
:mergeReleaseShaders
:compileReleaseShaders
:generateReleaseAssets
:Firebase:mergeReleaseShaders
:Firebase:compileReleaseShaders
:Firebase:generateReleaseAssets
:Firebase:mergeReleaseAssets
:GooglePlayGamesManifest.plugin:mergeReleaseShaders
:GooglePlayGamesManifest.plugin:processReleaseResources
:GooglePlayGamesManifest.plugin:generateReleaseSources
:GooglePlayGamesManifest.plugin:compileReleaseJavaWithJavac
:GooglePlayGamesManifest.plugin:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:GooglePlayGamesManifest.plugin:compileReleaseShaders
:GooglePlayGamesManifest.plugin:generateReleaseAssets
:GooglePlayGamesManifest.plugin:mergeReleaseAssets
:IronSource:mergeReleaseShaders
:IronSource:compileReleaseShaders
:IronSource:generateReleaseAssets
:IronSource:mergeReleaseAssets
:unity-android-resources:mergeReleaseShaders
:unity-android-resources:compileReleaseShaders
:unity-android-resources:generateReleaseAssets
:unity-android-resources:mergeReleaseAssets
:mergeReleaseAssets
:mergeReleaseJniLibFolders
:Firebase:compileReleaseNdk NO-SOURCE
:Firebase:mergeReleaseJniLibFolders
:Firebase:transformNativeLibsWithMergeJniLibsForRelease
:Firebase:transformNativeLibsWithStripDebugSymbolForRelease
:Firebase:transformNativeLibsWithIntermediateJniLibsForRelease
:GooglePlayGamesManifest.plugin:compileReleaseNdk NO-SOURCE
:GooglePlayGamesManifest.plugin:mergeReleaseJniLibFolders
:GooglePlayGamesManifest.plugin:transformNativeLibsWithMergeJniLibsForRelease
:GooglePlayGamesManifest.plugin:transformNativeLibsWithStripDebugSymbolForRelease
:GooglePlayGamesManifest.plugin:transformNativeLibsWithIntermediateJniLibsForRelease
:IronSource:compileReleaseNdk NO-SOURCE
:IronSource:mergeReleaseJniLibFolders
:IronSource:transformNativeLibsWithMergeJniLibsForRelease
:IronSource:transformNativeLibsWithStripDebugSymbolForRelease
:IronSource:transformNativeLibsWithIntermediateJniLibsForRelease
:unity-android-resources:compileReleaseNdk NO-SOURCE
:unity-android-resources:mergeReleaseJniLibFolders
:unity-android-resources:transformNativeLibsWithMergeJniLibsForRelease
:unity-android-resources:transformNativeLibsWithStripDebugSymbolForRelease
:unity-android-resources:transformNativeLibsWithIntermediateJniLibsForRelease
:processReleaseJavaRes NO-SOURCE
:validateSigningRelease
:Firebase:extractReleaseAnnotations
:Firebase:mergeReleaseConsumerProguardFiles
:Firebase:transformResourcesWithMergeJavaResForRelease
:Firebase:transformClassesAndResourcesWithSyncLibJarsForRelease
:Firebase:transformNativeLibsWithSyncJniLibsForRelease
:Firebase:bundleRelease
:Firebase:compileReleaseSources
:Firebase:mergeReleaseResources
:Firebase:verifyReleaseResources
:Firebase:assembleRelease
:GooglePlayGamesManifest.plugin:extractReleaseAnnotations
:GooglePlayGamesManifest.plugin:mergeReleaseConsumerProguardFiles
:GooglePlayGamesManifest.plugin:transformResourcesWithMergeJavaResForRelease
:IronSource:processReleaseResources
:IronSource:generateReleaseSources
:IronSource:compileReleaseJavaWithJavac
:IronSource:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:GooglePlayGamesManifest.plugin:transformClassesAndResourcesWithSyncLibJarsForRelease
:GooglePlayGamesManifest.plugin:transformNativeLibsWithSyncJniLibsForRelease
:GooglePlayGamesManifest.plugin:bundleRelease
:GooglePlayGamesManifest.plugin:compileReleaseSources
:GooglePlayGamesManifest.plugin:mergeReleaseResources
:GooglePlayGamesManifest.plugin:verifyReleaseResources
:GooglePlayGamesManifest.plugin:assembleRelease
:IronSource:extractReleaseAnnotations
:IronSource:mergeReleaseConsumerProguardFiles
:IronSource:transformResourcesWithMergeJavaResForRelease
:IronSource:transformClassesAndResourcesWithSyncLibJarsForRelease
:IronSource:transformNativeLibsWithSyncJniLibsForRelease
:IronSource:bundleRelease
:IronSource:compileReleaseSources
:IronSource:mergeReleaseResources
:IronSource:verifyReleaseResources
:IronSource:assembleRelease
:unity-android-resources:mergeReleaseConsumerProguardFiles
:unity-android-resources:transformNativeLibsWithSyncJniLibsForRelease
:unity-android-resources:mergeReleaseResources
:unity-android-resources:verifyReleaseResources
:unity-android-resources:processReleaseResources
:processReleaseResources
:generateReleaseSources
:unity-android-resources:generateReleaseSources
:unity-android-resources:compileReleaseJavaWithJavac
:unity-android-resources:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:javaPreCompileRelease
:compileReleaseJavaWithJavac
:compileReleaseSources
:lintVitalRelease
:transformClassesWithPreDexForRelease
:transformNativeLibsWithMergeJniLibsForRelease FAILED
130 actionable tasks: 130 executed
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

**Comment by DenizPiri** [comment] 2019-06-08 14:10
We had exactly the same problem. We use a custom gradle build file.  A modified copy of Unity's and Firebase further applies modifications to it.

Adding **exclude ('/lib/armeabi-v7a/*' + '*')** somewhere inside **android { packagingOptions {** solves the problem. I feel like this is a problem in **PlayServicesResolver**.

**Comment by Mecze** [comment] 2019-06-10 14:18
Something very similar happens to us described here: https://github.com/firebase/quickstart-unity/issues/383

**Comment by stewartmiles** [comment] 2019-06-12 18:12
Hi folks,

When `Patch mainTemplate.gradle` is enabled in the Android Resolver settings, as you've noticed, rather than downloading the Android libraries into the project the resolver simply injects the dependencies into mainTemplate.gradle.  Firebase - and some other plugins - ship some AARs along with their plugins using the artifact extension `.srcaar` to allow older versions of Unity to ignore the file, `.aar` files automatically get included in Android builds if they're in any folder of a project in some versions of Unity.

Since the Android Gradle plugin used by `mainTemplate.gradle` doesn't know what a `.srcaar` artifact is, the Android Resolver will copy the `.srcaar` files referenced by the project to `.aar` files (e.g `firebase-app-unity-6.0.0.srcaar` to `firebase-app-unity-6.0.0.aar`) and modifies the Unity file metadata (those .metadata files) to _disable_ the Android platform for these files which prevents Unity from including these files.  AFAIK only possible to disable the Android platform for `.aar` files in version 2017+. 

However, the metadata change to disable the Android platform for copied `.aar` files appears to be lost if Unity is closed and reopened.  This behavior seems to be different to other metadata modification in a Unity project :( . If the project is saved after resolution, `.aar` files remain disabled when Unity is closed and reopened, hence this build error goes away.

So the solution appears to be that any time we modify file metadata in the [https://github.com/googlesamples/unity-jar-resolver](Play Services Resolver) plugin suite, we should save the project to make sure the changes continue to be applied.

**Comment by stewartmiles** [comment] 2019-06-12 20:47
This is fixed in Android Resolver 1.2.117
https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.117 

This will be rolled into the next Firebase Unity SDK release.

**Comment by Mecze** [comment] 2019-06-13 08:07
I can confirm 1.2.117 fixes the issue
Thanks @stewartmiles

**Closed** 2019-06-17 17:15 UTC
Labels: type: bug

**Comment by mrtslk** [comment] 2019-09-08 20:53
same bug still there in 1.2.124 release.
