### ISSUE TITLE
[Bug] Analytics: missing iOS events

### ISSUE THREAD

**Issue by VolodymyrBS** [firebase/quickstart-unity#1243] opened 2022-03-17 18:34 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.24f1, 2019.4.16f1
  * Firebase Unity SDK version: 8.7.0, 8.8.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: none
  * Additional SDKs you are using: none
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Hi! I have a problem with Firebase Analytics. I see no events except a few buildin.
tried to configure testapp but it still logs no events.

this is debug view that I see after clicking all buttons in the tests app and vaiting for some time

![image](https://user-images.githubusercontent.com/20375870/158871998-6b61116d-2201-44be-82fa-dc2c19654e3d.png)

#### Steps to reproduce:

1. build for iOS
2. run in XCode with debug https://firebase.google.com/docs/analytics/debugview#ios+
3. Click all Log* buttons in the app
4. Nothing in Debug View except few building events

Related to https://github.com/firebase/firebase-unity-sdk/issues/205

**Comment by paulinon** [comment] 2022-03-18 10:09
Hi @VolodymyrBS, 

Thanks for this report. It seems that there is a known bug wherein Firebase Analytics Unity SDK is not capturing custom events. 

I'll be marking this as a bug for now. You may refer to this thread for updates.

**Comment by VolodymyrBS** [comment] 2022-03-18 10:49
Hi @paulinon,
Looks like I have just found the issue,
https://github.com/firebase/quickstart-unity/issues/1178 Enabling `Link frameworks statically` fixed the testapp. I will try with real project soon

**Comment by VolodymyrBS** [comment] 2022-03-18 14:15
Yeah, I could confirm that enabling Link frameworks statically fix real project as well

**Comment by DellaBitta** [comment] 2022-03-18 17:10
Thanks for circling back with us VolodymyrBS.  I'm going to close this a duplicate of #1178.

**Comment by DellaBitta** [comment] 2022-03-18 17:11
Duplicate of #1178.

**Comment by DellaBitta** [comment] 2022-03-18 17:12
Duplicate of #1178.

**Closed by DellaBitta** 2022-03-18 17:12 UTC
Labels: duplicate, api: analytics
