### ISSUE TITLE
Generation of the Firebase Android resource file google-services ....failed

### ISSUE THREAD

**Issue by MidiSmallYue** [firebase/quickstart-unity#541] opened 2019-12-19 16:04 UTC
**Please fill in the following fields:**
Unity editor version: 2018.4.6f1
Firebase Unity SDK version: 6.8.1
Firebase plugins in use : Firebase Analytics
Additional SDKs you are using : Admob
Platform you are using the Unity editor on : Windows.
Platform you are targeting : Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

**Please describe the issue here:**
1.在已经包含Amodb的项目中导入Firebase Analytics。
2.从firebase控制台下载google-services.json，并导入untiy项目中
3.运行unity项目，你将看到一下错误：
Generation of the Firebase Android resource file google-services.xml from Assets/Firebase/google-services.json failed.
If you have not included a valid Firebase Android resources in your app it will fail to initialize.
`.../Unity/Assets\..\Assets/Firebase/Editor/generate_xml_from_google_services_json.exe -i "Assets/Firebase/google-services.json" -l`.

Error loading Python DLL: ...AppData\Local\Temp\_MEI82522\python27.dll (error code 14001)
You can start to diagnose this issue by executing "`.../Unity/Assets\..\Assets/Firebase/Editor/generate_xml_from_google_services_json.exe -i "Assets/Firebase/google-services.json" -l`." from the command line.
UnityEngine.Debug:LogError(Object)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:RunResourceGenerator(String, String, Boolean) (at Z:/tmp/tmp.s8bDhUcuGf/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:555)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:ReadBundleIds(String) (at Z:/tmp/tmp.s8bDhUcuGf/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:394)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:UpdateConfigFileDirectory() (at Z:/tmp/tmp.s8bDhUcuGf/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:286)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:CheckConfiguration() (at Z:/tmp/tmp.s8bDhUcuGf/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:237)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:<GenerateXmlFromGoogleServicesJson>m__0() (at Z:/tmp/tmp.s8bDhUcuGf/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:102)
Google.RunOnMainThread:ExecuteNext() (at Z:/tmp/tmp.ZseAuJaQr9/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:377)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.ZseAuJaQr9/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:408)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.ZseAuJaQr9/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.ZseAuJaQr9/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

4.我尝试在命令行中运行，显示结果为：Error loading Python DLL: ...AppData\Local\Temp\_MEI82522\python27.dll (error code 14001)

Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Didn't test.

What's the issue repro rate? 100 %

**Comment by stewartmiles** [comment] 2019-12-19 17:47
Closing as duplicate of #541

**Closed by stewartmiles** 2019-12-19 17:47 UTC
Labels: duplicate
