### ISSUE TITLE
Game restart required on iOS for push notifications to work

### ISSUE THREAD

**Issue by thsbrown** [firebase/quickstart-unity#820] opened 2020-10-14 05:04 UTC
### Please fill in the following fields:

  * Unity editor version: 2018.4.17f1
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Cloud Messaging (Auth, Database, etc.)
  * Other Firebase Components in use: Core (Auth, Database, etc.)
  * Additional SDKs you are using: PlayFab (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: ios (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### Please describe the issue here:

The issue is pretty much summarized [here](https://github.com/firebase/quickstart-unity/issues/603). Overall though i'm noticing that no matter the configuration it requires me closing the game, reopening it and closing it again in order to get push notifications to be sent through on ios.

Repro Rate: 100%

#### Steps to reproduce:

1. Run the unity quickstart Cloud Messages quick start on ios.
2.When the app/game opens press allow notifications.
3.Kill the app/game in ios.
4.Send a notification using "New Notification" button in FIrebase cloud messaging dev console.
5.Notice no notification comes through.
6.Open the app/game up again on ios.
7.Kill app/game again.
8.Repeat step 4.
9.Notice notification comes through.

#### Relevant Code:

All done utilizing code from cloud messaging quickstart [here](https://github.com/firebase/quickstart-unity/blob/master/messaging/testapp/Assets/Firebase/Sample/Messaging/UIHandler.cs)

**Comment by chkuang-g** [comment] 2020-10-16 00:32
Hi @thsbrown 

Thank you for reporting this issue.  I think I can reproduce with our quickstart as well.  The behavior seems to be that you need to close the app at least once in order to receive push notification, either when the app is in the background or when it is killed.

I'm not sure if this is an issue in Unity/C++ level or in iOS SDK level.  I'll contact the team to look into this.

Shawn

**Comment by chliangGoogle** [comment] 2020-10-19 18:44
@chkuang-g I think https://github.com/firebase/firebase-ios-sdk/pull/6669 should fix this, What's the approach for unity SDK to pick up the change?

**Comment by chkuang-g** [comment] 2020-10-19 18:49
@chliangGoogle The latest Unity SDK `6.16.0` is using `Firebase/Messaging` Pod `6.32.2`.

Since that change is merged 12 days ago, I assume it is in `6.34.0`?

**Comment by chliangGoogle** [comment] 2020-10-19 19:10
@chkuang-g yeah, should be out in the next release. I'm not sure what unity version is. in the meantime, is there a way developer can patch the change in unity now?

**Comment by chkuang-g** [comment] 2020-10-19 19:23
Well, if the patch has not been released yet, there are some considerations:

- Is there any API changes from `6.32.2` to the next iOS release? If not, continue
- Is it possible to build iOS SDK from [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk) repo and manually install the SDK into Xcode project? If so, continue
- If both concerns are addressed, I guess the user can try to override the FCM iOS SDK in Xcode project after Unity generate it.   Otherwise, I think Unity SDK will bump up iOS SDK version for FireConf release.

Shawn

**Comment by chkuang-g** [comment] 2021-01-11 19:01
Hey folks,

6.17.0 has been released.  I will closed this thread for now.  If the issue persists, please open a new issue and reference this one please.

Shawn

**Closed by chkuang-g** 2021-01-11 19:01 UTC
Labels: api: messaging, needs-info, type: process
