### ISSUE TITLE
[4.5.0] Dynamic Links / Invites not received on Android

### ISSUE THREAD

**Issue by bilck** [firebase/quickstart-unity#141] opened 2018-03-03 17:21 UTC
We have detected (using Fabric) that some of our users' devices crash due to the following Firebase-related exception:
-------------------------------
Fatal Exception: java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2017.3.1p2
Device model      : samsung SM-G530M
Device fingerprint: samsung/fortunalteub/fortunalte:4.4.4/KTU84P/G530MUBU1ANL1:user/release-keys

Caused by java.lang.UnsatisfiedLinkError: Native method not found: com.google.firebase.app.internal.cpp.Log.nativeLog:(ILjava/lang/String;Ljava/lang/String;)V
       at com.google.firebase.app.internal.cpp.Log.nativeLog(Log.java)
       at com.google.firebase.app.internal.cpp.Log.getInstance(Log.java:73)
       at com.google.firebase.app.internal.cpp.Log.d(Log.java:21)
       at com.google.firebase.invites.internal.cpp.AppInviteNativeWrapper$6.onResult(AppInviteNativeWrapper.java:456)
       at com.google.firebase.invites.internal.cpp.AppInviteNativeWrapper$6.onResult(AppInviteNativeWrapper.java:453)
       at com.google.android.gms.common.api.internal.BasePendingResult$zza.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5433)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
-------------------------------

This happens with a lot of devices on various Android OS versions (4, 5, 6 and 7) and different devices.

We are using IL2CPP scripting backend.

**Comment by stewartmiles** [comment] 2018-03-05 00:44
Is it possible you're calling FIrebaseApp.Dispose() or somehow trying to clear all references to FirebaseApp and FirebaseDynamicLinks / FirebaseInvites while a fetch operation is in progress?

It looks like the Dynamic Links or App Invites Java component is receiving a completion and then the C++ component of the logger is being torn down.  The logger will only be destroyed if all FirebaseApp instances in the application are destroyed.

**Comment by stewartmiles** [comment] 2018-03-05 00:44
@jonsimantov @johnb003 FYI

**Comment by bilck** [comment] 2018-03-07 03:09
Unfortunately not.

We only use Firebase directly in 2 classes in our project, they don't dispose Firebase at all, specially regarding dynamic links/invites. If it is of any help I can send you those classes.

**Comment by bilck** [comment] 2018-03-07 03:11
By the way, this is the link to the crash report: http://crashes.to/s/24a987e0163

**Comment by stewartmiles** [comment] 2018-03-14 17:39
@bilck I spent a bit of time looking a ways this could happen yesterday and came up with a few theories.
- If Firebase static classes are touched (e.g Invites / Dynamic Links) a dynamic link / invite fetch will start.  Then if FirebaseApp.CheckDependencies() is called afterwards (which currently and incorrectly tears down the all FirebaseApp objects) the dynamic link / invite fetch can complete when everything is torn down resulting in the crash.
- If FirebaseApp.Dispose() is called or FirebaseApp is somehow dereferenced by all classes in the application resulting in garbage collecting the object this will also result in a crash with an active fetch in progress.
- If the Firebase native library is somehow unloaded.

So we've done a few things for the next release:
- Changed FirebaseApp.CheckDependencies() to no longer tear down all FirebaseApp objects.  Instead we now check for a valid default app with FirebaseApp.GetInstance(FirebaseApp.DefaultName) before running expensive Google Play services checks.
- Made dynamic link / invite completion more robust to the native library being torn out from under it.  If a fetch is started and the app tears Firebase down, the fetch completion will fail gracefully writing an error to logcat instead.

**Comment by bilck** [comment] 2018-03-17 00:48
Hello Stewart,

So I guess that was the case, because some analytics events occur independetly of Firebase Dynamic Links "Initialization"/DependencyCheck. We have predicted this behaviour worked around it by using another class that is set to "initialized" state **after** checking dependencies.
That reduced the number of ocurrences, but they are still happening.

Do you have any estimate time of release for an updated Unity Firebase SDK?

Thanks!

**Comment by stewartmiles** [comment] 2018-03-17 03:06
@bilck we're aiming on next week, hold tight.

**Comment by mgrogin** [comment] 2018-03-21 12:34
@stewartmiles is this resolved in the new version thats out (4.5.0)? 
I'm still having issues with it.
I don't receive a Dynamic link event on android if the app is closed
If I comment out my call to FirebaseApp.CheckDependencies()  everything works again

**Comment by stewartmiles** [comment] 2018-03-22 01:08
Hi @mgrogin and @bilck while we fixed the crash it looks like the code path that checks and fixes dependencies is now tearing down the default app instance after it is created which is - somehow - (we haven't root caused the issue yet) consuming the dynamic link before it's send to your application.

The workaround with the 4.5.0 SDK is to do the following in your initialization code:

```
  void Start() {
    try {
      app = Firebase.FirebaseApp.DefaultInstance;
	  dependencyStatus = Firebase.DependencyStatus.Available;
	  InitializeFirebase();
    } catch (Firebase.InitializationException) {
      Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
        dependencyStatus = task.Result;
        if (dependencyStatus == Firebase.DependencyStatus.Available) {
          InitializeFirebase();
        } else {
          Debug.LogError(
            "Could not resolve all Firebase dependencies: " + dependencyStatus);
        }
      });
    }
  }
```

Here we're attempting to create FirebaseApp, if it fails we check and fix dependencies and then try again working around the dynamic link / invite being consumed by `CheckAndFixDependenciesAsync`.

**Comment by chkuang-g** [comment] 2018-04-03 18:28
We found the problem and the fix should be included in the next release.

**Comment by a-maurice** [comment] 2018-04-17 17:37
This should now be resolved in our 4.5.1 update.  https://firebase.google.com/support/release-notes/unity#4.5.1  Dynamic Links and Invites should now be received correctly, with CheckAndFixDependenciesAsync being called as it is in the Invites testapp.

**Closed by a-maurice** 2018-04-17 17:37 UTC
Labels: bug

**Comment by xtrecoolx** [comment] 2019-02-16 09:51
@a-maurice I came across this thread when we are talking on a different thread. There's gotta be something wrong in SDK 5.4.4. The dynamic links do not work on app start. It's driving me insane. All I am doing is simply the following:

`
		 void CheckFirebaseSDK() {

			Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
			var dependencyStatus = task.Result;
			if (dependencyStatus == Firebase.DependencyStatus.Available) {
				// Create and hold a reference to your FirebaseApp,
				// where app is a Firebase.FirebaseApp property of your application class.
				  firebaseApp = Firebase.FirebaseApp.DefaultInstance;
				  InitializeDynamicLinks();
				  InitializeFirebaseRemoteConfig();
				  FetchFirebaseRemoteConfigDataAsync();
				  InitializeFirebaseMessaging();
				  

				// Set a flag here to indicate whether Firebase is ready to use by your app.
			} else {
				UnityEngine.Debug.LogError(System.String.Format(
				"Could not resolve all Firebase dependencies: {0}", dependencyStatus));
				// Firebase Unity SDK is not safe to use here.
			}
			});

		}
		void InitializeDynamicLinks() {
			
			DynamicLinks.DynamicLinkReceived += OnDynamicLink;
			Debug.Log("Listening for dynamic links");

		}
		
		  void OnDynamicLink(object sender, EventArgs args) {
			    
				Debug.Log("There is a dynamic link");

      			var dynamicLinkEventArgs = args as ReceivedDynamicLinkEventArgs;
      			Debug.Log(String.Format("Received dynamic link {0}",dynamicLinkEventArgs.ReceivedDynamicLink.Url.OriginalString));
				

    	}
`

**Comment by xtrecoolx** [comment] 2019-02-16 11:31
One more thing. Do we need to have an intent-filter for androidmanifest.xml for dynamic links to work ? The android documentation shows an intent-filter but I don't see it for Unity.

**Comment by chkuang-g** [comment] 2019-02-22 02:17
@xtrecoolx Could you try to reproduce with our [Firebase DynamicLink testapp](https://github.com/firebase/quickstart-unity/tree/master/dynamic_links/testapp)?

Thank you
