### ISSUE TITLE
[Bug] Error Exception of type 'Google.GoogleSignIn+SignInException' was thrown.

### ISSUE THREAD

**Issue by surajsk1812** [firebase/quickstart-unity#1050] opened 2021-05-20 15:15 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.14_____
  * Firebase Unity SDK version: __7.0.2___
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:
 **Getting error for google silent login**

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment] 2021-05-21 05:43
Hi @surajsk1812,

In order to isolate what's causing this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project as well as the complete steps you've taken before facing this issue?

**Comment by surajsk1812** [comment] 2021-05-21 06:15
1) Open app and login with google (First Google login will always be a normal Login) and normal Login is working fine.
2) Close app after successfully logging in with google(normal login)
3) Again open app, app will try to login with google silently(Auto Login) but it's not working.

Getting **"Error Exception of type 'Google.GoogleSignIn+SignInException' was thrown."**

I have uploaded the Google Sign In script
[Google Login.pdf](https://github.com/firebase/quickstart-unity/files/6520462/Google.Login.pdf)

**Comment by cynthiajoan** [comment] 2021-05-21 16:48
Hi @surajsk1812 , can you please also attach the call stack and more log info?

**Comment by surajsk1812** [comment] 2021-05-21 16:57
Call Stack
1) OnSignInSilently()
2) OnAuthenticationFinished(Task<GoogleSignInUser> task) => Getting error in this method (check this if statement **if(task.IsFaulted)**)

Getting only one error - **Error Exception of type 'Google.GoogleSignIn+SignInException' was thrown**

**Comment by chkuang-g** [comment] 2021-06-10 01:47
Hi @surajsk1812 

Which platform did you experience the issue? Android/iOS/desktop?

Also, I saw both `OnSignInSilently()` and `OnSignin()` are public functions. How are they called? Any why do you want to call `OnSignInSilently()` instead of `OnSignIn()` when the app is launched for the second time?

AFAIK, if you signed-in successfully before the app closed, you should not need to call `auth.SignInWithCredentialAsync()` again, since FirebaseAuth persists previous sign-in.  If `FirebaseAuth.DefaultInstance.CurrentUser` is not null, it means the user has signed-in before. 

I suspect the error occurred because you tried to signed in again before signing out.  

Here is my suggestion: change your sign-in logic to something like this:
```
if (auth.CurrentUser) {
  // The user has signed in previously. Do not need to sign-in again.
} else {
  // Do GoogleSignIn and auth.SignInWithCredentialAsync()
```

You might want to change the logic about how `OnSignInSilently()` and `OnSignin()` are called :)

**Comment by surajsk1812** [comment] 2021-06-21 07:23
Facing this issue in android.

I am calling auth.SignInWithCredentialAsync() only once when I login with google for the first time. 

OnSignInSilently() will login without any user interaction(Auto Login).

**Comment by DellaBitta** [comment] 2021-06-22 13:00
Hi @surajsk1812,

[GoogleSignIn](https://github.com/googlesamples/google-signin-unity) is a separate plugin managed by the Google Sign In team. The token it generates is later used for Firebase authentication but the code to generate the token is their own.

It looks like the `Google.GoogleSignIn+SignInException` exception originates from that plugin and not Firebase Auth. I see that you've already created a [ticket in their repo](https://github.com/googlesamples/google-signin-unity/issues/184).  I will post a link this ticket in that issue list, and close this one, as that community will have a better idea of wha the issue might be.  Thanks!

**Closed by DellaBitta** 2021-06-22 13:00 UTC
Labels: api: auth, needs-attention, type: question

**Comment by surajsk1812** [comment] 2021-06-22 13:49
Hi @DellaBitta 

I wasn't getting any reply from GoogleSignIn team. So, I reported issue here.
