### ISSUE TITLE
[Bug]  Authentication with Facebook

### ISSUE THREAD

**Issue by Vah94** [firebase/quickstart-unity#1141] opened 2021-09-15 13:58 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.18f1
  * Firebase Unity SDK version: 8.2.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Auth (Auth, Database, etc.)
  * Other Firebase Components in use: Database, Analytics, RemoteConfige, Crashlytics (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, Applovin (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP(Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
SignInWithCredentialAsync encountered an error: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: The supplied auth credential is malformed or has expired.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: The supplied auth credential is malformed or has expired.
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Firebase.FirebaseException: The supplied auth credential is malformed or has expired.<---
<---

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? You didn't have test app for Facebook Auth.
What's the issue repro rate? (eg 100%, 1/5 etc)
100%
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
1. Log in to your Facebook account with Facebook Unity SDK
2. Get token
3. FacebookAuthProvider.GetCredential(token)
4. SignInWithCredentialAsync(credential)
If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

` var credential = FacebookAuthProvider.GetCredential(token);
            _firebaseAuth.SignInWithCredentialAsync(credential)
                .ContinueWithOnMainThread(GetSignInTask(callback));
protected Action<Task<FirebaseUser>> GetSignInTask(
            Action<FirebaseUser> callback = null)
        {
            return task =>
            {
                if (task.IsCanceled)
                {
                    _debugLogUtil.Log("SignInWithCredentialAsync was canceled.", LogType.Warning);
                    callback?.Invoke(null);
                }
                else if (task.IsFaulted)
                {
                    _debugLogUtil.Log(
                        "SignInWithCredentialAsync encountered an error: " + task.Exception,
                        LogType.Warning);
                    callback?.Invoke(null);
                }
                else
                {
                    var firebaseUser = task.Result;
                    _debugLogUtil.Log(
                        "LogIn Results"
                        + $"\nDisplayName: {firebaseUser.DisplayName}"
                        + $"\nEmail: {firebaseUser.Email}"
                        + $"\nPhotoUrl: {firebaseUser.PhotoUrl}"
                        + $"\nProviderId: {firebaseUser.ProviderId}"
                        + $"\nUserId: {firebaseUser.UserId}");
                    _fireBaseAuthDataManager.SetFirebaseUserId(firebaseUser.UserId, firebaseUser.PhotoUrl.ToString());
                    callback?.Invoke(firebaseUser);
                }
            };
        }`

**Comment by gevorgyanmp** [comment] 2021-09-15 14:51
[REQUIRED] Please fill in the following fields:

- Unity editor version: 2020.3.18f1
- Firebase Unity SDK version: 8.2.0
- Source you installed the SDK: .unitypackage
- Problematic Firebase Component: Auth 
- Other Firebase Components in use: Database, Analytics, RemoteConfige, Crashlytics 
- Additional SDKs you are using: Facebook, Applovin
- Platform you are using the Unity editor on: Mac 
- Platform you are targeting: Android
- Scripting Runtime: IL2CPP

[REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
SignInWithCredentialAsync encountered an error: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: The supplied auth credential is malformed or has expired.
--- End of inner exception stack trace ---
--- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: The supplied auth credential is malformed or has expired.
--- End of inner exception stack trace ---
---> (Inner Exception #0) Firebase.FirebaseException: The supplied auth credential is malformed or has expired.<---
<---

I have the same issue in the project. In another project, where App Type: Gaming everything works. In this project App Type: Gaming Services and it's crashes.

**Comment by paulinon** [comment] 2021-09-15 15:07
Hi @Vah94,

Thanks for reporting the issue. Based on the information you provided, it seems that the code you provided is in Swift. Is that correct? If so, could you confirm if you have used this in your implementation? 

A [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project would be helpful in order to identify the cause of this behavior.

**Comment by Vah94** [comment] 2021-09-16 06:50
Hi @paulinon, 
It's a c#, You don't need a complex project to reproduce the bug.
1. Register a new Facebook app.
2. Log in to Facebook.
3. Log in to Firebase with the Facebook token.

Expected result: Successful Firebase  login
Actual result: Login failed -> Firebase.FirebaseException: The supplied auth credential is malformed or has expired.

**Comment by paulinon** [comment] 2021-09-21 15:34
Hi @Vah94,

Thanks for providing additional information. I was able to replicate this issue, and it turns out that logins with this App Type isn't supported yet as mentioned in #826.

I'll be closing this ticket for now, but you may refer to the thread I provided for more updates.

**Comment by paulinon** [comment] 2021-09-21 15:35
Duplicate of #826

**Closed by paulinon** 2021-09-21 15:35 UTC
Labels: type: question, needs-attention, api: auth
