### ISSUE TITLE
Database example does not work in Unity 2019.1

### ISSUE THREAD

**Issue by col000r** [firebase/quickstart-unity#352] opened 2019-04-25 07:51 UTC
## Please fill in the following fields:
Unity editor version: 2019.1.0f2
Firebase Unity SDK version: 5.7.0
Firebase plugins in use (Auth, Database, etc.): Database
Additional SDKs you are using (Facebook, AdMob, etc.): -
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): testing with Unity in Desktop mode

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I added my json and plist files, imported the dotnet4/FirebaseDatabase.unitypackage, put my firebase realtime database url into UIHandler.cs, but when I enter play mode I just get a stream of Errors:

25/04/2019 7:21:52 a.m. [Error] WebSocket: ws_0 - could not connect
System.Net.Sockets.SocketException (0x80004005): No route to host
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remoteEP) [0x00033] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x000ea] in Z:\tmp\tmp.UJsYTuiaFJ\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:323 
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.lznH2AxwEU/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:19)
Firebase.Unity.UnityLoggingService:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.lznH2AxwEU/firebase/app/client/unity/src/Unity/UnityLoggingService.cs:13)
Firebase.Database.Internal.Logging.DefaultLogger:Error(String, String) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:68)
Firebase.Database.Internal.Logging.DefaultLogger:OnLogMessage(Level, String, String, Int64) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:32)
Firebase.Database.Internal.Logging.LogWrapper:Error(String, Exception) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/LogWrapper.cs:36)
Firebase.Database.Internal.TubeSock.WebSocket:LogError(String, Exception) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:143)
Firebase.Database.Internal.TubeSock.WebSocket:CreateSocket() (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:325)
Firebase.Database.Internal.TubeSock.WebSocket:RunReader() (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:386)
Firebase.Database.Internal.TubeSock.Runnable101:Run() (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:516)
Google.Sharpen.Thread:InternalRun() (at Z:/tmp/tmp.vANha6D0V6/third_party/dotnet_src/sharpen/Sharpen/Thread.cs:80)
System.Threading.ThreadHelper:ThreadStart()

And this one:

25/04/2019 7:21:52 a.m. [Error] WebSocket: ws_0 - WebSocketException during handshake
Firebase.Database.Internal.TubeSock.WebSocketException: unknown host: [EDITEDOUTMYPROJECTID].firebaseio.com ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remoteEP) [0x00033] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x000ea] in Z:\tmp\tmp.UJsYTuiaFJ\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:323 
   --- End of inner exception stack trace ---
  at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x0010c] in Z:\tmp\tmp.UJsYTuiaFJ\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:327 
  at Firebase.Database.Internal.TubeSock.WebSocket.RunReader () [0x0001b] in Z:\tmp\tmp.UJsYTuiaFJ\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:386 
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.lznH2AxwEU/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:19)
Firebase.Unity.UnityLoggingService:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.lznH2AxwEU/firebase/app/client/unity/src/Unity/UnityLoggingService.cs:13)
Firebase.Database.Internal.Logging.DefaultLogger:Error(String, String) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:68)
Firebase.Database.Internal.Logging.DefaultLogger:OnLogMessage(Level, String, String, Int64) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:32)
Firebase.Database.Internal.Logging.LogWrapper:Error(String, Exception) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/LogWrapper.cs:36)
Firebase.Database.Internal.TubeSock.WebSocket:LogError(String, Exception) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:143)
Firebase.Database.Internal.TubeSock.WebSocket:RunReader() (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:468)
Firebase.Database.Internal.TubeSock.Runnable101:Run() (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:516)
Google.Sharpen.Thread:InternalRun() (at Z:/tmp/tmp.vANha6D0V6/third_party/dotnet_src/sharpen/Sharpen/Thread.cs:80)
System.Threading.ThreadHelper:ThreadStart()

What's up with that? (Auth example works fine)

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? yes

**Comment by patm1987** [comment] 2019-04-25 16:05
Hi @col000r ,

I'm really sorry that you're experiencing this.

I think that you're running into this bug: https://github.com/firebase/quickstart-unity/issues/106
To verify, can you check to see if:
1) it works on your phone/tablet
2) see if it works under different network conditions (specifically whether you can connect to secure websockets)
3) whether or not the workaround here works: https://stackoverflow.com/questions/50651865/unityfirebase-databaseerror-websocket-ws-0-could-not-connect
I will caution with this last one that you should be careful not to deploy your app with these DLLs swapped. It may work more reliably in editor, but you lose some nice performance features on mobile.

Thanks for reporting this issue!
--Patrick

**Comment by stewartmiles** [comment] 2019-05-01 17:27
Closing this as a duplicate of #106 .

**Closed by stewartmiles** 2019-05-01 17:27 UTC
Labels: type: bug
