### ISSUE TITLE
Crashlytics: App orientation always reported as Portrait

### ISSUE THREAD

**Issue by Ruco** [firebase/quickstart-unity#358] opened 2019-05-06 13:48 UTC
## Please fill in the following fields:
Unity editor version: 2018.1.9f2
Firebase Unity SDK version: 5.7.0
Firebase plugins in use (Auth, Database, etc.): Analytics, Crashlytics, Remote Config
Additional SDKs you are using (Facebook, AdMob, etc.): AdMob (+ InMobi & FAN for mediation)
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
Our app has only landscape orientation. Therefore it is odd to see all the crashes reported by Crashlytics (Firebase, not Fabric) to only have listed Portrait as the device and OS orientation. Even when the crash reportedly happened in the foreground.

**Comment by stewartmiles** [comment] 2019-05-06 14:47
Thanks for the report @Ruco we'll forward this to the Crashlytics folks who should be able to get back to your shortly.

**Comment by Ruco** [comment] 2019-05-08 06:48
Update: Still haven't seen another orientation than Portrait.
But we've added some more log statements to figure out the cause of the crashes. And it seems that it may report being in Portrait because (most of) the crashes occur when the app is already quitting (OnApplicationQuit). And this is a quit that is initiated by user him/herself.

**Comment by Ruco** [comment] 2019-05-13 11:47
Update: Still only seeing orientation Portrait only.
Even when receiving crashes I know are while inside our app (so Landscape). Although these crashes are from Ads (so different Activity than Unity). This might be why it also reported as Portrait(?)

**Comment by patm1987** [comment] 2019-08-20 17:17
Hi @Ruco,

I hate to be the person who bubbles up the information that the team decided to classify this as "Won't Fix" for now. But, let me go into a little more details about why and suggest a workaround!

First, the issue is that the value reported by Crashlytics is the value stored in `android.content.res.Configuration.orientation`. This value is simply not accurate in Unity due to how the engine is handling orientation. Since Crashlytics is actually iOS Framework or Android aar under the hood, it really doesn't have any knowledge of Unity and doesn't have the hooks needed to handle the special case of Unity.

For a workaround, If you think this is a valuable piece of debugging information you can use a custom key in Crashlytics. Some documentation is available [here](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=unity) and I go over that call in [Part 2](https://medium.com/firebase-developers/crashlytics-and-unity-part-2-498dce6d36ba) of a Crashlytics and Unity blog post I wrote. In the case of the post I'm logging the current scene, but you can easily associate a key with `Input.deviceOrientation`.

I hope that helps!
--Patrick

**Closed by patm1987** 2019-08-20 17:17 UTC
Labels: type: bug

**Comment by Ruco** [comment] 2019-08-21 17:48
Hi patm1987,

Thank you. I understand.

We don't really need this information (our app is purely landscape), but thought it might somehow be "part of the puzzle" on certain crashes.
And at least wanted to report this so you guys were aware of the problem.

-- Rutger
